#!/usr/bin/env python3

# Script to add remaining languages to seed_ui_translations.py
remaining_languages = {
  "es": {
    "homepage.nav_link": "¿Buscas un servicio?",
    "homepage.hero_prefix": "Consigue clientes para",
    "homepage.hero_suffix": "en Varsovia",
    "homepage.hero_subtitle": "Gratis. Sin comisión. Contacto directo.",
    "homepage.trust_1": "Sin comisión",
    "homepage.trust_2": "Registro 2 minutos",
    "homepage.trust_3": "Solicitudes reales",
    "homepage.social_proof": "47 especialistas • 120 solicitudes este mes",
    "homepage.cta_hero": "Empezar gratis",
    "homepage.how_title": "Cómo funciona",
    "homepage.step1_title": "Crear perfil",
    "homepage.step1_sub": "2 minutos",
    "homepage.step2_title": "Recibir solicitudes de clientes",
    "homepage.step2_sub": "inmediatamente después del registro",
    "homepage.step3_title": "Contactar directamente",
    "homepage.step3_sub": "sin intermediarios",
    "homepage.cat_cleaning_name": "Limpieza",
    "homepage.cat_cleaning_leads": "26 solicitudes esta semana",
    "homepage.cat_plumbing_name": "Fontanería",
    "homepage.cat_plumbing_leads": "18 solicitudes esta semana",
    "homepage.cat_massage_name": "Masaje",
    "homepage.cat_massage_leads": "14 solicitudes esta semana",
    "homepage.cat_cta": "Ofrezco este servicio",
    "homepage.rotating_categories": "Masaje,Limpieza,Fontanería",
    "homepage.activity_title": "Últimas solicitudes",
    "homepage.activity_1": "Krzysztof de Varsovia busca limpieza",
    "homepage.activity_1_time": "hace 8 min",
    "homepage.activity_2": "Anna de Varsovia busca masaje",
    "homepage.activity_2_time": "hace 1 hora",
    "homepage.activity_3": "Marek de Varsovia busca fontanero",
    "homepage.activity_3_time": "hace 3 horas",
    "homepage.why_title": "Por qué los especialistas eligen Nevumo",
    "homepage.why_1_title": "Gratis",
    "homepage.why_1_sub": "sin tarifas ocultas",
    "homepage.why_2": "Contacto directo con los clientes",
    "homepage.why_3": "Perfil + página SEO que trabaja para ti 24/7",
    "homepage.cta2_title": "¿Listo para nuevos clientes?",
    "homepage.cta2_btn": "Crear perfil gratuito",
    "homepage.footer_title": "¿Buscas un servicio en Varsovia?",
    "homepage.footer_link_cleaning": "Limpieza en Varsovia",
    "homepage.footer_link_plumbing": "Fontanería en Varsovia",
    "homepage.footer_link_massage": "Masaje en Varsovia",
    "homepage.footer_popular": "Popular: Masaje • Limpieza • Fontanería",
    "category.nav_link": "Conviértete en especialista",
    "category.trust_specialists": "especialistas",
    "category.trust_rating": "valoración",
    "category.trust_requests": "solicitudes este mes",
    "category.trust_response": "Respuesta media: ~30 min",
    "category.empty_state": "Los primeros especialistas se están uniendo. Vuelve mañana.",
    "category.form_title": "Enviar solicitud",
    "category.form_subtitle": "Gratis • Sin compromiso",
    "category.form_phone": "Tu número de teléfono",
    "category.form_desc": "Describe lo que necesitas (opcional)",
    "category.form_btn": "Enviar solicitud",
    "category.form_trust_1": "Gratis",
    "category.form_trust_2": "Sin compromiso",
    "category.form_trust_3": "Respuesta en 30 min",
    "category.provider_cta_prefix": "¿Ofreces",
    "category.provider_cta_suffix": "en Varsovia?",
    "category.provider_cta_link": "Únete gratis →",
    "category.also_check": "Ver también:",
    "category.h1_cleaning": "Limpieza en Varsovia",
    "category.h1_plumbing": "Fontanería en Varsovia",
    "category.h1_massage": "Masaje en Varsovia",
    "category.subtitle_cleaning": "Encuentra especialistas de limpieza en Varsovia. Solicitud gratuita, sin compromiso.",
    "category.subtitle_plumbing": "Encuentra un fontanero en Varsovia. Solicitud gratuita, sin compromiso.",
    "category.subtitle_massage": "Encuentra masajistas en Varsovia. Solicitud gratuita, sin compromiso.",
  },
}

if __name__ == "__main__":
    print("This script would add the remaining languages to the seed file.")
    print(f"Languages to add: {list(remaining_languages.keys())}")
