"""Add pending_lead_claims table

Revision ID: 20260406_204326
Revises: p1q2r3s4t5u6
Create Date: 2026-04-06 20:43:26.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260406_204326'
down_revision: Union[str, None] = 'p1q2r3s4t5u6'
branch_labels: Union[str, None] = None
depends_on: Union[str, None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS pending_lead_claims (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            lead_id UUID NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
            email TEXT NOT NULL,
            phone TEXT,
            claimed BOOLEAN NOT NULL DEFAULT FALSE,
            claimed_at TIMESTAMP,
            magic_link_sent BOOLEAN NOT NULL DEFAULT FALSE,
            magic_link_sent_at TIMESTAMP,
            expires_at TIMESTAMP NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT NOW()
        );
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_pending_claims_lead ON pending_lead_claims(lead_id);
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_pending_claims_email ON pending_lead_claims(email);
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_pending_claims_claimed ON pending_lead_claims(claimed);
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_pending_claims_expires ON pending_lead_claims(expires_at);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS pending_lead_claims;")
    # ### end Alembic commands ###
