"""Add phone field to users table

Revision ID: p1q2r3s4t5u6
Revises: i8j9k0l1m2n3
Create Date: 2026-04-06 12:02:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'p1q2r3s4t5u6'
down_revision: Union[str, None] = 'i8j9k0l1m2n3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users
        ADD COLUMN IF NOT EXISTS phone TEXT;
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone)
        WHERE phone IS NOT NULL;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_users_phone;")
    op.execute("ALTER TABLE users DROP COLUMN IF EXISTS phone;")
    # ### end Alembic commands ###
