"""
seed_terms_annex_bodies.py  —  Nevumo | namespace: terms
Key: annex1_body (34 езика)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_terms_annex_bodies
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"
COMPANY = '„ФИЛИПС ЦЕНТЬР БЪЛГАРИЯ" ООД'

TRANSLATIONS: dict[str, dict[str, str]] = {
    "annex1_body": {
        "en": (
            f'WARNING: This form is used exclusively to withdraw from a contract '
            f'concluded with Nevumo (e.g. a paid subscription or paid platform feature). '
            f'It does NOT apply to contracts between you and a service provider. '
            f'To withdraw from a service booked with a provider, contact that provider directly.\n\n'
            f'(Complete and return this form only if you wish to withdraw from a contract with Nevumo)\n\n'
            f'To: {COMPANY} / Nevumo\n'
            f'Email: privacy@nevumo.com\n\n'
            f'I/We (*) hereby give notice that I/We (*) withdraw from my/our (*) contract '
            f'with Nevumo for the provision of the following platform service/subscription:\n\n'
            f'• Service/subscription ordered on: ___________\n'
            f'• Name of consumer(s): ___________\n'
            f'• Address of consumer(s): ___________\n'
            f'• Signature of consumer(s) (paper submission only): ___________\n'
            f'• Date: ___________\n\n'
            f'(*) Delete as appropriate.'
        ),
        "pl": (
            f'WAŻNE: Niniejszy formularz dotyczy wyłącznie odstąpienia od umowy zawartej '
            f'z Nevumo (np. płatna subskrypcja lub płatna funkcja platformy). '
            f'Nie dotyczy umów zawartych z Usługodawcą — w celu odstąpienia od takiej '
            f'umowy prosimy o bezpośredni kontakt z Usługodawcą.\n\n'
            f'(Wypełnij i wyślij tylko jeśli chcesz odstąpić od umowy z Nevumo)\n\n'
            f'Do: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Ja/My (*) niniejszym informuję/informujemy (*) o odstąpieniu od umowy '
            f'z Nevumo dotyczącej następującej usługi/abonamentu platformy:\n\n'
            f'• Usługa/abonament zamówiona(-y) dnia: ___________\n'
            f'• Imię i nazwisko konsumenta(-ów): ___________\n'
            f'• Adres konsumenta(-ów): ___________\n'
            f'• Podpis konsumenta(-ów) (tylko formularz papierowy): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Niepotrzebne skreślić.'
        ),
        "bg": (
            f'ВАЖНО: Този формуляр е предназначен единствено за отказ от договор, '
            f'сключен с Nevumo (напр. платен абонамент или платена функция на платформата). '
            f'Не се прилага за договори между Клиента и Доставчик — за отказ от такъв '
            f'договор Клиентът трябва да се свърже директно с Доставчика.\n\n'
            f'(Попълнете и изпратете формуляра само ако желаете да се откажете от договор с Nevumo)\n\n'
            f'До: {COMPANY} / Nevumo\n'
            f'Имейл: privacy@nevumo.com\n\n'
            f'Аз/Ние (*) уведомявам/уведомяваме с настоящото за отказа ми/ни (*) от '
            f'сключения договор с Nevumo за следната услуга/абонамент на платформата:\n\n'
            f'• Услугата/абонаментът е поръчан на: ___________\n'
            f'• Имена на потребителя(-ите): ___________\n'
            f'• Адрес на потребителя(-ите): ___________\n'
            f'• Подпис на потребителя(-ите) (само при хартиен формуляр): ___________\n'
            f'• Дата: ___________\n\n'
            f'(*) Излишното се зачертава.'
        ),
        "cs": (
            f'UPOZORNĚNÍ: Tento formulář se používá výhradně k odstoupení od smlouvy '
            f'uzavřené s Nevumo (např. placené předplatné nebo placená funkce platformy). '
            f'Nevztahuje se na smlouvy uzavřené s poskytovatelem — pro odstoupení od takové '
            f'smlouvy kontaktujte poskytovatele přímo.\n\n'
            f'(Vyplňte a odešlete pouze pokud chcete odstoupit od smlouvy s Nevumo)\n\n'
            f'Komu: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Já/My (*) tímto oznamujeme (*) odstoupení od smlouvy s Nevumo '
            f'o poskytnutí následující platformní služby/předplatného:\n\n'
            f'• Služba/předplatné objednáno dne: ___________\n'
            f'• Jméno spotřebitele(-ů): ___________\n'
            f'• Adresa spotřebitele(-ů): ___________\n'
            f'• Podpis spotřebitele(-ů) (pouze papírový formulář): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Nehodící se škrtněte.'
        ),
        "da": (
            f'ADVARSEL: Denne formular bruges udelukkende til at fortryde en kontrakt '
            f'indgået med Nevumo (f.eks. betalt abonnement eller betalt platformsfunktion). '
            f'Den gælder IKKE for kontrakter med en serviceudbyder — kontakt udbyderen '
            f'direkte for at fortryde sådanne kontrakter.\n\n'
            f'(Udfyld og returnér kun denne formular hvis du vil fortryde en kontrakt med Nevumo)\n\n'
            f'Til: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Jeg/Vi (*) meddeler hermed (*) fortrydelse af min/vores (*) kontrakt '
            f'med Nevumo vedrørende følgende platformstjeneste/abonnement:\n\n'
            f'• Tjeneste/abonnement bestilt den: ___________\n'
            f'• Forbrugerens(-nes) navn: ___________\n'
            f'• Forbrugerens(-nes) adresse: ___________\n'
            f'• Underskrift(-er) (kun papirformular): ___________\n'
            f'• Dato: ___________\n\n'
            f'(*) Slet det, der ikke er relevant.'
        ),
        "de": (
            f'HINWEIS: Dieses Formular dient ausschließlich dem Widerruf eines mit Nevumo '
            f'geschlossenen Vertrages (z. B. kostenpflichtiges Abonnement oder '
            f'kostenpflichtige Plattformfunktion). Es gilt NICHT für Verträge mit '
            f'Dienstleistern — wenden Sie sich für den Widerruf direkt an den Anbieter.\n\n'
            f'(Füllen Sie das Formular nur aus, wenn Sie einen Vertrag mit Nevumo widerrufen möchten)\n\n'
            f'An: {COMPANY} / Nevumo\n'
            f'E-Mail: privacy@nevumo.com\n\n'
            f'Ich/Wir (*) widerrufe(n) hiermit (*) meinen/unseren (*) Vertrag mit Nevumo '
            f'über die Bereitstellung folgender Plattformdienstleistung/Abonnements:\n\n'
            f'• Dienstleistung/Abonnement bestellt am: ___________\n'
            f'• Name des/der Verbraucher(s): ___________\n'
            f'• Adresse des/der Verbraucher(s): ___________\n'
            f'• Unterschrift(en) (nur bei Papiereinsendung): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Unzutreffendes bitte streichen.'
        ),
        "el": (
            f'ΠΡΟΣΟΧΗ: Αυτό το έντυπο χρησιμοποιείται αποκλειστικά για υπαναχώρηση από '
            f'σύμβαση που συνήφθη με το Nevumo (π.χ. επί πληρωμή συνδρομή ή χαρακτηριστικό '
            f'πλατφόρμας). ΔΕΝ ισχύει για συμβάσεις με παρόχους υπηρεσιών — '
            f'επικοινωνήστε απευθείας με τον πάροχο.\n\n'
            f'(Συμπληρώστε και επιστρέψτε μόνο εάν επιθυμείτε υπαναχώρηση από σύμβαση με Nevumo)\n\n'
            f'Προς: {COMPANY} / Nevumo\n'
            f'Email: privacy@nevumo.com\n\n'
            f'Εγώ/Εμείς (*) δηλώνουμε δια του παρόντος (*) την υπαναχώρησή μου/μας (*) '
            f'από τη σύμβαση με το Nevumo για την παροχή της ακόλουθης υπηρεσίας/συνδρομής:\n\n'
            f'• Υπηρεσία/συνδρομή παραγγελθείσα στις: ___________\n'
            f'• Ονοματεπώνυμο καταναλωτή(-ών): ___________\n'
            f'• Διεύθυνση καταναλωτή(-ών): ___________\n'
            f'• Υπογραφή(-ές) (μόνο για χάρτινη υποβολή): ___________\n'
            f'• Ημερομηνία: ___________\n\n'
            f'(*) Διαγράψτε ό,τι δεν ισχύει.'
        ),
        "es": (
            f'AVISO: Este formulario se utiliza exclusivamente para desistir de un contrato '
            f'celebrado con Nevumo (p. ej. suscripción de pago o función de pago). '
            f'NO se aplica a contratos con proveedores de servicios — contacte '
            f'directamente al proveedor para desistir de esos contratos.\n\n'
            f'(Complete y devuelva este formulario solo si desea desistir de un contrato con Nevumo)\n\n'
            f'A: {COMPANY} / Nevumo\n'
            f'Email: privacy@nevumo.com\n\n'
            f'Por la presente le comunico/comunicamos (*) mi/nuestra (*) decisión de '
            f'desistir del contrato con Nevumo para la prestación del siguiente '
            f'servicio/suscripción de plataforma:\n\n'
            f'• Servicio/suscripción pedido(-a) el: ___________\n'
            f'• Nombre del/los consumidor(es): ___________\n'
            f'• Dirección del/los consumidor(es): ___________\n'
            f'• Firma(s) (solo envío en papel): ___________\n'
            f'• Fecha: ___________\n\n'
            f'(*) Táchese lo que no proceda.'
        ),
        "et": (
            f'TÄHELEPANU: See vorm on mõeldud ainult Nevumoga sõlmitud lepingust '
            f'taganemiseks (nt tasuline tellimus või tasuline platvormi funktsioon). '
            f'See EI kehti teenusepakkujatega sõlmitud lepingute kohta — '
            f'nende puhul võtke pakkujaga otse ühendust.\n\n'
            f'(Täitke ja tagastage ainult juhul, kui soovite Nevumoga sõlmitud lepingust taganeda)\n\n'
            f'Kellele: {COMPANY} / Nevumo\n'
            f'E-post: privacy@nevumo.com\n\n'
            f'Käesolevaga teatan/teatame (*), et taganen/taganeme (*) Nevumoga sõlmitud '
            f'lepingust järgmise platvormi teenuse/tellimuse osas:\n\n'
            f'• Teenus/tellimus tellitud: ___________\n'
            f'• Tarbija(-te) nimi: ___________\n'
            f'• Tarbija(-te) aadress: ___________\n'
            f'• Allkiri(-d) (ainult pabervormi puhul): ___________\n'
            f'• Kuupäev: ___________\n\n'
            f'(*) Kustutage mittevajalik.'
        ),
        "fi": (
            f'HUOMIO: Tätä lomaketta käytetään yksinomaan Nevumon kanssa tehdystä '
            f'sopimuksesta peruuttamiseen (esim. maksullinen tilaus tai ominaisuus). '
            f'Se EI koske sopimuksia palveluntarjoajien kanssa — '
            f'ota heihin suoraan yhteyttä peruuttaaksesi.\n\n'
            f'(Täytä ja palauta vain jos haluat peruuttaa sopimuksen Nevumon kanssa)\n\n'
            f'Vastaanottaja: {COMPANY} / Nevumo\n'
            f'Sähköposti: privacy@nevumo.com\n\n'
            f'Ilmoitan/Ilmoitamme (*) täten peruuttavani/peruuttavamme (*) sopimuksen '
            f'Nevumon kanssa seuraavan alustapalvelun/tilauksen osalta:\n\n'
            f'• Palvelu/tilaus tilattu: ___________\n'
            f'• Kuluttajan(-jien) nimi: ___________\n'
            f'• Kuluttajan(-jien) osoite: ___________\n'
            f'• Allekirjoitus(-et) (vain paperilomakkeessa): ___________\n'
            f'• Päivämäärä: ___________\n\n'
            f'(*) Poista tarpeettomat tiedot.'
        ),
        "fr": (
            f'AVERTISSEMENT : Ce formulaire est utilisé exclusivement pour se rétracter '
            f'd\'un contrat conclu avec Nevumo (p. ex. abonnement payant ou '
            f'fonctionnalité payante). Il ne s\'applique PAS aux contrats conclus '
            f'avec des prestataires — contactez-les directement.\n\n'
            f'(Complétez et renvoyez ce formulaire uniquement si vous souhaitez vous '
            f'rétracter d\'un contrat avec Nevumo)\n\n'
            f'À : {COMPANY} / Nevumo\n'
            f'E-mail : privacy@nevumo.com\n\n'
            f'Je/Nous (*) vous notifions (*) par la présente ma/notre (*) rétractation '
            f'du contrat avec Nevumo pour la fourniture du service/abonnement '
            f'de plateforme suivant :\n\n'
            f'• Service/abonnement commandé le : ___________\n'
            f'• Nom du/des consommateur(s) : ___________\n'
            f'• Adresse du/des consommateur(s) : ___________\n'
            f'• Signature(s) (formulaire papier uniquement) : ___________\n'
            f'• Date : ___________\n\n'
            f'(*) Rayer la mention inutile.'
        ),
        "ga": (
            f'RABHADH: Úsáidtear an fhoirm seo go heisiach le haistarraingt ó chonradh '
            f'a rinneadh le Nevumo (m.sh. síntiús nó gné íoctha). NÍ bhaineann sí le '
            f'conarthaí le soláthróirí — déan teagmháil leo go díreach.\n\n'
            f'(Comhlánaigh agus seol ar ais an fhoirm seo más mian leat aistarraingt '
            f'ó chonradh le Nevumo)\n\n'
            f'Chuig: {COMPANY} / Nevumo\n'
            f'Ríomhphost: privacy@nevumo.com\n\n'
            f'Tugaim/Tugaimid (*) fógra leis seo faoi mo/ár (*) n-aistarraingt ón '
            f'gconradh le Nevumo i leith na seirbhíse/síntiúis ardáin seo a leanas:\n\n'
            f'• Seirbhís/síntiús ordaithe ar: ___________\n'
            f'• Ainm an/na tomhaltóra (-óirí): ___________\n'
            f'• Seoladh an/na tomhaltóra (-óirí): ___________\n'
            f'• Síniú (-ithe) (foirm pháipéir amháin): ___________\n'
            f'• Dáta: ___________\n\n'
            f'(*) Scrios an méid nach bhfuil ábhartha.'
        ),
        "hr": (
            f'UPOZORENJE: Ovaj obrazac koristi se isključivo za odustanak od ugovora '
            f'sklopljenog s Nevumo (npr. plaćena pretplata ili platforma). '
            f'NE odnosi se na ugovore s davateljem usluga — kontaktirajte ih izravno.\n\n'
            f'(Ispunite i pošaljite samo ako želite odustati od ugovora s Nevumo)\n\n'
            f'Za: {COMPANY} / Nevumo\n'
            f'E-pošta: privacy@nevumo.com\n\n'
            f'Ja/Mi (*) ovime obavještavamo (*) o odustanku od ugovora s Nevumo '
            f'za sljedeću uslugu/pretplatu platforme:\n\n'
            f'• Usluga/pretplata naručena: ___________\n'
            f'• Ime potrošača(-a): ___________\n'
            f'• Adresa potrošača(-a): ___________\n'
            f'• Potpis(-i) (samo za papirni obrazac): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Prekrižite što nije primjenjivo.'
        ),
        "hu": (
            f'FIGYELMEZTETÉS: Ez a nyilatkozat kizárólag a Nevumóval kötött szerződéstől '
            f'(pl. fizetős előfizetés) való elállásra szolgál. NEM vonatkozik a '
            f'szolgáltatókkal kötött szerződésekre — ezek esetén közvetlenül '
            f'lépjen kapcsolatba a szolgáltatóval.\n\n'
            f'(Töltse ki és küldje vissza, csak ha a Nevumóval kötött szerződéstől kíván elállni)\n\n'
            f'Címzett: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Alulírott/Alulírottak (*) ezennel bejelentem/bejelentjük (*) elállásomat/elállásunkat (*) '
            f'a Nevumóval kötött szerződéstől az alábbi platformszolgáltatás/előfizetés esetén:\n\n'
            f'• Szolgáltatás/előfizetés megrendelésének dátuma: ___________\n'
            f'• Fogyasztó(-k) neve: ___________\n'
            f'• Fogyasztó(-k) címe: ___________\n'
            f'• Aláírás(-ok) (csak papíros benyújtás esetén): ___________\n'
            f'• Dátum: ___________\n\n'
            f'(*) A nem kívánt rész törlendő.'
        ),
        "is": (
            f'VIÐVÖRUN: Þetta eyðublað er notað eingöngu til að afturkalla samning '
            f'gerðan við Nevumo (t.d. greitt áskrift eða greidd eiginleiki). '
            f'Það á EKKI við um samninga við þjónustuaðila — hafðu samband við þá beint.\n\n'
            f'(Fylltu út og sendu þetta eyðublað aðeins ef þú vilt afturkalla samning við Nevumo)\n\n'
            f'Til: {COMPANY} / Nevumo\n'
            f'Netfang: privacy@nevumo.com\n\n'
            f'Ég/við (*) tilkynni/tilkynnum hér með (*) afturköllun mína/okkar (*) '
            f'á samningi við Nevumo um eftirfarandi vettvangþjónustu/áskrift:\n\n'
            f'• Þjónusta/áskrift pöntuð: ___________\n'
            f'• Nafn neytanda(-a): ___________\n'
            f'• Heimilisfang neytanda(-a): ___________\n'
            f'• Undirskrift(-ir) (aðeins pappírseyrðublað): ___________\n'
            f'• Dagsetning: ___________\n\n'
            f'(*) Strikið yfir það sem á ekki við.'
        ),
        "it": (
            f'AVVISO: Questo modulo è utilizzato esclusivamente per recedere da un '
            f'contratto concluso con Nevumo (es. abbonamento a pagamento). '
            f'NON si applica ai contratti con prestatori — contattali direttamente.\n\n'
            f'(Compilare e restituire solo se si desidera recedere da un contratto con Nevumo)\n\n'
            f'A: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Con la presente io/noi (*) comunichiamo (*) il recesso dal contratto '
            f'con Nevumo per la fornitura del seguente servizio/abbonamento:\n\n'
            f'• Servizio/abbonamento ordinato il: ___________\n'
            f'• Nome del/dei consumatore(i): ___________\n'
            f'• Indirizzo del/dei consumatore(i): ___________\n'
            f'• Firma(-e) (solo invio cartaceo): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Cancellare la voce che non interessa.'
        ),
        "lb": (
            f'WARNHINWEIS: Dëse Formulaire gëtt ausschliisslech benotzt fir en '
            f'Kontrakt mat Nevumo ze widderruffen (z.B. bezuelt Abonnement). '
            f'Gëlt NET fir Kontrakter mat Serviceprestatairen — kontaktéiert dës direkt.\n\n'
            f'(Fëllt aus an schéckt nëmme wann Dir e Kontrakt mat Nevumo widderruffe wëllt)\n\n'
            f'Un: {COMPANY} / Nevumo\n'
            f'E-Mail: privacy@nevumo.com\n\n'
            f'Ech/Mir (*) widderholen hei mat (*) mäin/eisen (*) Kontrakt mat Nevumo '
            f'fir déi folgend Plattformservice/Abonnement:\n\n'
            f'• Service/Abonnement bestellt um: ___________\n'
            f'• Numm vum/vun de Konsument(-en): ___________\n'
            f'• Adress vum/vun de Konsument(-en): ___________\n'
            f'• Ënnerschrëft(-en) (nëmmen Pabeierformulaire): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Net Zutreffendes streichen.'
        ),
        "lt": (
            f'ĮSPĖJIMAS: Ši forma naudojama tik sutarčiai su Nevumo (pvz., '
            f'mokama prenumerata) atsisakyti. Ji NETAIKOMA sutartims su paslaugų '
            f'teikėjais — kreipkitės į juos tiesiogiai.\n\n'
            f'(Užpildykite ir grąžinkite tik norėdami atsisakyti sutarties su Nevumo)\n\n'
            f'Kam: {COMPANY} / Nevumo\n'
            f'El. paštas: privacy@nevumo.com\n\n'
            f'Aš/Mes (*) pranešame (*) apie atsisakymą nuo sutarties su Nevumo '
            f'dėl šios platformos paslaugos/prenumeratos:\n\n'
            f'• Paslauga/prenumerata užsakyta: ___________\n'
            f'• Vartotojo(-ų) vardas(-ai): ___________\n'
            f'• Vartotojo(-ų) adresas(-ai): ___________\n'
            f'• Parašas(-ai) (tik popierinė forma): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Nereikalingą ištrinkite.'
        ),
        "lv": (
            f'BRĪDINĀJUMS: Šī veidlapa tiek izmantota tikai, lai atsauktu ar Nevumo '
            f'noslēgtu līgumu (piemēram, maksas abonements). Tā NEATTIECAS uz '
            f'līgumiem ar pakalpojumu sniedzējiem — sazinieties ar tiem tieši.\n\n'
            f'(Aizpildiet un iesniedziet tikai, ja vēlaties atsaukt līgumu ar Nevumo)\n\n'
            f'Kam: {COMPANY} / Nevumo\n'
            f'E-pasts: privacy@nevumo.com\n\n'
            f'Es/Mēs (*) ar šo paziņoju/paziņojam (*) par atteikumu no līguma '
            f'ar Nevumo par šādu platformas pakalpojumu/abonementu:\n\n'
            f'• Pakalpojums/abonements pasūtīts: ___________\n'
            f'• Patērētāja(-u) vārds(-i): ___________\n'
            f'• Patērētāja(-u) adrese(-es): ___________\n'
            f'• Paraksts(-i) (tikai papīra veidlapa): ___________\n'
            f'• Datums: ___________\n\n'
            f'(*) Svītrojiet nevajadzīgo.'
        ),
        "mk": (
            f'ПРЕДУПРЕДУВАЊЕ: Овој формулар е наменет исклучиво за отстапување '
            f'од договор склучен со Nevumo (напр. платен абонаман). НЕ се применува '
            f'на договори со Даватели — контактирајте ги директно.\n\n'
            f'(Пополнете и вратете само ако сакате да се откажете од договор со Nevumo)\n\n'
            f'До: {COMPANY} / Nevumo\n'
            f'Е-пошта: privacy@nevumo.com\n\n'
            f'Јас/Ние (*) со ова го известуваме (*) отстапувањето од договорот '
            f'со Nevumo за следната услуга/абонаман на платформата:\n\n'
            f'• Услугата/абонаманот е нарачан на: ___________\n'
            f'• Имиња на потрошувачот(-ите): ___________\n'
            f'• Адреса на потрошувачот(-ите): ___________\n'
            f'• Потпис(-и) (само хартиен формулар): ___________\n'
            f'• Датум: ___________\n\n'
            f'(*) Непотребното се прецртува.'
        ),
        "mt": (
            f'TWISSIJA: Din il-formola tintuża esklussivament biex tirtira minn '
            f'kuntratt konkluż ma\' Nevumo (eż. abbonament imħallas). '
            f'MA tapplikax għal kuntratti ma\' fornituri — ikkuntattjahom direttament.\n\n'
            f'(Imla u ibgħat din il-formola biss jekk trid tirtira minn kuntratt ma\' Nevumo)\n\n'
            f'Lil: {COMPANY} / Nevumo\n'
            f'Email: privacy@nevumo.com\n\n'
            f'Jiena/Aħna (*) b\'dan ninnotifika/ninnotifikaw (*) l-irtirar tiegħi/tagħna (*) '
            f'mill-kuntratt ma\' Nevumo għas-servizz/abbonament tal-pjattaforma li ġej:\n\n'
            f'• Servizz/abbonament ordnat fid-data: ___________\n'
            f'• Isem il-konsumatur(-i): ___________\n'
            f'• Indirizz il-konsumatur(-i): ___________\n'
            f'• Firma(-i) (biss formola bil-karti): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Ħassar dak li ma japplikax.'
        ),
        "nl": (
            f'WAARSCHUWING: Dit formulier wordt uitsluitend gebruikt om te herroepen '
            f'van een overeenkomst met Nevumo (bijv. betaald abonnement). '
            f'Het is NIET van toepassing op overeenkomsten met providers — '
            f'neem direct contact met hen op.\n\n'
            f'(Vul in en retourneer dit formulier alleen als u een overeenkomst met Nevumo wilt herroepen)\n\n'
            f'Aan: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Ik/Wij (*) deel/delen hierbij mede dat ik/wij (*) herroep/herroepen (*) '
            f'van mijn/onze (*) overeenkomst met Nevumo betreffende de volgende '
            f'platformdienst/het abonnement:\n\n'
            f'• Dienst/abonnement besteld op: ___________\n'
            f'• Naam consument(en): ___________\n'
            f'• Adres consument(en): ___________\n'
            f'• Handtekening(-en) (alleen bij papieren inzending): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Doorhalen wat niet van toepassing is.'
        ),
        "no": (
            f'ADVARSEL: Dette skjemaet brukes utelukkende til å trekke seg fra en '
            f'kontrakt inngått med Nevumo (f.eks. betalt abonnement). '
            f'Det gjelder IKKE for kontrakter med tjenesteleverandører — '
            f'kontakt dem direkte.\n\n'
            f'(Fyll ut og returner bare hvis du vil trekke deg fra en kontrakt med Nevumo)\n\n'
            f'Til: {COMPANY} / Nevumo\n'
            f'E-post: privacy@nevumo.com\n\n'
            f'Jeg/Vi (*) meddeler herved (*) at jeg/vi (*) trekker meg/oss (*) fra '
            f'kontrakten med Nevumo om følgende plattformtjeneste/abonnement:\n\n'
            f'• Tjeneste/abonnement bestilt den: ___________\n'
            f'• Forbrukerens(-nes) navn: ___________\n'
            f'• Forbrukerens(-nes) adresse: ___________\n'
            f'• Underskrift(-er) (kun papirskjema): ___________\n'
            f'• Dato: ___________\n\n'
            f'(*) Stryk det som ikke passer.'
        ),
        "pt": (
            f'ATENÇÃO: Este formulário é usado exclusivamente para desistir de um '
            f'contrato celebrado com o Nevumo (ex. subscrição paga). NÃO se aplica '
            f'a contratos com prestadores — contacte-os diretamente.\n\n'
            f'(Preencha e devolva apenas se desejar desistir de um contrato com o Nevumo)\n\n'
            f'Para: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Eu/Nós (*) comunicamos (*) pelo presente a desistência do meu/nosso (*) '
            f'contrato com o Nevumo relativo ao seguinte serviço/subscrição:\n\n'
            f'• Serviço/subscrição pedido(-a) em: ___________\n'
            f'• Nome do(s) consumidor(es): ___________\n'
            f'• Endereço do(s) consumidor(es): ___________\n'
            f'• Assinatura(s) (apenas envio em papel): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Riscar o que não interessa.'
        ),
        "pt-PT": (
            f'ATENÇÃO: Este formulário é utilizado exclusivamente para retractação de '
            f'um contrato celebrado com o Nevumo (ex. subscrição paga). NÃO se aplica '
            f'a contratos com prestadores — contacte-os directamente.\n\n'
            f'(Preencha e devolva apenas se desejar retratar-se de um contrato com o Nevumo)\n\n'
            f'Para: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Eu/Nós (*) comunico/comunicamos (*) pelo presente a retractação do '
            f'meu/nosso (*) contrato com o Nevumo relativo ao seguinte serviço/subscrição:\n\n'
            f'• Serviço/subscrição encomendado(-a) em: ___________\n'
            f'• Nome do(s) consumidor(es): ___________\n'
            f'• Endereço do(s) consumidor(es): ___________\n'
            f'• Assinatura(s) (apenas formulário em papel): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Riscar o que não interessa.'
        ),
        "ro": (
            f'ATENȚIE: Acest formular este utilizat exclusiv pentru retragerea din '
            f'un contract încheiat cu Nevumo (ex. abonament plătit). NU se aplică '
            f'contractelor cu prestatorii — contactați-i direct.\n\n'
            f'(Completați și returnați doar dacă doriți să vă retrageți dintr-un contract cu Nevumo)\n\n'
            f'Către: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Eu/Noi (*) notific/notificăm (*) prin prezenta retragerea mea/noastră (*) '
            f'din contractul cu Nevumo pentru următorul serviciu/abonament de platformă:\n\n'
            f'• Serviciu/abonament comandat la data: ___________\n'
            f'• Numele consumatorului(-ilor): ___________\n'
            f'• Adresa consumatorului(-ilor): ___________\n'
            f'• Semnătura(-urile) (doar formularul pe hârtie): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Ștergeți mențiunile inutile.'
        ),
        "ru": (
            f'ВНИМАНИЕ: Данная форма используется исключительно для отказа от договора, '
            f'заключённого с Nevumo (напр. платная подписка). Она НЕ применяется '
            f'к договорам с исполнителями — обращайтесь к ним напрямую.\n\n'
            f'(Заполните и верните форму только если желаете отказаться от договора с Nevumo)\n\n'
            f'Кому: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Я/Мы (*) настоящим уведомляем (*) об отказе от договора с Nevumo '
            f'в отношении следующей платформенной услуги/подписки:\n\n'
            f'• Услуга/подписка заказана: ___________\n'
            f'• Имя потребителя(-ей): ___________\n'
            f'• Адрес потребителя(-ей): ___________\n'
            f'• Подпись(-и) (только при бумажной подаче): ___________\n'
            f'• Дата: ___________\n\n'
            f'(*) Ненужное зачеркнуть.'
        ),
        "sk": (
            f'UPOZORNENIE: Tento formulár slúži výhradne na odstúpenie od zmluvy '
            f'uzatvorenej s Nevumo (napr. platené predplatné). NEVZŤAHUJE sa na '
            f'zmluvy s poskytovateľmi — kontaktujte ich priamo.\n\n'
            f'(Vyplňte a odošlite iba ak chcete odstúpiť od zmluvy s Nevumo)\n\n'
            f'Komu: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Ja/My (*) týmto oznamujem/oznamujeme (*) odstúpenie od zmluvy s Nevumo '
            f'týkajúcej sa nasledujúcej platformovej služby/predplatného:\n\n'
            f'• Služba/predplatné objednané dňa: ___________\n'
            f'• Meno spotrebiteľa(-ov): ___________\n'
            f'• Adresa spotrebiteľa(-ov): ___________\n'
            f'• Podpis(-y) (iba papierový formulár): ___________\n'
            f'• Dátum: ___________\n\n'
            f'(*) Nehodiace sa prečiarknite.'
        ),
        "sl": (
            f'OPOZORILO: Ta obrazec se uporablja izključno za odstop od pogodbe, '
            f'sklenjene z Nevumo (npr. plačljiva naročnina). NE velja za pogodbe '
            f's ponudniki — stopite v stik z njimi neposredno.\n\n'
            f'(Izpolnite in vrnite samo, če želite odstopiti od pogodbe z Nevumo)\n\n'
            f'Za: {COMPANY} / Nevumo\n'
            f'E-pošta: privacy@nevumo.com\n\n'
            f'Jaz/Mi (*) s tem obveščamo (*) o odstopu od moje/naše (*) pogodbe '
            f'z Nevumo za naslednjo storitev/naročnino:\n\n'
            f'• Storitev/naročnina naročena: ___________\n'
            f'• Ime potrošnika(-ov): ___________\n'
            f'• Naslov potrošnika(-ov): ___________\n'
            f'• Podpis(-i) (samo papirni obrazec): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Neustrezno prečrtajte.'
        ),
        "sq": (
            f'PARALAJMËRIM: Ky formular përdoret ekskluzivisht për t\'u tërhequr '
            f'nga një kontratë e lidhur me Nevumo (p.sh. abonim me pagesë). '
            f'NUK aplikohet për kontratat me ofruesit — kontaktojini drejtpërdrejt.\n\n'
            f'(Plotësoni dhe ktheni vetëm nëse dëshironi të tërhiqeni nga kontrata me Nevumo)\n\n'
            f'Për: {COMPANY} / Nevumo\n'
            f'Email: privacy@nevumo.com\n\n'
            f'Unë/Ne (*) njoftojmë me këtë (*) tërheqjen time/tonë (*) nga kontrata '
            f'me Nevumo për shërbimin/abonimin e mëposhtëm:\n\n'
            f'• Shërbimi/abonamenti i porositur më: ___________\n'
            f'• Emri i konsumatorit(-ëve): ___________\n'
            f'• Adresa e konsumatorit(-ëve): ___________\n'
            f'• Nënshkrim(-et) (vetëm formulari me letër): ___________\n'
            f'• Data: ___________\n\n'
            f'(*) Fshini çfarë nuk aplikohet.'
        ),
        "sr": (
            f'UPOZORENJE: Ovaj obrazac koristi se isključivo za odustanak od ugovora '
            f'zaključenog sa Nevumo (npr. plaćena pretplata). NE odnosi se na ugovore '
            f'sa pružaocima — kontaktirajte ih direktno.\n\n'
            f'(Popunite i pošaljite samo ako želite da odustanete od ugovora sa Nevumo)\n\n'
            f'Za: {COMPANY} / Nevumo\n'
            f'E-pošta: privacy@nevumo.com\n\n'
            f'Ja/Mi (*) ovim obaveštavamo (*) o odustanku od ugovora sa Nevumo '
            f'za sledeću uslugu/pretplatu platforme:\n\n'
            f'• Usluga/pretplata naručena: ___________\n'
            f'• Ime potrošača(-a): ___________\n'
            f'• Adresa potrošača(-a): ___________\n'
            f'• Potpis(-i) (samo papirni obrazac): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Precrtati nepotrebno.'
        ),
        "sv": (
            f'VARNING: Detta formulär används uteslutande för att ångra ett avtal '
            f'ingånget med Nevumo (t.ex. betald prenumeration). Det GÄLLER INTE '
            f'avtal med tjänsteleverantörer — kontakta dem direkt.\n\n'
            f'(Fyll i och returnera bara om du vill ångra ett avtal med Nevumo)\n\n'
            f'Till: {COMPANY} / Nevumo\n'
            f'E-post: privacy@nevumo.com\n\n'
            f'Jag/Vi (*) meddelar härmed (*) att jag/vi (*) frånträder mitt/vårt (*) '
            f'avtal med Nevumo avseende följande plattformstjänst/prenumeration:\n\n'
            f'• Tjänst/prenumeration beställd: ___________\n'
            f'• Konsumentens(-ernas) namn: ___________\n'
            f'• Konsumentens(-ernas) adress: ___________\n'
            f'• Underskrift(-er) (endast pappersformulär): ___________\n'
            f'• Datum: ___________\n\n'
            f'(*) Stryk det som inte är tillämpligt.'
        ),
        "tr": (
            f'UYARI: Bu form yalnızca Nevumo ile yapılan bir sözleşmeden cayma '
            f'amacıyla kullanılır (örn. ücretli abonelik). Hizmet sağlayıcılarla '
            f'yapılan sözleşmelere UYGULANMAZ — onlarla doğrudan iletişime geçin.\n\n'
            f'(Bu formu yalnızca Nevumo ile yaptığınız sözleşmeden caymak istiyorsanız doldurun)\n\n'
            f'Alıcı: {COMPANY} / Nevumo\n'
            f'E-posta: privacy@nevumo.com\n\n'
            f'Ben/Biz (*) aşağıdaki platform hizmeti/aboneliğine ilişkin Nevumo ile '
            f'yapılan sözleşmeden cayma bildiriminde bulunuyorum/bulunuyoruz (*):\n\n'
            f'• Hizmet/abonelik sipariş tarihi: ___________\n'
            f'• Tüketici(-lerin) adı: ___________\n'
            f'• Tüketici(-lerin) adresi: ___________\n'
            f'• İmza(-lar) (yalnızca kâğıt formda): ___________\n'
            f'• Tarih: ___________\n\n'
            f'(*) Uygun olmayanı silin.'
        ),
        "uk": (
            f'УВАГА: Ця форма використовується виключно для відмови від договору, '
            f'укладеного з Nevumo (напр. платна підписка). Вона НЕ застосовується '
            f'до договорів з виконавцями — зверніться до них безпосередньо.\n\n'
            f'(Заповніть та поверніть форму лише якщо бажаєте відмовитися від договору з Nevumo)\n\n'
            f'Кому: {COMPANY} / Nevumo\n'
            f'E-mail: privacy@nevumo.com\n\n'
            f'Я/Ми (*) цим повідомляємо (*) про відмову від мого/нашого (*) договору '
            f'з Nevumo щодо наступної послуги/підписки платформи:\n\n'
            f'• Послуга/підписка замовлена: ___________\n'
            f'• Ім\'я споживача(-ів): ___________\n'
            f'• Адреса споживача(-ів): ___________\n'
            f'• Підпис(-и) (лише паперова форма): ___________\n'
            f'• Дата: ___________\n\n'
            f'(*) Непотрібне закреслити.'
        ),
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_annex_bodies: {count} rows upserted ({NAMESPACE}, annex1_body × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()
