"""
seed_terms_p1.py  —  Nevumo | namespace: terms | Part 1
Keys: page_title, effective_date, version, pl_notice,
      art1_title, art2_title, art3_title
Run : docker exec nevumo-api python -m apps.api.scripts.seed_terms_p1
"""
import os

from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"

TRANSLATIONS: dict[str, dict[str, str]] = {

    "page_title": {
        "bg": "Общи условия за клиенти на Nevumo",
        "cs": "Obchodní podmínky pro klienty Nevumo",
        "da": "Betingelser for klienter på Nevumo",
        "de": "Allgemeine Geschäftsbedingungen für Kunden von Nevumo",
        "el": "Όροι και Προϋποθέσεις για Πελάτες του Nevumo",
        "en": "Terms & Conditions for Clients",
        "es": "Términos y Condiciones para Clientes de Nevumo",
        "et": "Nevumo klientide kasutustingimused",
        "fi": "Käyttöehdot Nevumon asiakkaille",
        "fr": "Conditions générales d'utilisation pour les clients de Nevumo",
        "ga": "Téarmaí agus Coinníollacha do Chliaint Nevumo",
        "hr": "Uvjeti korištenja za klijente Nevumo",
        "hu": "Általános Szerződési Feltételek Nevumo ügyfelek számára",
        "is": "Skilmálar fyrir viðskiptavini Nevumo",
        "it": "Termini e Condizioni per i Clienti di Nevumo",
        "lb": "Allgemeng Geschäftsbedéngungen fir Klienten vu Nevumo",
        "lt": "Nevumo klientų naudojimo sąlygos",
        "lv": "Nevumo klientu lietošanas noteikumi",
        "mk": "Општи услови за клиенти на Nevumo",
        "mt": "Termini u Kundizzjonijiet għall-Klijenti ta' Nevumo",
        "nl": "Algemene Voorwaarden voor Klanten van Nevumo",
        "no": "Vilkår og betingelser for kunder av Nevumo",
        "pl": "Regulamin serwisu Nevumo dla Klientów",
        "pt": "Termos e Condições para Clientes da Nevumo",
        "pt-PT": "Termos e Condições para Clientes da Nevumo",
        "ro": "Termeni și Condiții pentru Clienții Nevumo",
        "ru": "Пользовательское соглашение для клиентов Nevumo",
        "sk": "Všeobecné obchodné podmienky pre klientov Nevumo",
        "sl": "Splošni pogoji za stranke Nevumo",
        "sq": "Termat dhe Kushtet për Klientët e Nevumo",
        "sr": "Opšti uslovi korišćenja za klijente Nevumo",
        "sv": "Allmänna villkor för kunder hos Nevumo",
        "tr": "Nevumo Müşterileri için Hüküm ve Koşullar",
        "uk": "Загальні умови для клієнтів Nevumo",
    },

    "effective_date": {
        "bg": "Дата на влизане в сила: 1 юни 2026 г.",
        "cs": "Datum účinnosti: 1. června 2026",
        "da": "Ikrafttrædelsesdato: 1. juni 2026",
        "de": "Datum des Inkrafttretens: 1. Juni 2026",
        "el": "Ημερομηνία έναρξης ισχύος: 1 Ιουνίου 2026",
        "en": "Effective date: 1 June 2026",
        "es": "Fecha de entrada en vigor: 1 de junio de 2026",
        "et": "Jõustumiskuupäev: 1. juuni 2026",
        "fi": "Voimaantulopäivä: 1. kesäkuuta 2026",
        "fr": "Date d'entrée en vigueur : 1er juin 2026",
        "ga": "Dáta éifeachtach: 1 Meitheamh 2026",
        "hr": "Datum stupanja na snagu: 1. lipnja 2026.",
        "hu": "Hatályba lépés dátuma: 2026. június 1.",
        "is": "Gildistökudagur: 1. júní 2026",
        "it": "Data di entrata in vigore: 1° giugno 2026",
        "lb": "Datum vum Abschloss: 1. Juni 2026",
        "lt": "Įsigaliojimo data: 2026 m. birželio 1 d.",
        "lv": "Spēkā stāšanās datums: 2026. gada 1. jūnijs",
        "mk": "Датум на стапување во сила: 1 јуни 2026",
        "mt": "Data ta' dħul fis-seħħ: 1 ta' Ġunju 2026",
        "nl": "Ingangsdatum: 1 juni 2026",
        "no": "Ikrafttredelsesdato: 1. juni 2026",
        "pl": "Data wejścia w życie: 1 czerwca 2026 r.",
        "pt": "Data de entrada em vigor: 1 de junho de 2026",
        "pt-PT": "Data de entrada em vigor: 1 de junho de 2026",
        "ro": "Data intrării în vigoare: 1 iunie 2026",
        "ru": "Дата вступления в силу: 1 июня 2026 г.",
        "sk": "Dátum účinnosti: 1. júna 2026",
        "sl": "Datum začetka veljavnosti: 1. junij 2026",
        "sq": "Data e hyrjes në fuqi: 1 qershor 2026",
        "sr": "Datum stupanja na snagu: 1. jun 2026.",
        "sv": "Ikraftträdandedatum: 1 juni 2026",
        "tr": "Yürürlük tarihi: 1 Haziran 2026",
        "uk": "Дата набрання чинності: 1 червня 2026 р.",
    },

    "version": {
        "bg": "Версия: 1.0",
        "cs": "Verze: 1.0",
        "da": "Version: 1.0",
        "de": "Version: 1.0",
        "el": "Έκδοση: 1.0",
        "en": "Version: 1.0",
        "es": "Versión: 1.0",
        "et": "Versioon: 1.0",
        "fi": "Versio: 1.0",
        "fr": "Version : 1.0",
        "ga": "Leagan: 1.0",
        "hr": "Verzija: 1.0",
        "hu": "Verzió: 1.0",
        "is": "Útgáfa: 1.0",
        "it": "Versione: 1.0",
        "lb": "Versioun: 1.0",
        "lt": "Versija: 1.0",
        "lv": "Versija: 1.0",
        "mk": "Верзија: 1.0",
        "mt": "Verżjoni: 1.0",
        "nl": "Versie: 1.0",
        "no": "Versjon: 1.0",
        "pl": "Wersja: 1.0",
        "pt": "Versão: 1.0",
        "pt-PT": "Versão: 1.0",
        "ro": "Versiunea: 1.0",
        "ru": "Версия: 1.0",
        "sk": "Verzia: 1.0",
        "sl": "Različica: 1.0",
        "sq": "Versioni: 1.0",
        "sr": "Verzija: 1.0",
        "sv": "Version: 1.0",
        "tr": "Sürüm: 1.0",
        "uk": "Версія: 1.0",
    },

    "pl_notice": {
        "bg": "Ако се намирате в Полша, допълнителните разпоредби, обозначени с [PL], се прилагат и имат предимство пред общите условия при противоречие.",
        "cs": "Pokud se nacházíte v Polsku, platí dodatečná ustanovení označená [PL], která mají v případě rozporu přednost před obecnými podmínkami.",
        "da": "Hvis du befinder dig i Polen, gælder yderligere bestemmelser markeret med [PL], som har forrang frem for de generelle vilkår i tilfælde af konflikt.",
        "de": "Wenn Sie sich in Polen befinden, gelten zusätzliche Bestimmungen, die mit [PL] gekennzeichnet sind und im Konfliktfall Vorrang vor den allgemeinen Bedingungen haben.",
        "el": "Εάν βρίσκεστε στην Πολωνία, ισχύουν επιπλέον διατάξεις που επισημαίνονται με [PL], οι οποίες υπερισχύουν των γενικών όρων σε περίπτωση σύγκρουσης.",
        "en": "If you are located in Poland, additional provisions marked [PL] apply and take precedence over the general terms in case of conflict.",
        "es": "Si se encuentra en Polonia, se aplican disposiciones adicionales marcadas con [PL] que prevalecen sobre las condiciones generales en caso de conflicto.",
        "et": "Kui asute Poolas, kohaldatakse täiendavaid [PL]-ga tähistatud sätteid, mis on vastuolu korral üldtingimuste ees ülimuslikud.",
        "fi": "Jos olet Puolassa, sovelletaan lisäsäännöksiä, jotka on merkitty [PL] ja jotka ovat ristiriitatilanteessa yleisten ehtojen edelle.",
        "fr": "Si vous êtes situé en Pologne, des dispositions supplémentaires marquées [PL] s'appliquent et prévalent sur les conditions générales en cas de conflit.",
        "ga": "Má tá tú suite sa Pholainn, tá forálacha breise marcáilte [PL] i bhfeidhm agus tá siad i dtosaíocht ar na téarmaí ginearálta i gcás coinbhleachta.",
        "hr": "Ako se nalazite u Poljskoj, primjenjuju se dodatne odredbe označene s [PL], koje imaju prednost pred općim uvjetima u slučaju sukoba.",
        "hu": "Ha Lengyelországban tartózkodik, a [PL]-lel jelölt további rendelkezések alkalmazandók, amelyek konfliktus esetén elsőbbséget élveznek az általános feltételekkel szemben.",
        "is": "Ef þú ert staðsettur í Póllandi gilda viðbótarákvæði merkt [PL], sem hafa forgang yfir almennum skilmálum við ágreining.",
        "it": "Se ti trovi in Polonia, si applicano disposizioni aggiuntive contrassegnate con [PL], che prevalgono sui termini generali in caso di conflitto.",
        "lb": "Wann Dir Iech a Polen befannen, gëllen zousätzlech Bestëmmungen, déi mat [PL] markéiert sinn a bei engem Konflikt Virrang virun den allgemengen Bedéngungen hunn.",
        "lt": "Jei esate Lenkijoje, taikomos papildomos nuostatos, pažymėtos [PL], kurios nesutarimų atveju turi viršenybę prieš bendruosius terminus.",
        "lv": "Ja atrodaties Polijā, piemērojami papildu noteikumi, kas apzīmēti ar [PL], kuriem pretrunu gadījumā ir prioritāte pār vispārējiem noteikumiem.",
        "mk": "Доколку се наоѓате во Полска, се применуваат дополнителни одредби означени со [PL], кои при судир имаат предност пред општите услови.",
        "mt": "Jekk tinsab fil-Polonja, japplikaw dispożizzjonijiet addizzjonali mmarkati [PL], li jipprevalu fuq it-termini ġenerali f'każ ta' kunflitt.",
        "nl": "Als u zich in Polen bevindt, zijn aanvullende bepalingen gemarkeerd met [PL] van toepassing, die in geval van conflict voorrang hebben boven de algemene voorwaarden.",
        "no": "Hvis du befinner deg i Polen, gjelder ytterligere bestemmelser merket med [PL], som har forrang foran de generelle vilkårene ved konflikt.",
        "pl": "Jeśli przebywasz w Polsce, zastosowanie mają dodatkowe postanowienia oznaczone [PL], które mają pierwszeństwo przed postanowieniami ogólnymi w przypadku konfliktu.",
        "pt": "Se você está localizado na Polônia, aplicam-se disposições adicionais marcadas com [PL], que prevalecem sobre os termos gerais em caso de conflito.",
        "pt-PT": "Se estiver localizado na Polónia, aplicam-se disposições adicionais assinaladas com [PL], que prevalecem sobre os termos gerais em caso de conflito.",
        "ro": "Dacă vă aflați în Polonia, se aplică dispoziții suplimentare marcate cu [PL], care prevalează asupra termenilor generali în caz de conflict.",
        "ru": "Если вы находитесь в Польше, применяются дополнительные положения, обозначенные [PL], которые при противоречии имеют приоритет над общими условиями.",
        "sk": "Ak sa nachádzate v Poľsku, platia dodatočné ustanovenia označené [PL], ktoré v prípade rozporu majú prednosť pred všeobecnými podmienkami.",
        "sl": "Če se nahajate na Poljskem, se uporabljajo dodatne določbe, označene z [PL], ki imajo v primeru nasprotja prednost pred splošnimi pogoji.",
        "sq": "Nëse ndodheni në Poloni, zbatohen dispozita shtesë të shënuara me [PL], të cilat kanë përparësi ndaj kushteve të përgjithshme në rast konflikti.",
        "sr": "Ako se nalazite u Poljskoj, primenjuju se dodatne odredbe označene sa [PL], koje imaju prednost pred opštim uslovima u slučaju sukoba.",
        "sv": "Om du befinner dig i Polen gäller ytterligare bestämmelser markerade med [PL], som har företräde framför de allmänna villkoren vid konflikt.",
        "tr": "Polonya'da iseniz, [PL] ile işaretlenmiş ek hükümler geçerlidir ve çatışma durumunda genel şartların önünde gelir.",
        "uk": "Якщо ви знаходитесь у Польщі, застосовуються додаткові положення, позначені [PL], які мають пріоритет над загальними умовами у разі суперечності.",
    },

    "art1_title": {
        "bg": "Чл. 1. Предмет и страни",
        "cs": "1. O platformě Nevumo a těchto podmínkách",
        "da": "1. Om Nevumo og disse vilkår",
        "de": "1. Über Nevumo und diese Bedingungen",
        "el": "1. Σχετικά με το Nevumo και τους παρόντες Όρους",
        "en": "1. About Nevumo and These Terms",
        "es": "1. Sobre Nevumo y estos Términos",
        "et": "1. Nevumo ja käesolevate tingimuste kohta",
        "fi": "1. Nevumosta ja näistä ehdoista",
        "fr": "1. À propos de Nevumo et des présentes Conditions",
        "ga": "1. Maidir le Nevumo agus na Téarmaí seo",
        "hr": "1. O Nevumu i ovim Uvjetima",
        "hu": "1. A Nevumóról és jelen Feltételekről",
        "is": "1. Um Nevumo og þessa skilmála",
        "it": "1. Informazioni su Nevumo e sui presenti Termini",
        "lb": "1. Iwwer Nevumo an dës Bedéngungen",
        "lt": "1. Apie Nevumo ir šias sąlygas",
        "lv": "1. Par Nevumo un šiem noteikumiem",
        "mk": "1. За Nevumo и овие услови",
        "mt": "1. Dwar Nevumo u dawn it-Termini",
        "nl": "1. Over Nevumo en deze Voorwaarden",
        "no": "1. Om Nevumo og disse vilkårene",
        "pl": "§1. Postanowienia ogólne",
        "pt": "1. Sobre a Nevumo e estes Termos",
        "pt-PT": "1. Sobre a Nevumo e estes Termos",
        "ro": "1. Despre Nevumo și acești Termeni",
        "ru": "1. О Nevumo и настоящих Условиях",
        "sk": "1. O platforme Nevumo a týchto podmienkach",
        "sl": "1. O Nevumu in teh Pogojih",
        "sq": "1. Rreth Nevumo dhe këtyre Kushteve",
        "sr": "1. O Nevumo i ovim Uslovima",
        "sv": "1. Om Nevumo och dessa Villkor",
        "tr": "1. Nevumo ve Bu Koşullar Hakkında",
        "uk": "1. Про Nevumo та ці Умови",
    },

    "art2_title": {
        "bg": "Чл. 2. Характер на услугата — Nevumo като посредник",
        "cs": "2. Povaha služby — Nevumo jako zprostředkovatel",
        "da": "2. Tjenestens karakter — Nevumo som formidler",
        "de": "2. Art der Dienstleistung — Nevumo als Vermittler",
        "el": "2. Φύση της Υπηρεσίας — Nevumo ως Διαμεσολαβητής",
        "en": "2. Nature of the Service — Nevumo as Intermediary",
        "es": "2. Naturaleza del Servicio — Nevumo como Intermediario",
        "et": "2. Teenuse olemus — Nevumo vahendajana",
        "fi": "2. Palvelun luonne — Nevumo välittäjänä",
        "fr": "2. Nature du Service — Nevumo en tant qu'Intermédiaire",
        "ga": "2. Cineál an tSeirbhís — Nevumo mar Idirghabhálaí",
        "hr": "2. Priroda usluge — Nevumo kao posrednik",
        "hu": "2. A szolgáltatás jellege — Nevumo mint közvetítő",
        "is": "2. Eðli þjónustunnar — Nevumo sem milliliður",
        "it": "2. Natura del Servizio — Nevumo come Intermediario",
        "lb": "2. Natur vun der Servicer — Nevumo als Vermëttler",
        "lt": "2. Paslaugos pobūdis — Nevumo kaip tarpininkas",
        "lv": "2. Pakalpojuma raksturs — Nevumo kā starpnieks",
        "mk": "2. Природа на услугата — Nevumo како посредник",
        "mt": "2. In-Natura tas-Servizz — Nevumo bħala Intermedjarji",
        "nl": "2. Aard van de Dienst — Nevumo als Tussenpersoon",
        "no": "2. Tjenestens natur — Nevumo som formidler",
        "pl": "§2. Charakter usługi — Nevumo jako pośrednik",
        "pt": "2. Natureza do Serviço — Nevumo como Intermediário",
        "pt-PT": "2. Natureza do Serviço — Nevumo como Intermediário",
        "ro": "2. Natura Serviciului — Nevumo ca Intermediar",
        "ru": "2. Характер услуги — Nevumo как посредник",
        "sk": "2. Povaha služby — Nevumo ako sprostredkovateľ",
        "sl": "2. Narava storitve — Nevumo kot posrednik",
        "sq": "2. Natyra e Shërbimit — Nevumo si Ndërmjetës",
        "sr": "2. Priroda usluge — Nevumo kao posrednik",
        "sv": "2. Tjänstens karaktär — Nevumo som förmedlare",
        "tr": "2. Hizmetin Niteliği — Aracı Olarak Nevumo",
        "uk": "2. Характер послуги — Nevumo як посередник",
    },

    "art3_title": {
        "bg": "Чл. 3. Изисквания за регистрация и акаунт",
        "cs": "3. Způsobilost a registrace účtu",
        "da": "3. Berettigelse og kontoregistrering",
        "de": "3. Nutzungsvoraussetzungen und Kontoregistrierung",
        "el": "3. Δικαίωμα Χρήσης και Εγγραφή Λογαριασμού",
        "en": "3. Eligibility and Account Registration",
        "es": "3. Elegibilidad y Registro de Cuenta",
        "et": "3. Nõuded kasutajale ja konto registreerimine",
        "fi": "3. Käyttöoikeus ja tilin rekisteröinti",
        "fr": "3. Conditions d'éligibilité et création de compte",
        "ga": "3. Incháilitheacht agus Clárú Cuntais",
        "hr": "3. Uvjeti korištenja i registracija računa",
        "hu": "3. Jogosultság és fiókregisztráció",
        "is": "3. Skilyrði og skráning reiknings",
        "it": "3. Idoneità e Registrazione dell'Account",
        "lb": "3. Berechtegung a Kontoregistréierung",
        "lt": "3. Tinkamumo reikalavimai ir paskyros registracija",
        "lv": "3. Atbilstības prasības un konta reģistrācija",
        "mk": "3. Услови за регистрација и акаунт",
        "mt": "3. Eliġibilità u Reġistrazzjoni tal-Kont",
        "nl": "3. Geschiktheid en Accountregistratie",
        "no": "3. Berettigelse og kontoregistrering",
        "pl": "§4. Rejestracja i konto Klienta",
        "pt": "3. Elegibilidade e Registro de Conta",
        "pt-PT": "3. Elegibilidade e Registo de Conta",
        "ro": "3. Eligibilitate și Înregistrarea Contului",
        "ru": "3. Требования к пользователям и регистрация аккаунта",
        "sk": "3. Spôsobilosť a registrácia účtu",
        "sl": "3. Pogoji za uporabo in registracija računa",
        "sq": "3. Kualifikimi dhe Regjistrimi i Llogarisë",
        "sr": "3. Uslovi korišćenja i registracija naloga",
        "sv": "3. Behörighet och kontoregistrering",
        "tr": "3. Uygunluk ve Hesap Kaydı",
        "uk": "3. Вимоги до користувачів та реєстрація облікового запису",
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_p1: {count} rows upserted ({NAMESPACE}, 7 keys × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()