"""Seed profile_strength_email translations — Package 2 (hr, hu, is, it, lb, lt, lv, mk, mt, nl)"""
import os
from sqlalchemy import create_engine, text

engine = create_engine(os.environ["DATABASE_URL"])

NAMESPACE = "profile_strength_email"

TRANSLATIONS = {
    "hr": {
        "subject":           "{n} stvari sprječavaju klijente da vas odaberu",
        "preview":           "Vaš profil je aktivan — evo točno što trebate dodati.",
        "hero_for":          "Za:",
        "hero_active":       "Vaš Nevumo profil je aktivan. ✓",
        "hero_found":        "Provjerio sam ga i pronašao {n} stvari koje klijenti gledaju prije odabira stručnjaka — a vi ih nemate.",
        "hero_time":         "Potrebne su 3 minute da ih dodate.",
        "block1_title":      "Profilna fotografija",
        "block1_body":       "Profili bez fotografije primaju znatno manje upita. Klijenti žele znati s kime rade.",
        "block1_cta":        "Dodaj fotografiju",
        "block2_title":      "Fotografije vašeg rada",
        "block2_body":       "Imate mjesta za 8 fotografija. Klijenti odlučuju očima — pravi rad uvjerava više od svakog opisa.",
        "block2_cta":        "Dodaj fotografije",
        "block3_title":      "Opis",
        "block3_body":       "Klijenti čitaju opis prije kontaktiranja. Čak i 2 rečenice čine razliku.",
        "block3_ex_cleaning": '„Stručnjak za čišćenje s 8 godina iskustva. Stambeni i uredski prostori. Radim s ekološkim sredstvima."',
        "block3_ex_plumbing": '„Vodoinstalater s 10 godina iskustva. Hitne intervencije 24/7. Besplatna procjena na licu mjesta."',
        "block3_ex_massage": '„Masažer s 5 godina iskustva. Sportska i opuštajuća masaža. Kućne posjete."',
        "block3_cta":        "Poboljšaj opis",
        "block4_title":      "Broj telefona",
        "block4_body":       "Dodaj telefon.",
        "block4_cta":        "Dodaj",
        "cta_main":          "Otvori svoj profil →",
        "footer_text":       "Primate ovaj e-mail jer ste registrirani pružatelj usluga na Nevumo.",
        "footer_unsub":      "Odjava",
    },
    "hu": {
        "subject":           "{n} dolog akadályozza az ügyfeleket abban, hogy Önt válasszák",
        "preview":           "Profilja aktív — íme pontosan az, amit hozzá kell adnia.",
        "hero_for":          "Részére:",
        "hero_active":       "Nevumo profilja aktív. ✓",
        "hero_found":        "Ellenőriztem, és {n} dolgot találtam, amelyet az ügyfelek egy szakértő kiválasztása előtt megnéznek — és ezek hiányoznak az Ön profiljából.",
        "hero_time":         "3 percbe telik ezek hozzáadása.",
        "block1_title":      "Profilkép",
        "block1_body":       "A kép nélküli profilok lényegesen kevesebb megkeresést kapnak. Az ügyfelek tudni akarják, kivel dolgoznak.",
        "block1_cta":        "Kép hozzáadása",
        "block2_title":      "Fotók a munkájáról",
        "block2_body":       "8 fotónak van helye. Az ügyfelek szemükkel döntenek — a valódi munka jobban meggyőz, mint bármilyen leírás.",
        "block2_cta":        "Fotók hozzáadása",
        "block3_title":      "Leírás",
        "block3_body":       "Az ügyfelek elolvassák a leírást kapcsolatfelvétel előtt. Még 2 mondat is változást hoz.",
        "block3_ex_cleaning": '„8 éves tapasztalattal rendelkező takarítási szakértő. Lakások és irodák. Környezetbarát termékekkel dolgozom."',
        "block3_ex_plumbing": '„10 éves tapasztalatú vízszerelő. Vészhelyzetek 24/7. Ingyenes helyszíni felmérés."',
        "block3_ex_massage": '„5 éves tapasztalatú masszőr. Sportos és relaxáló masszázs. Házi látogatások."',
        "block3_cta":        "Leírás javítása",
        "block4_title":      "Telefonszám",
        "block4_body":       "Adja meg telefonszámát.",
        "block4_cta":        "Hozzáadás",
        "cta_main":          "Profil megnyitása →",
        "footer_text":       "Azért kapja ezt az e-mailt, mert Ön regisztrált szolgáltató a Nevumón.",
        "footer_unsub":      "Leiratkozás",
    },
    "is": {
        "subject":           "{n} hlutir koma í veg fyrir að viðskiptavinir velji þig",
        "preview":           "Prófíllinn þinn er virkur — hér er nákvæmlega það sem þú þarft að bæta við.",
        "hero_for":          "Til:",
        "hero_active":       "Nevumo-prófíllinn þinn er virkur. ✓",
        "hero_found":        "Ég skoðaði hann og fann {n} hluti sem viðskiptavinir skoða áður en þeir velja sérfræðing — og þú ert ekki með þá.",
        "hero_time":         "Það tekur 3 mínútur að bæta þeim við.",
        "block1_title":      "Prófílmynd",
        "block1_body":       "Prófílar án myndar fá mun færri fyrirspurnir. Viðskiptavinir vilja vita hverjum þeir eru að vinna með.",
        "block1_cta":        "Bæta við mynd",
        "block2_title":      "Myndir af verkum þínum",
        "block2_body":       "Þú hefur pláss fyrir 8 myndir. Viðskiptavinir ákveða með augunum — raunveruleg verk sannfæra meira en nokkur lýsing.",
        "block2_cta":        "Bæta við myndum",
        "block3_title":      "Lýsing",
        "block3_body":       "Viðskiptavinir lesa lýsinguna áður en þeir hafa samband. Jafnvel 2 setningar skipta máli.",
        "block3_ex_cleaning": '„Þrif sérfræðingur með 8 ára reynslu. Íbúðir og skrifstofur. Ég nota umhverfisvænar vörur."',
        "block3_ex_plumbing": '„Pípulagningamaður með 10 ára reynslu. Neyðarviðgerðir 24/7. Ókeypis mat á staðnum."',
        "block3_ex_massage": '„Nuddari með 5 ára reynslu. Íþróttanudd og slökunarnudd. Heimsóknir."',
        "block3_cta":        "Bæta lýsingu",
        "block4_title":      "Símanúmer",
        "block4_body":       "Bæta við síma.",
        "block4_cta":        "Bæta við",
        "cta_main":          "Opna prófíl minn →",
        "footer_text":       "Þú færð þetta tölvupóst vegna þess að þú ert skráður þjónustuaðili á Nevumo.",
        "footer_unsub":      "Afskrá",
    },
    "it": {
        "subject":           "{n} cose impediscono ai clienti di sceglierti",
        "preview":           "Il tuo profilo è attivo — ecco esattamente cosa devi aggiungere.",
        "hero_for":          "Per:",
        "hero_active":       "Il tuo profilo Nevumo è attivo. ✓",
        "hero_found":        "L'ho controllato e ho trovato {n} cose che i clienti guardano prima di scegliere uno specialista — e tu non le hai.",
        "hero_time":         "Ci vogliono 3 minuti per aggiungerle.",
        "block1_title":      "Foto del profilo",
        "block1_body":       "I profili senza foto ricevono significativamente meno richieste. I clienti vogliono sapere con chi stanno lavorando.",
        "block1_cta":        "Aggiungi foto",
        "block2_title":      "Foto del tuo lavoro",
        "block2_body":       "Hai spazio per 8 foto. I clienti decidono con gli occhi — il lavoro reale convince più di qualsiasi descrizione.",
        "block2_cta":        "Aggiungi foto",
        "block3_title":      "Descrizione",
        "block3_body":       "I clienti leggono la descrizione prima di contattarti. Anche 2 frasi fanno la differenza.",
        "block3_ex_cleaning": '„Specialista delle pulizie con 8 anni di esperienza. Residenziale e uffici. Lavoro con prodotti ecologici."',
        "block3_ex_plumbing": '„Idraulico con 10 anni di esperienza. Emergenze 24/7. Sopralluogo gratuito."',
        "block3_ex_massage": '„Massaggiatore con 5 anni di esperienza. Massaggio sportivo e rilassante. Visite a domicilio."',
        "block3_cta":        "Migliora la descrizione",
        "block4_title":      "Numero di telefono",
        "block4_body":       "Aggiungi telefono.",
        "block4_cta":        "Aggiungi",
        "cta_main":          "Apri il mio profilo →",
        "footer_text":       "Ricevi questa email perché sei un fornitore registrato su Nevumo.",
        "footer_unsub":      "Annulla iscrizione",
    },
    "lb": {
        "subject":           "{n} Saachen hënneren d'Clienten dech ze wielen",
        "preview":           "Däi Profil ass aktiv — hei ass genee wat du muss dobäisetzen.",
        "hero_for":          "Un:",
        "hero_active":       "Däi Nevumo-Profil ass aktiv. ✓",
        "hero_found":        "Ech hunn et iwwerpréift a {n} Saachen fonnt, déi d'Clienten kucken ier si e Spezialist wielen — a déi hues du net.",
        "hero_time":         "Et dauert 3 Minutten se dobäizusetzen.",
        "block1_title":      "Profilbild",
        "block1_body":       "Profiler ouni Bild kréien däitlech manner Ufroe. Clienten wëllen wëssen, mat wie si schaffen.",
        "block1_cta":        "Bild dobäisetzen",
        "block2_title":      "Fotoen vun denger Aarbecht",
        "block2_body":       "Du hues Plaz fir 8 Fotoen. Clienten entscheeden mat den Aen — richteg Aarbecht iwwerzeegt méi wéi all Beschreiwung.",
        "block2_cta":        "Fotoen dobäisetzen",
        "block3_title":      "Beschreiwung",
        "block3_body":       "Clienten liesen d'Beschreiwung ier si Kontakt ophuelen. Souguer 2 Sätz maachen e Ënnerscheed.",
        "block3_ex_cleaning": '„Botzspezialist mat 8 Joer Erfahrung. Wunnengen a Büroe. Ech schaffe mat ëmweltfrëndlechen Produkter."',
        "block3_ex_plumbing": '„Klempner mat 10 Joer Erfahrung. Noutfäll 24/7. Gratis Visite virun Ort."',
        "block3_ex_massage": '„Masseur mat 5 Joer Erfahrung. Sport- a Relax-Massage. Heemvisiten."',
        "block3_cta":        "Beschreiwung verbesseren",
        "block4_title":      "Telefonnummer",
        "block4_body":       "Telefon dobäisetzen.",
        "block4_cta":        "Dobäisetzen",
        "cta_main":          "Mäi Profil opmaachen →",
        "footer_text":       "Du kréis dës E-Mail well du e registréierte Prestataire op Nevumo bass.",
        "footer_unsub":      "Ofmellen",
    },
    "lt": {
        "subject":           "{n} dalykai trukdo klientams pasirinkti jus",
        "preview":           "Jūsų profilis aktyvus — štai tiksliai ką reikia pridėti.",
        "hero_for":          "Kam:",
        "hero_active":       "Jūsų Nevumo profilis yra aktyvus.",
        "hero_found":        "Patikrinau ir radau {n} dalykus, į kuriuos klientai žiūri prieš pasirinkdami specialistą — jų jūs neturite.",
        "hero_time":         "Jų pridėjimas užtruks 3 minutes.",
        "block1_title":      "Profilio nuotrauka",
        "block1_body":       "Profiliai be nuotraukos gauna žymiai mažiau užklausų. Klientai nori žinoti, su kuo dirba.",
        "block1_cta":        "Pridėti nuotrauką",
        "block2_title":      "Jūsų darbo nuotraukos",
        "block2_body":       "Turite vietos 8 nuotraukoms. Klientai sprendžia akimis — tikras darbas įtikina labiau nei bet koks aprašymas.",
        "block2_cta":        "Pridėti nuotraukas",
        "block3_title":      "Aprašymas",
        "block3_body":       "Klientai skaito aprašymą prieš susisiekdami. Net 2 sakiniai daro skirtumą.",
        "block3_ex_cleaning": '„Valymo specialistas su 8 metų patirtimi. Gyvenamieji ir biurų patalpų valymas. Dirbu su ekologiškomis priemonėmis."',
        "block3_ex_plumbing": '„Santechnikas su 10 metų patirtimi. Avarijos 24/7. Nemokamas įvertinimas vietoje."',
        "block3_ex_massage": '„Masažistas su 5 metų patirtimi. Sportinis ir atpalaiduojantis masažas. Namų vizitai."',
        "block3_cta":        "Pagerinti aprašymą",
        "block4_title":      "Telefono numeris",
        "block4_body":       "Pridėkite telefoną.",
        "block4_cta":        "Pridėti",
        "cta_main":          "Atidaryti savo profilį →",
        "footer_text":       "Šį el. laišką gaunat, nes esate registruotas paslaugų teikėjas Nevumo.",
        "footer_unsub":      "Atsisakyti prenumeratos",
    },
    "lv": {
        "subject":           "{n} lietas neļauj klientiem izvēlēties jūs",
        "preview":           "Jūsu profils ir aktīvs — lūk, tieši tas, kas jāpievieno.",
        "hero_for":          "Kam:",
        "hero_active":       "Jūsu Nevumo profils ir aktīvs. ✓",
        "hero_found":        "Es to pārbaudīju un atradu {n} lietas, ko klienti skatās pirms speciālista izvēles — un jums tās nav.",
        "hero_time":         "To pievienošana aizņem 3 minūtes.",
        "block1_title":      "Profila foto",
        "block1_body":       "Profili bez fotogrāfijas saņem ievērojami mazāk pieprasījumu. Klienti vēlas zināt, ar ko viņi strādā.",
        "block1_cta":        "Pievienot foto",
        "block2_title":      "Jūsų darbo fotogrāfijas",
        "block2_body":       "Jums ir vieta 8 fotogrāfijām. Klienti izlemj ar acīm — reāls darbs pārliecina vairāk nekā jebkurš apraksts.",
        "block2_cta":        "Pievienot fotogrāfijas",
        "block3_title":      "Apraksts",
        "block3_body":       "Klienti lasa aprakstu pirms sazināšanās. Pat 2 teikumi veido atšķirību.",
        "block3_ex_cleaning": '„Uzkopšanas speciālists ar 8 gadu pieredzi. Dzīvojamās telpas un biroji. Strādāju ar ekoloģiskiem produktiem."',
        "block3_ex_plumbing": '„Santehniķis ar 10 gadu pieredzi. Avārijas 24/7. Bezmaksas novērtējums uz vietas."',
        "block3_ex_massage": '„Masieris ar 5 gadu pieredzi. Sporta un relaksācijas masāža. Mājas vizītes."',
        "block3_cta":        "Uzlabot aprakstu",
        "block4_title":      "Tālruņa numurs",
        "block4_body":       "Pievienojiet tālruni.",
        "block4_cta":        "Pievienot",
        "cta_main":          "Atvērt savu profilu →",
        "footer_text":       "Jūs saņemat šo e-pastu, jo esat reģistrēts pakalpojumu sniedzējs Nevumo.",
        "footer_unsub":      "Atteikties",
    },
    "mk": {
        "subject":           "{n} работи ги спречуваат клиентите да те изберат",
        "preview":           "Профилот ти е активен — еве точно што треба да додадеш.",
        "hero_for":          "За:",
        "hero_active":       "Профилот ти на Nevumo е активен. ✓",
        "hero_found":        "Го проверив и најдов {n} работи кои клиентите ги гледаат пред да изберат специјалист — и ти ги нема.",
        "hero_time":         "Потребни се 3 минути за да ги додадеш.",
        "block1_title":      "Профилна слика",
        "block1_body":       "Профилите без слика добиваат значително помалку барања. Клиентите сакаат да знаат со кого работат.",
        "block1_cta":        "Додади слика",
        "block2_title":      "Слики од твојата работа",
        "block2_body":       "Имаш место за 8 слики. Клиентите одлучуваат со очите — вистинската работа убедува повеќе од секој опис.",
        "block2_cta":        "Додади слики",
        "block3_title":      "Опис",
        "block3_body":       "Клиентите го читаат описот пред да се јават. Дури и 2 реченици прават разлика.",
        "block3_ex_cleaning": '„Специјалист за чистење со 8г. искуство. Станбени и деловни простори. Работам со еко средства."',
        "block3_ex_plumbing": '„ВиК специјалист со 10г. искуство. Хаварии 24/7. Бесплатна проценка на лице место."',
        "block3_ex_massage": '„Масажист со 5г. искуство. Спортска и релаксирачка масажа. Домашни посети."',
        "block3_cta":        "Подобри го описот",
        "block4_title":      "Телефонски број",
        "block4_body":       "Додади телефон.",
        "block4_cta":        "Додади",
        "cta_main":          "Отвори го профилот →",
        "footer_text":       "Го добиваш овој имејл затоа што си регистриран давател на услуги на Nevumo.",
        "footer_unsub":      "Откажи се",
    },
    "mt": {
        "subject":           "{n} affarijiet qed jimpedixxu lill-klijenti milli jagħżluk",
        "preview":           "Il-profil tiegħek huwa attiv — hawn eżattament x'għandek iżżid.",
        "hero_for":          "Għal:",
        "hero_active":       "Il-profil tiegħek fuq Nevumo huwa attiv. ✓",
        "hero_found":        "Iċċekkjajtu u sibt {n} affarijiet li l-klijenti jħarsu lejhom qabel jagħżlu speċjalista — u int ma għandhomx.",
        "hero_time":         "Jieħu 3 minuti biex iżżidhom.",
        "block1_title":      "Ritratt tal-profil",
        "block1_body":       "Il-profili mingħajr ritratt jirċievu ferm inqas mistoqsijiet. Il-klijenti jridu jkunu jafu ma' min qegħdin jaħdmu.",
        "block1_cta":        "Żid ritratt",
        "block2_title":      "Ritratti tax-xogħol tiegħek",
        "block2_body":       "Għandek spazju għal 8 ritratti. Il-klijenti jiddeċiedu bl-għajnejn — ix-xogħol reali jikkonvinċi aktar minn kull deskrizzjoni.",
        "block2_cta":        "Żid ritratti",
        "block3_title":      "Deskrizzjoni",
        "block3_body":       "Il-klijenti jaqraw id-deskrizzjoni qabel jikkuntattjawk. Saħansitra 2 sentenzi jagħmlu differenza.",
        "block3_ex_cleaning": "„Speċjalista fit-tindif b'8 snin esperjenza. Djar u uffiċċji. Naħdem b'prodotti ekoloġiċi.'",
        "block3_ex_plumbing": "„Idrawliku b'10 snin esperjenza. Emerġenzi 24/7. Valutazzjoni b'xejn fuq il-post.'",
        "block3_ex_massage": "„Massaġġista b'5 snin esperjenza. Massaġġ sportiv u ta' relax. Żjarat tad-dar.'",
        "block3_cta":        "Itjeb id-deskrizzjoni",
        "block4_title":      "Numru tat-telefown",
        "block4_body":       "Żid it-telefown.",
        "block4_cta":        "Żid",
        "cta_main":          "Iftaħ il-profil tiegħi →",
        "footer_text":       "Qiegħed tirċievi din l-email għax inti fornitur reġistrat fuq Nevumo.",
        "footer_unsub":      "Irtirat",
    },
    "nl": {
        "subject":           "{n} dingen weerhouden klanten ervan u te kiezen",
        "preview":           "Uw profiel is actief — dit is precies wat u moet toevoegen.",
        "hero_for":          "Voor:",
        "hero_active":       "Uw Nevumo-profiel is actief. ✓",
        "hero_found":        "Ik heb het gecontroleerd en {n} dingen gevonden die klanten bekijken voordat ze een specialist kiezen — en die heeft u niet.",
        "hero_time":         "Het duurt 3 minuten om ze toe te voegen.",
        "block1_title":      "Profielfoto",
        "block1_body":       "Profielen zonder foto ontvangen aanzienlijk minder aanvragen. Klanten willen weten met wie ze werken.",
        "block1_cta":        "Foto toevoegen",
        "block2_title":      "Foto's van uw werk",
        "block2_body":       "U heeft ruimte voor 8 foto's. Klanten beslissen met hun ogen — echt werk overtuigt meer dan welke beschrijving dan ook.",
        "block2_cta":        "Foto's toevoegen",
        "block3_title":      "Beschrijving",
        "block3_body":       "Klanten lezen de beschrijving voordat ze contact opnemen. Zelfs 2 zinnen maken een verschil.",
        "block3_ex_cleaning": '„Schoonmaakspecialist met 8 jaar ervaring. Woningen en kantoren. Ik werk met milieuvriendelijke producten."',
        "block3_ex_plumbing": '„Loodgieter met 10 jaar ervaring. Spoedreparaties 24/7. Gratis inspectie ter plaatse."',
        "block3_ex_massage": '„Masseur met 5 jaar ervaring. Sport- en ontspanningsmassage. Huisbezoeken."',
        "block3_cta":        "Beschrijving verbeteren",
        "block4_title":      "Telefoonnummer",
        "block4_body":       "Telefoon toevoegen.",
        "block4_cta":        "Toevoegen",
        "cta_main":          "Mijn profiel openen →",
        "footer_text":       "U ontvangt deze e-mail omdat u een geregistreerde aanbieder bent op Nevumo.",
        "footer_unsub":      "Afmelden",
    },
}

def main() -> None:
    rows = [
        {"lang": lang, "key": f"{NAMESPACE}.{key}", "value": value}
        for lang, keys in TRANSLATIONS.items()
        for key, value in keys.items()
    ]
    with engine.begin() as conn:
        for row in rows:
            conn.execute(
                text("""
                    INSERT INTO translations (lang, key, value)
                    VALUES (:lang, :key, :value)
                    ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                """),
                row,
            )
    print(f"✅ Seeded {len(rows)} rows ({len(TRANSLATIONS)} languages)")

if __name__ == "__main__":
    main()
