"""Seed profile_strength_email translations — Package 1 (bg, cs, da, de, el, en, es, et, fi, fr, ga)"""
import os
from sqlalchemy import create_engine, text

engine = create_engine(os.environ["DATABASE_URL"])

NAMESPACE = "profile_strength_email"

TRANSLATIONS = {
    "bg": {
        "subject":           "{n} неща спират клиентите да те изберат",
        "preview":           "Профилът ти е активен — ето точно какво трябва да добавиш.",
        "hero_for":          "За:",
        "hero_active":       "Профилът ти в Nevumo е активен. ✓",
        "hero_found":        "Проверих го и открих {n} неща, които клиентите гледат преди да изберат специалист — и ти ги нямаш.",
        "hero_time":         "Отнема 3 минути да ги добавиш.",
        "block1_title":      "Профилна снимка",
        "block1_body":       "Профилите без снимка получават значително по-малко запитвания. Клиентите искат да знаят с кого работят.",
        "block1_cta":        "Добави снимка",
        "block2_title":      "Снимки от работата ти",
        "block2_body":       "Имаш място за 8 снимки. Клиентите вземат решение с очите си — реалната работа убеждава повече от всяко описание.",
        "block2_cta":        "Добави снимки",
        "block3_title":      "Описание",
        "block3_body":       "Клиентите четат описанието преди да се свържат. Дори 2 изречения правят разликата.",
        "block3_ex_cleaning": '„Специалист по почистване с 8г. опит. Жилищно и офис. Работя с еко препарати."',
        "block3_ex_plumbing": '„ВиК специалист с 10г. опит. Аварии 24/7. Безплатна оценка на място."',
        "block3_ex_massage": '„Масажист с 5г. опит. Спортен и релаксиращ масаж. Домашни посещения."',
        "block3_cta":        "Подобри описанието",
        "block4_title":      "Телефонен номер",
        "block4_body":       "Добави телефон.",
        "block4_cta":        "Добави",
        "cta_main":          "Отвори профила си →",
        "footer_text":       "Получаваш този имейл защото си регистриран доставчик в Nevumo.",
        "footer_unsub":      "Откажи се",
    },
    "cs": {
        "subject":           "{n} věcí brání klientům vybrat si vás",
        "preview":           "Váš profil je aktivní — tady přesně to, co potřebujete přidat.",
        "hero_for":          "Pro:",
        "hero_active":       "Váš profil na Nevumo je aktivní. ✓",
        "hero_found":        "Zkontroloval jsem ho a našel {n} věci, které klienti kontrolují před výběrem specialisty — a vy je nemáte.",
        "hero_time":         "Jejich přidání zabere 3 minuty.",
        "block1_title":      "Profilová fotografie",
        "block1_body":       "Profily bez fotografie dostávají výrazně méně poptávek. Klienti chtějí vědět, s kým pracují.",
        "block1_cta":        "Přidat fotografii",
        "block2_title":      "Fotografie vaší práce",
        "block2_body":       "Máte místo pro 8 fotografií. Klienti se rozhodují zrakem — skutečná práce přesvědčí více než jakýkoli popis.",
        "block2_cta":        "Přidat fotografie",
        "block3_title":      "Popis",
        "block3_body":       "Klienti čtou popis před kontaktováním. Dokonce i 2 věty dělají rozdíl.",
        "block3_ex_cleaning": '„Specialista na úklid s 8 lety zkušeností. Bytové i kancelářské prostory. Pracuji s ekologickými přípravky."',
        "block3_ex_plumbing": '„Instalatér s 10 lety zkušeností. Havárie 24/7. Bezplatná prohlídka na místě."',
        "block3_ex_massage": '„Masér s 5 lety zkušeností. Sportovní a relaxační masáže. Domácí návštěvy."',
        "block3_cta":        "Vylepšit popis",
        "block4_title":      "Telefonní číslo",
        "block4_body":       "Přidejte telefon.",
        "block4_cta":        "Přidat",
        "cta_main":          "Otevřít svůj profil →",
        "footer_text":       "Tento e-mail dostáváte, protože jste registrovaný poskytovatel na Nevumo.",
        "footer_unsub":      "Odhlásit se",
    },
    "da": {
        "subject":           "{n} ting forhindrer kunder i at vælge dig",
        "preview":           "Din profil er aktiv — her er præcis hvad du skal tilføje.",
        "hero_for":          "Til:",
        "hero_active":       "Din Nevumo-profil er aktiv. ✓",
        "hero_found":        "Jeg tjekkede det og fandt {n} ting, som kunder ser på, før de vælger en specialist — og dem har du ikke.",
        "hero_time":         "Det tager 3 minutter at tilføje dem.",
        "block1_title":      "Profilbillede",
        "block1_body":       "Profiler uden billede modtager betydeligt færre forespørgsler. Kunder vil vide, hvem de arbejder med.",
        "block1_cta":        "Tilføj billede",
        "block2_title":      "Billeder af dit arbejde",
        "block2_body":       "Du har plads til 8 billeder. Kunder beslutter med øjnene — rigtigt arbejde overbeviser mere end enhver beskrivelse.",
        "block2_cta":        "Tilføj billeder",
        "block3_title":      "Beskrivelse",
        "block3_body":       "Kunder læser beskrivelsen, inden de kontakter dig. Selv 2 sætninger gør en forskel.",
        "block3_ex_cleaning": '„Rengøringsspecialist med 8 års erfaring. Boliger og kontorer. Jeg bruger miljøvenlige rengøringsmidler."',
        "block3_ex_plumbing": '„VVS-specialist med 10 års erfaring. Akuthjælp 24/7. Gratis besigtigelse på stedet."',
        "block3_ex_massage": '„Massør med 5 års erfaring. Sports- og afslapningsmassage. Hjemmebesøg."',
        "block3_cta":        "Forbedr beskrivelsen",
        "block4_title":      "Telefonnummer",
        "block4_body":       "Tilføj telefon.",
        "block4_cta":        "Tilføj",
        "cta_main":          "Åbn din profil →",
        "footer_text":       "Du modtager denne e-mail, fordi du er registreret udbyder på Nevumo.",
        "footer_unsub":      "Afmeld",
    },
    "de": {
        "subject":           "{n} Dinge hindern Kunden daran, Sie zu wählen",
        "preview":           "Ihr Profil ist aktiv — hier ist genau das, was Sie hinzufügen müssen.",
        "hero_for":          "Für:",
        "hero_active":       "Ihr Nevumo-Profil ist aktiv. ✓",
        "hero_found":        "Ich habe es überprüft und {n} Dinge gefunden, die Kunden vor der Wahl eines Spezialisten ansehen — und die haben Sie nicht.",
        "hero_time":         "Das Hinzufügen dauert 3 Minuten.",
        "block1_title":      "Profilfoto",
        "block1_body":       "Profile ohne Foto erhalten deutlich weniger Anfragen. Kunden möchten wissen, mit wem sie arbeiten.",
        "block1_cta":        "Foto hinzufügen",
        "block2_title":      "Fotos Ihrer Arbeit",
        "block2_body":       "Sie haben Platz für 8 Fotos. Kunden entscheiden mit den Augen — echte Arbeit überzeugt mehr als jede Beschreibung.",
        "block2_cta":        "Fotos hinzufügen",
        "block3_title":      "Beschreibung",
        "block3_body":       "Kunden lesen die Beschreibung, bevor sie sich melden. Bereits 2 Sätze machen einen Unterschied.",
        "block3_ex_cleaning": '„Reinigungsspezialist mit 8 Jahren Erfahrung. Privat- und Büroreinigung. Ich arbeite mit umweltfreundlichen Mitteln."',
        "block3_ex_plumbing": '„Installateur mit 10 Jahren Erfahrung. Notfälle 24/7. Kostenlose Besichtigung vor Ort."',
        "block3_ex_massage": '„Masseur mit 5 Jahren Erfahrung. Sport- und Entspannungsmassage. Hausbesuche."',
        "block3_cta":        "Beschreibung verbessern",
        "block4_title":      "Telefonnummer",
        "block4_body":       "Telefon hinzufügen.",
        "block4_cta":        "Hinzufügen",
        "cta_main":          "Profil öffnen →",
        "footer_text":       "Sie erhalten diese E-Mail, weil Sie ein registrierter Anbieter bei Nevumo sind.",
        "footer_unsub":      "Abmelden",
    },
    "el": {
        "subject":           "{n} πράγματα εμποδίζουν τους πελάτες να σας επιλέξουν",
        "preview":           "Το προφίλ σας είναι ενεργό — εδώ ακριβώς τι πρέπει να προσθέσετε.",
        "hero_for":          "Για:",
        "hero_active":       "Το προφίλ σας στο Nevumo είναι ενεργό. ✓",
        "hero_found":        "Το έλεγξα και βρήκα {n} πράγματα που οι πελάτες κοιτάνε πριν επιλέξουν ειδικό — και εσείς δεν τα έχετε.",
        "hero_time":         "Χρειάζονται 3 λεπτά για να τα προσθέσετε.",
        "block1_title":      "Φωτογραφία προφίλ",
        "block1_body":       "Τα προφίλ χωρίς φωτογραφία λαμβάνουν σημαντικά λιγότερα αιτήματα. Οι πελάτες θέλουν να ξέρουν με ποιον δουλεύουν.",
        "block1_cta":        "Προσθέστε φωτογραφία",
        "block2_title":      "Φωτογραφίες από τη δουλειά σας",
        "block2_body":       "Έχετε χώρο για 8 φωτογραφίες. Οι πελάτες αποφασίζουν με τα μάτια τους — η πραγματική δουλειά πείθει περισσότερο από κάθε περιγραφή.",
        "block2_cta":        "Προσθέστε φωτογραφίες",
        "block3_title":      "Περιγραφή",
        "block3_body":       "Οι πελάτες διαβάζουν την περιγραφή πριν επικοινωνήσουν. Ακόμα και 2 προτάσεις κάνουν τη διαφορά.",
        "block3_ex_cleaning": '„Ειδικός καθαρισμού με 8 χρόνια εμπειρία. Κατοικίες και γραφεία. Χρησιμοποιώ οικολογικά προϊόντα."',
        "block3_ex_plumbing": '„Υδραυλικός με 10 χρόνια εμπειρία. Επείγουσες επισκευές 24/7. Δωρεάν εκτίμηση επί τόπου."',
        "block3_ex_massage": "„Μασέρ με 5 χρόνια εμπειρία. Αθλητικό και χαλαρωτικό μασάζ. Επισκέψεις κατ' οίκον.\"",
        "block3_cta":        "Βελτιώστε την περιγραφή",
        "block4_title":      "Αριθμός τηλεφώνου",
        "block4_body":       "Προσθέστε τηλέφωνο.",
        "block4_cta":        "Προσθέστε",
        "cta_main":          "Ανοίξτε το προφίλ σας →",
        "footer_text":       "Λαμβάνετε αυτό το email επειδή είστε εγγεγραμμένος πάροχος στο Nevumo.",
        "footer_unsub":      "Κατάργηση εγγραφής",
    },
    "en": {
        "subject":           "{n} things are stopping clients from choosing you",
        "preview":           "Your profile is active — here's exactly what you need to add.",
        "hero_for":          "For:",
        "hero_active":       "Your Nevumo profile is active. ✓",
        "hero_found":        "I checked it and found {n} things clients look at before choosing a specialist — and you're missing them.",
        "hero_time":         "It takes 3 minutes to add them.",
        "block1_title":      "Profile photo",
        "block1_body":       "Profiles without a photo receive significantly fewer enquiries. Clients want to know who they're working with.",
        "block1_cta":        "Add photo",
        "block2_title":      "Photos of your work",
        "block2_body":       "You have room for 8 photos. Clients decide with their eyes — real work convinces more than any description.",
        "block2_cta":        "Add photos",
        "block3_title":      "Description",
        "block3_body":       "Clients read the description before getting in touch. Even 2 sentences make a difference.",
        "block3_ex_cleaning": '„Cleaning specialist with 8 years of experience. Residential and office cleaning. I use eco-friendly products."',
        "block3_ex_plumbing": '„Plumbing specialist with 10 years of experience. Emergency repairs 24/7. Free on-site assessment.\"',
        "block3_ex_massage": '„Massage therapist with 5 years of experience. Sports and relaxation massage. Home visits available.\"',
        "block3_cta":        "Improve description",
        "block4_title":      "Phone number",
        "block4_body":       "Add your phone number.",
        "block4_cta":        "Add",
        "cta_main":          "Open your profile →",
        "footer_text":       "You are receiving this email because you are a registered provider on Nevumo.",
        "footer_unsub":      "Unsubscribe",
    },
    "es": {
        "subject":           "{n} cosas impiden que los clientes te elijan",
        "preview":           "Tu perfil está activo — aquí está exactamente lo que necesitas añadir.",
        "hero_for":          "Para:",
        "hero_active":       "Tu perfil en Nevumo está activo. ✓",
        "hero_found":        "Lo revisé y encontré {n} cosas que los clientes miran antes de elegir un especialista — y tú no las tienes.",
        "hero_time":         "Solo tarda 3 minutos en añadirlos.",
        "block1_title":      "Foto de perfil",
        "block1_body":       "Los perfiles sin foto reciben significativamente menos consultas. Los clientes quieren saber con quién trabajan.",
        "block1_cta":        "Añadir foto",
        "block2_title":      "Fotos de tu trabajo",
        "block2_body":       "Tienes espacio para 8 fotos. Los clientes deciden con los ojos — el trabajo real convence más que cualquier descripción.",
        "block2_cta":        "Añadir fotos",
        "block3_title":      "Descripción",
        "block3_body":       "Los clientes leen la descripción antes de ponerse en contacto. Incluso 2 frases marcan la diferencia.",
        "block3_ex_cleaning": '„Especialista en limpieza con 8 años de experiencia. Viviendas y oficinas. Trabajo con productos ecológicos."',
        "block3_ex_plumbing": '„Fontanero con 10 años de experiencia. Urgencias 24/7. Presupuesto gratuito en el sitio."',
        "block3_ex_massage": '„Masajista con 5 años de experiencia. Masaje deportivo y relajante. Visitas a domicilio."',
        "block3_cta":        "Mejorar descripción",
        "block4_title":      "Número de teléfono",
        "block4_body":       "Añade teléfono.",
        "block4_cta":        "Añadir",
        "cta_main":          "Abrir mi perfil →",
        "footer_text":       "Recibes este correo porque eres un proveedor registrado en Nevumo.",
        "footer_unsub":      "Darse de baja",
    },
    "et": {
        "subject":           "{n} asja takistavad kliente teid valimast",
        "preview":           "Teie profiil on aktiivne — siin on täpselt see, mida peate lisama.",
        "hero_for":          "Kellele:",
        "hero_active":       "Teie Nevumo profiil on aktiivne. ✓",
        "hero_found":        "Kontrollisin seda ja leidsin {n} asja, mida kliendid enne spetsialisti valimist vaatavad — ja teil neid pole.",
        "hero_time":         "Nende lisamine võtab 3 minutit.",
        "block1_title":      "Profiilipilt",
        "block1_body":       "Profiilid ilma fotota saavad oluliselt vähem päringuid. Kliendid tahavad teada, kellega nad töötavad.",
        "block1_cta":        "Lisa foto",
        "block2_title":      "Fotod teie tööst",
        "block2_body":       "Teil on ruumi 8 fotole. Kliendid otsustavad silmadega — päris töö veenab rohkem kui ükski kirjeldus.",
        "block2_cta":        "Lisa fotod",
        "block3_title":      "Kirjeldus",
        "block3_body":       "Kliendid loevad kirjeldust enne kontakteerumist. Isegi 2 lauset teevad vahe.",
        "block3_ex_cleaning": '„Koristusspetsialist 8-aastase kogemusega. Elamud ja kontorid. Töötan keskkonnasõbralike vahenditega."',
        "block3_ex_plumbing": '„Torustikuinstallaator 10-aastase kogemusega. Avariitööd 24/7. Tasuta kohapealne hindamine."',
        "block3_ex_massage": '„Massöör 5-aastase kogemusega. Spordi- ja lõõgastusmassaaž. Koduvisiidid."',
        "block3_cta":        "Paranda kirjeldust",
        "block4_title":      "Telefoninumber",
        "block4_body":       "Lisa telefon.",
        "block4_cta":        "Lisa",
        "cta_main":          "Ava oma profiil →",
        "footer_text":       "Saate selle e-kirja, kuna olete Nevumo registreeritud teenusepakkuja.",
        "footer_unsub":      "Tühista tellimus",
    },
    "fi": {
        "subject":           "{n} asiaa estää asiakkaita valitsemasta sinua",
        "preview":           "Profiilisi on aktiivinen — tässä on tarkalleen mitä sinun täytyy lisätä.",
        "hero_for":          "Vastaanottaja:",
        "hero_active":       "Nevumo-profiilisi on aktiivinen. ✓",
        "hero_found":        "Tarkistin sen ja löysin {n} asiaa, joita asiakkaat katsovat ennen asiantuntijan valitsemista — ja sinulta ne puuttuvat.",
        "hero_time":         "Niiden lisääminen kestää 3 minuuttia.",
        "block1_title":      "Profiilikuva",
        "block1_body":       "Profiilit ilman kuvaa saavat huomattavasti vähemmän kyselyjä. Asiakkaat haluavat tietää, kenen kanssa he työskentelevät.",
        "block1_cta":        "Lisää kuva",
        "block2_title":      "Kuvia töistäsi",
        "block2_body":       "Sinulla on tilaa 8 kuvalle. Asiakkaat päättävät silmillään — todellinen työ vakuuttaa enemmän kuin mikään kuvaus.",
        "block2_cta":        "Lisää kuvia",
        "block3_title":      "Kuvaus",
        "block3_body":       "Asiakkaat lukevat kuvauksen ennen yhteydenottoa. Jopa 2 lausetta tekee eron.",
        "block3_ex_cleaning": '„Siivousasiantuntija, jolla on 8 vuoden kokemus. Asunnot ja toimistot. Käytän ympäristöystävällisiä tuotteita."',
        "block3_ex_plumbing": '„Putkistospesialisti, jolla on 10 vuoden kokemus. Hätäkorjaukset 24/7. Ilmainen arviointi paikan päällä."',
        "block3_ex_massage": '„Hieroja, jolla on 5 vuoden kokemus. Urheilu- ja rentoutusmassage. Kotikäynnit."',
        "block3_cta":        "Paranna kuvausta",
        "block4_title":      "Puhelinnumero",
        "block4_body":       "Lisää puhelin.",
        "block4_cta":        "Lisää",
        "cta_main":          "Avaa profiilisi →",
        "footer_text":       "Saat tämän sähköpostin, koska olet rekisteröity palveluntarjoaja Nevumossa.",
        "footer_unsub":      "Peruuta tilaus",
    },
    "fr": {
        "subject":           "{n} choses empêchent les clients de vous choisir",
        "preview":           "Votre profil est actif — voici exactement ce que vous devez ajouter.",
        "hero_for":          "Pour :",
        "hero_active":       "Votre profil Nevumo est actif. ✓",
        "hero_found":        "Je l'ai vérifié et j'ai trouvé {n} choses que les clients regardent avant de choisir un spécialiste — et vous ne les avez pas.",
        "hero_time":         "Il faut 3 minutes pour les ajouter.",
        "block1_title":      "Photo de profil",
        "block1_body":       "Les profils sans photo reçoivent beaucoup moins de demandes. Les clients veulent savoir avec qui ils travaillent.",
        "block1_cta":        "Ajouter une photo",
        "block2_title":      "Photos de votre travail",
        "block2_body":       "Vous avez de la place pour 8 photos. Les clients décident avec les yeux — le vrai travail convainc plus que n'importe quelle description.",
        "block2_cta":        "Ajouter des photos",
        "block3_title":      "Description",
        "block3_body":       "Les clients lisent la description avant de vous contacter. Même 2 phrases font la différence.",
        "block3_ex_cleaning": '„Spécialiste du nettoyage avec 8 ans d\'expérience. Résidentiel et bureaux. Je travaille avec des produits écologiques."',
        "block3_ex_plumbing": '„Plombier avec 10 ans d\'expérience. Urgences 24/7. Devis gratuit sur place."',
        "block3_ex_massage":  '„Masseur avec 5 ans d\'expérience. Massage sportif et relaxant. Visites à domicile."',
        "block3_cta":        "Améliorer la description",
        "block4_title":      "Numéro de téléphone",
        "block4_body":       "Ajoutez un téléphone.",
        "block4_cta":        "Ajouter",
        "cta_main":          "Ouvrir mon profil →",
        "footer_text":       "Vous recevez cet e-mail parce que vous êtes un prestataire enregistré sur Nevumo.",
        "footer_unsub":      "Se désabonner",
    },
    "ga": {
        "subject":           "{n} rud ag cosc ar chliaint tú a roghnú",
        "preview":           "Tá do phróifíl gníomhach — seo go díreach cad is gá duit a chur leis.",
        "hero_for":          "Do:",
        "hero_active":       "Tá do phróifíl Nevumo gníomhach. ✓",
        "hero_found":        "Sheiceáil mé é agus fuair mé {n} rud a mheasann cliaint sula roghnaíonn siad speisialtóir — agus níl siad agat.",
        "hero_time":         "Tógann sé 3 nóiméad iad a chur leis.",
        "block1_title":      "Grianghraf próifíle",
        "block1_body":       "Faigheann próifílí gan grianghraf i bhfad níos lú fiosrúchán. Teastaíonn ó chliaint a fháil amach cé leis a bhfuil siad ag obair.",
        "block1_cta":        "Cuir grianghraf leis",
        "block2_title":      "Grianghraif de do chuid oibre",
        "block2_body":       "Tá áit agat do 8 grianghraf. Cinneann cliaint lena súile — dearbhaíonn obair fíor níos mó ná aon chur síos.",
        "block2_cta":        "Cuir grianghraif leis",
        "block3_title":      "Cur síos",
        "block3_body":       "Léann cliaint an cur síos sula dteangmhaíonn siad leat. Fiú amháin 2 abairt is leor.",
        "block3_ex_cleaning": '„Speisialtóir glantacháin le 8 mbliana taithí. Tithe agus oifigí. Oibrím le táirgí éiceolaíocha."',
        "block3_ex_plumbing": '„Pluiméir le 10 mbliana taithí. Éigeandálaí 24/7. Measúnú saor in aisce ar an láthair."',
        "block3_ex_massage": '„Masáisteoir le 5 bliana taithí. Spóirt agus masáiste suaimhnitheach. Cuairteanna baile."',
        "block3_cta":        "Feabhas a chur ar an gcur síos",
        "block4_title":      "Uimhir ghutháin",
        "block4_body":       "Cuir d'uimhir ghutháin leis.",
        "block4_cta":        "Cuir leis",
        "cta_main":          "Oscail do phróifíl →",
        "footer_text":       "Tá an ríomhphost seo á fháil agat toisc go bhfuil tú cláraithe mar sholáthraí ar Nevumo.",
        "footer_unsub":      "Dí-liostáil",
    },
}

def main() -> None:
    rows = [
        {"lang": lang, "key": f"{NAMESPACE}.{key}", "value": value}
        for lang, keys in TRANSLATIONS.items()
        for key, value in keys.items()
    ]
    with engine.begin() as conn:
        for row in rows:
            conn.execute(
                text("""
                    INSERT INTO translations (lang, key, value)
                    VALUES (:lang, :key, :value)
                    ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                """),
                row,
            )
    print(f"✅ Seeded {len(rows)} rows ({len(TRANSLATIONS)} languages)")

if __name__ == "__main__":
    main()
