"""
Seed script: cookies namespace — p24
Keys: s5_p_consent, s5_p_lang, s5_p_ga, s5_p_ga_id,
      s5_p_stripe_mid, s5_p_stripe_sid, s5_p_auth_token,
      s5_p_auth_user, s5_p_phone, s5_p_intent, s5_p_city, s5_p_auth_email
34 languages × 12 keys = 408 rows
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p24
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads")
engine = create_engine(DATABASE_URL)

NAMESPACE = "cookies"

TRANSLATIONS = {
    "s5_p_consent": {
        "en": "Records your cookie consent choices",
        "pl": "Rejestruje Twoje wybory dotyczące zgody na cookies",
        "bg": "Записва вашите избори за съгласие с бисквитки",
        "de": "Speichert Ihre Cookie-Einwilligungsentscheidungen",
        "fr": "Enregistre vos choix de consentement aux cookies",
        "es": "Registra sus opciones de consentimiento de cookies",
        "it": "Registra le tue scelte di consenso ai cookie",
        "pt": "Regista as suas opções de consentimento de cookies",
        "pt-PT": "Regista as suas opções de consentimento de cookies",
        "nl": "Slaat uw cookie-toestemmingskeuzes op",
        "cs": "Zaznamenává vaše volby souhlasu s cookies",
        "sk": "Zaznamenáva vaše voľby súhlasu s cookies",
        "hu": "Rögzíti a cookie-hozzájárulási döntéseit",
        "ro": "Înregistrează alegerile dvs. privind consimțământul la cookie-uri",
        "hr": "Bilježi vaše odabire pristanka na kolačiće",
        "sr": "Beleži vaše izbore pristanka na kolačiće",
        "sl": "Shranjuje vaše odločitve o soglasju za piškotke",
        "uk": "Записує ваші вибори щодо згоди на файли cookie",
        "ru": "Записывает ваши решения о согласии на файлы cookie",
        "tr": "Çerez onay tercihlerinizi kaydeder",
        "el": "Καταγράφει τις επιλογές συγκατάθεσης cookies σας",
        "da": "Registrerer dine cookiesamtykkevalg",
        "sv": "Registrerar dina cookiesamtyckesvalen",
        "no": "Registrerer dine valg for informasjonskapselsamtykke",
        "fi": "Tallentaa evästeiden suostumuspäätöksesi",
        "et": "Salvestab teie küpsiste nõusoleku valikud",
        "lv": "Reģistrē jūsu sīkdatņu piekrišanas izvēles",
        "lt": "Įrašo jūsų slapukų sutikimo pasirinkimus",
        "ga": "Taifeadann do roghanna toilithe fianán",
        "is": "Skráir val þitt á samþykki vafrakaka",
        "lb": "Späichert Är Cookie-Zoustëmmungswahlen",
        "mk": "Ги снима вашите избори за согласност за колачиња",
        "sq": "Regjistron zgjedhjet tuaja të miratimit të skedarëve të personalizimit",
        "mt": "Jirreġistra l-għażliet tiegħek tal-kunsens tal-cookies",
    },
    "s5_p_lang": {
        "en": "Stores your selected display language",
        "pl": "Przechowuje wybrany język wyświetlania",
        "bg": "Съхранява избрания от вас език за показване",
        "de": "Speichert Ihre ausgewählte Anzeigesprache",
        "fr": "Enregistre votre langue d'affichage sélectionnée",
        "es": "Almacena el idioma de visualización seleccionado",
        "it": "Memorizza la lingua di visualizzazione selezionata",
        "pt": "Armazena o idioma de visualização selecionado",
        "pt-PT": "Armazena o idioma de visualização selecionado",
        "nl": "Slaat uw geselecteerde weergavetaal op",
        "cs": "Ukládá vámi vybraný jazyk zobrazení",
        "sk": "Ukladá vami zvolený jazyk zobrazenia",
        "hu": "Tárolja a kiválasztott megjelenítési nyelvet",
        "ro": "Stochează limba de afișare selectată",
        "hr": "Pohranjuje odabrani jezik prikaza",
        "sr": "Čuva odabrani jezik prikaza",
        "sl": "Shrani izbrani jezik prikaza",
        "uk": "Зберігає вибрану мову відображення",
        "ru": "Сохраняет выбранный язык отображения",
        "tr": "Seçilen görüntüleme dilini kaydeder",
        "el": "Αποθηκεύει την επιλεγμένη γλώσσα εμφάνισης",
        "da": "Gemmer dit valgte visningssprog",
        "sv": "Lagrar ditt valda visningsspråk",
        "no": "Lagrer ditt valgte visningsspråk",
        "fi": "Tallentaa valitun näyttökielen",
        "et": "Salvestab teie valitud kuvamiskeele",
        "lv": "Saglabā jūsu izvēlēto attēlošanas valodu",
        "lt": "Išsaugo jūsų pasirinktą rodymų kalbą",
        "ga": "Stórálann do theanga taispeána roghnaithe",
        "is": "Geymir valið skjámál þitt",
        "lb": "Späichert Är ausgewielten Unzeigsproch",
        "mk": "Го чува вашиот избран јазик за прикажување",
        "sq": "Ruan gjuhën e shfaqjes të zgjedhur",
        "mt": "Jaħżen il-lingwa tal-wiri magħżula tiegħek",
    },
    "s5_p_ga": {
        "en": "Google Analytics — distinguishes unique users",
        "pl": "Google Analytics — rozróżnia unikatowych użytkowników",
        "bg": "Google Analytics — разграничава уникални потребители",
        "de": "Google Analytics — unterscheidet eindeutige Benutzer",
        "fr": "Google Analytics — distingue les utilisateurs uniques",
        "es": "Google Analytics — distingue usuarios únicos",
        "it": "Google Analytics — distingue gli utenti unici",
        "pt": "Google Analytics — distingue utilizadores únicos",
        "pt-PT": "Google Analytics — distingue utilizadores únicos",
        "nl": "Google Analytics — onderscheidt unieke gebruikers",
        "cs": "Google Analytics — rozlišuje jedinečné uživatele",
        "sk": "Google Analytics — rozlišuje jedinečných používateľov",
        "hu": "Google Analytics — megkülönbözteti az egyedi felhasználókat",
        "ro": "Google Analytics — distinge utilizatorii unici",
        "hr": "Google Analytics — razlikuje jedinstvene korisnike",
        "sr": "Google Analytics — razlikuje jedinstvene korisnike",
        "sl": "Google Analytics — razlikuje edinstvene uporabnike",
        "uk": "Google Analytics — розрізняє унікальних користувачів",
        "ru": "Google Analytics — различает уникальных пользователей",
        "tr": "Google Analytics — benzersiz kullanıcıları ayırt eder",
        "el": "Google Analytics — διακρίνει μοναδικούς χρήστες",
        "da": "Google Analytics — skelner unikke brugere",
        "sv": "Google Analytics — skiljer unika användare åt",
        "no": "Google Analytics — skiller unike brukere",
        "fi": "Google Analytics — erottaa yksilölliset käyttäjät",
        "et": "Google Analytics — eristab unikaalseid kasutajaid",
        "lv": "Google Analytics — izšķir unikālos lietotājus",
        "lt": "Google Analytics — skiria unikalius vartotojus",
        "ga": "Google Analytics — idirdhealaíonn úsáideoirí uathúla",
        "is": "Google Analytics — greinir einstaka notendur",
        "lb": "Google Analytics — ënnerscheet eenzegaarteg Benotzer",
        "mk": "Google Analytics — разликува уникатни корисници",
        "sq": "Google Analytics — dallon përdoruesit unikë",
        "mt": "Google Analytics — jiddistingwi utenti uniċi",
    },
    "s5_p_ga_id": {
        "en": "Google Analytics — session tracking",
        "pl": "Google Analytics — śledzenie sesji",
        "bg": "Google Analytics — проследяване на сесия",
        "de": "Google Analytics — Sitzungsverfolgung",
        "fr": "Google Analytics — suivi de session",
        "es": "Google Analytics — seguimiento de sesión",
        "it": "Google Analytics — monitoraggio della sessione",
        "pt": "Google Analytics — rastreamento de sessão",
        "pt-PT": "Google Analytics — rastreamento de sessão",
        "nl": "Google Analytics — sessietracking",
        "cs": "Google Analytics — sledování relace",
        "sk": "Google Analytics — sledovanie relácie",
        "hu": "Google Analytics — munkamenet-követés",
        "ro": "Google Analytics — urmărirea sesiunii",
        "hr": "Google Analytics — praćenje sesije",
        "sr": "Google Analytics — praćenje sesije",
        "sl": "Google Analytics — sledenje seji",
        "uk": "Google Analytics — відстеження сесії",
        "ru": "Google Analytics — отслеживание сеанса",
        "tr": "Google Analytics — oturum takibi",
        "el": "Google Analytics — παρακολούθηση συνεδρίας",
        "da": "Google Analytics — sessionssporing",
        "sv": "Google Analytics — sessionsspårning",
        "no": "Google Analytics — øktsporing",
        "fi": "Google Analytics — istunnon seuranta",
        "et": "Google Analytics — seansi jälgimine",
        "lv": "Google Analytics — sesijas izsekošana",
        "lt": "Google Analytics — sesijos stebėjimas",
        "ga": "Google Analytics — rianú seisiúin",
        "is": "Google Analytics — lota-eftirlit",
        "lb": "Google Analytics — Sessiounsverfollegung",
        "mk": "Google Analytics — следење на сесија",
        "sq": "Google Analytics — gjurmimi i sesionit",
        "mt": "Google Analytics — traċċar ta' sessjoni",
    },
    "s5_p_stripe_mid": {
        "en": "Stripe fraud prevention — device fingerprint",
        "pl": "Zapobieganie oszustwom Stripe — odcisk urządzenia",
        "bg": "Предотвратяване на измами от Stripe — пръстов отпечатък на устройство",
        "de": "Stripe-Betrugsprävention — Gerätefingerabdruck",
        "fr": "Prévention de la fraude Stripe — empreinte de l'appareil",
        "es": "Prevención de fraude de Stripe — huella digital del dispositivo",
        "it": "Prevenzione frodi Stripe — impronta digitale del dispositivo",
        "pt": "Prevenção de fraude Stripe — impressão digital do dispositivo",
        "pt-PT": "Prevenção de fraude Stripe — impressão digital do dispositivo",
        "nl": "Stripe fraudepreventie — apparaatvingerafdruk",
        "cs": "Prevence podvodů Stripe — otisk zařízení",
        "sk": "Prevencia podvodov Stripe — odtlačok zariadenia",
        "hu": "Stripe csalásmegelőzés — eszközlenyomat",
        "ro": "Prevenirea fraudei Stripe — amprenta dispozitivului",
        "hr": "Sprečavanje prijevare Stripe — otisak uređaja",
        "sr": "Sprečavanje prevara Stripe — otisak uređaja",
        "sl": "Preprečevanje goljufij Stripe — prstni odtis naprave",
        "uk": "Захист від шахрайства Stripe — відбиток пристрою",
        "ru": "Защита от мошенничества Stripe — отпечаток устройства",
        "tr": "Stripe sahtekarlık önleme — cihaz parmak izi",
        "el": "Πρόληψη απάτης Stripe — αποτύπωμα συσκευής",
        "da": "Stripe svindelforebyggelse — enhedsfingeraftryk",
        "sv": "Stripe bedrägeriförebyggande — enhetsfingeravtryck",
        "no": "Stripe svindelforebygging — enhetsfingeravtrykk",
        "fi": "Stripe-petoksentorjunta — laitteen sormenjälki",
        "et": "Stripe pettuste ennetamine — seadme sõrmejälg",
        "lv": "Stripe krāpšanas novēršana — ierīces nospiedums",
        "lt": "Stripe sukčiavimo prevencija — įrenginio pirštų atspaudas",
        "ga": "Cosc calaoise Stripe — méarlorg gléis",
        "is": "Stripe svikavarnir — fingrafaravistun tækis",
        "lb": "Stripe Bedruchspräventioun — Apparat-Fingerofdreck",
        "mk": "Stripe спречување измами — отпечаток на уред",
        "sq": "Parandalimi i mashtrimit Stripe — gjurma e pajisjes",
        "mt": "Prevenzjoni tal-frodi Stripe — fingerprint tal-apparat",
    },
    "s5_p_stripe_sid": {
        "en": "Stripe fraud prevention — session identifier",
        "pl": "Zapobieganie oszustwom Stripe — identyfikator sesji",
        "bg": "Предотвратяване на измами от Stripe — идентификатор на сесия",
        "de": "Stripe-Betrugsprävention — Sitzungskennung",
        "fr": "Prévention de la fraude Stripe — identifiant de session",
        "es": "Prevención de fraude de Stripe — identificador de sesión",
        "it": "Prevenzione frodi Stripe — identificatore di sessione",
        "pt": "Prevenção de fraude Stripe — identificador de sessão",
        "pt-PT": "Prevenção de fraude Stripe — identificador de sessão",
        "nl": "Stripe fraudepreventie — sessie-id",
        "cs": "Prevence podvodů Stripe — identifikátor relace",
        "sk": "Prevencia podvodov Stripe — identifikátor relácie",
        "hu": "Stripe csalásmegelőzés — munkamenet-azonosító",
        "ro": "Prevenirea fraudei Stripe — identificator de sesiune",
        "hr": "Sprečavanje prijevare Stripe — identifikator sesije",
        "sr": "Sprečavanje prevara Stripe — identifikator sesije",
        "sl": "Preprečevanje goljufij Stripe — identifikator seje",
        "uk": "Захист від шахрайства Stripe — ідентифікатор сесії",
        "ru": "Защита от мошенничества Stripe — идентификатор сеанса",
        "tr": "Stripe sahtekarlık önleme — oturum tanımlayıcısı",
        "el": "Πρόληψη απάτης Stripe — αναγνωριστικό συνεδρίας",
        "da": "Stripe svindelforebyggelse — sessionsidentifikator",
        "sv": "Stripe bedrägeriförebyggande — sessionsidentifierare",
        "no": "Stripe svindelforebygging — øktidentifikator",
        "fi": "Stripe-petoksentorjunta — istuntotunniste",
        "et": "Stripe pettuste ennetamine — seansi identifikaator",
        "lv": "Stripe krāpšanas novēršana — sesijas identifikators",
        "lt": "Stripe sukčiavimo prevencija — sesijos identifikatorius",
        "ga": "Cosc calaoise Stripe — aitheantóir seisiúin",
        "is": "Stripe svikavarnir — lotuskilríki",
        "lb": "Stripe Bedruchspräventioun — Sessiounsidentifizéierer",
        "mk": "Stripe спречување измами — идентификатор на сесија",
        "sq": "Parandalimi i mashtrimit Stripe — identifikues i sesionit",
        "mt": "Prevenzjoni tal-frodi Stripe — identifikatur tas-sessjoni",
    },
    "s5_p_auth_token": {
        "en": "Authentication JWT — keeps you logged in",
        "pl": "JWT uwierzytelniania — utrzymuje sesję logowania",
        "bg": "JWT за удостоверяване — поддържа ви влезли в профила",
        "de": "Authentifizierungs-JWT — hält Sie angemeldet",
        "fr": "JWT d'authentification — vous maintient connecté",
        "es": "JWT de autenticación — le mantiene conectado",
        "it": "JWT di autenticazione — ti mantiene connesso",
        "pt": "JWT de autenticação — mantém-no com sessão iniciada",
        "pt-PT": "JWT de autenticação — mantém-no com sessão iniciada",
        "nl": "Authenticatie-JWT — houdt u ingelogd",
        "cs": "Autentizační JWT — udržuje vás přihlášeného",
        "sk": "Autentifikačný JWT — udržuje vás prihláseného",
        "hu": "Hitelesítési JWT — bejelentkezve tart",
        "ro": "JWT de autentificare — vă menține autentificat",
        "hr": "JWT za autentikaciju — ostajete prijavljeni",
        "sr": "JWT za autentikaciju — ostajete prijavljeni",
        "sl": "Overiteljski JWT — ohranja vaš prijavljeni status",
        "uk": "Автентифікаційний JWT — підтримує вас у системі",
        "ru": "Аутентификационный JWT — поддерживает вас авторизованным",
        "tr": "Kimlik doğrulama JWT'si — oturumunuzu açık tutar",
        "el": "JWT πιστοποίησης — σας διατηρεί συνδεδεμένο",
        "da": "Godkendelses-JWT — holder dig logget ind",
        "sv": "Autentiserings-JWT — håller dig inloggad",
        "no": "Autentiserings-JWT — holder deg innlogget",
        "fi": "Todennuksen JWT — pitää sinut kirjautuneena",
        "et": "Autentimise JWT — hoiab teid sisse logituna",
        "lv": "Autentifikācijas JWT — uztur jūs pieteikušos",
        "lt": "Autentifikacijos JWT — palaiko jūsų prisijungimą",
        "ga": "JWT fíordheimhnithe — coinníonn tú logáilte isteach",
        "is": "Auðkenningar-JWT — heldur þér innskráðum",
        "lb": "Authentifizéierungs-JWT — hält Iech ageloggt",
        "mk": "JWT за автентикација — ве одржува најавени",
        "sq": "JWT i autentifikimit — ju mban të kyçur",
        "mt": "JWT ta' awtentikazzjoni — iżommok dħul",
    },
    "s5_p_auth_user": {
        "en": "Cached user profile data (id, name, role)",
        "pl": "Zbuforowane dane profilu użytkownika (id, imię, rola)",
        "bg": "Кеширани данни за потребителски профил (id, ime, роля)",
        "de": "Zwischengespeicherte Benutzerprofildaten (ID, Name, Rolle)",
        "fr": "Données de profil utilisateur mises en cache (id, nom, rôle)",
        "es": "Datos de perfil de usuario en caché (id, nombre, rol)",
        "it": "Dati profilo utente in cache (id, nome, ruolo)",
        "pt": "Dados de perfil de utilizador em cache (id, nome, função)",
        "pt-PT": "Dados de perfil de utilizador em cache (id, nome, função)",
        "nl": "Gecachte gebruikersprofielgegevens (id, naam, rol)",
        "cs": "Uložená data profilu uživatele (id, jméno, role)",
        "sk": "Uložené údaje profilu používateľa (id, meno, rola)",
        "hu": "Gyorsítótárban tárolt felhasználói profiladatok (id, név, szerepkör)",
        "ro": "Date de profil de utilizator în cache (id, nume, rol)",
        "hr": "Predmemorirani podaci korisničkog profila (id, ime, uloga)",
        "sr": "Keširani podaci korisničkog profila (id, ime, uloga)",
        "sl": "Predpomnilniški podatki profila (id, ime, vloga)",
        "uk": "Кешовані дані профілю користувача (id, ім'я, роль)",
        "ru": "Кешированные данные профиля пользователя (id, имя, роль)",
        "tr": "Önbellekteki kullanıcı profili verileri (id, ad, rol)",
        "el": "Δεδομένα προφίλ χρήστη σε cache (id, όνομα, ρόλος)",
        "da": "Cachelagrede brugerprofildata (id, navn, rolle)",
        "sv": "Cachade användarprofildata (id, namn, roll)",
        "no": "Bufrede brukerprofildata (id, navn, rolle)",
        "fi": "Välimuistiin tallennetut käyttäjäprofiilitiedot (id, nimi, rooli)",
        "et": "Vahemällu salvestatud kasutajaprofiili andmed (id, nimi, roll)",
        "lv": "Kešotie lietotāja profila dati (id, vārds, loma)",
        "lt": "Talpykloje saugomi vartotojo profilio duomenys (id, vardas, vaidmuo)",
        "ga": "Sonraí próifíle úsáideora i dtaisce (id, ainm, ról)",
        "is": "Geymd notandaprófílgögn (id, nafn, hlutverk)",
        "lb": "Gecachten Benotzerprofildaten (id, Numm, Roll)",
        "mk": "Кеширани податоци на кориснички профил (id, ime, улога)",
        "sq": "Të dhëna të profilit të përdoruesit në cache (id, emër, rol)",
        "mt": "Data tal-profil tal-utent fil-cache (id, isem, rwol)",
    },
    "s5_p_phone": {
        "en": "Phone number autofill",
        "pl": "Autouzupełnianie numeru telefonu",
        "bg": "Автоматично попълване на телефонен номер",
        "de": "Automatisches Ausfüllen der Telefonnummer",
        "fr": "Saisie automatique du numéro de téléphone",
        "es": "Autocompletado del número de teléfono",
        "it": "Compilazione automatica del numero di telefono",
        "pt": "Preenchimento automático do número de telefone",
        "pt-PT": "Preenchimento automático do número de telefone",
        "nl": "Automatisch invullen van telefoonnummer",
        "cs": "Automatické vyplnění telefonního čísla",
        "sk": "Automatické vyplnenie telefónneho čísla",
        "hu": "Telefonszám automatikus kitöltése",
        "ro": "Completare automată a numărului de telefon",
        "hr": "Automatsko popunjavanje broja telefona",
        "sr": "Automatsko popunjavanje broja telefona",
        "sl": "Samodejna zapolnitev telefonske številke",
        "uk": "Автозаповнення номера телефону",
        "ru": "Автозаполнение номера телефона",
        "tr": "Telefon numarası otomatik doldurma",
        "el": "Αυτόματη συμπλήρωση αριθμού τηλεφώνου",
        "da": "Automatisk udfyldning af telefonnummer",
        "sv": "Autofyll av telefonnummer",
        "no": "Automatisk utfylling av telefonnummer",
        "fi": "Puhelinnumeron automaattinen täyttö",
        "et": "Telefoninumbri automaatne täitmine",
        "lv": "Automātiskā tālruņa numura aizpilde",
        "lt": "Automatinis telefono numerio užpildymas",
        "ga": "Uathlíonadh uimhir ghutháin",
        "is": "Sjálfvirk útfylling símanúmers",
        "lb": "Automatesch Ausfëllen vun der Telefonsnummer",
        "mk": "Автоматско пополнување на телефонски број",
        "sq": "Plotësim automatik i numrit të telefonit",
        "mt": "Awtokompletar tan-numru tat-telefon",
    },
    "s5_p_intent": {
        "en": "Stores your selected role intent (client / provider)",
        "pl": "Przechowuje wybraną rolę (klient / usługodawca)",
        "bg": "Съхранява избраната роля (клиент / доставчик)",
        "de": "Speichert Ihre gewählte Rollenpräferenz (Kunde / Anbieter)",
        "fr": "Enregistre votre rôle sélectionné (client / prestataire)",
        "es": "Almacena su intención de rol seleccionada (cliente / proveedor)",
        "it": "Memorizza il ruolo selezionato (cliente / fornitore)",
        "pt": "Armazena a intenção de papel selecionada (cliente / prestador)",
        "pt-PT": "Armazena a intenção de papel selecionada (cliente / prestador)",
        "nl": "Slaat uw geselecteerde rolintentie op (klant / aanbieder)",
        "cs": "Ukládá vámi zvolenou roli (klient / poskytovatel)",
        "sk": "Ukladá vami zvolenú rolu (klient / poskytovateľ)",
        "hu": "Tárolja a kiválasztott szerepkört (ügyfél / szolgáltató)",
        "ro": "Stochează rolul selectat (client / furnizor)",
        "hr": "Pohranjuje odabranu ulogu (klijent / pružatelj usluge)",
        "sr": "Čuva odabranu ulogu (klijent / pružalac usluge)",
        "sl": "Shrani izbrano vlogo (stranka / ponudnik)",
        "uk": "Зберігає вибрану роль (клієнт / постачальник)",
        "ru": "Сохраняет выбранную роль (клиент / поставщик)",
        "tr": "Seçilen rol amacını kaydeder (müşteri / hizmet sağlayıcı)",
        "el": "Αποθηκεύει τον επιλεγμένο ρόλο (πελάτης / πάροχος)",
        "da": "Gemmer din valgte rollehensigt (klient / udbyder)",
        "sv": "Lagrar din valda rollintention (klient / leverantör)",
        "no": "Lagrer din valgte rolleintensjon (klient / leverandør)",
        "fi": "Tallentaa valitun rooliaikomuksen (asiakas / palveluntarjoaja)",
        "et": "Salvestab teie valitud rolli (klient / teenusepakkuja)",
        "lv": "Saglabā jūsu izvēlēto lomu (klients / pakalpojumu sniedzējs)",
        "lt": "Išsaugo jūsų pasirinktą vaidmenį (klientas / paslaugų teikėjas)",
        "ga": "Stórálann d'intinn róil roghnaithe (cliant / soláthraí)",
        "is": "Geymir valdar hlutverkshvatar þínar (viðskiptavinur / þjónustuaðili)",
        "lb": "Späichert Är gewielten Roll (Client / Prestataire)",
        "mk": "Ја чува вашата избрана улога (клиент / давател на услуга)",
        "sq": "Ruan qëllimin e rolit të zgjedhur (klient / ofrues)",
        "mt": "Jaħżen l-intenzjoni tar-rwol magħżul tiegħek (klijent / fornitur)",
    },
    "s5_p_city": {
        "en": "Stores your selected city",
        "pl": "Przechowuje wybrane miasto",
        "bg": "Съхранява избрания град",
        "de": "Speichert Ihre ausgewählte Stadt",
        "fr": "Enregistre votre ville sélectionnée",
        "es": "Almacena su ciudad seleccionada",
        "it": "Memorizza la città selezionata",
        "pt": "Armazena a cidade selecionada",
        "pt-PT": "Armazena a cidade selecionada",
        "nl": "Slaat uw geselecteerde stad op",
        "cs": "Ukládá vámi vybrané město",
        "sk": "Ukladá vami zvolené mesto",
        "hu": "Tárolja a kiválasztott várost",
        "ro": "Stochează orașul selectat",
        "hr": "Pohranjuje odabrani grad",
        "sr": "Čuva odabrani grad",
        "sl": "Shrani izbrano mesto",
        "uk": "Зберігає вибране місто",
        "ru": "Сохраняет выбранный город",
        "tr": "Seçilen şehri kaydeder",
        "el": "Αποθηκεύει την επιλεγμένη πόλη",
        "da": "Gemmer din valgte by",
        "sv": "Lagrar din valda stad",
        "no": "Lagrer din valgte by",
        "fi": "Tallentaa valitun kaupungin",
        "et": "Salvestab teie valitud linna",
        "lv": "Saglabā jūsu izvēlēto pilsētu",
        "lt": "Išsaugo jūsų pasirinktą miestą",
        "ga": "Stórálann do chathair roghnaithe",
        "is": "Geymir valda borg þína",
        "lb": "Späichert Är ausgewielten Stad",
        "mk": "Го чува вашиот избран град",
        "sq": "Ruan qytetin tuaj të zgjedhur",
        "mt": "Jaħżen il-belt magħżula tiegħek",
    },
    "s5_p_auth_email": {
        "en": "Temporarily stores email address during registration",
        "pl": "Tymczasowo przechowuje adres e-mail podczas rejestracji",
        "bg": "Временно съхранява имейл адрес по време на регистрация",
        "de": "Speichert die E-Mail-Adresse vorübergehend während der Registrierung",
        "fr": "Stocke temporairement l'adresse e-mail lors de l'inscription",
        "es": "Almacena temporalmente la dirección de correo electrónico durante el registro",
        "it": "Memorizza temporaneamente l'indirizzo e-mail durante la registrazione",
        "pt": "Armazena temporariamente o endereço de e-mail durante o registo",
        "pt-PT": "Armazena temporariamente o endereço de e-mail durante o registo",
        "nl": "Slaat het e-mailadres tijdelijk op tijdens registratie",
        "cs": "Dočasně ukládá e-mailovou adresu během registrace",
        "sk": "Dočasne ukladá e-mailovú adresu počas registrácie",
        "hu": "Átmenetileg tárolja az e-mail-címet a regisztráció során",
        "ro": "Stochează temporar adresa de e-mail în timpul înregistrării",
        "hr": "Privremeno pohranjuje adresu e-pošte tijekom registracije",
        "sr": "Privremeno čuva adresu e-pošte tokom registracije",
        "sl": "Začasno shrani e-poštni naslov med registracijo",
        "uk": "Тимчасово зберігає адресу електронної пошти під час реєстрації",
        "ru": "Временно сохраняет адрес электронной почты в процессе регистрации",
        "tr": "Kayıt sırasında e-posta adresini geçici olarak kaydeder",
        "el": "Αποθηκεύει προσωρινά τη διεύθυνση e-mail κατά την εγγραφή",
        "da": "Gemmer midlertidigt e-mailadresse under registrering",
        "sv": "Lagrar tillfälligt e-postadress under registrering",
        "no": "Lagrer midlertidig e-postadresse under registrering",
        "fi": "Tallentaa tilapäisesti sähköpostiosoitteen rekisteröinnin aikana",
        "et": "Salvestab registreerimise ajal ajutiselt e-posti aadressi",
        "lv": "Uz laiku saglabā e-pasta adresi reģistrācijas laikā",
        "lt": "Laikinai išsaugo el. pašto adresą registracijos metu",
        "ga": "Stórálann seoladh ríomhphoist go sealadach le linn clárúcháin",
        "is": "Geymir netfang tímabundið við skráningu",
        "lb": "Späichert d'E-Mail-Adress temporär während der Registréierung",
        "mk": "Привремено го чува е-маил адресата за време на регистрацијата",
        "sq": "Ruan përkohësisht adresën e emailit gjatë regjistrimit",
        "mt": "Jaħżen temporanjament l-indirizz tal-email matul ir-reġistrazzjoni",
    },
}


def seed():
    with engine.begin() as conn:
        count = 0
        for key, lang_map in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_map.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (lang, key, value)
                        VALUES (:lang, :key, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        print(f"[seed_cookies_p24] Upserted {count} rows.")


if __name__ == "__main__":
    seed()
