"""
seed_provider_terms_p14_art7_body.py  —  Nevumo | namespace: provider_terms
Key: art7_body  (1 key x 34 langs = 34 rows)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_provider_terms_p14_art7_body
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "provider_terms"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "art7_body": {
        "en": (
            "7.1 You agree to:\n"
            "- provide services to Clients in a professional, diligent, and timely manner;\n"
            "- maintain all licences, permits, and insurances required by applicable law for the services you offer;\n"
            "- respond to Client Leads within a reasonable time;\n"
            "- update your Profile and Service Listings to reflect current availability and pricing;\n"
            "- treat Clients with respect and without discrimination;\n"
            "- comply with all applicable laws, including consumer protection, data protection, and tax regulations.\n\n"
            "7.2 You must not:\n"
            "- submit false or manipulated reviews about yourself or other Providers;\n"
            "- contact Clients outside the Platform for the purpose of bypassing Nevumo's intermediary services during an active transaction;\n"
            "- misuse or attempt to scrape Platform data;\n"
            "- attempt to gain unauthorised access to other accounts or Platform systems;\n"
            "- engage in fraudulent or deceptive practices of any kind."
        ),
        "pl": (
            "7.1 Dostawca zobowiązuje się:\n"
            "- świadczyć usługi na rzecz Klientów w sposób profesjonalny, staranny i terminowy;\n"
            "- posiadać wszelkie zezwolenia, licencje i ubezpieczenia wymagane przez obowiązujące przepisy prawa w związku z oferowanymi usługami;\n"
            "- odpowiadać na Zapytania Klientów w rozsądnym terminie;\n"
            "- aktualizować Profil i Oferty Usług tak, aby odzwierciedlały aktualną dostępność i ceny;\n"
            "- traktować Klientów z szacunkiem i bez dyskryminacji;\n"
            "- przestrzegać wszelkich obowiązujących przepisów prawa, w tym przepisów o ochronie konsumentów, ochronie danych osobowych i przepisów podatkowych.\n\n"
            "7.2 Dostawcy zabrania się:\n"
            "- wystawiania fałszywych lub zmanipulowanych opinii o sobie lub innych Dostawcach;\n"
            "- kontaktowania się z Klientami poza Platformą w celu ominięcia usług pośrednictwa Nevumo w trakcie aktywnej transakcji;\n"
            "- nadużywania lub próby zescrapowania danych Platformy;\n"
            "- próby uzyskania nieautoryzowanego dostępu do innych kont lub systemów Platformy;\n"
            "- podejmowania jakichkolwiek działań o charakterze oszukańczym lub wprowadzającym w błąd."
        ),
        "bg": (
            "7.1 Доставчикът се задължава:\n"
            "- да предоставя услуги на Клиентите по професионален, грижлив и навременен начин;\n"
            "- да притежава всички лицензи, разрешителни и застраховки, изисквани от приложимото законодателство за предлаганите услуги;\n"
            "- да отговаря на Запитвания от Клиенти в разумен срок;\n"
            "- да актуализира своя Профил и Обявите за услуги, така че да отразяват актуалната наличност и цени;\n"
            "- да третира Клиентите с уважение и без дискриминация;\n"
            "- да спазва всички приложими правни норми, включително в областта на защитата на потребителите, защитата на личните данни и данъчното законодателство.\n\n"
            "7.2 На Доставчика е забранено:\n"
            "- да публикува неверни или манипулирани отзиви за себе си или за други Доставчици;\n"
            "- да се свързва с Клиенти извън Платформата с цел заобикаляне на посредническите услуги на Nevumo по време на активна транзакция;\n"
            "- да злоупотребява с или да прави опити да скрейпва данни от Платформата;\n"
            "- да прави опити за неоторизиран достъп до други акаунти или системи на Платформата;\n"
            "- да извършва действия с измамен или подвеждащ характер от какъвто и да е вид."
        ),
        "de": (
            "7.1 Sie stimmen zu:\n"
            "- Dienstleistungen für Kunden professionell, sorgfältig und zeitnah zu erbringen;\n"
            "- alle Lizenzen, Genehmigungen und Versicherungen aufrechtzuerhalten, die nach geltendem Recht für die von Ihnen angebotenen Dienstleistungen erforderlich sind;\n"
            "- auf Kundenanfragen innerhalb einer angemessenen Frist zu antworten;\n"
            "- Ihr Profil und Ihre Serviceangebote zu aktualisieren, um die aktuelle Verfügbarkeit und Preisgestaltung widerzuspiegeln;\n"
            "- Kunden mit Respekt und ohne Diskriminierung zu behandeln;\n"
            "- alle geltenden Gesetze, einschließlich Verbraucherschutz, Datenschutz und Steuervorschriften, einzuhalten.\n\n"
            "7.2 Es ist Ihnen untersagt:\n"
            "- falsche oder manipulierte Bewertungen über sich selbst oder andere Anbieter abzugeben;\n"
            "- Kunden außerhalb der Plattform zu kontaktieren, um die Vermittlungsdienste von Nevumo während einer aktiven Transaktion zu umgehen;\n"
            "- Plattformdaten zu missbrauchen oder zu versuchen, sie zu scrapen;\n"
            "- zu versuchen, unbefugten Zugriff auf andere Konten oder Plattformsysteme zu erlangen;\n"
            "- sich an betrügerischen oder irreführenden Praktiken jeglicher Art zu beteiligen."
        ),
        "fr": (
            "7.1 Vous acceptez de :\n"
            "- fournir des services aux Clients de manière professionnelle, diligente et opportune ;\n"
            "- maintenir toutes les licences, permis et assurances requis par la loi applicable pour les services que vous offrez ;\n"
            "- répondre aux demandes des Clients dans un délai raisonnable ;\n"
            "- mettre à jour votre Profil et vos offres de services pour refléter la disponibilité et les prix actuels ;\n"
            "- traiter les Clients avec respect et sans discrimination ;\n"
            "- respecter toutes les lois applicables, y compris la protection des consommateurs, la protection des données et les réglementations fiscales.\n\n"
            "7.2 Vous ne devez pas :\n"
            "- soumettre des avis faux ou manipulés sur vous-même ou sur d'autres Prestataires ;\n"
            "- contacter des Clients en dehors de la Plateforme dans le but de contourner les services d'intermédiation de Nevumo lors d'une transaction active ;\n"
            "- utiliser abusivement ou tenter de récupérer (scraper) les données de la Plateforme ;\n"
            "- tenter d'obtenir un accès non autorisé à d'autres comptes ou systèmes de la Plateforme ;\n"
            "- vous engager dans des pratiques frauduleuses ou trompeuses de quelque nature que ce soit."
        ),
        "es": (
            "7.1 Usted se compromete a:\n"
            "- prestar servicios a los Clientes de manera profesional, diligente y oportuna;\n"
            "- mantener todas las licencias, permisos y seguros requeridos por la ley aplicable para los servicios que ofrece;\n"
            "- responder a las solicitudes de los Clientes en un plazo razonable;\n"
            "- actualizar su Perfil y Listados de Servicios para reflejar la disponibilidad y los precios actuales;\n"
            "- tratar a los Clientes con respeto y sin discriminación;\n"
            "- cumplir con todas las leyes aplicables, incluyendo la protección del consumidor, protección de datos y normativas fiscales.\n\n"
            "7.2 Usted no debe:\n"
            "- enviar reseñas falsas o manipuladas sobre usted u otros Proveedores;\n"
            "- contactar a los Clientes fuera de la Plataforma con el fin de eludir los servicios de intermediación de Nevumo durante una transacción activa;\n"
            "- hacer un mal uso o intentar extraer datos de la Plataforma;\n"
            "- intentar obtener acceso no autorizado a otras cuentas o sistemas de la Plataforma;\n"
            "- participar en prácticas fraudulentas o engañosas de cualquier tipo."
        ),
        "it": (
            "7.1 Accetti di:\n"
            "- fornire servizi ai Clienti in modo professionale, diligente e tempestivo;\n"
            "- mantenere tutte le licenze, i permessi e le assicurazioni richiesti dalla legge applicabile per i servizi offerti;\n"
            "- rispondere alle richieste dei Clienti in tempi ragionevoli;\n"
            "- aggiornare il tuo Profilo e gli Annunci dei Servizi per riflettere l'attuale disponibilità e i prezzi;\n"
            "- trattare i Clienti con rispetto e senza discriminazioni;\n"
            "- rispettare tutte le leggi applicabili, inclusa la protezione dei consumatori, la protezione dei dati e le normative fiscali.\n\n"
            "7.2 Non devi:\n"
            "- inviare recensioni false o manipolate su te stesso o su altri Fornitori;\n"
            "- contattare i Clienti al di fuori della Piattaforma allo scopo di aggirare i servizi di intermediazione di Nevumo durante una transazione attiva;\n"
            "- abusare o tentare di effettuare lo scraping dei dati della Piattaforma;\n"
            "- tentare di ottenere un accesso non autorizzato ad altri account o ai sistemi della Piattaforma;\n"
            "- intraprendere pratiche fraudolente o ingannevoli di alcun tipo."
        ),
        "nl": (
            "7.1 U gaat ermee akkoord om:\n"
            "- diensten aan Klanten op een professionele, zorgvuldige en tijdige manier te verlenen;\n"
            "- alle licenties, vergunningen en verzekeringen te behouden die volgens de toepasselijke wetgeving vereist zijn voor de diensten die u aanbiedt;\n"
            "- binnen een redelijke termijn te reageren op aanvragen van Klanten;\n"
            "- uw Profiel en Dienstvermeldingen bij te werken om de huidige beschikbaarheid en prijzen weer te geven;\n"
            "- Klanten met respect en zonder discriminatie te behandelen;\n"
            "- te voldoen aan alle toepasselijke wetten, inclusief consumentenbescherming, gegevensbescherming en belastingvoorschriften.\n\n"
            "7.2 Het is u niet toegestaan om:\n"
            "- valse of gemanipuleerde beoordelingen over uzelf of andere Dienstverleners in te dienen;\n"
            "- contact op te nemen met Klanten buiten het Platform met het doel de bemiddelingsdiensten van Nevumo tijdens een actieve transactie te omzeilen;\n"
            "- Platformgegevens te misbruiken of te proberen te scrapen;\n"
            "- proberen onbevoegde toegang te krijgen tot andere accounts of Platformsystemen;\n"
            "- zich in te laten met frauduleuze of misleidende praktijken van welke aard dan ook."
        ),
        "pt": (
            "7.1 O Prestador concorda em:\n"
            "- prestar serviços aos Clientes de forma profissional, diligente e atempada;\n"
            "- manter todas as licenças, autorizações e seguros exigidos pela lei aplicável para os serviços que oferece;\n"
            "- responder aos pedidos dos Clientes num prazo razoável;\n"
            "- atualizar o seu Perfil e Listagens de Serviços para refletir a disponibilidade e os preços atuais;\n"
            "- tratar os Clientes com respeito e sem discriminação;\n"
            "- cumprir todas as leis aplicáveis, incluindo a defesa do consumidor, proteção de dados e regulamentos fiscais.\n\n"
            "7.2 O Prestador não deve:\n"
            "- enviar avaliações falsas ou manipuladas sobre si próprio ou outros Prestadores;\n"
            "- contactar Clientes fora da Plataforma com o objetivo de contornar os serviços de intermediação da Nevumo durante uma transação ativa;\n"
            "- utilizar indevidamente ou tentar extrair (scrape) dados da Plataforma;\n"
            "- tentar obter acesso não autorizado a outras contas ou sistemas da Plataforma;\n"
            "- envolver-se em práticas fraudulentas ou enganosas de qualquer tipo."
        ),
        "pt-PT": (
            "7.1 O Prestador concorda em:\n"
            "- prestar serviços aos Clientes de forma profissional, diligente e atempada;\n"
            "- manter todas as licenças, autorizações e seguros exigidos pela lei aplicável para os serviços que oferece;\n"
            "- responder aos pedidos dos Clientes num prazo razoável;\n"
            "- atualizar o seu Perfil e Listagens de Serviços para refletir a disponibilidade e os preços atuais;\n"
            "- tratar os Clientes com respeito e sem discriminação;\n"
            "- cumprir todas as leis aplicáveis, incluindo a defesa do consumidor, proteção de dados e regulamentos fiscais.\n\n"
            "7.2 O Prestador não deve:\n"
            "- enviar avaliações falsas ou manipuladas sobre si próprio ou outros Prestadores;\n"
            "- contactar Clientes fora da Plataforma com o objetivo de contornar os serviços de intermediação da Nevumo durante uma transação ativa;\n"
            "- utilizar indevidamente ou tentar extrair (scrape) dados da Plataforma;\n"
            "- tentar obter acesso não autorizado a outras contas ou sistemas da Plataforma;\n"
            "- envolver-se em práticas fraudulentas ou enganosas de qualquer tipo."
        ),
        "ro": (
            "7.1 Sunteți de acord să:\n"
            "- oferiți servicii Clienților într-o manieră profesională, diligentă și la timp;\n"
            "- mențineți toate licențele, permisele și asigurările solicitate de legea aplicabilă pentru serviciile pe care le oferiți;\n"
            "- răspundeți la solicitările Clienților într-un timp rezonabil;\n"
            "- actualizați Profilul și Listările de Servicii pentru a reflecta disponibilitatea și prețurile actuale;\n"
            "- tratați Clienții cu respect și fără discriminare;\n"
            "- respectați toate legile aplicabile, inclusiv protecția consumatorilor, protecția datelor și reglementările fiscale.\n\n"
            "7.2 Nu trebuie să:\n"
            "- trimiteți recenzii false sau manipulate despre dvs. sau despre alți Furnizori;\n"
            "- contactați Clienții în afara Platformei cu scopul de a ocoli serviciile de intermediere ale Nevumo în timpul unei tranzacții active;\n"
            "- utilizați abuziv sau să încercați să extrageți date de pe Platformă;\n"
            "- încercați să obțineți acces neautorizat la alte conturi sau sisteme ale Platformei;\n"
            "- vă angajați în practici frauduloase sau înșelătoare de orice fel."
        ),
        "ru": (
            "7.1 Вы соглашаетесь:\n"
            "- предоставлять услуги Клиентам профессионально, добросовестно и своевременно;\n"
            "- поддерживать все лицензии, разрешения и страховки, требуемые применимым законодательством для предлагаемых вами услуг;\n"
            "- отвечать на запросы Клиентов в разумные сроки;\n"
            "- обновлять свой Профиль и Списки услуг, чтобы они отражали текущую доступность и цены;\n"
            "- относиться к Клиентам с уважением и без дискриминации;\n"
            "- соблюдать все применимые законы, включая защиту прав потребителей, защиту данных и налоговые правила.\n\n"
            "7.2 Вам запрещается:\n"
            "- отправлять ложные или манипулятивные отзывы о себе или других Поставщиках;\n"
            "- связываться с Клиентами за пределами Платформы с целью обхода посреднических услуг Nevumo во время активной транзакции;\n"
            "- злоупотреблять или пытаться извлекать (парсить) данные Платформы;\n"
            "- пытаться получить несанкционированный доступ к другим учетным записям или системам Платформы;\n"
            "- участвовать в мошеннических или вводящих в заблуждение действиях любого рода."
        ),
        "uk": (
            "7.1 Ви погоджуєтесь:\n"
            "- надавати послуги Клієнтам професійно, сумлінно та своєчасно;\n"
            "- підтримувати всі ліцензії, дозволи та страховки, які вимагаються чинним законодавством для послуг, які ви пропонуєте;\n"
            "- відповідати на запити Клієнтів у розумні терміни;\n"
            "- оновлювати свій Профіль та Списки послуг, щоб вони відображали поточну доступність та ціни;\n"
            "- ставитися до Клієнтів з повагою та без дискримінації;\n"
            "- дотримуватися всіх чинних законів, включаючи захист прав споживачів, захист даних та податкові правила.\n\n"
            "7.2 Вам забороняється:\n"
            "- надсилати неправдиві або маніпулятивні відгуки про себе або інших Постачальників;\n"
            "- зв'язуватися з Клієнтами поза Платформою з метою обходу посередницьких послуг Nevumo під час активної транзакції;\n"
            "- зловживати або намагатися витягувати (парсити) дані Платформи;\n"
            "- намагатися отримати несанкціонований доступ до інших облікових записів або систем Платформи;\n"
            "- брати участь у шахрайських або оманливих діях будь-якого роду."
        ),
        "cs": (
            "7.1 Souhlasíte, že budete:\n"
            "- poskytovat služby Klientům profesionálně, pečlivě a včas;\n"
            "- udržovat všechny licence, povolení a pojištění vyžadovaná platnými právními předpisy pro služby, které nabízíte;\n"
            "- odpovídat na poptávky Klientů v přiměřené lhůtě;\n"
            "- aktualizovat svůj Profil a Nabídky služeb, aby odrážely aktuální dostupnost a ceny;\n"
            "- zacházet s Klienty s respektem a bez diskriminace;\n"
            "- dodržovat všechny platné zákony, včetně ochrany spotřebitele, ochrany osobních údajů a daňových předpisů.\n\n"
            "7.2 Nesmíte:\n"
            "- předkládat falešné nebo zmanipulované recenze o sobě nebo jiných Poskytovatelích;\n"
            "- kontaktovat Klienty mimo Platformu za účelem obcházení zprostředkovatelských služeb společnosti Nevumo během aktivní transakce;\n"
            "- zneužívat nebo se pokoušet o scraping dat Platformy;\n"
            "- pokoušet se získat neoprávněný přístup k jiným účtům nebo systémům Platformy;\n"
            "- zapojit se do podvodných nebo klamavých praktik jakéhokoli druhu."
        ),
        "da": (
            "7.1 Du accepterer at:\n"
            "- levere tjenester til Kunder på en professionel, omhyggelig og rettidig måde;\n"
            "- opretholde alle licenser, tilladelser og forsikringer, der kræves i henhold til gældende lovgivning for de tjenester, du tilbyder;\n"
            "- svare på Kundehenvendelser inden for rimelig tid;\n"
            "- opdatere din Profil og Tjenestelister for at afspejle den aktuelle tilgængelighed og prisfastsættelse;\n"
            "- behandle Kunder med respekt og uden diskrimination;\n"
            "- overholde alle gældende love, herunder forbrugerbeskyttelse, databeskyttelse og skatteregler.\n\n"
            "7.2 Du må ikke:\n"
            "- indsende falske eller manipulerede anmeldelser om dig selv eller andre Udbydere;\n"
            "- kontakte Kunder uden for Platformen med det formål at omgå Nevumos formidlingstjenester under en aktiv transaktion;\n"
            "- misbruge eller forsøge at scrape Platformdata;\n"
            "- forsøge at få uautoriseret adgang til andre konti eller Platformsystemer;\n"
            "- deltage i svigagtig eller vildledende praksis af nogen art."
        ),
        "sv": (
            "7.1 Du godkänner att:\n"
            "- tillhandahålla tjänster till Kunder på ett professionellt, noggrant och i tid;\n"
            "- upprätthålla alla licenser, tillstånd och försäkringar som krävs enligt tillämplig lag för de tjänster du erbjuder;\n"
            "- svara på Kundförfrågningar inom rimlig tid;\n"
            "- uppdatera din Profil och Tjänsteannonser för att återspegla aktuell tillgänglighet och prissättning;\n"
            "- behandla Kunder med respekt och utan diskriminering;\n"
            "- följa alla tillämpliga lagar, inklusive konsumentskydd, dataskydd och skatteregler.\n\n"
            "7.2 Du får inte:\n"
            "- skicka in falska eller manipulerade recensioner om dig själv eller andra Leverantörer;\n"
            "- kontakta Kunder utanför Plattformen i syfte att kringgå Nevumos förmedlingstjänster under en aktiv transaktion;\n"
            "- missbruka eller försöka skrapa Plattformsdata;\n"
            "- försöka få obehörig åtkomst till andra konton eller Plattformsystem;\n"
            "- ägna dig åt bedrägliga eller vilseledande metoder av något slag."
        ),
        "no": (
            "7.1 Du godtar å:\n"
            "- yte tjenester til Kunder på en profesjonell, grundig og rettidig måte;\n"
            "- opprettholde alle lisenser, tillatelser og forsikringer som kreves i henhold til gjeldende lov for tjenestene du tilbyr;\n"
            "- svare på Kundehenvendelser innen rimelig tid;\n"
            "- oppdatere din Profil og Tjenesteoppføringer for å gjenspeile gjeldende tilgjengelighet og priser;\n"
            "- behandle Kunder med respekt og uten diskriminering;\n"
            "- overholde alle gjeldende lover, inkludert forbrukervern, personvern og skatteregler.\n\n"
            "7.2 Du må ikke:\n"
            "- sende inn falske eller manipulerte anmeldelser om deg selv eller andre Leverandører;\n"
            "- kontakte Kunder utenfor Plattformen for å omgå Nevumos formidlingstjenester under en aktiv transaksjon;\n"
            "- misbruke eller forsøke å skrape Plattformsdata;\n"
            "- forsøke å få uautorisert tilgang til andre kontoer eller Plattformsystemer;\n"
            "- engasjere deg i uredelig eller villedende praksis av noe slag."
        ),
        "fi": (
            "7.1 Suostut:\n"
            "- tarjoamaan palveluja Asiakkaille ammattimaisesti, huolellisesti ja oikea-aikaisesti;\n"
            "- ylläpitämään kaikkia sovellettavan lain edellyttämiä lisenssejä, lupia ja vakuutuksia tarjoamillesi palveluille;\n"
            "- vastaamaan Asiakkaiden tiedusteluihin kohtuullisessa ajassa;\n"
            "- päivittämään Profiilisi ja Palvelu-ilmoituksesi vastaamaan nykyistä saatavuutta ja hinnoittelua;\n"
            "- kohtelemaan Asiakkaita kunnioittavasti ja ilman syrjintää;\n"
            "- noudattamaan kaikkia sovellettavia lakeja, mukaan lukien kuluttajansuoja-, tietosuoja- ja veromääräykset.\n\n"
            "7.2 Et saa:\n"
            "- lähettää väärennettyjä tai manipuloituja arvosteluja itsestäsi tai muista Palveluntarjoajista;\n"
            "- ottaa yhteyttä Asiakkaisiin Alustan ulkopuolella Nevumon välityspalveluiden kiertämiseksi aktiivisen tapahtuman aikana;\n"
            "- väärinkäyttää tai yrittää kopioida (scrape) Alustan tietoja;\n"
            "- yrittää saada luvatonta pääsyä muihin tileihin tai Alustajärjestelmiin;\n"
            "- osallistua minkäänlaisiin vilpillisiin tai harhaanjohtaviin käytäntöihin."
        ),
        "et": (
            "7.1 Te nõustute:\n"
            "- osutama teenuseid Klientidele professionaalselt, hoolsalt ja õigeaegselt;\n"
            "- hoidma kehtivana kõik kohaldatavate seadustega nõutavad litsentsid, load ja kindlustused teie pakutavate teenuste jaoks;\n"
            "- vastama Klientide päringutele mõistliku aja jooksul;\n"
            "- värskendama oma Profiili ja Teenuste nimekirju, et kajastada praegust saadavust ja hindu;\n"
            "- kohtlema Kliente austusega ja ilma diskrimineerimiseta;\n"
            "- järgima kõiki kohaldatavaid seadusi, sealhulgas tarbijakaitse, andmekaitse ja maksueeskirju.\n\n"
            "7.2 Te ei tohi:\n"
            "- esitada enda või teiste Teenusepakkujate kohta valesid või manipuleeritud arvustusi;\n"
            "- võtta Klientidega ühendust väljaspool Platvormi eesmärgiga minna aktiivse tehingu ajal mööda Nevumo vahendusteenustest;\n"
            "- kuritarvitada või püüda kopeerida (scrape) Platvormi andmeid;\n"
            "- püüda saada loata juurdepääsu teistele kontodele või Platvormi süsteemidele;\n"
            "- osaleda mis tahes petlikes või eksitavates tegevustes."
        ),
        "lt": (
            "7.1 Jūs sutinkate:\n"
            "- teikti paslaugas Klientams profesionaliai, rūpestingai ir laiku;\n"
            "- išlaikyti visas licencijas, leidimus ir draudimus, kurių reikalauja taikomi įstatymai jūsų siūlomoms paslaugoms;\n"
            "- atsakyti į Klientų užklausas per protingą laiką;\n"
            "- atnaujinti savo Profilį ir Paslaugų sąrašus, kad jie atspindėtų dabartinį prieinamumą ir kainas;\n"
            "- elgtis su Klientais pagarbiai ir be diskriminacijos;\n"
            "- laikytis visų taikomų įstatymų, įskaitant vartotojų apsaugos, duomenų apsaugos ir mokesčių taisykles.\n\n"
            "7.2 Jūs neturite:\n"
            "- pateikti melagingų ar manipuliuotų atsiliepimų apie save ar kitus Teikėjus;\n"
            "- susisiekti su Klientais už Platformos ribų siekiant apeiti Nevumo tarpininkavimo paslaugas aktyvaus sandorio metu;\n"
            "- piktnaudžiauti ar bandyti nukopijuoti (scrape) Platformos duomenis;\n"
            "- bandyti gauti neteisėtą prieigą prie kitų paskyrų ar Platformos sistemų;\n"
            "- dalyvauti bet kokio pobūdžio apgaulingoje ar klaidinančioje veikloje."
        ),
        "lv": (
            "7.1 Jūs piekrītat:\n"
            "- sniegt pakalpojumus Klientiem profesionāli, rūpīgi un savlaicīgi;\n"
            "- uzturēt visas licences, atļaujas un apdrošināšanu, ko pieprasa piemērojamie tiesību akti jūsu piedāvātajiem pakalpojumiem;\n"
            "- atbildēt uz Klientu pieprasījumiem saprātīgā laikā;\n"
            "- atjaunināt savu Profilu un Pakalpojumu sarakstus, lai tie atspoguļotu pašreizējo pieejamību un cenas;\n"
            "- izturēties pret Klientiem ar cieņu un bez diskriminācijas;\n"
            "- ievērot visus piemērojamos likumus, tostarp patērētāju aizsardzības, datu aizsardzības un nodokļu noteikumus.\n\n"
            "7.2 Jūs nedrīkstat:\n"
            "- iesniegt viltotas vai manipulētas atsauksmes par sevi vai citiem Pakalpojumu sniedzējiem;\n"
            "- sazināties ar Klientiem ārpus Platformas nolūkā apiet Nevumo starpniecības pakalpojumus aktīva darījuma laikā;\n"
            "- ļaunprātīgi izmantot vai mēģināt nokasīt (scrape) Platformas datus;\n"
            "- mēģināt iegūt neautorizētu piekļuvi citiem kontiem vai Platformas sistēmām;\n"
            "- iesaistīties jebkāda veida krāpnieciskā vai maldinošā praksē."
        ),
        "hu": (
            "7.1 Ön beleegyezik, hogy:\n"
            "- szolgáltatásokat nyújt az Ügyfeleknek professzionális, gondos és időszerű módon;\n"
            "- fenntart minden olyan licencet, engedélyt és biztosítást, amelyet az Ön által kínált szolgáltatásokra vonatkozó alkalmazandó jogszabályok megkövetelnek;\n"
            "- ésszerű időn belül válaszol az Ügyfelek megkereséseire;\n"
            "- frissíti Profilját és Szolgáltatáslistáit, hogy azok tükrözzék a jelenlegi elérhetőséget és árakat;\n"
            "- az Ügyfelekkel tiszteletteljesen és megkülönböztetés nélkül bánik;\n"
            "- megfelel minden alkalmazandó jogszabálynak, beleértve a fogyasztóvédelmi, adatvédelmi és adóügyi előírásokat.\n\n"
            "7.2 Önnek tilos:\n"
            "- hamis vagy manipulált értékeléseket beküldeni önmagáról vagy más Szolgáltatókról;\n"
            "- az Ügyfelekkel a Platformon kívül kapcsolatba lépni azzal a céllal, hogy aktív tranzakció során megkerülje a Nevumo közvetítői szolgáltatásait;\n"
            "- visszaélni a Platform adataival, vagy megkísérelni azok lekaparását (scraping);\n"
            "- megkísérelni jogosulatlan hozzáférést szerezni más fiókokhoz vagy Platformrendszerekhez;\n"
            "- bármilyen jellegű csalárd vagy megtévesztő gyakorlatot folytatni."
        ),
        "hr": (
            "7.1 Slažete se da ćete:\n"
            "- pružati usluge Klijentima na profesionalan, pažljiv i pravovremen način;\n"
            "- održavati sve licence, dozvole i osiguranja koja zahtijevaju važeći zakoni za usluge koje nudite;\n"
            "- odgovoriti na upite Klijenata u razumnom roku;\n"
            "- ažurirati svoj Profil i Popise usluga kako bi odražavali trenutnu dostupnost i cijene;\n"
            "- odnositi se prema Klijentima s poštovanjem i bez diskriminacije;\n"
            "- poštivati sve primjenjive zakone, uključujući zaštitu potrošača, zaštitu podataka i porezne propise.\n\n"
            "7.2 Ne smijete:\n"
            "- slati lažne ili manipulirane recenzije o sebi ili drugim Pružateljima;\n"
            "- kontaktirati Klijente izvan Platforme u svrhu zaobilaženja posredničkih usluga Nevuma tijekom aktivne transakcije;\n"
            "- zloupotrijebiti ili pokušati prikupiti (scrape) podatke s Platforme;\n"
            "- pokušati dobiti neovlašteni pristup drugim računima ili sustavima Platforme;\n"
            "- baviti se lažnim ili prijevarnim praksama bilo koje vrste."
        ),
        "sk": (
            "7.1 Súhlasíte, že budete:\n"
            "- poskytovať služby Klientom profesionálne, dôsledne a včas;\n"
            "- udržiavať všetky licencie, povolenia a poistenia, ktoré vyžadujú platné právne predpisy pre služby, ktoré ponúkate;\n"
            "- odpovedať na dopyty Klientov v primeranej lehote;\n"
            "- aktualizovať svoj Profil a Zoznamy služieb tak, aby odrážali aktuálnu dostupnosť a ceny;\n"
            "- zaobchádzať s Klientmi s rešpektom a bez diskriminácie;\n"
            "- dodržiavať všetky platné zákony, vrátane ochrany spotrebiteľa, ochrany osobných údajov a daňových predpisov.\n\n"
            "7.2 Nesmiete:\n"
            "- predkladať falošné alebo zmanipulované recenzie o sebe alebo iných Poskytovateľoch;\n"
            "- kontaktovať Klientov mimo Platformy za účelom obchádzania sprostredkovateľských služieb Nevumo počas aktívnej transakcie;\n"
            "- zneužívať alebo sa pokúšať o scraping dát Platformy;\n"
            "- pokúšať sa získať neoprávnený prístup k iným účtom alebo systémom Platformy;\n"
            "- zapájať sa do podvodných alebo klamlivých praktík akéhokoľvek druhu."
        ),
        "sl": (
            "7.1 Strinjate se, da boste:\n"
            "- zagotavljali storitve Strankam na strokoven, skrbem in pravočasen način;\n"
            "- vzdrževali vse licence, dovoljenja in zavarovanja, ki jih zahteva veljavna zakonodaja za storitve, ki jih ponujate;\n"
            "- odgovorili na povpraševanja Strank v razumnem času;\n"
            "- posodobili svoj Profil in Sezname storitev, da bodo odražali trenutno razpoložljivost in cene;\n"
            "- obravnavali Stranke s spoštovanjem in brez diskriminacije;\n"
            "- spoštovali vse veljavne zakone, vključno z varstvom potrošnikov, varstvom podatkov in davčnimi predpisi.\n\n"
            "7.2 Ne smete:\n"
            "- oddajati lažnih ali manipuliranih ocen o sebi ali drugih Ponudnikih;\n"
            "- stopiti v stik s Strankami zunaj Platforme z namenom zaobiti posredniške storitve Nevumo med aktivno transakcijo;\n"
            "- zlorabiti ali poskušati postrgati (scrape) podatke s Platforme;\n"
            "- poskušati pridobiti nepooblaščen dostop do drugih računov ali sistemov Platforme;\n"
            "- se vključiti v goljufive ali zavajajoče prakse kakršne koli vrste."
        ),
        "el": (
            "7.1 Συμφωνείτε να:\n"
            "- παρέχετε υπηρεσίες στους Πελάτες με επαγγελματικό, επιμελή και έγκαιρο τρόπο;\n"
            "- διατηρείτε όλες τις άδειες, εγκρίσεις και ασφάλειες που απαιτούνται από την ισχύουσα νομοθεσία για τις υπηρεσίες που προσφέρετε;\n"
            "- απαντάτε στα αιτήματα των Πελατών εντός εύλογου χρόνου;\n"
            "- ενημερώνετε το Προφίλ και τις Καταχωρήσεις Υπηρεσιών σας για να αντικατοπτρίζουν την τρέχουσα διαθεσιμότητα και τιμολόγηση;\n"
            "- αντιμετωπίζετε τους Πελάτες με σεβασμό και χωρίς διακρίσεις;\n"
            "- συμμορφώνεστε με όλους τους ισχύοντες νόμους, συμπεριλαμβανομένης της προστασίας των καταναλωτών, της προστασίας δεδομένων και των φορολογικών κανονισμών.\n\n"
            "7.2 Δεν πρέπει να:\n"
            "- υποβάλλετε ψευδείς ή παραποιημένες κριτικές για τον εαυτό σας ή άλλους Παρόχους;\n"
            "- επικοινωνείτε με Πελάτες εκτός της Πλατφόρμας με σκοπό την παράκαμψη των υπηρεσιών διαμεσολάβησης της Nevumo κατά τη διάρκεια μιας ενεργής συναλλαγής;\n"
            "- κάνετε κακή χρήση ή προσπαθείτε να εξάγετε (scrape) δεδομένα της Πλατφόρμας;\n"
            "- προσπαθείτε να αποκτήσετε μη εξουσιοδοτημένη πρόσβαση σε άλλους λογαριασμούς ή συστήματα της Πλατφόρμας;\n"
            "- εμπλακείτε σε δόλιες ή παραπλανητικές πρακτικές οποιουδήποτε είδους."
        ),
        "tr": (
            "7.1 Şunları yapmayı kabul edersiniz:\n"
            "- Müşterilere profesyonel, özenli ve zamanında hizmet sunmak;\n"
            "- Sunduğunuz hizmetler için yürürlükteki kanunların gerektirdiği tüm lisans, izin ve sigortaları sürdürmek;\n"
            "- Müşteri Taleplerine makul bir süre içinde yanıt vermek;\n"
            "- Mevcut uygunluğu ve fiyatlandırmayı yansıtmak için Profilinizi ve Hizmet Listelerinizi güncellemek;\n"
            "- Müşterilere saygılı ve ayrımcılık yapmadan davranmak;\n"
            "- Tüketiciyi koruma, veri koruma ve vergi düzenlemeleri dahil olmak üzere tüm geçerli yasalara uymak.\n\n"
            "7.2 Şunları yapmamalısınız:\n"
            "- Kendiniz veya diğer Sağlayıcılar hakkında sahte veya manipüle edilmiş yorumlar göndermek;\n"
            "- Aktif bir işlem sırasında Nevumo'nun aracılık hizmetlerini atlamak amacıyla Platform dışında Müşterilerle iletişime geçmek;\n"
            "- Platform verilerini kötüye kullanmak veya kazımaya (scrape) çalışmak;\n"
            "- Diğer hesaplara veya Platform sistemlerine yetkisiz erişim sağlamaya çalışmak;\n"
            "- Herhangi bir türde dolandırıcılık veya aldatıcı uygulamaya girmek."
        ),
        "ga": (
            "7.1 Aontaíonn tú le:\n"
            "- seirbhísí a sholáthar do Chustaiméirí ar bhealach gairmiúil, dícheallach agus tráthúil;\n"
            "- gach ceadúnas, cead agus árachas a theastaíonn faoin dlí is infheidhme maidir leis na seirbhísí a chuireann tú ar fáil a choinneáil;\n"
            "- freagairt d'iarratais ó Chustaiméirí laistigh de thréimhse réasúnta;\n"
            "- do Phróifíl agus Liostaí Seirbhíse a nuashonrú chun infhaighteacht agus praghsáil reatha a léiriú;\n"
            "- caitheamh le Custaiméirí le meas agus gan leithcheal;\n"
            "- gach dlí is infheidhme a chomhlíonadh, lena n-áirítear cosaint tomhaltóirí, cosaint sonraí agus rialacháin chánach.\n\n"
            "7.2 Ní mór duit gan:\n"
            "- léirmheasanna bréagacha nó ionramháilte fút féin nó faoi Sholáthraithe eile a chur isteach;\n"
            "- teagmháil a dhéanamh le Custaiméirí lasmuigh den Ardán chun seirbhísí idirghabhála Nevumo a sheachaint le linn idirbheart gníomhach;\n"
            "- mí-úsáid a bhaint as sonraí an Ardáin nó iarracht a dhéanamh iad a scríobadh (scrape);\n"
            "- iarracht a dhéanamh rochtain neamhúdaraithe a fháil ar chuntais eile nó ar chórais an Ardáin;\n"
            "- dul i mbun cleachtais chalaoiseacha nó mhealltacha d'aon chineál."
        ),
        "is": (
            "7.1 Þú samþykkir að:\n"
            "- veita Viðskiptavinum þjónustu á faglegan, vandvirkan og tímanlegan hátt;\n"
            "- viðhalda öllum leyfum, heimildum og tryggingum sem krafist er samkvæmt gildandi lögum fyrir þá þjónustu sem þú býður;\n"
            "- svara fyrirspurnum Viðskiptavina innan sanngjarns tíma;\n"
            "- uppfæra Prófílinn þinn og Þjónustuskráningar til að endurspegla núverandi framboð og verðlagningu;\n"
            "- koma fram við Viðskiptavini af virðingu og án mismununar;\n"
            "- fara að öllum gildandi lögum, þar á meðal neytendavernd, persónuvernd og skattareglum.\n\n"
            "7.2 Þú mátt ekki:\n"
            "- senda inn falskar eða falsaðar umsagnir um sjálfan þig eða aðra Veitendur;\n"
            "- hafa samband við Viðskiptavini utan Vettvangsins í þeim tilgangi að fara framhjá milligönguþjónustu Nevumo meðan á virkum viðskiptum stendur;\n"
            "- misnota eða reyna að skafa (scrape) gögn Vettvangsins;\n"
            "- reyna að fá óheimilan aðgang að öðrum reikningum eða kerfum Vettvangsins;\n"
            "- taka þátt í sviksamlegum eða blekkjandi vinnubrögðum af neinu tagi."
        ),
        "lb": (
            "7.1 Dir averstan sidd:\n"
            "- Servicer fir Clienten op eng professionell, suergfälteg an zäitgerecht Manéier ze bidden;\n"
            "- all Lizenzen, Permis an Assurancen z'erhalen, déi vum gültege Gesetz fir déi ugebuede Servicer verlaangt sinn;\n"
            "- op Clienteufroen an enger raisonnabeler Zäit ze äntweren;\n"
            "- Äre Profil a Service-Lëschten ze aktualiséieren fir déi aktuell Disponibilitéit a Präisser ze reflektéieren;\n"
            "- Clienten mat Respekt an ouni Diskriminéierung ze behandelen;\n"
            "- all applicabel Gesetzer ze respektéieren, dorënner Konsumenteschutz, Dateschutz a Steierreglementer.\n\n"
            "7.2 Et ass Iech net erlaabt:\n"
            "- falsch oder manipuléiert Rezensiounen iwwer Iech selwer oder aner Ubidder ofzeginn;\n"
            "- Clienten ausserhalb vun der Plattform ze kontaktéieren fir d'Vermëttlungsservicer vum Nevumo während enger aktiver Transaktioun ëmzegoen;\n"
            "- Plattformdaten ze mëssbrauchen oder ze probéieren se ze scrapen;\n"
            "- ze probéieren onerlaabten Zougang zu anere Konten oder Plattformsystemer ze kréien;\n"
            "- un betrügereschen oder irreführenden Praktike vun iergendenger Aart deelzehuelen."
        ),
        "mk": (
            "7.1 Вие се согласувате да:\n"
            "- обезбедувате услуги на Клиентите на професионален, внимателен и навремен начин;\n"
            "- ги одржувате сите лиценци, дозволи и осигурувања кои се бараат со применливиот закон за услугите што ги нудите;\n"
            "- одговарате на прашања од Клиентите во разумен рок;\n"
            "- го ажурирате вашиот Профил и Листите на услуги за да ја одразуваат тековната достапност и цените;\n"
            "- ги третирате Клиентите со почит и без дискриминација;\n"
            "- ги почитувате сите применливи закони, вклучувајќи заштита на потрошувачите, заштита на податоците и даночни регулативи.\n\n"
            "7.2 Не смеете:\n"
            "- да поднесувате лажни или манипулирани прегледи за себе или за други Даватели;\n"
            "- да контактирате со Клиенти надвор од Платформата со цел да ги заобиколите посредничките услуги на Nevumo за време на активна трансакција;\n"
            "- да злоупотребувате или да се обидувате да стругате (scrape) податоци од Платформата;\n"
            "- да се обидувате да добиете неовластен пристап до други сметки или системи на Платформата;\n"
            "- да се вклучите во измамнички или залажувачки практики од секаков вид."
        ),
        "mt": (
            "7.1 Inti taqbel li:\n"
            "- tipprovdi servizzi lill-Klijenti b'mod professjonali, diligenti, u fil-hin;\n"
            "- izzomm il-liċenzji, il-permessi, u l-assigurazzjonijiet kollha mehtiega mil-ligi applikabbli ghas-servizzi li toffri;\n"
            "- twiegeb ghall-Mistoqsijiet tal-Klijenti f'hin ragonevoli;\n"
            "- taggorna l-Profil u l-Listi tas-Servizzi tieghek biex jirriflettu d-disponibbiltà u l-ipprezzar attwali;\n"
            "- tittratta lill-Klijenti b'rispett u minghajr diskriminazzjoni;\n"
            "- tikkonforma mal-ligijiet applikabbli kollha, inkluzi l-protezzjoni tal-konsumatur, il-protezzjoni tad-dejta, u r-regolamenti tat-taxxa.\n\n"
            "7.2 M'ghandekx:\n"
            "- tissottometti revizjonijiet foloz jew manipulati dwarek innifsek jew Fornituri ohra;\n"
            "- tikkuntattja lill-Klijenti barra l-Pjattaforma bl-iskop li tevita s-servizzi ta intermedjazzjoni ta Nevumo waqt transazzjoni attiva;\n"
            "- tuzu hazin jew tipprova tiskrappa d-dejta tal-Pjattaforma;\n"
            "- tipprova tikseb aċċess mhux awtorizzat ghal kontijiet ohra jew sistemi tal-Pjattaforma;\n"
            "- tiehu sehem fi prattiki frodulenti jew qarrieqa ta kwalunkwe tip."
        ),
        "sq": (
            "7.1 Ju pranoni të:\n"
            "- ofroni shërbime për Klientët në një mënyrë profesionale, të zellshme dhe në kohë;\n"
            "- mbani të gjitha licencat, lejet dhe sigurimet e kërkuara nga ligji i zbatueshëm për shërbimet që ofroni;\n"
            "- t'u përgjigjeni kërkesave të Klientëve brenda një kohe të arsyeshme;\n"
            "- përditësoni Profilin tuaj dhe Listimet e Shërbimeve për të pasqyruar disponueshmërinë dhe çmimet aktuale;\n"
            "- trajtoni Klientët me respekt dhe pa diskriminim;\n"
            "- pajtoheni me të gjitha ligjet e zbatueshme, duke përfshirë mbrojtjen e konsumatorit, mbrojtjen e të dhënave dhe rregulloret tatimore.\n\n"
            "7.2 Ju nuk duhet:\n"
            "- të dërgoni rishikime të rreme ose të manipuluara rreth vetes ose Ofruesve të tjerë;\n"
            "- të kontaktoni Klientët jashtë Platformës me qëllim që të anashkaloni shërbimet ndërmjetësuese të Nevumo gjatë një transaksioni aktiv;\n"
            "- të keqpërdorni ose të përpiqeni të mblidhni (scrape) të dhënat e Platformës;\n"
            "- të përpiqeni të fitoni qasje të paautorizuar në llogari ose sisteme të tjera të Platformës;\n"
            "- të angazhoheni në praktika mashtruese ose gënjyese të çdo lloji."
        ),
        "sr": (
            "7.1 Slažete se da ćete:\n"
            "- pružati usluge Klijentima na profesionalan, pažljiv i pravovremen način;\n"
            "- održavati sve licence, dozvole i osiguranja koja zahtevaju važeći zakoni za usluge koje nudite;\n"
            "- odgovoriti na upite Klijenata u razumnom roku;\n"
            "- ažurirati svoj Profil i Popise usluga kako bi odražavali trenutnu dostupnost i cene;\n"
            "- odnositi se prema Klijentima s poštovanjem i bez diskriminacije;\n"
            "- poštovati sve primenjive zakone, uključujući zaštitu potrošača, zaštitu podataka i poreske propise.\n\n"
            "7.2 Ne smete:\n"
            "- slati lažne ili manipulisane recenzije o sebi ili drugim Pružaocima;\n"
            "- kontaktirati Klijente izvan Platforme u svrhu zaobilaženja posredničkih usluga Nevuma tokom aktivne transakcije;\n"
            "- zloupotrebiti ili pokušati da prikupite (scrape) podatke s Platforme;\n"
            "- pokušati da dobijete neovlašćen pristup drugim nalozima ili sistemima Platforme;\n"
            "- baviti se lažnim ili prevarantskim praksama bilo koje vrste."
        ),
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            
            for lang, text_val in lang_values.items():
                query = text("""
                    INSERT INTO translations (key, lang, value)
                    VALUES (:k, :l, :v)
                    ON CONFLICT (key, lang)
                    DO UPDATE SET value = EXCLUDED.value
                """)
                session.execute(query, {"k": db_key, "l": lang, "v": text_val})
                count += 1

        session.commit()
        print(f"✅ Seeded {count} translations for {NAMESPACE}.art7_body")

if __name__ == "__main__":
    seed()
