#!/usr/bin/env python3
"""Seed claim v2_p2 namespace translations into the translations table."""

import os
import psycopg2
from psycopg2.extras import execute_values

# Database connection string
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@localhost:5433/nevumo_leads")

# Translations: language -> dict of keys
TRANSLATIONS = {
    "mk": {
        "urgency": "Вашиот профил е видлив за клиенти — но нивните барања одат кај конкурентите",
        "kicker": "Го пронајдовме вашиот бизнис на Nevumo",
        "hero_title": "Тој е тука. Само вас чека.",
        "your_profile_badge": "Вашиот профил",
        "leads_title": "Последни барања од клиенти",
        "leads_overlay": "Преземете го профилот за да ги видите барањата",
        "leads_overlay_sub": "Бесплатно · Без провизија",
        "benefit_1_title": "Директни барања",
        "benefit_1_sub": "Без посредник",
        "benefit_2_title": "Видливост на Google",
        "benefit_2_sub": "SEO профил",
        "benefit_3_title": "Нула провизија!",
        "benefit_3_sub": "Засекогаш!",
        "vs_bad_1": "Плаќате за секое барање",
        "vs_bad_2": "Дури и ако клиентот одбие",
        "vs_good_1": "Клиентите ве гледаат и доаѓаат директно кај вас",
        "vs_good_2": "Без посредник, без провизија",
        "time_signal": "Трае само 2 минути",
        "login_hint": "Веќе имате сметка? Најавете се и преземете →",
        "social_proof_zero": "Бидете еден од првите даватели во {city} — колку порано, толку поvidливи ќе бидете!",
        "social_proof_few": "Веќе {count} даватели во {city} се на Nevumo — колку порано, толку поvidliви ќе бидете!",
        "social_proof_many": "{count} даватели во {city} веќе примаат барања",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Без претплата",
        "trust_cancel": "Откажете во секое време",
        "free_badge": "Бесплатно за даватели",
        "notfound_title": "Овој линк е невалиден или истечен",
        "notfound_desc": "Профилот кон кој упатува овој линк не е пронајден. Можеби сте добиле погрешен линк или тој веќе е употребен.",
        "notfound_support": "Добивте е-пошта од нас? Контактирајте не на support@nevumo.com — ќе ви испратиме нов линк.",
        "notfound_cta": "Додајте го вашиот бизнис на Nevumo",
        "notfound_ghost": "Барате услуга? Најдете давател →",
        "claimed_title": "Овој профил веќе е активиран",
        "claimed_desc": "Овој профил веќе е преземен и активен на Nevumo. Ако сте сопственик, најавете се на вашата сметка.",
        "claimed_cta": "Најавете се на сметката",
        "claimed_support": "Не е ваш, но треба да биде? Контактирајте не на support@nevumo.com",
    },
    "mt": {
        "urgency": "Il-profil tiegħek huwa viżibbli għall-klijenti — iżda t-talbiet tagħhom imorru għand il-kompetituri",
        "kicker": "Sibna n-negozju tiegħek fuq Nevumo",
        "hero_title": "Qiegħed hawn. Jistenna biss lilek.",
        "your_profile_badge": "Il-profil tiegħek",
        "leads_title": "L-aħħar talbiet tal-klijenti",
        "leads_overlay": "Ħu l-profil biex tara t-talbiet",
        "leads_overlay_sub": "B'xejn · Mingħajr kummissjoni",
        "benefit_1_title": "Talbiet diretti",
        "benefit_1_sub": "Mingħajr intermedjarju",
        "benefit_2_title": "Viżibbiltà fuq Google",
        "benefit_2_sub": "Profil SEO",
        "benefit_3_title": "Żero kummissjoni!",
        "benefit_3_sub": "Għal dejjem!",
        "vs_bad_1": "Tħallas għal kull talba",
        "vs_bad_2": "Anke jekk il-klijent jirrifjuta",
        "vs_good_1": "Il-klijenti jarawk u jiġu direttament għandek",
        "vs_good_2": "Mingħajr intermedjarju, mingħajr kummissjoni",
        "time_signal": "Jieħu biss 2 minuti",
        "login_hint": "Diġà għandek kont? Idħol u ħu →",
        "social_proof_zero": "Kun wieħed mill-ewwel fornituri f'{city} — kemm aktar kmieni, daqshekk aktar viżibbli tkun!",
        "social_proof_few": "Diġà {count} fornituri f'{city} huma fuq Nevumo — kemm aktar kmieni, daqshekk aktar viżibbli tkun!",
        "social_proof_many": "{count} fornituri f'{city} diġà qed jirċievu talbiet",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Mingħajr abbonament",
        "trust_cancel": "Ikkanċella fi kwalunkwe ħin",
        "free_badge": "B'xejn għall-fornituri",
        "notfound_title": "Dan il-link mhuwiex validu jew skada",
        "notfound_desc": "Il-profil li dan il-link jipponta għalih ma nstabx. Forsi rċievejt link ħażin jew diġà intuża.",
        "notfound_support": "Irċevejt email mingħandna? Ikkuntattjana fuq support@nevumo.com — nibgħtulek link ġdid.",
        "notfound_cta": "Żid in-negozju tiegħek fuq Nevumo",
        "notfound_ghost": "Qed tfittex servizz? Sib fornitur →",
        "claimed_title": "Dan il-profil diġà ġie attivat",
        "claimed_desc": "Dan il-profil diġà ittieħed u huwa attiv fuq Nevumo. Jekk inti s-sid, idħol fil-kont tiegħek.",
        "claimed_cta": "Idħol fil-kont tiegħek",
        "claimed_support": "Mhux tiegħek iżda għandu jkun? Ikkuntattjana fuq support@nevumo.com",
    },
    "nl": {
        "urgency": "Uw profiel is zichtbaar voor klanten — maar hun verzoeken gaan naar uw concurrenten",
        "kicker": "We hebben uw bedrijf gevonden op Nevumo",
        "hero_title": "Het is hier. Het wacht alleen op u.",
        "your_profile_badge": "Uw profiel",
        "leads_title": "Meest recente klantverzoeken",
        "leads_overlay": "Claim het profiel om verzoeken te zien",
        "leads_overlay_sub": "Gratis · Zonder commissie",
        "benefit_1_title": "Directe verzoeken",
        "benefit_1_sub": "Geen tussenpersoon",
        "benefit_2_title": "Zichtbaarheid op Google",
        "benefit_2_sub": "SEO-profiel",
        "benefit_3_title": "Nul commissie!",
        "benefit_3_sub": "Voor altijd!",
        "vs_bad_1": "U betaalt voor elk verzoek",
        "vs_bad_2": "Zelfs als de klant weigert",
        "vs_good_1": "Klanten zien u en komen direct naar u",
        "vs_good_2": "Geen tussenpersoon, geen commissie",
        "time_signal": "Duurt slechts 2 minuten",
        "login_hint": "Heeft u al een account? Log in en claim →",
        "social_proof_zero": "Wees een van de eerste aanbieders in {city} — hoe eerder, hoe zichtbaarder u bent!",
        "social_proof_few": "Al {count} aanbieders in {city} zijn op Nevumo — hoe eerder, hoe zichtbaarder!",
        "social_proof_many": "{count} aanbieders in {city} ontvangen al verzoeken",
        "trust_gdpr": "AVG",
        "trust_no_sub": "Geen abonnement",
        "trust_cancel": "Op elk moment opzeggen",
        "free_badge": "Gratis voor aanbieders",
        "notfound_title": "Deze link is ongeldig of verlopen",
        "notfound_desc": "Het profiel waarnaar deze link verwijst is niet gevonden. Mogelijk heeft u een onjuiste link ontvangen of is deze al gebruikt.",
        "notfound_support": "Heeft u een e-mail van ons ontvangen? Neem contact op via support@nevumo.com — we sturen u een nieuwe link.",
        "notfound_cta": "Voeg uw bedrijf toe aan Nevumo",
        "notfound_ghost": "Op zoek naar een dienst? Vind een aanbieder →",
        "claimed_title": "Dit profiel is al geactiveerd",
        "claimed_desc": "Dit profiel is al geclaimd en actief op Nevumo. Als u de eigenaar bent, log dan in op uw account.",
        "claimed_cta": "Inloggen op uw account",
        "claimed_support": "Niet van u, maar zou het moeten zijn? Neem contact op via support@nevumo.com",
    },
    "no": {
        "urgency": "Profilen din er synlig for kunder — men forespørslene deres går til konkurrentene",
        "kicker": "Vi fant bedriften din på Nevumo",
        "hero_title": "Den er her. Den venter bare på deg.",
        "your_profile_badge": "Din profil",
        "leads_title": "Siste kundeforespørsler",
        "leads_overlay": "Ta over profilen for å se forespørsler",
        "leads_overlay_sub": "Gratis · Ingen provisjon",
        "benefit_1_title": "Direkte forespørsler",
        "benefit_1_sub": "Ingen mellomledd",
        "benefit_2_title": "Synlighet på Google",
        "benefit_2_sub": "SEO-profil",
        "benefit_3_title": "Null provisjon!",
        "benefit_3_sub": "For alltid!",
        "vs_bad_1": "Du betaler for hver forespørsel",
        "vs_bad_2": "Selv om kunden avslår",
        "vs_good_1": "Kunder ser deg og kommer direkte til deg",
        "vs_good_2": "Ingen mellomledd, ingen provisjon",
        "time_signal": "Tar bare 2 minutter",
        "login_hint": "Har du allerede en konto? Logg inn og ta over →",
        "social_proof_zero": "Bli en av de første leverandørene i {city} — jo tidligere, jo mer synlig!",
        "social_proof_few": "Allerede {count} leverandører i {city} er på Nevumo — jo tidligere, jo mer synlig!",
        "social_proof_many": "{count} leverandører i {city} mottar allerede forespørsler",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Intet abonnement",
        "trust_cancel": "Avslutt når som helst",
        "free_badge": "Gratis for leverandører",
        "notfound_title": "Denne lenken er ugyldig eller utløpt",
        "notfound_desc": "Profilen denne lenken peker til ble ikke funnet. Du har kanskje mottatt en feil lenke eller den er allerede brukt.",
        "notfound_support": "Mottok du en e-post fra oss? Kontakt oss på support@nevumo.com — vi sender deg en ny lenke.",
        "notfound_cta": "Legg til bedriften din på Nevumo",
        "notfound_ghost": "Leter du etter en tjeneste? Finn en leverandør →",
        "claimed_title": "Denne profilen er allerede aktivert",
        "claimed_desc": "Denne profilen er allerede tatt over og aktiv på Nevumo. Hvis du er eieren, logg inn på kontoen din.",
        "claimed_cta": "Logg inn på kontoen din",
        "claimed_support": "Ikke din, men burde det være? Kontakt oss på support@nevumo.com",
    },
    "pl": {
        "urgency": "Twój profil jest widoczny dla klientów — ale ich zapytania trafiają do konkurencji",
        "kicker": "Znaleźliśmy Twoją firmę na Nevumo",
        "hero_title": "Jest tutaj. Czeka tylko na Ciebie.",
        "your_profile_badge": "Twój profil",
        "leads_title": "Ostatnie zapytania od klientów",
        "leads_overlay": "Przejmij profil, aby zobaczyć zapytania",
        "leads_overlay_sub": "Bezpłatnie · Bez prowizji",
        "benefit_1_title": "Bezpośrednie zapytania",
        "benefit_1_sub": "Bez pośrednika",
        "benefit_2_title": "Widoczność w Google",
        "benefit_2_sub": "Profil SEO",
        "benefit_3_title": "Zero prowizji!",
        "benefit_3_sub": "Na zawsze!",
        "vs_bad_1": "Płacisz za każde zapytanie",
        "vs_bad_2": "Nawet jeśli klient rezygnuje",
        "vs_good_1": "Klienci widzą Cię i przychodzą bezpośrednio do Ciebie",
        "vs_good_2": "Bez pośrednika, bez prowizji",
        "time_signal": "Zajmuje tylko 2 minuty",
        "login_hint": "Masz już konto? Zaloguj się i przejmij →",
        "social_proof_zero": "Bądź jednym z pierwszych dostawców w {city} — im wcześniej, tym bardziej widoczny będziesz!",
        "social_proof_few": "Już {count} dostawców w {city} jest na Nevumo — im wcześniej, tym bardziej widoczny będziesz!",
        "social_proof_many": "{count} dostawców w {city} już otrzymuje zapytania",
        "trust_gdpr": "RODO",
        "trust_no_sub": "Bez abonamentu",
        "trust_cancel": "Anuluj w dowolnym momencie",
        "free_badge": "Bezpłatne dla dostawców",
        "notfound_title": "Ten link jest nieprawidłowy lub wygasł",
        "notfound_desc": "Profil, do którego prowadzi ten link, nie został znaleziony. Możliwe, że otrzymałeś nieprawidłowy link lub został już użyty.",
        "notfound_support": "Otrzymałeś od nas e-mail? Skontaktuj się z nami na support@nevumo.com — wyślemy Ci nowy link.",
        "notfound_cta": "Dodaj swoją firmę do Nevumo",
        "notfound_ghost": "Szukasz usługi? Znajdź dostawcę →",
        "claimed_title": "Ten profil jest już aktywowany",
        "claimed_desc": "Ten profil został już przejęty i jest aktywny na Nevumo. Jeśli jesteś właścicielem, zaloguj się na swoje konto.",
        "claimed_cta": "Zaloguj się na swoje konto",
        "claimed_support": "Nie Twój, ale powinien być? Skontaktuj się z nami na support@nevumo.com",
    },
    "pt": {
        "urgency": "Seu perfil está visível para os clientes — mas os pedidos deles estão indo para seus concorrentes",
        "kicker": "Encontramos sua empresa no Nevumo",
        "hero_title": "Está aqui. Só está esperando por você.",
        "your_profile_badge": "Seu perfil",
        "leads_title": "Últimas solicitações de clientes",
        "leads_overlay": "Reivindique o perfil para ver as solicitações",
        "leads_overlay_sub": "Gratuito · Sem comissão",
        "benefit_1_title": "Solicitações diretas",
        "benefit_1_sub": "Sem intermediário",
        "benefit_2_title": "Visibilidade no Google",
        "benefit_2_sub": "Perfil SEO",
        "benefit_3_title": "Zero comissão!",
        "benefit_3_sub": "Para sempre!",
        "vs_bad_1": "Você paga por cada solicitação",
        "vs_bad_2": "Mesmo que o cliente recuse",
        "vs_good_1": "Os clientes te veem e vêm diretamente até você",
        "vs_good_2": "Sem intermediário, sem comissão",
        "time_signal": "Leva apenas 2 minutos",
        "login_hint": "Já tem uma conta? Entre e reivindique →",
        "social_proof_zero": "Seja um dos primeiros fornecedores em {city} — quanto mais cedo, mais visível você será!",
        "social_proof_few": "Já {count} fornecedores em {city} estão no Nevumo — quanto mais cedo, mais visível você será!",
        "social_proof_many": "{count} fornecedores em {city} já estão recebendo solicitações",
        "trust_gdpr": "LGPD",
        "trust_no_sub": "Sem assinatura",
        "trust_cancel": "Cancele a qualquer momento",
        "free_badge": "Gratuito para fornecedores",
        "notfound_title": "Este link é inválido ou expirou",
        "notfound_desc": "O perfil para o qual este link aponta não foi encontrado. Você pode ter recebido um link incorreto ou ele já foi usado.",
        "notfound_support": "Recebeu um e-mail nosso? Entre em contato em support@nevumo.com — enviaremos um novo link.",
        "notfound_cta": "Adicione sua empresa ao Nevumo",
        "notfound_ghost": "Procurando um serviço? Encontre um fornecedor →",
        "claimed_title": "Este perfil já foi ativado",
        "claimed_desc": "Este perfil já foi reivindicado e está ativo no Nevumo. Se você for o proprietário, faça login em sua conta.",
        "claimed_cta": "Entrar na minha conta",
        "claimed_support": "Não é seu, mas deveria ser? Entre em contato em support@nevumo.com",
    },
    "pt-PT": {
        "urgency": "O seu perfil está visível para os clientes — mas os pedidos deles estão a ir para os seus concorrentes",
        "kicker": "Encontrámos a sua empresa no Nevumo",
        "hero_title": "Está aqui. Só precisa de si.",
        "your_profile_badge": "O seu perfil",
        "leads_title": "Últimos pedidos de clientes",
        "leads_overlay": "Reclame o perfil para ver os pedidos",
        "leads_overlay_sub": "Gratuito · Sem comissão",
        "benefit_1_title": "Pedidos diretos",
        "benefit_1_sub": "Sem intermediário",
        "benefit_2_title": "Visibilidade no Google",
        "benefit_2_sub": "Perfil SEO",
        "benefit_3_title": "Zero comissão!",
        "benefit_3_sub": "Para sempre!",
        "vs_bad_1": "Paga por cada pedido",
        "vs_bad_2": "Mesmo que o cliente recuse",
        "vs_good_1": "Os clientes veem-no e vêm diretamente até si",
        "vs_good_2": "Sem intermediário, sem comissão",
        "time_signal": "Demora apenas 2 minutos",
        "login_hint": "Já tem conta? Inicie sessão e reclame →",
        "social_proof_zero": "Seja um dos primeiros fornecedores em {city} — quanto mais cedo, mais visível será!",
        "social_proof_few": "Já {count} fornecedores em {city} estão no Nevumo — quanto mais cedo, mais visível será!",
        "social_proof_many": "{count} fornecedores em {city} já estão a receber pedidos",
        "trust_gdpr": "RGPD",
        "trust_no_sub": "Sem subscrição",
        "trust_cancel": "Cancele em qualquer altura",
        "free_badge": "Gratuito para fornecedores",
        "notfound_title": "Esta ligação é inválida ou expirou",
        "notfound_desc": "O perfil para o qual esta ligação aponta não foi encontrado. Pode ter recebido uma ligação incorreta ou já foi utilizada.",
        "notfound_support": "Recebeu um e-mail nosso? Contacte-nos em support@nevumo.com — enviaremos uma nova ligação.",
        "notfound_cta": "Adicione a sua empresa ao Nevumo",
        "notfound_ghost": "À procura de um serviço? Encontre um fornecedor →",
        "claimed_title": "Este perfil já foi ativado",
        "claimed_desc": "Este perfil já foi reclamado e está ativo no Nevumo. Se for o proprietário, inicie sessão na sua conta.",
        "claimed_cta": "Iniciar sessão na conta",
        "claimed_support": "Não é seu, mas deveria ser? Contacte-nos em support@nevumo.com",
    },
    "ro": {
        "urgency": "Profilul dvs. este vizibil pentru clienți — dar solicitările lor merg la concurenți",
        "kicker": "Am găsit compania dvs. pe Nevumo",
        "hero_title": "Este aici. Vă așteaptă doar pe dvs.",
        "your_profile_badge": "Profilul dvs.",
        "leads_title": "Cele mai recente solicitări de clienți",
        "leads_overlay": "Revendicați profilul pentru a vedea solicitările",
        "leads_overlay_sub": "Gratuit · Fără comision",
        "benefit_1_title": "Solicitări directe",
        "benefit_1_sub": "Fără intermediar",
        "benefit_2_title": "Vizibilitate pe Google",
        "benefit_2_sub": "Profil SEO",
        "benefit_3_title": "Zero comision!",
        "benefit_3_sub": "Pentru totdeauna!",
        "vs_bad_1": "Plătiți pentru fiecare solicitare",
        "vs_bad_2": "Chiar dacă clientul refuză",
        "vs_good_1": "Clienții vă văd și vin direct la dvs.",
        "vs_good_2": "Fără intermediar, fără comision",
        "time_signal": "Durează doar 2 minute",
        "login_hint": "Aveți deja un cont? Conectați-vă și revendicați →",
        "social_proof_zero": "Fiți unul dintre primii furnizori din {city} — cu cât mai devreme, cu atât mai vizibil veți fi!",
        "social_proof_few": "Deja {count} furnizori din {city} sunt pe Nevumo — cu cât mai devreme, cu atât mai vizibil veți fi!",
        "social_proof_many": "{count} furnizori din {city} primesc deja solicitări",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Fără abonament",
        "trust_cancel": "Anulați oricând",
        "free_badge": "Gratuit pentru furnizori",
        "notfound_title": "Acest link este invalid sau a expirat",
        "notfound_desc": "Profilul la care duce acest link nu a fost găsit. Este posibil să fi primit un link incorect sau acesta a fost deja utilizat.",
        "notfound_support": "Ați primit un e-mail de la noi? Contactați-ne la support@nevumo.com — vă vom trimite un link nou.",
        "notfound_cta": "Adăugați compania dvs. pe Nevumo",
        "notfound_ghost": "Căutați un serviciu? Găsiți un furnizor →",
        "claimed_title": "Acest profil a fost deja activat",
        "claimed_desc": "Acest profil a fost deja revendicat și este activ pe Nevumo. Dacă sunteți proprietarul, conectați-vă la contul dvs.",
        "claimed_cta": "Conectați-vă la cont",
        "claimed_support": "Nu este al dvs., dar ar trebui să fie? Contactați-ne la support@nevumo.com",
    },
    "ru": {
        "urgency": "Ваш профиль виден клиентам — но их запросы уходят к конкурентам",
        "kicker": "Мы нашли ваш бизнес на Nevumo",
        "hero_title": "Он здесь. Ждёт только вас.",
        "your_profile_badge": "Ваш профиль",
        "leads_title": "Последние запросы от клиентов",
        "leads_overlay": "Получите профиль, чтобы видеть запросы",
        "leads_overlay_sub": "Бесплатно · Без комиссии",
        "benefit_1_title": "Прямые запросы",
        "benefit_1_sub": "Без посредников",
        "benefit_2_title": "Видимость в Google",
        "benefit_2_sub": "SEO профиль",
        "benefit_3_title": "Ноль комиссии!",
        "benefit_3_sub": "Навсегда!",
        "vs_bad_1": "Вы платите за каждый запрос",
        "vs_bad_2": "Даже если клиент отказывается",
        "vs_good_1": "Клиенты видят вас и приходят прямо к вам",
        "vs_good_2": "Без посредников, без комиссии",
        "time_signal": "Занимает всего 2 минуты",
        "login_hint": "Уже есть аккаунт? Войдите и получите →",
        "social_proof_zero": "Станьте одним из первых поставщиков в {city} — чем раньше, тем заметнее вы будете!",
        "social_proof_few": "Уже {count} поставщиков в {city} на Nevumo — чем раньше, тем заметнее вы будете!",
        "social_proof_many": "{count} поставщиков в {city} уже получают запросы",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Без подписки",
        "trust_cancel": "Отмените в любое время",
        "free_badge": "Бесплатно для поставщиков",
        "notfound_title": "Эта ссылка недействительна или устарела",
        "notfound_desc": "Профиль, на который указывает эта ссылка, не найден. Возможно, вы получили неверную ссылку или она уже была использована.",
        "notfound_support": "Получили письмо от нас? Свяжитесь с нами по адресу support@nevumo.com — мы пришлём новую ссылку.",
        "notfound_cta": "Добавьте свой бизнес на Nevumo",
        "notfound_ghost": "Ищете услугу? Найдите поставщика →",
        "claimed_title": "Этот профиль уже активирован",
        "claimed_desc": "Этот профиль уже получен и активен на Nevumo. Если вы владелец, войдите в свой аккаунт.",
        "claimed_cta": "Войти в аккаунт",
        "claimed_support": "Не ваш, но должен быть? Свяжитесь с нами по адресу support@nevumo.com",
    },
    "sk": {
        "urgency": "Váš profil je viditeľný pre klientov — ale ich požiadavky idú ku konkurencii",
        "kicker": "Našli sme vašu firmu na Nevumo",
        "hero_title": "Je tu. Čaká len na vás.",
        "your_profile_badge": "Váš profil",
        "leads_title": "Najnovšie požiadavky klientov",
        "leads_overlay": "Prevezmite profil na zobrazenie požiadaviek",
        "leads_overlay_sub": "Zadarmo · Bez provízie",
        "benefit_1_title": "Priame požiadavky",
        "benefit_1_sub": "Bez sprostredkovateľa",
        "benefit_2_title": "Viditeľnosť na Google",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nulová provízia!",
        "benefit_3_sub": "Navždy!",
        "vs_bad_1": "Platíte za každú požiadavku",
        "vs_bad_2": "Aj keď klient odmietne",
        "vs_good_1": "Klienti vás vidia a prichádzajú priamo k vám",
        "vs_good_2": "Bez sprostredkovateľa, bez provízie",
        "time_signal": "Trvá len 2 minúty",
        "login_hint": "Máte už konto? Prihláste sa a prevezmite →",
        "social_proof_zero": "Buďte jedným z prvých poskytovateľov v {city} — čím skôr, tým viditeľnejší budete!",
        "social_proof_few": "Už {count} poskytovateľov v {city} je na Nevumo — čím skôr, tým viditeľnejší budete!",
        "social_proof_many": "{count} poskytovateľov v {city} už prijíma požiadavky",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Bez predplatného",
        "trust_cancel": "Zrušte kedykoľvek",
        "free_badge": "Zadarmo pre poskytovateľov",
        "notfound_title": "Tento odkaz je neplatný alebo vypršal",
        "notfound_desc": "Profil, na ktorý tento odkaz odkazuje, sa nenašiel. Možno ste dostali nesprávny odkaz alebo bol už použitý.",
        "notfound_support": "Dostali ste od nás e-mail? Kontaktujte nás na support@nevumo.com — pošleme vám nový odkaz.",
        "notfound_cta": "Pridajte svoju firmu na Nevumo",
        "notfound_ghost": "Hľadáte službu? Nájdite poskytovateľa →",
        "claimed_title": "Tento profil je už aktivovaný",
        "claimed_desc": "Tento profil bol už prevzatý a je aktívny na Nevumo. Ak ste vlastníkom, prihláste sa do svojho konta.",
        "claimed_cta": "Prihlásiť sa do konta",
        "claimed_support": "Nie je váš, ale malo by byť? Kontaktujte nás na support@nevumo.com",
    },
    "sl": {
        "urgency": "Vaš profil je viden strankam — toda njihove zahteve gredo h konkurenci",
        "kicker": "Našli smo vaše podjetje na Nevumo",
        "hero_title": "Je tukaj. Čaka samo vas.",
        "your_profile_badge": "Vaš profil",
        "leads_title": "Najnovejše zahteve strank",
        "leads_overlay": "Prevzemite profil za ogled zahtev",
        "leads_overlay_sub": "Brezplačno · Brez provizije",
        "benefit_1_title": "Neposredne zahteve",
        "benefit_1_sub": "Brez posrednika",
        "benefit_2_title": "Vidnost na Googlu",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nič provizije!",
        "benefit_3_sub": "Za vedno!",
        "vs_bad_1": "Plačate za vsako zahtevo",
        "vs_bad_2": "Tudi če stranka zavrne",
        "vs_good_1": "Stranke vas vidijo in pridejo neposredno k vam",
        "vs_good_2": "Brez posrednika, brez provizije",
        "time_signal": "Traja samo 2 minuti",
        "login_hint": "Že imate račun? Prijavite se in prevzemite →",
        "social_proof_zero": "Bodite eden prvih ponudnikov v {city} — prej ko se pridružite, bolj vidni boste!",
        "social_proof_few": "Že {count} ponudnikov v {city} je na Nevumo — prej ko se pridružite, bolj vidni boste!",
        "social_proof_many": "{count} ponudnikov v {city} že prejema zahteve",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Brez naročnine",
        "trust_cancel": "Kadarkoli prekličite",
        "free_badge": "Brezplačno za ponudnike",
        "notfound_title": "Ta povezava je neveljavna ali je potekla",
        "notfound_desc": "Profila, na katerega kaže ta povezava, ni bilo mogoče najti. Morda ste prejeli napačno povezavo ali je bila že uporabljena.",
        "notfound_support": "Ste prejeli e-pošto od nas? Stopite v stik z nami na support@nevumo.com — poslali vam bomo novo povezavo.",
        "notfound_cta": "Dodajte svoje podjetje na Nevumo",
        "notfound_ghost": "Iščete storitev? Poiščite ponudnika →",
        "claimed_title": "Ta profil je že aktiviran",
        "claimed_desc": "Ta profil je že prevzet in aktiven na Nevumo. Če ste lastnik, se prijavite v svoj račun.",
        "claimed_cta": "Prijavite se v račun",
        "claimed_support": "Ni vaš, pa bi moral biti? Stopite v stik z nami na support@nevumo.com",
    },
    "sq": {
        "urgency": "Profili juaj është i dukshëm për klientët — por kërkesat e tyre shkojnë tek konkurrentët",
        "kicker": "Gjetëm biznesin tuaj në Nevumo",
        "hero_title": "Është këtu. Pret vetëm ju.",
        "your_profile_badge": "Profili juaj",
        "leads_title": "Kërkesat e fundit të klientëve",
        "leads_overlay": "Merrni profilin për të parë kërkesat",
        "leads_overlay_sub": "Falas · Pa komision",
        "benefit_1_title": "Kërkesa direkte",
        "benefit_1_sub": "Pa ndërmjetës",
        "benefit_2_title": "Dukshmëri në Google",
        "benefit_2_sub": "Profil SEO",
        "benefit_3_title": "Zero komision!",
        "benefit_3_sub": "Përgjithmonë!",
        "vs_bad_1": "Paguani për çdo kërkesë",
        "vs_bad_2": "Edhe nëse klienti refuzon",
        "vs_good_1": "Klientët ju shohin dhe vijnë drejtpërdrejt tek ju",
        "vs_good_2": "Pa ndërmjetës, pa komision",
        "time_signal": "Zgjat vetëm 2 minuta",
        "login_hint": "Keni tashmë llogari? Hyni dhe merrni →",
        "social_proof_zero": "Bëhuni një nga ofruesit e parë në {city} — sa më herët, aq më i dukshëm do të jeni!",
        "social_proof_few": "Tashmë {count} ofrues në {city} janë në Nevumo — sa më herët, aq më i dukshëm do të jeni!",
        "social_proof_many": "{count} ofrues në {city} tashmë po marrin kërkesa",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Pa aboniment",
        "trust_cancel": "Anuloni në çdo kohë",
        "free_badge": "Falas për ofruesit",
        "notfound_title": "Ky link është i pavlefshëm ose ka skaduar",
        "notfound_desc": "Profili që ky link tregon nuk u gjet. Mund të keni marrë një link të gabuar ose ai është përdorur tashmë.",
        "notfound_support": "Morët një email nga ne? Kontaktoni support@nevumo.com — do t'ju dërgojmë një link të ri.",
        "notfound_cta": "Shtoni biznesin tuaj në Nevumo",
        "notfound_ghost": "Po kërkoni shërbim? Gjeni një ofrues →",
        "claimed_title": "Ky profil është aktivizuar tashmë",
        "claimed_desc": "Ky profil është marrë tashmë dhe është aktiv në Nevumo. Nëse jeni pronari, hyni në llogarinë tuaj.",
        "claimed_cta": "Hyni në llogarinë tuaj",
        "claimed_support": "Nuk është juaji, por duhet të jetë? Kontaktoni support@nevumo.com",
    },
    "sr": {
        "urgency": "Vaš profil je vidljiv klijentima — ali njihovi zahtevi idu konkurenciji",
        "kicker": "Pronašli smo vaše preduzeće na Nevumo",
        "hero_title": "Ovde je. Čeka samo vas.",
        "your_profile_badge": "Vaš profil",
        "leads_title": "Najnoviji zahtevi klijenata",
        "leads_overlay": "Preuzmite profil da vidite zahteve",
        "leads_overlay_sub": "Besplatno · Bez provizije",
        "benefit_1_title": "Direktni zahtevi",
        "benefit_1_sub": "Bez posrednika",
        "benefit_2_title": "Vidljivost na Google-u",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nula provizije!",
        "benefit_3_sub": "Zauvek!",
        "vs_bad_1": "Plaćate za svaki zahtev",
        "vs_bad_2": "Čak i kada klijent odbije",
        "vs_good_1": "Klijenti vas vide i dolaze direktno kod vas",
        "vs_good_2": "Bez posrednika, bez provizije",
        "time_signal": "Traje samo 2 minuta",
        "login_hint": "Već imate nalog? Prijavite se i preuzmite →",
        "social_proof_zero": "Budite jedan od prvih pružalaca u {city} — što pre, to vidljiviji!",
        "social_proof_few": "Već {count} pružalaca u {city} su na Nevumo — što pre, to vidljiviji!",
        "social_proof_many": "{count} pružalaca u {city} već prima zahteve",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Bez pretplate",
        "trust_cancel": "Otkažite u bilo kom trenutku",
        "free_badge": "Besplatno za pružaoce",
        "notfound_title": "Ovaj link je nevažeći ili je istekao",
        "notfound_desc": "Profil na koji ovaj link upućuje nije pronađen. Možda ste primili pogrešan link ili je već korišćen.",
        "notfound_support": "Primili ste e-mail od nas? Kontaktirajte nas na support@nevumo.com — poslaćemo vam novi link.",
        "notfound_cta": "Dodajte svoje preduzeće na Nevumo",
        "notfound_ghost": "Tražite uslugu? Pronađite pružaoca →",
        "claimed_title": "Ovaj profil je već aktiviran",
        "claimed_desc": "Ovaj profil je već preuzet i aktivan na Nevumo. Ako ste vlasnik, prijavite se na nalog.",
        "claimed_cta": "Prijavite se na nalog",
        "claimed_support": "Nije vaš, ali bi trebalo biti? Kontaktirajte nas na support@nevumo.com",
    },
    "sv": {
        "urgency": "Din profil är synlig för kunder — men deras förfrågningar går till dina konkurrenter",
        "kicker": "Vi hittade ditt företag på Nevumo",
        "hero_title": "Den är här. Den väntar bara på dig.",
        "your_profile_badge": "Din profil",
        "leads_title": "Senaste kundförfrågningar",
        "leads_overlay": "Ta över profilen för att se förfrågningar",
        "leads_overlay_sub": "Gratis · Ingen provision",
        "benefit_1_title": "Direkta förfrågningar",
        "benefit_1_sub": "Ingen mellanhand",
        "benefit_2_title": "Synlighet på Google",
        "benefit_2_sub": "SEO-profil",
        "benefit_3_title": "Noll provision!",
        "benefit_3_sub": "För alltid!",
        "vs_bad_1": "Du betalar för varje förfrågan",
        "vs_bad_2": "Även om kunden tackar nej",
        "vs_good_1": "Kunder ser dig och kommer direkt till dig",
        "vs_good_2": "Ingen mellanhand, ingen provision",
        "time_signal": "Tar bara 2 minuter",
        "login_hint": "Har du redan ett konto? Logga in och ta över →",
        "social_proof_zero": "Bli en av de första leverantörerna i {city} — ju tidigare, desto synligare!",
        "social_proof_few": "Redan {count} leverantörer i {city} är på Nevumo — ju tidigare, desto synligare!",
        "social_proof_many": "{count} leverantörer i {city} tar redan emot förfrågningar",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Ingen prenumeration",
        "trust_cancel": "Avsluta när som helst",
        "free_badge": "Gratis för leverantörer",
        "notfound_title": "Den här länken är ogiltig eller har gått ut",
        "notfound_desc": "Profilen som den här länken pekar på hittades inte. Du kan ha fått en felaktig länk eller den har redan använts.",
        "notfound_support": "Fick du ett e-postmeddelande från oss? Kontakta oss på support@nevumo.com — vi skickar en ny länk.",
        "notfound_cta": "Lägg till ditt företag på Nevumo",
        "notfound_ghost": "Letar du efter en tjänst? Hitta en leverantör →",
        "claimed_title": "Den här profilen har redan aktiverats",
        "claimed_desc": "Den här profilen har redan tagits över och är aktiv på Nevumo. Om du är ägaren, logga in på ditt konto.",
        "claimed_cta": "Logga in på ditt konto",
        "claimed_support": "Inte din, men borde vara? Kontakta oss på support@nevumo.com",
    },
    "tr": {
        "urgency": "Profiliniz müşterilere görünür — ancak talepleri rakiplerinize gidiyor",
        "kicker": "İşletmenizi Nevumo'da bulduk",
        "hero_title": "Burada. Sadece sizi bekliyor.",
        "your_profile_badge": "Profiliniz",
        "leads_title": "Son müşteri talepleri",
        "leads_overlay": "Talepleri görmek için profili talep edin",
        "leads_overlay_sub": "Ücretsiz · Komisyon yok",
        "benefit_1_title": "Doğrudan talepler",
        "benefit_1_sub": "Aracı yok",
        "benefit_2_title": "Google'da görünürlük",
        "benefit_2_sub": "SEO profili",
        "benefit_3_title": "Sıfır komisyon!",
        "benefit_3_sub": "Sonsuza dek!",
        "vs_bad_1": "Her talep için ödeme yapıyorsunuz",
        "vs_bad_2": "Müşteri reddetse bile",
        "vs_good_1": "Müşteriler sizi görür ve doğrudan size gelir",
        "vs_good_2": "Aracı yok, komisyon yok",
        "time_signal": "Yalnızca 2 dakika sürer",
        "login_hint": "Zaten hesabınız var mı? Giriş yapın ve talep edin →",
        "social_proof_zero": "{city}'deki ilk sağlayıcılardan biri olun — ne kadar erken, o kadar görünür olursunuz!",
        "social_proof_few": "{city}'de {count} sağlayıcı zaten Nevumo'da — ne kadar erken, o kadar görünür olursunuz!",
        "social_proof_many": "{city}'deki {count} sağlayıcı zaten talep alıyor",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Abonelik yok",
        "trust_cancel": "İstediğiniz zaman iptal edin",
        "free_badge": "Sağlayıcılar için ücretsiz",
        "notfound_title": "Bu bağlantı geçersiz veya süresi dolmuş",
        "notfound_desc": "Bu bağlantının işaret ettiği profil bulunamadı. Yanlış bir bağlantı almış olabilirsiniz veya daha önce kullanılmış olabilir.",
        "notfound_support": "Bizden e-posta aldınız mı? support@nevumo.com adresinden bize ulaşın — size yeni bir bağlantı göndereceğiz.",
        "notfound_cta": "İşletmenizi Nevumo'ya ekleyin",
        "notfound_ghost": "Hizmet mi arıyorsunuz? Sağlayıcı bulun →",
        "claimed_title": "Bu profil zaten etkinleştirildi",
        "claimed_desc": "Bu profil zaten talep edildi ve Nevumo'da aktif. Sahibiyseniz hesabınıza giriş yapın.",
        "claimed_cta": "Hesabınıza giriş yapın",
        "claimed_support": "Sizin değil ama olmalı mı? support@nevumo.com adresinden bize ulaşın",
    },
    "uk": {
        "urgency": "Ваш профіль видимий клієнтам — але їхні запити йдуть до конкурентів",
        "kicker": "Ми знайшли ваш бізнес на Nevumo",
        "hero_title": "Він тут. Чекає тільки вас.",
        "your_profile_badge": "Ваш профіль",
        "leads_title": "Останні запити від клієнтів",
        "leads_overlay": "Отримайте профіль, щоб бачити запити",
        "leads_overlay_sub": "Безкоштовно · Без комісії",
        "benefit_1_title": "Прямі запити",
        "benefit_1_sub": "Без посередників",
        "benefit_2_title": "Видимість у Google",
        "benefit_2_sub": "SEO профіль",
        "benefit_3_title": "Нуль комісії!",
        "benefit_3_sub": "Назавжди!",
        "vs_bad_1": "Ви платите за кожен запит",
        "vs_bad_2": "Навіть якщо клієнт відмовляється",
        "vs_good_1": "Клієнти бачать вас і приходять прямо до вас",
        "vs_good_2": "Без посередників, без комісії",
        "time_signal": "Займає лише 2 хвилини",
        "login_hint": "Вже є акаунт? Увійдіть і отримайте →",
        "social_proof_zero": "Станьте одним із перших постачальників у {city} — чим раніше, тим помітніші ви будете!",
        "social_proof_few": "Вже {count} постачальників у {city} на Nevumo — чим раніше, тим помітніші ви будете!",
        "social_proof_many": "{count} постачальників у {city} вже отримують запити",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Без підписки",
        "trust_cancel": "Скасуйте будь-коли",
        "free_badge": "Безкоштовно для постачальників",
        "notfound_title": "Це посилання недійсне або застаріло",
        "notfound_desc": "Профіль, на який вказує це посилання, не знайдено. Можливо, ви отримали неправильне посилання або воно вже було використано.",
        "notfound_support": "Отримали від нас листа? Зв'яжіться з нами на support@nevumo.com — ми надішлемо вам нове посилання.",
        "notfound_cta": "Додайте свій бізнес на Nevumo",
        "notfound_ghost": "Шукаєте послугу? Знайдіть постачальника →",
        "claimed_title": "Цей профіль вже активовано",
        "claimed_desc": "Цей профіль вже отримано і активний на Nevumo. Якщо ви власник, увійдіть у свій акаунт.",
        "claimed_cta": "Увійти в акаунт",
        "claimed_support": "Не ваш, але повинен бути? Зв'яжіться з нами на support@nevumo.com",
    },
}


def seed_translations() -> int:
    """Seed translations into the database."""
    conn = psycopg2.connect(DATABASE_URL)
    cursor = conn.cursor()

    rows_to_upsert = []
    total_count = 0

    for lang, keys in TRANSLATIONS.items():
        for key, value in keys.items():
            full_key = f"claim.{key}"
            rows_to_upsert.append((lang, full_key, value))
        print(f"Seeded {lang}: {len(keys)} keys")
        total_count += len(keys)

    execute_values(
        cursor,
        """
        INSERT INTO translations (lang, key, value)
        VALUES %s
        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
        """,
        rows_to_upsert,
        template="(%s, %s, %s)",
    )

    conn.commit()
    cursor.close()
    conn.close()

    return total_count


if __name__ == "__main__":
    count = seed_translations()
    print(f"✅ Done: {count} translations inserted/updated")
