from apps.api.database import SessionLocal
from sqlalchemy import text

def seed():
    db = SessionLocal()
    try:
        rows = [
            ('en', 'provider_dashboard.nav_widget', 'Widget'),
            ('en', 'provider_dashboard.widget_title', 'Receive requests from multiple websites easily'),
            ('en', 'provider_dashboard.widget_preview_title', 'Preview'),
            ('bg', 'provider_dashboard.nav_widget', 'Widget'),
            ('bg', 'provider_dashboard.widget_title', 'Получавай заявки от много сайтове лесно'),
            ('bg', 'provider_dashboard.widget_preview_title', 'Преглед'),
            ('pl', 'provider_dashboard.nav_widget', 'Widget'),
            ('pl', 'provider_dashboard.widget_title', 'Łatwo otrzymuj zapytania z wielu stron internetowych'),
            ('pl', 'provider_dashboard.widget_preview_title', 'Podgląd'),
            ('de', 'provider_dashboard.nav_widget', 'Widget'),
            ('de', 'provider_dashboard.widget_title', 'Erhalten Sie ganz einfach Anfragen von vielen Websites'),
            ('de', 'provider_dashboard.widget_preview_title', 'Vorschau'),
            ('fr', 'provider_dashboard.nav_widget', 'Widget'),
            ('fr', 'provider_dashboard.widget_title', 'Recevez facilement des demandes de plusieurs sites Web'),
            ('fr', 'provider_dashboard.widget_preview_title', 'Aperçu'),
            ('es', 'provider_dashboard.nav_widget', 'Widget'),
            ('es', 'provider_dashboard.widget_title', 'Recibe solicitudes de múltiples sitios web fácilmente'),
            ('es', 'provider_dashboard.widget_preview_title', 'Vista previa'),
            ('it', 'provider_dashboard.nav_widget', 'Widget'),
            ('it', 'provider_dashboard.widget_title', 'Ricevi facilmente richieste da più siti web'),
            ('it', 'provider_dashboard.widget_preview_title', 'Anteprima'),
            ('pt', 'provider_dashboard.nav_widget', 'Widget'),
            ('pt', 'provider_dashboard.widget_title', 'Receba solicitações de vários sites facilmente'),
            ('pt', 'provider_dashboard.widget_preview_title', 'Pré-visualização'),
            ('pt-PT', 'provider_dashboard.nav_widget', 'Widget'),
            ('pt-PT', 'provider_dashboard.widget_title', 'Receba pedidos de vários sites facilmente'),
            ('pt-PT', 'provider_dashboard.widget_preview_title', 'Pré-visualização'),
            ('nl', 'provider_dashboard.nav_widget', 'Widget'),
            ('nl', 'provider_dashboard.widget_title', 'Ontvang eenvoudig aanvragen van meerdere websites'),
            ('nl', 'provider_dashboard.widget_preview_title', 'Voorbeeld'),
            ('cs', 'provider_dashboard.nav_widget', 'Widget'),
            ('cs', 'provider_dashboard.widget_title', 'Získávejte poptávky z mnoha webů snadno'),
            ('cs', 'provider_dashboard.widget_preview_title', 'Náhled'),
            ('sk', 'provider_dashboard.nav_widget', 'Widget'),
            ('sk', 'provider_dashboard.widget_title', 'Získavajte dopyty z mnohých webov jednoducho'),
            ('sk', 'provider_dashboard.widget_preview_title', 'Náhľad'),
            ('ro', 'provider_dashboard.nav_widget', 'Widget'),
            ('ro', 'provider_dashboard.widget_title', 'Primește cu ușurință cereri de la mai multe site-uri web'),
            ('ro', 'provider_dashboard.widget_preview_title', 'Previzualizare'),
            ('hu', 'provider_dashboard.nav_widget', 'Widget'),
            ('hu', 'provider_dashboard.widget_title', 'Könnyedén kaphat ajánlatkéréseket több weboldalról'),
            ('hu', 'provider_dashboard.widget_preview_title', 'Előnézet'),
            ('hr', 'provider_dashboard.nav_widget', 'Widget'),
            ('hr', 'provider_dashboard.widget_title', 'Jednostavno primajte upite s brojnih web stranica'),
            ('hr', 'provider_dashboard.widget_preview_title', 'Pregled'),
            ('sl', 'provider_dashboard.nav_widget', 'Widget'),
            ('sl', 'provider_dashboard.widget_title', 'Enostavno prejemajte povpraševanja z več spletnih mest'),
            ('sl', 'provider_dashboard.widget_preview_title', 'Predogled'),
            ('da', 'provider_dashboard.nav_widget', 'Widget'),
            ('da', 'provider_dashboard.widget_title', 'Få nemt anmodninger fra mange hjemmesider'),
            ('da', 'provider_dashboard.widget_preview_title', 'Forhåndsvisning'),
            ('sv', 'provider_dashboard.nav_widget', 'Widget'),
            ('sv', 'provider_dashboard.widget_title', 'Ta enkelt emot förfrågningar från många webbplatser'),
            ('sv', 'provider_dashboard.widget_preview_title', 'Förhandsgranskning'),
            ('no', 'provider_dashboard.nav_widget', 'Widget'),
            ('no', 'provider_dashboard.widget_title', 'Motta enkelt forespørsler fra mange nettsider'),
            ('no', 'provider_dashboard.widget_preview_title', 'Forhåndsvisning'),
            ('fi', 'provider_dashboard.nav_widget', 'Widget'),
            ('fi', 'provider_dashboard.widget_title', 'Vastaanota helposti pyyntöjä useilta verkkosivustoilta'),
            ('fi', 'provider_dashboard.widget_preview_title', 'Esikatselu'),
            ('et', 'provider_dashboard.nav_widget', 'Widget'),
            ('et', 'provider_dashboard.widget_title', 'Saage hõlpsasti päringuid mitmetelt veebisaitidelt'),
            ('et', 'provider_dashboard.widget_preview_title', 'Eelvaade'),
            ('lv', 'provider_dashboard.nav_widget', 'Widget'),
            ('lv', 'provider_dashboard.widget_title', 'Viegli saņemiet pieprasījumus no daudzām vietnēm'),
            ('lv', 'provider_dashboard.widget_preview_title', 'Priekšskatījums'),
            ('lt', 'provider_dashboard.nav_widget', 'Widget'),
            ('lt', 'provider_dashboard.widget_title', 'Lengvai gaukite užklausas iš daugelio svetainių'),
            ('lt', 'provider_dashboard.widget_preview_title', 'Peržiūra'),
            ('el', 'provider_dashboard.nav_widget', 'Widget'),
            ('el', 'provider_dashboard.widget_title', 'Λάβετε εύκολα αιτήματα από πολλούς ιστότοπους'),
            ('el', 'provider_dashboard.widget_preview_title', 'Προεπισκόπηση'),
            ('ru', 'provider_dashboard.nav_widget', 'Widget'),
            ('ru', 'provider_dashboard.widget_title', 'Легко получайте заявки с множества сайтов'),
            ('ru', 'provider_dashboard.widget_preview_title', 'Предпросмотр'),
            ('uk', 'provider_dashboard.nav_widget', 'Widget'),
            ('uk', 'provider_dashboard.widget_title', 'Легко отримуйте заявки з багатьох сайтів'),
            ('uk', 'provider_dashboard.widget_preview_title', 'Попередній перегляд'),
            ('sr', 'provider_dashboard.nav_widget', 'Widget'),
            ('sr', 'provider_dashboard.widget_title', 'Lako dobijajte zahteve sa mnogih veb sajtova'),
            ('sr', 'provider_dashboard.widget_preview_title', 'Pregled'),
            ('mk', 'provider_dashboard.nav_widget', 'Widget'),
            ('mk', 'provider_dashboard.widget_title', 'Добивајте барања од многу веб-страници лесно'),
            ('mk', 'provider_dashboard.widget_preview_title', 'Преглед'),
            ('sq', 'provider_dashboard.nav_widget', 'Widget'),
            ('sq', 'provider_dashboard.widget_title', 'Merrni lehtësisht kërkesa nga shumë faqe interneti'),
            ('sq', 'provider_dashboard.widget_preview_title', 'Pamje paraprake'),
            ('ga', 'provider_dashboard.nav_widget', 'Widget'),
            ('ga', 'provider_dashboard.widget_title', 'Faigh iarratais ó iliomad suíomhanna gréasáin go héasca'),
            ('ga', 'provider_dashboard.widget_preview_title', 'Réamhamharc'),
            ('is', 'provider_dashboard.nav_widget', 'Widget'),
            ('is', 'provider_dashboard.widget_title', 'Fáðu auðveldlega beiðnir frá mörgum vefsíðum'),
            ('is', 'provider_dashboard.widget_preview_title', 'Forskoðun'),
            ('lb', 'provider_dashboard.nav_widget', 'Widget'),
            ('lb', 'provider_dashboard.widget_title', 'Kritt einfach Ufroe vu ville Websäiten'),
            ('lb', 'provider_dashboard.widget_preview_title', 'Virowschau'),
            ('mt', 'provider_dashboard.nav_widget', 'Widget'),
            ('mt', 'provider_dashboard.widget_title', 'Irċievi talbiet minn ħafna websajts faċilment'),
            ('mt', 'provider_dashboard.widget_preview_title', 'Anteprima'),
            ('tr', 'provider_dashboard.nav_widget', 'Widget'),
            ('tr', 'provider_dashboard.widget_title', 'Birçok web sitesinden kolayca talep alın'),
            ('tr', 'provider_dashboard.widget_preview_title', 'Önizleme'),
        ]
        for lang, key, value in rows:
            db.execute(text("""
                INSERT INTO translations (lang, key, value)
                VALUES (:lang, :key, :value)
                ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
            """), {"lang": lang, "key": key, "value": value})
        db.commit()
        print(f"Seeded {len(rows)} rows.")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
