from apps.api.database import SessionLocal
from sqlalchemy import text

def seed():
    db = SessionLocal()
    try:
        rows = [
            ('en', 'provider_dashboard.widget_code_title', 'Embed Code'),
            ('en', 'provider_dashboard.widget_code_copy', 'Copy'),
            ('en', 'provider_dashboard.widget_code_copied', 'Copied!'),
            ('bg', 'provider_dashboard.widget_code_title', 'Embed код'),
            ('bg', 'provider_dashboard.widget_code_copy', 'Копирай'),
            ('bg', 'provider_dashboard.widget_code_copied', 'Копирано!'),
            ('pl', 'provider_dashboard.widget_code_title', 'Kod osadzania'),
            ('pl', 'provider_dashboard.widget_code_copy', 'Kopiuj'),
            ('pl', 'provider_dashboard.widget_code_copied', 'Skopiowano!'),
            ('de', 'provider_dashboard.widget_code_title', 'Einbettungscode'),
            ('de', 'provider_dashboard.widget_code_copy', 'Kopieren'),
            ('de', 'provider_dashboard.widget_code_copied', 'Kopiert!'),
            ('fr', 'provider_dashboard.widget_code_title', 'Code d\'intégration'),
            ('fr', 'provider_dashboard.widget_code_copy', 'Copier'),
            ('fr', 'provider_dashboard.widget_code_copied', 'Copié !'),
            ('es', 'provider_dashboard.widget_code_title', 'Código de inserción'),
            ('es', 'provider_dashboard.widget_code_copy', 'Copiar'),
            ('es', 'provider_dashboard.widget_code_copied', '¡Copiado!'),
            ('it', 'provider_dashboard.widget_code_title', 'Codice di incorporamento'),
            ('it', 'provider_dashboard.widget_code_copy', 'Copia'),
            ('it', 'provider_dashboard.widget_code_copied', 'Copiato!'),
            ('pt', 'provider_dashboard.widget_code_title', 'Código de incorporação'),
            ('pt', 'provider_dashboard.widget_code_copy', 'Copiar'),
            ('pt', 'provider_dashboard.widget_code_copied', 'Copiado!'),
            ('pt-PT', 'provider_dashboard.widget_code_title', 'Código de incorporação'),
            ('pt-PT', 'provider_dashboard.widget_code_copy', 'Copiar'),
            ('pt-PT', 'provider_dashboard.widget_code_copied', 'Copiado!'),
            ('nl', 'provider_dashboard.widget_code_title', 'Insluitcode'),
            ('nl', 'provider_dashboard.widget_code_copy', 'Kopiëren'),
            ('nl', 'provider_dashboard.widget_code_copied', 'Gekopieerd!'),
            ('cs', 'provider_dashboard.widget_code_title', 'Kód pro vložení'),
            ('cs', 'provider_dashboard.widget_code_copy', 'Kopírovat'),
            ('cs', 'provider_dashboard.widget_code_copied', 'Zkopírováno!'),
            ('sk', 'provider_dashboard.widget_code_title', 'Kód na vloženie'),
            ('sk', 'provider_dashboard.widget_code_copy', 'Kopírovať'),
            ('sk', 'provider_dashboard.widget_code_copied', 'Skopírované!'),
            ('ro', 'provider_dashboard.widget_code_title', 'Cod de incorporare'),
            ('ro', 'provider_dashboard.widget_code_copy', 'Copiați'),
            ('ro', 'provider_dashboard.widget_code_copied', 'Copiat!'),
            ('hu', 'provider_dashboard.widget_code_title', 'Beágyazási kód'),
            ('hu', 'provider_dashboard.widget_code_copy', 'Másolás'),
            ('hu', 'provider_dashboard.widget_code_copied', 'Másolva!'),
            ('hr', 'provider_dashboard.widget_code_title', 'Kod za ugradnju'),
            ('hr', 'provider_dashboard.widget_code_copy', 'Kopiraj'),
            ('hr', 'provider_dashboard.widget_code_copied', 'Kopirano!'),
            ('sl', 'provider_dashboard.widget_code_title', 'Koda za vdelavo'),
            ('sl', 'provider_dashboard.widget_code_copy', 'Kopiraj'),
            ('sl', 'provider_dashboard.widget_code_copied', 'Kopirano!'),
            ('da', 'provider_dashboard.widget_code_title', 'Integreringskode'),
            ('da', 'provider_dashboard.widget_code_copy', 'Kopier'),
            ('da', 'provider_dashboard.widget_code_copied', 'Kopieret!'),
            ('sv', 'provider_dashboard.widget_code_title', 'Inbäddningskod'),
            ('sv', 'provider_dashboard.widget_code_copy', 'Kopiera'),
            ('sv', 'provider_dashboard.widget_code_copied', 'Kopierat!'),
            ('no', 'provider_dashboard.widget_code_title', 'Integreringskode'),
            ('no', 'provider_dashboard.widget_code_copy', 'Kopier'),
            ('no', 'provider_dashboard.widget_code_copied', 'Kopiert!'),
            ('fi', 'provider_dashboard.widget_code_title', 'Upotuskoodi'),
            ('fi', 'provider_dashboard.widget_code_copy', 'Kopioi'),
            ('fi', 'provider_dashboard.widget_code_copied', 'Kopioitu!'),
            ('et', 'provider_dashboard.widget_code_title', 'Manustamiskood'),
            ('et', 'provider_dashboard.widget_code_copy', 'Kopeeri'),
            ('et', 'provider_dashboard.widget_code_copied', 'Kopeeritud!'),
            ('lv', 'provider_dashboard.widget_code_title', 'Iegulšanas kods'),
            ('lv', 'provider_dashboard.widget_code_copy', 'Kopēt'),
            ('lv', 'provider_dashboard.widget_code_copied', 'Nokopēts!'),
            ('lt', 'provider_dashboard.widget_code_title', 'Įterpimo kodas'),
            ('lt', 'provider_dashboard.widget_code_copy', 'Kopijuoti'),
            ('lt', 'provider_dashboard.widget_code_copied', 'Nukopijuota!'),
            ('el', 'provider_dashboard.widget_code_title', 'Κωδικός ενσωμάτωσης'),
            ('el', 'provider_dashboard.widget_code_copy', 'Αντιγραφή'),
            ('el', 'provider_dashboard.widget_code_copied', 'Αντιγράφηκε!'),
            ('ru', 'provider_dashboard.widget_code_title', 'Код для встраивания'),
            ('ru', 'provider_dashboard.widget_code_copy', 'Копировать'),
            ('ru', 'provider_dashboard.widget_code_copied', 'Скопировано!'),
            ('uk', 'provider_dashboard.widget_code_title', 'Код для вбудовування'),
            ('uk', 'provider_dashboard.widget_code_copy', 'Копіювати'),
            ('uk', 'provider_dashboard.widget_code_copied', 'Скопійовано!'),
            ('sr', 'provider_dashboard.widget_code_title', 'Kod za ugradnju'),
            ('sr', 'provider_dashboard.widget_code_copy', 'Kopiraj'),
            ('sr', 'provider_dashboard.widget_code_copied', 'Kopirano!'),
            ('mk', 'provider_dashboard.widget_code_title', 'Код за вградување'),
            ('mk', 'provider_dashboard.widget_code_copy', 'Копирај'),
            ('mk', 'provider_dashboard.widget_code_copied', 'Копирано!'),
            ('sq', 'provider_dashboard.widget_code_title', 'Kodi i integrimit'),
            ('sq', 'provider_dashboard.widget_code_copy', 'Kopjo'),
            ('sq', 'provider_dashboard.widget_code_copied', 'U kopjua!'),
            ('ga', 'provider_dashboard.widget_code_title', 'Cód leabaithe'),
            ('ga', 'provider_dashboard.widget_code_copy', 'Cóipeáil'),
            ('ga', 'provider_dashboard.widget_code_copied', 'Cóipeáilte!'),
            ('is', 'provider_dashboard.widget_code_title', 'Innfelliningarkóði'),
            ('is', 'provider_dashboard.widget_code_copy', 'Afrita'),
            ('is', 'provider_dashboard.widget_code_copied', 'Afritað!'),
            ('lb', 'provider_dashboard.widget_code_title', 'Agbanncode'),
            ('lb', 'provider_dashboard.widget_code_copy', 'Kopéieren'),
            ('lb', 'provider_dashboard.widget_code_copied', 'Kopéiert!'),
            ('mt', 'provider_dashboard.widget_code_title', 'Kodiċi tal-embedding'),
            ('mt', 'provider_dashboard.widget_code_copy', 'Ikkopja'),
            ('mt', 'provider_dashboard.widget_code_copied', 'Ikkopjat!'),
            ('tr', 'provider_dashboard.widget_code_title', 'Gömme Kodu'),
            ('tr', 'provider_dashboard.widget_code_copy', 'Kopyala'),
            ('tr', 'provider_dashboard.widget_code_copied', 'Kopyalandı!'),
        ]
        for lang, key, value in rows:
            db.execute(text("""
                INSERT INTO translations (lang, key, value)
                VALUES (:lang, :key, :value)
                ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
            """), {"lang": lang, "key": key, "value": value})
        db.commit()
        print(f"Seeded {len(rows)} rows.")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
