from apps.api.database import SessionLocal
from sqlalchemy import text

def seed():
    db = SessionLocal()
    try:
        rows = [
            ('en', 'provider_dashboard.widget_bio_title', 'Link in bio (Linktree, Beacons)'),
            ('en', 'provider_dashboard.widget_bio_description', 'Add your Nevumo public page link to your Linktree, Facebook or Instagram page. Clients land directly on your profile and send a request.'),
            ('en', 'provider_dashboard.widget_share_title', 'Share your public page'),
            ('bg', 'provider_dashboard.widget_bio_title', 'Линк в bio (Linktree, Beacons)'),
            ('bg', 'provider_dashboard.widget_bio_description', 'Добавете линка към вашата публична страница в Nevumo към вашия Linktree, Facebook или Instagram. Клиентите попадат директно на вашия профил и изпращат заявка.'),
            ('bg', 'provider_dashboard.widget_share_title', 'Споделете публичната си страница'),
            ('pl', 'provider_dashboard.widget_bio_title', 'Link w bio (Linktree, Beacons)'),
            ('pl', 'provider_dashboard.widget_bio_description', 'Dodaj link do swojej publicznej strony Nevumo do Linktree, Facebooka lub Instagrama. Klienci trafiają bezpośrednio na Twój profil i wysyłają zapytanie.'),
            ('pl', 'provider_dashboard.widget_share_title', 'Udostępnij swoją publiczną stronę'),
            ('de', 'provider_dashboard.widget_bio_title', 'Link in Bio (Linktree, Beacons)'),
            ('de', 'provider_dashboard.widget_bio_description', 'Fügen Sie den Link Ihrer öffentlichen Nevumo-Seite zu Ihrem Linktree, Facebook oder Instagram hinzu. Kunden landen direkt auf Ihrem Profil und senden eine Anfrage.'),
            ('de', 'provider_dashboard.widget_share_title', 'Teilen Sie Ihre öffentliche Seite'),
            ('fr', 'provider_dashboard.widget_bio_title', 'Lien en bio (Linktree, Beacons)'),
            ('fr', 'provider_dashboard.widget_bio_description', 'Ajoutez le lien de votre page publique Nevumo à votre Linktree, Facebook ou Instagram. Les clients arrivent directement sur votre profil et envoient une demande.'),
            ('fr', 'provider_dashboard.widget_share_title', 'Partagez votre page publique'),
            ('es', 'provider_dashboard.widget_bio_title', 'Enlace en bio (Linktree, Beacons)'),
            ('es', 'provider_dashboard.widget_bio_description', 'Añade el enlace de tu página pública de Nevumo a tu Linktree, Facebook o Instagram. Los clientes llegan directamente a tu perfil y envían una solicitud.'),
            ('es', 'provider_dashboard.widget_share_title', 'Comparte tu página pública'),
            ('it', 'provider_dashboard.widget_bio_title', 'Link in bio (Linktree, Beacons)'),
            ('it', 'provider_dashboard.widget_bio_description', 'Aggiungi il link della tua pagina pubblica Nevumo al tuo Linktree, Facebook o Instagram. I clienti arrivano direttamente al tuo profilo e inviano una richiesta.'),
            ('it', 'provider_dashboard.widget_share_title', 'Condividi la tua pagina pubblica'),
            ('pt', 'provider_dashboard.widget_bio_title', 'Link na bio (Linktree, Beacons)'),
            ('pt', 'provider_dashboard.widget_bio_description', 'Adicione o link da sua página pública Nevumo ao seu Linktree, Facebook ou Instagram. Os clientes chegam diretamente ao seu perfil e enviam um pedido.'),
            ('pt', 'provider_dashboard.widget_share_title', 'Compartilhe sua página pública'),
            ('pt-PT', 'provider_dashboard.widget_bio_title', 'Link na bio (Linktree, Beacons)'),
            ('pt-PT', 'provider_dashboard.widget_bio_description', 'Adicione o link da sua página pública Nevumo ao seu Linktree, Facebook ou Instagram. Os clientes chegam diretamente ao seu perfil e enviam um pedido.'),
            ('pt-PT', 'provider_dashboard.widget_share_title', 'Partilhe a sua página pública'),
            ('nl', 'provider_dashboard.widget_bio_title', 'Link in bio (Linktree, Beacons)'),
            ('nl', 'provider_dashboard.widget_bio_description', 'Voeg de link van uw openbare Nevumo-pagina toe aan uw Linktree, Facebook of Instagram. Klanten komen direct op uw profiel en sturen een aanvraag.'),
            ('nl', 'provider_dashboard.widget_share_title', 'Deel uw openbare pagina'),
            ('cs', 'provider_dashboard.widget_bio_title', 'Odkaz v bio (Linktree, Beacons)'),
            ('cs', 'provider_dashboard.widget_bio_description', 'Přidejte odkaz na svou veřejnou stránku Nevumo do Linktree, Facebooku nebo Instagramu. Klienti přijdou přímo na váš profil a pošlou žádost.'),
            ('cs', 'provider_dashboard.widget_share_title', 'Sdílejte svou veřejnou stránku'),
            ('sk', 'provider_dashboard.widget_bio_title', 'Odkaz v bio (Linktree, Beacons)'),
            ('sk', 'provider_dashboard.widget_bio_description', 'Pridajte odkaz na svoju verejnú stránku Nevumo do Linktree, Facebooku alebo Instagramu. Klienti prídu priamo na váš profil a pošlú požiadavku.'),
            ('sk', 'provider_dashboard.widget_share_title', 'Zdieľajte svoju verejnú stránku'),
            ('ro', 'provider_dashboard.widget_bio_title', 'Link în bio (Linktree, Beacons)'),
            ('ro', 'provider_dashboard.widget_bio_description', 'Adaugă linkul paginii tale publice Nevumo pe Linktree, Facebook sau Instagram. Clienții ajung direct pe profilul tău și trimit o cerere.'),
            ('ro', 'provider_dashboard.widget_share_title', 'Distribuie pagina ta publică'),
            ('hu', 'provider_dashboard.widget_bio_title', 'Link a bióban (Linktree, Beacons)'),
            ('hu', 'provider_dashboard.widget_bio_description', 'Add hozzá a Nevumo nyilvános oldalad linkjét a Linktree-hez, Facebookhoz vagy Instagramhoz. Az ügyfelek közvetlenül a profilodon landolnak és kérést küldenek.'),
            ('hu', 'provider_dashboard.widget_share_title', 'Oszd meg a nyilvános oldaladat'),
            ('hr', 'provider_dashboard.widget_bio_title', 'Link u bio (Linktree, Beacons)'),
            ('hr', 'provider_dashboard.widget_bio_description', 'Dodajte link vaše javne Nevumo stranice na Linktree, Facebook ili Instagram. Klijenti dolaze izravno na vaš profil i šalju zahtjev.'),
            ('hr', 'provider_dashboard.widget_share_title', 'Podijelite svoju javnu stranicu'),
            ('sl', 'provider_dashboard.widget_bio_title', 'Povezava v bio (Linktree, Beacons)'),
            ('sl', 'provider_dashboard.widget_bio_description', 'Dodajte povezavo do svoje javne strani Nevumo na Linktree, Facebook ali Instagram. Stranke pristanejo neposredno na vašem profilu in pošljejo zahtevo.'),
            ('sl', 'provider_dashboard.widget_share_title', 'Delite svojo javno stran'),
            ('da', 'provider_dashboard.widget_bio_title', 'Link i bio (Linktree, Beacons)'),
            ('da', 'provider_dashboard.widget_bio_description', 'Tilføj linket til din offentlige Nevumo-side til din Linktree, Facebook eller Instagram. Kunder lander direkte på din profil og sender en anmodning.'),
            ('da', 'provider_dashboard.widget_share_title', 'Del din offentlige side'),
            ('sv', 'provider_dashboard.widget_bio_title', 'Länk i bio (Linktree, Beacons)'),
            ('sv', 'provider_dashboard.widget_bio_description', 'Lägg till länken till din offentliga Nevumo-sida på Linktree, Facebook eller Instagram. Kunder landar direkt på din profil och skickar en förfrågan.'),
            ('sv', 'provider_dashboard.widget_share_title', 'Dela din offentliga sida'),
            ('no', 'provider_dashboard.widget_bio_title', 'Lenke i bio (Linktree, Beacons)'),
            ('no', 'provider_dashboard.widget_bio_description', 'Legg til lenken til din offentlige Nevumo-side på Linktree, Facebook eller Instagram. Kunder lander direkte på profilen din og sender en forespørsel.'),
            ('no', 'provider_dashboard.widget_share_title', 'Del din offentlige side'),
            ('fi', 'provider_dashboard.widget_bio_title', 'Linkki biossa (Linktree, Beacons)'),
            ('fi', 'provider_dashboard.widget_bio_description', 'Lisää Nevumo-julkisen sivusi linkki Linktreehen, Facebookiin tai Instagramiin. Asiakkaat laskeutuvat suoraan profiiliisi ja lähettävät pyynnön.'),
            ('fi', 'provider_dashboard.widget_share_title', 'Jaa julkinen sivusi'),
            ('et', 'provider_dashboard.widget_bio_title', 'Link bio-s (Linktree, Beacons)'),
            ('et', 'provider_dashboard.widget_bio_description', 'Lisa oma Nevumo avaliku lehe link Linktree-sse, Facebooki või Instagrami. Kliendid maanduvad otse sinu profiilile ja saadavad päringu.'),
            ('et', 'provider_dashboard.widget_share_title', 'Jaga oma avalikku lehte'),
            ('lv', 'provider_dashboard.widget_bio_title', 'Saite bio (Linktree, Beacons)'),
            ('lv', 'provider_dashboard.widget_bio_description', 'Pievienojiet savas Nevumo publiskās lapas saiti Linktree, Facebook vai Instagram. Klienti nonāk tieši jūsu profilā un nosūta pieprasījumu.'),
            ('lv', 'provider_dashboard.widget_share_title', 'Kopīgojiet savu publisko lapu'),
            ('lt', 'provider_dashboard.widget_bio_title', 'Nuoroda bio (Linktree, Beacons)'),
            ('lt', 'provider_dashboard.widget_bio_description', 'Pridėkite savo Nevumo viešojo puslapio nuorodą į Linktree, Facebook ar Instagram. Klientai patenka tiesiai į jūsų profilį ir siunčia užklausą.'),
            ('lt', 'provider_dashboard.widget_share_title', 'Bendrinkite savo viešąjį puslapį'),
            ('el', 'provider_dashboard.widget_bio_title', 'Σύνδεσμος στο bio (Linktree, Beacons)'),
            ('el', 'provider_dashboard.widget_bio_description', 'Προσθέστε τον σύνδεσμο της δημόσιας σελίδας σας στο Nevumo στο Linktree, Facebook ή Instagram. Οι πελάτες φτάνουν απευθείας στο προφίλ σας και στέλνουν αίτηση.'),
            ('el', 'provider_dashboard.widget_share_title', 'Μοιραστείτε τη δημόσια σελίδα σας'),
            ('ru', 'provider_dashboard.widget_bio_title', 'Ссылка в bio (Linktree, Beacons)'),
            ('ru', 'provider_dashboard.widget_bio_description', 'Добавьте ссылку на вашу публичную страницу Nevumo в Linktree, Facebook или Instagram. Клиенты попадают прямо на ваш профиль и отправляют заявку.'),
            ('ru', 'provider_dashboard.widget_share_title', 'Поделитесь публичной страницей'),
            ('uk', 'provider_dashboard.widget_bio_title', 'Посилання в bio (Linktree, Beacons)'),
            ('uk', 'provider_dashboard.widget_bio_description', 'Додайте посилання на вашу публічну сторінку Nevumo до Linktree, Facebook або Instagram. Клієнти потрапляють прямо на ваш профіль і надсилають заявку.'),
            ('uk', 'provider_dashboard.widget_share_title', 'Поділіться публічною сторінкою'),
            ('sr', 'provider_dashboard.widget_bio_title', 'Link u bio (Linktree, Beacons)'),
            ('sr', 'provider_dashboard.widget_bio_description', 'Dodajte link vaše javne Nevumo stranice na Linktree, Facebook ili Instagram. Klijenti dolaze direktno na vaš profil i šalju zahtev.'),
            ('sr', 'provider_dashboard.widget_share_title', 'Podelite svoju javnu stranicu'),
            ('mk', 'provider_dashboard.widget_bio_title', 'Линк во bio (Linktree, Beacons)'),
            ('mk', 'provider_dashboard.widget_bio_description', 'Додајте го линкот на вашата јавна страница на Nevumo во Linktree, Facebook или Instagram. Клиентите доаѓаат директно на вашиот профил и праќаат барање.'),
            ('mk', 'provider_dashboard.widget_share_title', 'Споделете ја вашата јавна страница'),
            ('sq', 'provider_dashboard.widget_bio_title', 'Lidhje në bio (Linktree, Beacons)'),
            ('sq', 'provider_dashboard.widget_bio_description', 'Shtoni lidhjen e faqes suaj publike Nevumo në Linktree, Facebook ose Instagram. Klientët arrijnë drejtpërdrejt në profilin tuaj dhe dërgojnë një kërkesë.'),
            ('sq', 'provider_dashboard.widget_share_title', 'Ndani faqen tuaj publike'),
            ('ga', 'provider_dashboard.widget_bio_title', 'Nasc sa bhith (Linktree, Beacons)'),
            ('ga', 'provider_dashboard.widget_bio_description', 'Cuir nasc do leathanach poiblí Nevumo le do Linktree, Facebook nó Instagram. Tagann cliant díreach chuig do phróifíl agus seolann siad iarratas.'),
            ('ga', 'provider_dashboard.widget_share_title', 'Roinn do leathanach poiblí'),
            ('is', 'provider_dashboard.widget_bio_title', 'Tengill í bio (Linktree, Beacons)'),
            ('is', 'provider_dashboard.widget_bio_description', 'Bættu tengli á opinberu Nevumo-síðuna þína við Linktree, Facebook eða Instagram. Viðskiptavinir lenda beint á prófílinn þinn og senda beiðni.'),
            ('is', 'provider_dashboard.widget_share_title', 'Deildu opinberu síðunni þinni'),
            ('lb', 'provider_dashboard.widget_bio_title', 'Link am Bio (Linktree, Beacons)'),
            ('lb', 'provider_dashboard.widget_bio_description', 'Füge de Link vun denger ëffentlecher Nevumo-Säit op Linktree, Facebook oder Instagram. Clienten landen direkt op dengem Profil a schécken eng Ufro.'),
            ('lb', 'provider_dashboard.widget_share_title', 'Deelt är ëffentlech Säit'),
            ('mt', 'provider_dashboard.widget_bio_title', 'Link fil-bio (Linktree, Beacons)'),
            ('mt', 'provider_dashboard.widget_bio_description', 'Żid il-link tal-paġna pubblika tiegħek ta\' Nevumo mal-Linktree, Facebook jew Instagram tiegħek. Il-klijenti jaslu direttament fuq il-profil tiegħek u jibagħtu talba.'),
            ('mt', 'provider_dashboard.widget_share_title', 'Aqsam il-paġna pubblika tiegħek'),
            ('tr', 'provider_dashboard.widget_bio_title', 'Biyoda bağlantı (Linktree, Beacons)'),
            ('tr', 'provider_dashboard.widget_bio_description', 'Nevumo genel sayfanızın bağlantısını Linktree, Facebook veya Instagram sayfanıza ekleyin. Müşteriler doğrudan profilinize ulaşır ve istek gönderir.'),
            ('tr', 'provider_dashboard.widget_share_title', 'Genel sayfanızı paylaşın'),
        ]
        for lang, key, value in rows:
            db.execute(text("""
                INSERT INTO translations (lang, key, value)
                VALUES (:lang, :key, :value)
                ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
            """), {"lang": lang, "key": key, "value": value})
        db.commit()
        print(f"Seeded {len(rows)} rows.")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
