"""
seed_terms_p1_bodies.py  —  Nevumo | namespace: terms
Key: art1_body (34 езика)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_terms_p1_bodies
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"
COMPANY = '„ФИЛИПС ЦЕНТЬР БЪЛГАРИЯ" ООД'

TRANSLATIONS: dict[str, dict[str, str]] = {
    "art1_body": {
        "en": (
            f'1.1 Nevumo is an online service marketplace operated by {COMPANY} '
            f'(transliteration: Filiphs Tsentar Bulgaria OOD), '
            f'a limited liability company registered in Bulgaria.\n\n'
            f'Company details:\n'
            f'• Legal name: {COMPANY}\n'
            f'• Registration number (ЕИК): 175369610\n'
            f'• Registered address: bul. Petko Karavelov, bl. 77, entrance A, apt. 19, '
            f'Triaditza district, postcode 1408, Sofia, Bulgaria\n'
            f'• Contact email: privacy@nevumo.com\n'
            f'• Brand name: Nevumo\n'
            f'• Website: nevumo.com\n\n'
            f'1.2 These Terms & Conditions govern the use of the Nevumo platform by clients — '
            f'users who browse, contact, and hire service providers through the platform.\n\n'
            f'1.3 By creating an account or using the platform, you agree to these Terms. '
            f'If you do not agree, you must not use Nevumo.\n\n'
            f'1.4 If you are located in Poland, additional provisions marked [PL] apply '
            f'and take precedence over the general terms in case of conflict.'
        ),
        "pl": (
            f'1.1 Niniejszy Regulamin określa zasady korzystania z platformy internetowej Nevumo '
            f'przez Klientów, tj. osoby fizyczne i prawne korzystające z platformy w celu '
            f'wyszukiwania i zamawiania usług.\n\n'
            f'1.2 Operatorem platformy Nevumo jest:\n'
            f'• Nazwa: {COMPANY} (FILIPHS TSENTAR BULGARIA OOD)\n'
            f'• Numer rejestracyjny (ЕИК): 175369610\n'
            f'• Adres siedziby: bul. Petko Karavelov, bl. 77, wejście A, apt. 19, '
            f'dzielnica Triaditza, kod pocztowy 1408, Sofia, Bułgaria\n'
            f'• Adres e-mail: privacy@nevumo.com\n'
            f'• Marka: Nevumo\n'
            f'• Serwis: nevumo.com\n\n'
            f'1.3 Regulamin stanowi umowę o świadczenie usług drogą elektroniczną '
            f'w rozumieniu ustawy z dnia 18 lipca 2002 r. (UŚUDE).\n\n'
            f'1.4 Korzystanie z serwisu Nevumo jest równoznaczne z akceptacją niniejszego Regulaminu. '
            f'Jeśli nie akceptujesz Regulaminu, nie możesz korzystać z serwisu.\n\n'
            f'1.5 Regulamin jest udostępniony bezpłatnie w serwisie w sposób umożliwiający '
            f'jego pobranie, utrwalenie i wydrukowanie.'
        ),
        "bg": (
            f'1.1 Настоящите Общи условия ("ОУ") уреждат отношенията между {COMPANY} '
            f'— оператор на платформата Nevumo — и Клиентите, т.е. потребителите, '
            f'които търсят и поръчват услуги чрез платформата.\n\n'
            f'1.2 Данни на оператора:\n'
            f'• Наименование: {COMPANY}\n'
            f'• ЕИК: 175369610\n'
            f'• Адрес: бул. Петко Каравелов бл. 77, вх. А, ап. 19, р-н Триадица, '
            f'п.к. 1408, гр. София, България\n'
            f'• Имейл: privacy@nevumo.com\n'
            f'• Марка: Nevumo\n'
            f'• Уебсайт: nevumo.com\n\n'
            f'1.3 С регистрацията на акаунт или с използването на платформата Клиентът приема '
            f'настоящите ОУ. Ако Клиентът не е съгласен с ОУ, не следва да използва платформата.\n\n'
            f'1.4 Настоящите ОУ представляват договор от разстояние по смисъла на Закона за '
            f'защита на потребителите (ЗЗП) и Закона за електронната търговия (ЗЕТ).'
        ),
        "cs": (
            f'1.1 Nevumo je online tržiště služeb provozované společností {COMPANY} '
            f'(transliterace: Filiphs Tsentar Bulgaria OOD), '
            f'společností s ručením omezeným registrovanou v Bulharsku.\n\n'
            f'Údaje o společnosti:\n'
            f'• Obchodní firma: {COMPANY}\n'
            f'• Registrační číslo (ЕИК): 175369610\n'
            f'• Sídlo: bul. Petko Karavelov, bl. 77, vchod A, byt 19, '
            f'okres Triaditza, PSČ 1408, Sofia, Bulharsko\n'
            f'• Kontaktní e-mail: privacy@nevumo.com\n'
            f'• Název značky: Nevumo\n'
            f'• Webové stránky: nevumo.com\n\n'
            f'1.2 Tyto Obchodní podmínky upravují používání platformy Nevumo klienty — '
            f'uživateli, kteří prostřednictvím platformy vyhledávají, kontaktují a najímají '
            f'poskytovatele služeb.\n\n'
            f'1.3 Vytvořením účtu nebo používáním platformy vyjadřujete souhlas s těmito podmínkami. '
            f'Pokud nesouhlasíte, nesmíte Nevumo používat.\n\n'
            f'1.4 Pokud se nacházíte v Polsku, platí dodatečná ustanovení označená [PL], '
            f'která mají v případě rozporu přednost před obecnými podmínkami.'
        ),
        "da": (
            f'1.1 Nevumo er en online servicemarkedsplads, der drives af {COMPANY} '
            f'(translitteration: Filiphs Tsentar Bulgaria OOD), '
            f'et anpartsselskab registreret i Bulgarien.\n\n'
            f'Firmaoplysninger:\n'
            f'• Juridisk navn: {COMPANY}\n'
            f'• Registreringsnummer (ЕИК): 175369610\n'
            f'• Registreret adresse: bul. Petko Karavelov, bl. 77, opgang A, lejl. 19, '
            f'Triaditza-kvarteret, postnummer 1408, Sofia, Bulgarien\n'
            f'• Kontakt-e-mail: privacy@nevumo.com\n'
            f'• Brandnavn: Nevumo\n'
            f'• Websted: nevumo.com\n\n'
            f'1.2 Disse Vilkår regulerer klienters brug af Nevumo-platformen — '
            f'brugere, der søger, kontakter og ansætter serviceudbydere via platformen.\n\n'
            f'1.3 Ved at oprette en konto eller bruge platformen accepterer du disse Vilkår. '
            f'Hvis du ikke accepterer, må du ikke bruge Nevumo.\n\n'
            f'1.4 Hvis du befinder dig i Polen, gælder yderligere bestemmelser markeret med [PL], '
            f'som har forrang frem for de generelle vilkår i tilfælde af konflikt.'
        ),
        "de": (
            f'1.1 Nevumo ist ein Online-Servicemarktplatz, der von {COMPANY} '
            f'(Transliteration: Filiphs Tsentar Bulgaria OOD), '
            f'einer in Bulgarien eingetragenen GmbH, betrieben wird.\n\n'
            f'Unternehmensdaten:\n'
            f'• Firmenname: {COMPANY}\n'
            f'• Registrierungsnummer (ЕИК): 175369610\n'
            f'• Eingetragene Adresse: bul. Petko Karavelov, bl. 77, Eingang A, Apt. 19, '
            f'Bezirk Triaditza, PLZ 1408, Sofia, Bulgarien\n'
            f'• Kontakt-E-Mail: privacy@nevumo.com\n'
            f'• Markenname: Nevumo\n'
            f'• Website: nevumo.com\n\n'
            f'1.2 Diese Allgemeinen Geschäftsbedingungen regeln die Nutzung der Nevumo-Plattform '
            f'durch Kunden — Nutzer, die über die Plattform Dienstleister suchen, '
            f'kontaktieren und beauftragen.\n\n'
            f'1.3 Durch die Erstellung eines Kontos oder die Nutzung der Plattform stimmen Sie '
            f'diesen Bedingungen zu. Wenn Sie nicht zustimmen, dürfen Sie Nevumo nicht nutzen.\n\n'
            f'1.4 Wenn Sie sich in Polen befinden, gelten zusätzliche Bestimmungen [PL], '
            f'die im Konfliktfall Vorrang vor den allgemeinen Bedingungen haben.'
        ),
        "el": (
            f'1.1 Το Nevumo είναι μια διαδικτυακή αγορά υπηρεσιών που λειτουργεί από την {COMPANY} '
            f'(μεταγραφή: Filiphs Tsentar Bulgaria OOD), '
            f'εταιρεία περιορισμένης ευθύνης εγγεγραμμένη στη Βουλγαρία.\n\n'
            f'Στοιχεία εταιρείας:\n'
            f'• Επωνυμία: {COMPANY}\n'
            f'• Αριθμός εγγραφής (ЕИК): 175369610\n'
            f'• Έδρα: bul. Petko Karavelov, bl. 77, είσοδος A, διαμ. 19, '
            f'συνοικία Triaditza, ΤΚ 1408, Σόφια, Βουλγαρία\n'
            f'• Email επικοινωνίας: privacy@nevumo.com\n'
            f'• Εμπορική επωνυμία: Nevumo\n'
            f'• Ιστότοπος: nevumo.com\n\n'
            f'1.2 Οι παρόντες Όροι και Προϋποθέσεις διέπουν τη χρήση της πλατφόρμας Nevumo '
            f'από πελάτες — χρήστες που αναζητούν, επικοινωνούν και προσλαμβάνουν παρόχους '
            f'υπηρεσιών μέσω της πλατφόρμας.\n\n'
            f'1.3 Δημιουργώντας λογαριασμό ή χρησιμοποιώντας την πλατφόρμα, αποδέχεστε τους '
            f'παρόντες Όρους. Εάν δεν συμφωνείτε, δεν επιτρέπεται να χρησιμοποιείτε το Nevumo.\n\n'
            f'1.4 Εάν βρίσκεστε στην Πολωνία, ισχύουν επιπλέον διατάξεις [PL], '
            f'οι οποίες υπερισχύουν των γενικών όρων σε περίπτωση σύγκρουσης.'
        ),
        "es": (
            f'1.1 Nevumo es un mercado de servicios en línea operado por {COMPANY} '
            f'(transliteración: Filiphs Tsentar Bulgaria OOD), '
            f'una sociedad de responsabilidad limitada registrada en Bulgaria.\n\n'
            f'Datos de la empresa:\n'
            f'• Razón social: {COMPANY}\n'
            f'• Número de registro (ЕИК): 175369610\n'
            f'• Domicilio social: bul. Petko Karavelov, bl. 77, entrada A, apto. 19, '
            f'distrito Triaditza, CP 1408, Sofía, Bulgaria\n'
            f'• Correo electrónico de contacto: privacy@nevumo.com\n'
            f'• Nombre de marca: Nevumo\n'
            f'• Sitio web: nevumo.com\n\n'
            f'1.2 Estos Términos y Condiciones rigen el uso de la plataforma Nevumo por parte '
            f'de los clientes — usuarios que buscan, contactan y contratan proveedores de servicios.\n\n'
            f'1.3 Al crear una cuenta o utilizar la plataforma, acepta estos Términos. '
            f'Si no está de acuerdo, no debe utilizar Nevumo.\n\n'
            f'1.4 Si se encuentra en Polonia, se aplican disposiciones adicionales marcadas con [PL] '
            f'que prevalecen sobre las condiciones generales en caso de conflicto.'
        ),
        "et": (
            f'1.1 Nevumo on veebipõhine teenusteturg, mida haldab {COMPANY} '
            f'(transliteratsioon: Filiphs Tsentar Bulgaria OOD), Bulgaarias registreeritud osaühing.\n\n'
            f'Ettevõtte andmed:\n'
            f'• Ärinimi: {COMPANY}\n'
            f'• Registreerimisnumber (ЕИК): 175369610\n'
            f'• Registreeritud aadress: bul. Petko Karavelov, bl. 77, sissepääs A, korter 19, '
            f'Triaditza linnaosa, postiindeks 1408, Sofia, Bulgaaria\n'
            f'• Kontakti e-post: privacy@nevumo.com\n'
            f'• Brändi nimi: Nevumo\n'
            f'• Veebisait: nevumo.com\n\n'
            f'1.2 Need kasutustingimused reguleerivad Nevumo platvormi kasutamist klientide poolt — '
            f'kasutajad, kes otsivad, võtavad ühendust ja palkavad teenusepakkujaid platvormi kaudu.\n\n'
            f'1.3 Konto loomisega või platvormi kasutamisega nõustute nende tingimustega. '
            f'Kui te ei nõustu, ei tohi te Nevumot kasutada.\n\n'
            f'1.4 Kui asute Poolas, kohaldatakse täiendavaid [PL]-ga tähistatud sätteid, '
            f'mis on vastuolu korral üldtingimuste ees ülimuslikud.'
        ),
        "fi": (
            f'1.1 Nevumo on verkkopalvelutori, jota hallinnoi {COMPANY} '
            f'(translitterointi: Filiphs Tsentar Bulgaria OOD), Bulgariaan rekisteröity osakeyhtiö.\n\n'
            f'Yritystiedot:\n'
            f'• Virallinen nimi: {COMPANY}\n'
            f'• Rekisterinumero (ЕИК): 175369610\n'
            f'• Rekisteröity osoite: bul. Petko Karavelov, bl. 77, sisäänkäynti A, huoneisto 19, '
            f'Triaditza kaupunginosa, postinumero 1408, Sofia, Bulgaria\n'
            f'• Yhteyssähköposti: privacy@nevumo.com\n'
            f'• Tuotemerkki: Nevumo\n'
            f'• Verkkosivusto: nevumo.com\n\n'
            f'1.2 Nämä käyttöehdot säätelevät Nevumo-alustan käyttöä asiakkaiden toimesta — '
            f'käyttäjät, jotka etsivät, ottavat yhteyttä ja palkkaavat palveluntarjoajia alustan kautta.\n\n'
            f'1.3 Luomalla tilin tai käyttämällä alustaa hyväksyt nämä ehdot. '
            f'Jos et hyväksy, et saa käyttää Nevumoa.\n\n'
            f'1.4 Jos olet Puolassa, sovelletaan lisäsäännöksiä merkittynä [PL], '
            f'jotka ovat ristiriitatilanteessa yleisten ehtojen edelle.'
        ),
        "fr": (
            f'1.1 Nevumo est une place de marché de services en ligne exploitée par {COMPANY} '
            f'(translittération : Filiphs Tsentar Bulgaria OOD), '
            f'une société à responsabilité limitée enregistrée en Bulgarie.\n\n'
            f'Informations sur la société :\n'
            f'• Dénomination légale : {COMPANY}\n'
            f'• Numéro d\'enregistrement (ЕИК) : 175369610\n'
            f'• Siège social : bul. Petko Karavelov, bl. 77, entrée A, apt. 19, '
            f'district Triaditza, code postal 1408, Sofia, Bulgarie\n'
            f'• E-mail de contact : privacy@nevumo.com\n'
            f'• Nom de marque : Nevumo\n'
            f'• Site web : nevumo.com\n\n'
            f'1.2 Les présentes Conditions générales régissent l\'utilisation de la plateforme '
            f'Nevumo par les clients — utilisateurs qui recherchent, contactent et engagent '
            f'des prestataires via la plateforme.\n\n'
            f'1.3 En créant un compte ou en utilisant la plateforme, vous acceptez ces Conditions. '
            f'Si vous n\'acceptez pas, vous ne devez pas utiliser Nevumo.\n\n'
            f'1.4 Si vous êtes situé en Pologne, des dispositions supplémentaires marquées [PL] '
            f's\'appliquent et prévalent sur les conditions générales en cas de conflit.'
        ),
        "ga": (
            f'1.1 Is ardán margaidh seirbhísí ar líne é Nevumo, á oibriú ag {COMPANY} '
            f'(traslitriú: Filiphs Tsentar Bulgaria OOD), '
            f'cuideachta theoranta dliteanais cláraithe sa Bhulgáir.\n\n'
            f'Sonraí na cuideachta:\n'
            f'• Ainm dlíthiúil: {COMPANY}\n'
            f'• Uimhir chláraithe (ЕИК): 175369610\n'
            f'• Seoladh cláraithe: bul. Petko Karavelov, bl. 77, bealach isteach A, árasán 19, '
            f'ceantar Triaditza, cód poist 1408, Sóifia, an Bhulgáir\n'
            f'• Ríomhphost teagmhála: privacy@nevumo.com\n'
            f'• Ainm branda: Nevumo\n'
            f'• Suíomh gréasáin: nevumo.com\n\n'
            f'1.2 Rialaíonn na Téarmaí agus Coinníollacha seo úsáid ardán Nevumo ag cliaint — '
            f'úsáideoirí a bhíonn ag cuardach, ag teagmháil agus ag fostú soláthróirí seirbhíse.\n\n'
            f'1.3 Trí chuntas a chruthú nó an t-ardán a úsáid, aontaíonn tú leis na Téarmaí seo. '
            f'Mura n-aontaíonn tú, ní ceadmhach duit Nevumo a úsáid.\n\n'
            f'1.4 Má tá tú suite sa Pholainn, tá forálacha breise marcáilte [PL] i bhfeidhm '
            f'agus tá siad i dtosaíocht ar na téarmaí ginearálta i gcás coinbhleachta.'
        ),
        "hr": (
            f'1.1 Nevumo je online tržište usluga kojim upravlja {COMPANY} '
            f'(transliteracija: Filiphs Tsentar Bulgaria OOD), '
            f'društvo s ograničenom odgovornošću registrirano u Bugarskoj.\n\n'
            f'Podaci o tvrtki:\n'
            f'• Pravni naziv: {COMPANY}\n'
            f'• Registracijski broj (ЕИК): 175369610\n'
            f'• Registrirana adresa: bul. Petko Karavelov, bl. 77, ulaz A, stan 19, '
            f'četvrt Triaditza, poštanski broj 1408, Sofia, Bugarska\n'
            f'• Kontaktna e-pošta: privacy@nevumo.com\n'
            f'• Naziv marke: Nevumo\n'
            f'• Web stranica: nevumo.com\n\n'
            f'1.2 Ovi Uvjeti korištenja uređuju korištenje platforme Nevumo od strane klijenata — '
            f'korisnika koji pretražuju, kontaktiraju i angažiraju davatelje usluga putem platforme.\n\n'
            f'1.3 Stvaranjem računa ili korištenjem platforme pristajete na ove Uvjete. '
            f'Ako se ne slažete, ne smijete koristiti Nevumo.\n\n'
            f'1.4 Ako se nalazite u Poljskoj, primjenjuju se dodatne odredbe označene s [PL], '
            f'koje imaju prednost pred općim uvjetima u slučaju sukoba.'
        ),
        "hu": (
            f'1.1 A Nevumo egy online szolgáltatói piactér, amelyet {COMPANY} '
            f'(átírás: Filiphs Tsentar Bulgaria OOD), '
            f'egy Bulgáriában bejegyzett korlátolt felelősségű társaság üzemeltet.\n\n'
            f'Cégadatok:\n'
            f'• Cégnév: {COMPANY}\n'
            f'• Nyilvántartási szám (ЕИК): 175369610\n'
            f'• Bejegyzett cím: bul. Petko Karavelov, bl. 77, A lépcsőház, 19. ajtó, '
            f'Triaditza kerület, irányítószám 1408, Szófia, Bulgária\n'
            f'• Kapcsolatfelvételi e-mail: privacy@nevumo.com\n'
            f'• Márkanév: Nevumo\n'
            f'• Weboldal: nevumo.com\n\n'
            f'1.2 Jelen feltételek szabályozzák a Nevumo platform ügyfelek általi használatát — '
            f'olyan felhasználók által, akik a platformon keresztül keresnek, kapcsolatba lépnek '
            f'és megbíznak szolgáltatókkal.\n\n'
            f'1.3 Fiók létrehozásával vagy a platform használatával elfogadja jelen feltételeket. '
            f'Ha nem fogadja el, nem használhatja a Nevumot.\n\n'
            f'1.4 Ha Lengyelországban tartózkodik, a [PL]-lel jelölt további rendelkezések '
            f'alkalmazandók, amelyek konfliktus esetén elsőbbséget élveznek az általános feltételekkel szemben.'
        ),
        "is": (
            f'1.1 Nevumo er netþjónustutorg rekið af {COMPANY} '
            f'(transliterun: Filiphs Tsentar Bulgaria OOD), '
            f'einkahlutafélagi skráðu í Búlgaríu.\n\n'
            f'Upplýsingar um fyrirtæki:\n'
            f'• Lögheiti: {COMPANY}\n'
            f'• Skráningarnúmer (ЕИК): 175369610\n'
            f'• Skráð heimilisfang: bul. Petko Karavelov, bl. 77, inngangur A, íbúð 19, '
            f'Triaditza-hverfi, póstnúmer 1408, Sofía, Búlgaría\n'
            f'• Netfang til samskipta: privacy@nevumo.com\n'
            f'• Vörumerki: Nevumo\n'
            f'• Vefsíða: nevumo.com\n\n'
            f'1.2 Þessir skilmálar gilda um notkun Nevumo-vettvangsins af viðskiptavinum — '
            f'notendum sem leita, hafa samband við og ráða þjónustuaðila í gegnum vettvanginn.\n\n'
            f'1.3 Með því að stofna reikning eða nota vettvanginn samþykkir þú þessa skilmála. '
            f'Ef þú samþykkir ekki, mátt þú ekki nota Nevumo.\n\n'
            f'1.4 Ef þú ert staðsettur í Póllandi gilda viðbótarákvæði merkt [PL], '
            f'sem hafa forgang yfir almennum skilmálum við ágreining.'
        ),
        "it": (
            f'1.1 Nevumo è un mercato online di servizi gestito da {COMPANY} '
            f'(traslitterazione: Filiphs Tsentar Bulgaria OOD), '
            f'una società a responsabilità limitata registrata in Bulgaria.\n\n'
            f'Dati della società:\n'
            f'• Denominazione legale: {COMPANY}\n'
            f'• Numero di registrazione (ЕИК): 175369610\n'
            f'• Sede legale: bul. Petko Karavelov, bl. 77, ingresso A, apt. 19, '
            f'quartiere Triaditza, CAP 1408, Sofia, Bulgaria\n'
            f'• E-mail di contatto: privacy@nevumo.com\n'
            f'• Nome del brand: Nevumo\n'
            f'• Sito web: nevumo.com\n\n'
            f'1.2 I presenti Termini e Condizioni regolano l\'utilizzo della piattaforma Nevumo '
            f'da parte dei clienti — utenti che cercano, contattano e assumono fornitori di servizi.\n\n'
            f'1.3 Creando un account o utilizzando la piattaforma, l\'utente accetta i presenti Termini. '
            f'In caso di mancato accordo, non è consentito utilizzare Nevumo.\n\n'
            f'1.4 Se ti trovi in Polonia, si applicano disposizioni aggiuntive contrassegnate con [PL], '
            f'che prevalgono sui termini generali in caso di conflitto.'
        ),
        "lb": (
            f'1.1 Nevumo ass en Online-Servicemaart, dee vun {COMPANY} '
            f'(Translitteratioun: Filiphs Tsentar Bulgaria OOD), '
            f'enger a Bulgarien ageschriwwener GmbH, bedriwwe gëtt.\n\n'
            f'Firmendetailer:\n'
            f'• Firmennum: {COMPANY}\n'
            f'• Registratiounsnummer (ЕИК): 175369610\n'
            f'• Ageschriwwener Sëtz: bul. Petko Karavelov, bl. 77, Entrée A, Apt. 19, '
            f'Triaditza-Bezirk, Postleitzuel 1408, Sofia, Bulgarien\n'
            f'• Kontakt-E-Mail: privacy@nevumo.com\n'
            f'• Markennum: Nevumo\n'
            f'• Websäit: nevumo.com\n\n'
            f'1.2 Dës allgemeng Geschäftsbedéngungen regelen d\'Benotze vun der Nevumo-Plattform '
            f'duerch Klienten — Benotzer, déi no Serviceprestatairen sichen, se kontaktéieren an engagéieren.\n\n'
            f'1.3 Andeems Dir e Kont erstellt oder d\'Plattform benotzt, stëmmt Dir dësen Bedéngungen zou. '
            f'Wann Dir net averstane sidd, däerft Dir Nevumo net benotzen.\n\n'
            f'1.4 Wann Dir Iech a Polen befannen, gëllen zousätzlech Bestëmmungen mat [PL] '
            f'a bei engem Konflikt Virrang virun den allgemengen Bedéngungen hunn.'
        ),
        "lt": (
            f'1.1 Nevumo yra internetinė paslaugų rinka, kurią valdo {COMPANY} '
            f'(transliteracija: Filiphs Tsentar Bulgaria OOD), '
            f'Bulgarijoje įregistruota uždaroji akcinė bendrovė.\n\n'
            f'Įmonės duomenys:\n'
            f'• Juridinis pavadinimas: {COMPANY}\n'
            f'• Registracijos numeris (ЕИК): 175369610\n'
            f'• Registruotas adresas: bul. Petko Karavelov, bl. 77, įėjimas A, butas 19, '
            f'Triaditza rajonas, pašto kodas 1408, Sofija, Bulgarija\n'
            f'• Kontaktinis el. paštas: privacy@nevumo.com\n'
            f'• Prekės ženklo pavadinimas: Nevumo\n'
            f'• Svetainė: nevumo.com\n\n'
            f'1.2 Šios naudojimo sąlygos reglamentuoja Nevumo platformos naudojimą klientų — '
            f'naudotojų, kurie per platformą ieško, susisiekia ir samdosi paslaugų teikėjus.\n\n'
            f'1.3 Sukūrę paskyrą arba naudodami platformą, sutinkate su šiomis sąlygomis. '
            f'Jei nesutinkate, neturite teisės naudoti Nevumo.\n\n'
            f'1.4 Jei esate Lenkijoje, taikomos papildomos nuostatos, pažymėtos [PL], '
            f'kurios nesutarimų atveju turi viršenybę prieš bendruosius terminus.'
        ),
        "lv": (
            f'1.1 Nevumo ir tiešsaistes pakalpojumu tirgus platforma, ko pārvalda {COMPANY} '
            f'(transliterācija: Filiphs Tsentar Bulgaria OOD), '
            f'Bulgārijā reģistrēta sabiedrība ar ierobežotu atbildību.\n\n'
            f'Uzņēmuma dati:\n'
            f'• Juridiskais nosaukums: {COMPANY}\n'
            f'• Reģistrācijas numurs (ЕИК): 175369610\n'
            f'• Reģistrētā adrese: bul. Petko Karavelov, bl. 77, ieeja A, dzīvoklis 19, '
            f'Triaditza rajons, pasta indekss 1408, Sofija, Bulgārija\n'
            f'• Kontaktinformācija: privacy@nevumo.com\n'
            f'• Zīmola nosaukums: Nevumo\n'
            f'• Vietne: nevumo.com\n\n'
            f'1.2 Šie lietošanas noteikumi regulē Nevumo platformas izmantošanu klientu — '
            f'lietotāju, kuri meklē, sazinās un nolīgst pakalpojumu sniedzējus.\n\n'
            f'1.3 Izveidojot kontu vai izmantojot platformu, jūs piekrītat šiem noteikumiem. '
            f'Ja nepiekrītat, jums nav atļauts izmantot Nevumo.\n\n'
            f'1.4 Ja atrodaties Polijā, piemērojami papildu noteikumi, kas apzīmēti ar [PL], '
            f'kuriem pretrunu gadījumā ir prioritāte pār vispārējiem noteikumiem.'
        ),
        "mk": (
            f'1.1 Nevumo е онлајн пазар на услуги, управуван од {COMPANY} '
            f'(транслитерација: Filiphs Tsentar Bulgaria OOD), '
            f'друштво со ограничена одговорност регистрирано во Бугарија.\n\n'
            f'Податоци за компанијата:\n'
            f'• Правен назив: {COMPANY}\n'
            f'• Регистарски број (ЕИК): 175369610\n'
            f'• Регистрирана адреса: bul. Petko Karavelov, bl. 77, влез A, стан 19, '
            f'населба Triaditza, поштенски код 1408, Софија, Бугарија\n'
            f'• Контакт е-пошта: privacy@nevumo.com\n'
            f'• Назив на бренд: Nevumo\n'
            f'• Веб-страница: nevumo.com\n\n'
            f'1.2 Овие Услови за користење го регулираат користењето на платформата Nevumo '
            f'од страна на клиентите — корисници кои бараат, контактираат и ангажираат '
            f'даватели на услуги преку платформата.\n\n'
            f'1.3 Со создавање на акаунт или со користење на платформата, се согласувате со овие Услови. '
            f'Ако не се согласувате, не смеете да го користите Nevumo.\n\n'
            f'1.4 Доколку се наоѓате во Полска, се применуваат дополнителни одредби означени со [PL], '
            f'кои при судир имаат предност пред општите услови.'
        ),
        "mt": (
            f'1.1 Nevumo hija suq ta\' servizzi online operat minn {COMPANY} '
            f'(translitterazzjoni: Filiphs Tsentar Bulgaria OOD), '
            f'kumpanija b\'responsabbiltà limitata rreġistrata fil-Bulgarija.\n\n'
            f'Dettalji tal-kumpanija:\n'
            f'• Isem legali: {COMPANY}\n'
            f'• Numru ta\' reġistrazzjoni (ЕИК): 175369610\n'
            f'• Indirizz irreġistrat: bul. Petko Karavelov, bl. 77, daħla A, apt. 19, '
            f'distrett Triaditza, kodiċi postali 1408, Sofia, il-Bulgarija\n'
            f'• Email ta\' kuntatt: privacy@nevumo.com\n'
            f'• Isem tal-brand: Nevumo\n'
            f'• Sit web: nevumo.com\n\n'
            f'1.2 Dawn it-Termini u Kundizzjonijiet jirregolaw l-użu tal-pjattaforma Nevumo '
            f'mill-klijenti — utenti li jfittxu, jikkuntattjaw u jinkludu fornituri ta\' servizzi.\n\n'
            f'1.3 Billi toħloq kont jew tuża l-pjattaforma, taqbel ma\' dawn it-Termini. '
            f'Jekk ma taqbilx, m\'għandekx tuża Nevumo.\n\n'
            f'1.4 Jekk tinsab fil-Polonja, japplikaw dispożizzjonijiet addizzjonali mmarkati [PL], '
            f'li jipprevalu fuq it-termini ġenerali f\'każ ta\' kunflitt.'
        ),
        "nl": (
            f'1.1 Nevumo is een online dienstenmarktplaats beheerd door {COMPANY} '
            f'(transliteratie: Filiphs Tsentar Bulgaria OOD), '
            f'een in Bulgarije geregistreerde besloten vennootschap.\n\n'
            f'Bedrijfsgegevens:\n'
            f'• Handelsnaam: {COMPANY}\n'
            f'• Registratienummer (ЕИК): 175369610\n'
            f'• Geregistreerd adres: bul. Petko Karavelov, bl. 77, ingang A, apt. 19, '
            f'wijk Triaditza, postcode 1408, Sofia, Bulgarije\n'
            f'• Contact e-mail: privacy@nevumo.com\n'
            f'• Merknaam: Nevumo\n'
            f'• Website: nevumo.com\n\n'
            f'1.2 Deze Algemene Voorwaarden regelen het gebruik van het Nevumo-platform door klanten — '
            f'gebruikers die via het platform serviceproviders zoeken, contacteren en inhuren.\n\n'
            f'1.3 Door een account aan te maken of het platform te gebruiken, gaat u akkoord '
            f'met deze Voorwaarden. Als u niet akkoord gaat, mag u Nevumo niet gebruiken.\n\n'
            f'1.4 Als u zich in Polen bevindt, zijn aanvullende bepalingen gemarkeerd met [PL] '
            f'van toepassing, die in geval van conflict voorrang hebben boven de algemene voorwaarden.'
        ),
        "no": (
            f'1.1 Nevumo er en nettbasert tjenestemarkedsplass drevet av {COMPANY} '
            f'(translitterering: Filiphs Tsentar Bulgaria OOD), '
            f'et aksjeselskap registrert i Bulgaria.\n\n'
            f'Firmaopplysninger:\n'
            f'• Juridisk navn: {COMPANY}\n'
            f'• Registreringsnummer (ЕИК): 175369610\n'
            f'• Registrert adresse: bul. Petko Karavelov, bl. 77, oppgang A, leil. 19, '
            f'Triaditza bydel, postnummer 1408, Sofia, Bulgaria\n'
            f'• Kontakt-e-post: privacy@nevumo.com\n'
            f'• Merkevarenavn: Nevumo\n'
            f'• Nettsted: nevumo.com\n\n'
            f'1.2 Disse Vilkårene regulerer klienters bruk av Nevumo-plattformen — '
            f'brukere som søker, kontakter og ansetter tjenesteleverandører via plattformen.\n\n'
            f'1.3 Ved å opprette en konto eller bruke plattformen, godtar du disse Vilkårene. '
            f'Hvis du ikke godtar, kan du ikke bruke Nevumo.\n\n'
            f'1.4 Hvis du befinner deg i Polen, gjelder ytterligere bestemmelser merket med [PL], '
            f'som har forrang foran de generelle vilkårene ved konflikt.'
        ),
        "pt": (
            f'1.1 O Nevumo é um mercado online de serviços operado pela {COMPANY} '
            f'(transliteração: Filiphs Tsentar Bulgaria OOD), '
            f'uma sociedade por quotas registrada na Bulgária.\n\n'
            f'Dados da empresa:\n'
            f'• Denominação social: {COMPANY}\n'
            f'• Número de registro (ЕИК): 175369610\n'
            f'• Endereço registrado: bul. Petko Karavelov, bl. 77, entrada A, apt. 19, '
            f'bairro Triaditza, CEP 1408, Sófia, Bulgária\n'
            f'• E-mail de contato: privacy@nevumo.com\n'
            f'• Nome da marca: Nevumo\n'
            f'• Site: nevumo.com\n\n'
            f'1.2 Estes Termos e Condições regulam o uso da plataforma Nevumo pelos clientes — '
            f'usuários que pesquisam, entram em contato e contratam prestadores de serviços.\n\n'
            f'1.3 Ao criar uma conta ou usar a plataforma, você concorda com estes Termos. '
            f'Se não concordar, não deve usar o Nevumo.\n\n'
            f'1.4 Se você estiver na Polônia, aplicam-se disposições adicionais marcadas com [PL], '
            f'que prevalecem sobre os termos gerais em caso de conflito.'
        ),
        "pt-PT": (
            f'1.1 O Nevumo é um mercado online de serviços operado pela {COMPANY} '
            f'(transliteração: Filiphs Tsentar Bulgaria OOD), '
            f'uma sociedade por quotas registada na Bulgária.\n\n'
            f'Dados da empresa:\n'
            f'• Denominação social: {COMPANY}\n'
            f'• Número de registo (ЕИК): 175369610\n'
            f'• Endereço registado: bul. Petko Karavelov, bl. 77, entrada A, apt. 19, '
            f'bairro Triaditza, código postal 1408, Sófia, Bulgária\n'
            f'• E-mail de contacto: privacy@nevumo.com\n'
            f'• Nome da marca: Nevumo\n'
            f'• Website: nevumo.com\n\n'
            f'1.2 Estes Termos e Condições regulam a utilização da plataforma Nevumo pelos clientes — '
            f'utilizadores que pesquisam, contactam e contratam prestadores de serviços.\n\n'
            f'1.3 Ao criar uma conta ou utilizar a plataforma, aceita os presentes Termos. '
            f'Se não aceitar, não deve utilizar o Nevumo.\n\n'
            f'1.4 Se estiver na Polónia, aplicam-se disposições adicionais assinaladas com [PL], '
            f'que prevalecem sobre os termos gerais em caso de conflito.'
        ),
        "ro": (
            f'1.1 Nevumo este o piață online de servicii operată de {COMPANY} '
            f'(transliterare: Filiphs Tsentar Bulgaria OOD), '
            f'o societate cu răspundere limitată înregistrată în Bulgaria.\n\n'
            f'Date ale companiei:\n'
            f'• Denumire legală: {COMPANY}\n'
            f'• Număr de înregistrare (ЕИК): 175369610\n'
            f'• Adresă înregistrată: bul. Petko Karavelov, bl. 77, intrarea A, apt. 19, '
            f'sectorul Triaditza, cod poștal 1408, Sofia, Bulgaria\n'
            f'• E-mail de contact: privacy@nevumo.com\n'
            f'• Nume de marcă: Nevumo\n'
            f'• Site web: nevumo.com\n\n'
            f'1.2 Acești Termeni și Condiții reglementează utilizarea platformei Nevumo de către clienți — '
            f'utilizatori care caută, contactează și angajează prestatori de servicii.\n\n'
            f'1.3 Prin crearea unui cont sau utilizarea platformei, acceptați acești Termeni. '
            f'Dacă nu sunteți de acord, nu trebuie să utilizați Nevumo.\n\n'
            f'1.4 Dacă vă aflați în Polonia, se aplică dispoziții suplimentare marcate cu [PL], '
            f'care prevalează asupra termenilor generali în caz de conflict.'
        ),
        "ru": (
            f'1.1 Nevumo — это онлайн-платформа для поиска услуг, которую ведёт {COMPANY} '
            f'(транслитерация: Filiphs Tsentar Bulgaria OOD), ООО, зарегистрированное в Болгарии.\n\n'
            f'Данные компании:\n'
            f'• Юридическое наименование: {COMPANY}\n'
            f'• Регистрационный номер (ЕИК): 175369610\n'
            f'• Юридический адрес: bul. Petko Karavelov, bl. 77, подъезд A, кв. 19, '
            f'район Триадица, индекс 1408, г. София, Болгария\n'
            f'• Контактный e-mail: privacy@nevumo.com\n'
            f'• Торговая марка: Nevumo\n'
            f'• Сайт: nevumo.com\n\n'
            f'1.2 Настоящее соглашение регулирует использование платформы Nevumo клиентами — '
            f'пользователями, которые ищут, связываются и нанимают исполнителей услуг.\n\n'
            f'1.3 Регистрируясь или используя платформу, вы принимаете условия соглашения. '
            f'Если вы не согласны, вы не вправе использовать Nevumo.\n\n'
            f'1.4 Если вы в Польше, применяются дополнительные положения [PL], '
            f'которые при противоречии имеют приоритет над общими условиями.'
        ),
        "sk": (
            f'1.1 Nevumo je online trhisko služieb prevádzkované spoločnosťou {COMPANY} '
            f'(transliterácia: Filiphs Tsentar Bulgaria OOD), '
            f'spoločnosťou s ručením obmedzeným registrovanou v Bulharsku.\n\n'
            f'Údaje spoločnosti:\n'
            f'• Obchodné meno: {COMPANY}\n'
            f'• Registračné číslo (ЕИК): 175369610\n'
            f'• Sídlo: bul. Petko Karavelov, bl. 77, vchod A, byt 19, '
            f'okres Triaditza, PSČ 1408, Sofia, Bulharsko\n'
            f'• Kontaktný e-mail: privacy@nevumo.com\n'
            f'• Názov značky: Nevumo\n'
            f'• Webová stránka: nevumo.com\n\n'
            f'1.2 Tieto Všeobecné obchodné podmienky upravujú používanie platformy Nevumo klientmi — '
            f'používateľmi, ktorí prostredníctvom platformy vyhľadávajú, kontaktujú a najímajú '
            f'poskytovateľov služieb.\n\n'
            f'1.3 Vytvorením účtu alebo používaním platformy vyjadrujete súhlas s týmito podmienkami. '
            f'Ak nesúhlasíte, nesmíte Nevumo používať.\n\n'
            f'1.4 Ak sa nachádzate v Poľsku, platia dodatočné ustanovenia označené [PL], '
            f'ktoré v prípade rozporu majú prednosť pred všeobecnými podmienkami.'
        ),
        "sl": (
            f'1.1 Nevumo je spletno tržišče storitev, ki ga upravlja {COMPANY} '
            f'(transliteracija: Filiphs Tsentar Bulgaria OOD), '
            f'družba z omejeno odgovornostjo, registrirana v Bolgariji.\n\n'
            f'Podatki o podjetju:\n'
            f'• Pravno ime: {COMPANY}\n'
            f'• Registrska številka (ЕИК): 175369610\n'
            f'• Registrirani naslov: bul. Petko Karavelov, bl. 77, vhod A, stanovanje 19, '
            f'četrt Triaditza, poštna številka 1408, Sofija, Bolgarija\n'
            f'• Kontaktni e-poštni naslov: privacy@nevumo.com\n'
            f'• Ime blagovne znamke: Nevumo\n'
            f'• Spletna stran: nevumo.com\n\n'
            f'1.2 Ti splošni pogoji urejajo uporabo platforme Nevumo s strani strank — '
            f'uporabnikov, ki prek platforme iščejo, stopajo v stik in angažirajo ponudnike storitev.\n\n'
            f'1.3 Z ustvarjanjem računa ali z uporabo platforme soglašate s temi pogoji. '
            f'Če se ne strinjate, platforme Nevumo ne smete uporabljati.\n\n'
            f'1.4 Če se nahajate na Poljskem, se uporabljajo dodatne določbe, označene z [PL], '
            f'ki imajo v primeru nasprotja prednost pred splošnimi pogoji.'
        ),
        "sq": (
            f'1.1 Nevumo është një treg online shërbimesh i operuar nga {COMPANY} '
            f'(transliterim: Filiphs Tsentar Bulgaria OOD), '
            f'shoqëri me përgjegjësi të kufizuar e regjistruar në Bullgari.\n\n'
            f'Të dhënat e kompanisë:\n'
            f'• Emri ligjor: {COMPANY}\n'
            f'• Numri i regjistrimit (ЕИК): 175369610\n'
            f'• Adresa e regjistruar: bul. Petko Karavelov, bl. 77, hyrja A, apt. 19, '
            f'lagjja Triaditza, kodi postar 1408, Sofje, Bullgari\n'
            f'• Email kontakti: privacy@nevumo.com\n'
            f'• Emri i markës: Nevumo\n'
            f'• Faqja web: nevumo.com\n\n'
            f'1.2 Këto Terma dhe Kushte rregullojnë përdorimin e platformës Nevumo nga klientët — '
            f'përdorues që kërkojnë, kontaktojnë dhe punësojnë ofruesit e shërbimeve.\n\n'
            f'1.3 Duke krijuar një llogari ose duke përdorur platformën, pranoni këto Terma. '
            f'Nëse nuk pranoni, nuk duhet të përdorni Nevumo.\n\n'
            f'1.4 Nëse ndodheni në Poloni, zbatohen dispozita shtesë të shënuara me [PL], '
            f'të cilat kanë përparësi ndaj kushteve të përgjithshme në rast konflikti.'
        ),
        "sr": (
            f'1.1 Nevumo je online tržište usluga kojim upravlja {COMPANY} '
            f'(transliteracija: Filiphs Tsentar Bulgaria OOD), '
            f'društvo sa ograničenom odgovornošću registrovano u Bugarskoj.\n\n'
            f'Podaci o kompaniji:\n'
            f'• Pravno ime: {COMPANY}\n'
            f'• Registarski broj (ЕИК): 175369610\n'
            f'• Registrovana adresa: bul. Petko Karavelov, bl. 77, ulaz A, stan 19, '
            f'četvrt Triaditza, poštanski broj 1408, Sofija, Bugarska\n'
            f'• Kontakt imejl: privacy@nevumo.com\n'
            f'• Naziv brenda: Nevumo\n'
            f'• Veb stranica: nevumo.com\n\n'
            f'1.2 Ovi Opšti uslovi uređuju korišćenje platforme Nevumo od strane klijenata — '
            f'korisnika koji pretražuju, kontaktiraju i angažuju pružaoce usluga putem platforme.\n\n'
            f'1.3 Kreiranjem naloga ili korišćenjem platforme pristajete na ove Uslove. '
            f'Ako se ne slažete, ne smete koristiti Nevumo.\n\n'
            f'1.4 Ako se nalazite u Poljskoj, primenjuju se dodatne odredbe označene sa [PL], '
            f'koje imaju prednost pred opštim uslovima u slučaju sukoba.'
        ),
        "sv": (
            f'1.1 Nevumo är en online-marknadsplats för tjänster som drivs av {COMPANY} '
            f'(translitterering: Filiphs Tsentar Bulgaria OOD), '
            f'ett i Bulgarien registrerat aktiebolag.\n\n'
            f'Företagsuppgifter:\n'
            f'• Juridiskt namn: {COMPANY}\n'
            f'• Registreringsnummer (ЕИК): 175369610\n'
            f'• Registrerad adress: bul. Petko Karavelov, bl. 77, ingång A, läg. 19, '
            f'Triaditza-distriktet, postnummer 1408, Sofia, Bulgarien\n'
            f'• Kontaktens e-postadress: privacy@nevumo.com\n'
            f'• Varumärkesnamn: Nevumo\n'
            f'• Webbplats: nevumo.com\n\n'
            f'1.2 Dessa Allmänna villkor reglerar klienters användning av Nevumo-plattformen — '
            f'användare som söker, kontaktar och anlitar tjänsteleverantörer via plattformen.\n\n'
            f'1.3 Genom att skapa ett konto eller använda plattformen godkänner du dessa Villkor. '
            f'Om du inte godkänner dem får du inte använda Nevumo.\n\n'
            f'1.4 Om du befinner dig i Polen gäller ytterligare bestämmelser markerade med [PL], '
            f'som har företräde framför de allmänna villkoren vid konflikt.'
        ),
        "tr": (
            f'1.1 Nevumo, Bulgaristan\'da kayıtlı bir limited şirket olan {COMPANY} '
            f'(transliterasyon: Filiphs Tsentar Bulgaria OOD) tarafından işletilen '
            f'çevrimiçi bir hizmet pazaryeridir.\n\n'
            f'Şirket bilgileri:\n'
            f'• Ticari unvan: {COMPANY}\n'
            f'• Kayıt numarası (ЕИК): 175369610\n'
            f'• Kayıtlı adres: bul. Petko Karavelov, bl. 77, A girişi, daire 19, '
            f'Triaditza bölgesi, posta kodu 1408, Sofya, Bulgaristan\n'
            f'• İletişim e-postası: privacy@nevumo.com\n'
            f'• Marka adı: Nevumo\n'
            f'• Web sitesi: nevumo.com\n\n'
            f'1.2 İşbu Hüküm ve Koşullar, Nevumo platformunun müşteriler tarafından '
            f'kullanımını düzenlemektedir — platform aracılığıyla hizmet sağlayıcı '
            f'arayan, iletişim kuran ve işe alan kullanıcılar.\n\n'
            f'1.3 Bir hesap oluşturarak veya platformu kullanarak bu Koşulları kabul etmiş '
            f'sayılırsınız. Kabul etmiyorsanız Nevumo\'yu kullanamazsınız.\n\n'
            f'1.4 Polonya\'da iseniz, [PL] ile işaretlenmiş ek hükümler geçerlidir '
            f've çatışma durumunda genel şartların önünde gelir.'
        ),
        "uk": (
            f'1.1 Nevumo — це онлайн-платформа для пошуку послуг, яку веде {COMPANY} '
            f'(транслітерація: Filiphs Tsentar Bulgaria OOD), '
            f'ТОВ, зареєстроване в Болгарії.\n\n'
            f'Дані компанії:\n'
            f'• Юридична назва: {COMPANY}\n'
            f'• Реєстраційний номер (ЄІК): 175369610\n'
            f'• Юридична адреса: bul. Petko Karavelov, bl. 77, під\'їзд A, кв. 19, '
            f'район Триадиця, індекс 1408, м. Софія, Болгарія\n'
            f'• Контактний e-mail: privacy@nevumo.com\n'
            f'• Назва бренду: Nevumo\n'
            f'• Веб-сайт: nevumo.com\n\n'
            f'1.2 Ці Умови використання регулюють використання платформи Nevumo клієнтами — '
            f'користувачами, які шукають, зв\'язуються та наймають виконавців послуг.\n\n'
            f'1.3 Реєструючись або використовуючи платформу, ви приймаєте ці Умови. '
            f'Якщо ви не погоджуєтесь, ви не можете використовувати Nevumo.\n\n'
            f'1.4 Якщо ви у Польщі, застосовуються додаткові положення, позначені [PL], '
            f'які мають пріоритет над загальними умовами у разі суперечності.'
        ),
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_p1_bodies: {count} rows upserted ({NAMESPACE}, art1_body × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()