# -*- coding: utf-8 -*-
"""
seed_cookies_p13.py - namespace 'cookies'
cookies.s4_text, cookies.s5_title, cookies.s5_col_name,
cookies.s5_col_type, cookies.s5_col_purpose
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p13
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL")
engine = create_engine(DATABASE_URL)

TRANSLATIONS = {
    "cookies.s4_text": {
        "en": "When you provide a phone number on the platform (e.g., when submitting a service request), we temporarily store it in your browser's local storage under the key nevumo_phone. This enables autofill on subsequent visits so you do not have to type it again. Legal basis: Art. 6(1)(f) GDPR - legitimate interest in reducing friction and improving user experience. This data never leaves your device unless you explicitly submit a form. You can delete it at any time by clearing your browser's local storage or via your account settings.",
        "bg": "Когато предоставите телефонен номер на платформата (напр. при изпращане на запитване за услуга), го съхраняваме временно в локалното хранилище на браузъра ви под ключ nevumo_phone. Това позволява автоматичното попълване при следващи посещения. Правно основание: Чл. 6, ал. 1, б. е) GDPR - легитимен интерес за намаляване на затруднения и подобряване на потребителското изживяване. Тези данни никога не напускат вашето устройство, освен ако изрично не изпратите формуляр. Можете да ги изтриете по всяко време, като изчистите local storage на браузъра или чрез настройките на профила.",
        "cs": "Když na platformě zadáte telefonní číslo (např. při odesílání žádosti o službu), dočasně jej uložíme do lokálního úložiště vašeho prohlížeče pod klíčem nevumo_phone. To umožňuje automatické vyplnění při dalších návštěvách. Právní základ: Čl. 6(1)(f) GDPR - oprávněný zájem na snížení zátěže a zlepšení uživatelského zážitku. Tato data nikdy neopustí vaše zařízení, pokud výslovně neodešlete formulář. Kdykoli je můžete smazat vymazáním lokálního úložiště prohlížeče nebo v nastavení účtu.",
        "da": "Når du angiver et telefonnummer på platformen (f.eks. ved indsendelse af en serviceanmodning), gemmer vi det midlertidigt i din browsers lokale lagring under nøglen nevumo_phone. Dette muliggør automatisk udfyldelse ved efterfølgende besøg. Retsgrundlag: Art. 6(1)(f) GDPR - legitim interesse i at reducere friktion og forbedre brugeroplevelsen. Disse data forlader aldrig din enhed, medmindre du eksplicit indsender en formular. Du kan slette dem til enhver tid ved at rydde din browsers lokale lagring eller via dine kontoindstillinger.",
        "de": "Wenn Sie auf der Plattform eine Telefonnummer angeben (z. B. beim Einreichen einer Serviceanfrage), speichern wir diese vorübergehend im lokalen Speicher Ihres Browsers unter dem Schlüssel nevumo_phone. Dies ermöglicht die automatische Vorausfüllung bei späteren Besuchen. Rechtsgrundlage: Art. 6(1)(f) DSGVO - berechtigtes Interesse an der Reduzierung von Reibung und der Verbesserung der Nutzererfahrung. Diese Daten verlassen Ihr Gerät nie, es sei denn, Sie senden explizit ein Formular ab. Sie können sie jederzeit löschen, indem Sie den lokalen Speicher Ihres Browsers leeren oder über Ihre Kontoeinstellungen.",
        "el": "Όταν παρέχετε αριθμό τηλεφώνου στην πλατφόρμα (π.χ. κατά την υποβολή αιτήματος υπηρεσίας), τον αποθηκεύουμε προσωρινά στον τοπικό χώρο αποθήκευσης του προγράμματος περιήγησής σας με το κλειδί nevumo_phone. Αυτό επιτρέπει την αυτόματη συμπλήρωση σε επόμενες επισκέψεις. Νομική βάση: Άρθρο 6(1)(στ) GDPR - έννομο συμφέρον για μείωση τριβής και βελτίωση εμπειρίας χρήστη. Αυτά τα δεδομένα δεν αφήνουν ποτέ τη συσκευή σας εκτός εάν υποβάλετε ρητά μια φόρμα. Μπορείτε να τα διαγράψετε ανά πάσα στιγμή εκκαθαρίζοντας τον τοπικό χώρο αποθήκευσης ή μέσω των ρυθμίσεων λογαριασμού.",
        "es": "Cuando proporciona un número de teléfono en la plataforma (p. ej., al enviar una solicitud de servicio), lo almacenamos temporalmente en el almacenamiento local de su navegador bajo la clave nevumo_phone. Esto permite el autocompletado en visitas posteriores. Base jurídica: Art. 6(1)(f) RGPD - interés legítimo en reducir la fricción y mejorar la experiencia del usuario. Estos datos nunca abandonan su dispositivo a menos que envíe explícitamente un formulario. Puede eliminarlos en cualquier momento borrando el almacenamiento local de su navegador o a través de la configuración de su cuenta.",
        "et": "Kui esitate platvormil telefoninumbri (nt teenusepäringu esitamisel), salvestame selle ajutiselt oma brauseri kohalikku salvestusruumi võtme nevumo_phone alla. See võimaldab automaatset täitmist järgnevatel külastustel. Õiguslik alus: Art. 6(1)(f) GDPR - õigustatud huvi hõõrdumise vähendamise ja kasutajakogemuse parandamise vastu. Need andmed ei lahku kunagi teie seadmest, välja arvatud juhul, kui esitate vormi selgesõnaliselt. Saate need igal ajal kustutada, tühjendades oma brauseri kohaliku salvestusruumi või oma konto seadete kaudu.",
        "fi": "Kun annat puhelinnumeron alustalla (esim. palvelupyyntöä lähettäessäsi), tallennamme sen väliaikaisesti selaimesi paikalliseen tallennustilaan avaimen nevumo_phone alle. Tämä mahdollistaa automaattisen täytön tulevilla vierailuilla. Oikeusperuste: Art. 6(1)(f) GDPR - oikeutettu etu kitkan vähentämisessä ja käyttäjäkokemuksen parantamisessa. Nämä tiedot eivät koskaan poistu laitteeltasi, ellei sinä nimenomaisesti lähetä lomaketta. Voit poistaa ne milloin tahansa tyhjentämällä selaimesi paikallisen tallennustilan tai tilin asetusten kautta.",
        "fr": "Lorsque vous fournissez un numéro de téléphone sur la plateforme (p. ex. lors de la soumission d'une demande de service), nous le stockons temporairement dans le stockage local de votre navigateur sous la clé nevumo_phone. Cela permet le remplissage automatique lors des visites suivantes. Base juridique : Art. 6(1)(f) RGPD - intérêt légitime à réduire les frictions et à améliorer l'expérience utilisateur. Ces données ne quittent jamais votre appareil sauf si vous soumettez explicitement un formulaire. Vous pouvez les supprimer à tout moment en effaçant le stockage local de votre navigateur ou via les paramètres de votre compte.",
        "ga": "Nuair a sholáthraíonn tú uimhir ghutháin ar an ardán (m.sh. agus iarratas seirbhíse á chur isteach), stóráilimid go sealadach é i stóráil áitiúil do bhrabhsálaí faoin eochair nevumo_phone. Cumasaíonn sé seo uathlíonadh ar chuairteanna ina dhiaidh sin. Bunús dlí: Alt 6(1)(f) GDPR - leas dlisteanach in fhrithchuimilt a laghdú agus an eispéireas úsáideora a fheabhsú. Ní fhágann na sonraí seo do ghléas riamh ach amháin má chuireann tú foirm isteach go sainráite. Is féidir leat iad a scriosadh am ar bith trí stóráil áitiúil do bhrabhsálaí a ghlanadh nó trí shocruithe do chuntais.",
        "hr": "Kada navedete telefonski broj na platformi (npr. pri slanju zahtjeva za uslugom), privremeno ga pohranjujemo u lokalnu pohranu vašeg preglednika pod ključem nevumo_phone. To omogućuje automatsko popunjavanje pri naknadnim posjetima. Pravna osnova: čl. 6(1)(f) GDPR - legitimni interes za smanjenje trenja i poboljšanje korisničkog iskustva. Ovi podaci nikad ne napuštaju vaš uređaj osim ako izričito ne podnesete obrazac. Možete ih obrisati u bilo koje vrijeme brisanjem lokalne pohrane preglednika ili putem postavki računa.",
        "hu": "Amikor telefonszámot ad meg a platformon (pl. szolgáltatási kérelem benyújtásakor), ideiglenesen tároljuk azt a böngésző helyi tárhelyén a nevumo_phone kulcs alatt. Ez lehetővé teszi az automatikus kitöltést a következő látogatásokon. Jogalap: 6. cikk (1) bek. f) pont GDPR - jogos érdek a súrlódás csökkentése és a felhasználói élmény javítása érdekében. Ezek az adatok soha nem hagyják el az eszközét, kivéve, ha kifejezetten benyújt egy űrlapot. Bármikor törölheti azokat a böngésző helyi tárhelyének törlésével vagy a fiókbeállítások segítségével.",
        "is": "Þegar þú gefur upp símanúmer á gáttinni (t.d. þegar þjónustubeiðni er send), geymum við það tímabundið í staðbundinni geymslu vafrans þíns undir lykilnum nevumo_phone. Þetta gerir kleift að sjálfvirkt fylla út við síðari heimsóknir. Lagagrundvöllur: Gr. 6(1)(f) GDPR - lögmætir hagsmunir af því að draga úr núningi og bæta notendaupplifun. Þessi gögn fara aldrei frá tækinu þínu nema þú sendirðu form sérstaklega. Þú getur eytt þeim hvenær sem er með því að hreinsa staðbundna geymslu vafrans þíns eða í gegnum reikningsstillingar.",
        "it": "Quando fornisci un numero di telefono sulla piattaforma (es. inviando una richiesta di servizio), lo memorizziamo temporaneamente nel local storage del tuo browser sotto la chiave nevumo_phone. Questo consente la compilazione automatica nelle visite successive. Base giuridica: Art. 6(1)(f) GDPR - interesse legittimo a ridurre le frizioni e migliorare l'esperienza utente. Questi dati non lasciano mai il tuo dispositivo a meno che tu non invii esplicitamente un modulo. Puoi eliminarli in qualsiasi momento cancellando il local storage del browser o tramite le impostazioni dell'account.",
        "lb": "Wann Dir eng Telefonnummer op der Plattform ugëtt (z.B. beim Abschécken vun enger Serviceanfroe), späichert mir se temporär am lokale Späicher vun Ärem Browser ënnert dem Schlëssel nevumo_phone. Dëst erlaabt d'Autofill bei nofolgende Besooche. Rechtlech Basis: Art. 6(1)(f) DSGVO - berechtigten Interesse fir d'Reibung ze reduzéieren an d'Notzererfahrung ze verbesseren. Dës Donnéeën verloossen Äre Apparat ni, ausser Dir schéckt explizit e Formulaire of. Dir kënnt se jederzeit läschen andeems Dir de lokale Späicher vum Browser leert oder iwwert d'Kontoastellungen.",
        "lt": "Kai platformoje pateikiate telefono numerį (pvz. teikiant paslaugos užklausą), laikinai jį saugome jūsų naršyklės vietinėje saugykloje pagal raktą nevumo_phone. Tai leidžia automatiškai užpildyti per tolesnius apsilankymus. Teisinis pagrindas: BDAR 6 str. 1 d. f p. - teisėtas interesas sumažinti trintį ir pagerinti naudotojo patirtį. Šie duomenys niekada nepalieka jūsų įrenginio, nebent aiškiai pateikiate formą. Galite juos ištrinti bet kada išvalydami naršyklės vietinę saugyklą arba per paskyros nustatymus.",
        "lv": "Kad platformā norādāt tālruņa numuru (piem. iesniedzot pakalpojuma pieprasījumu), mēs to īslaicīgi saglabājam jūsu pārlūkprogrammas lokālajā krātuvē zem atslēgas nevumo_phone. Tas ļauj automātiski aizpildīt turpmākajos apmeklējumos. Juridiskais pamats: VDAR 6. panta 1. punkta f) apakšpunkts - leģitīmās intereses berzes samazināšanā un lietotāja pieredzes uzlabošanā. Šie dati nekad neatstāj jūsu ierīci, ja vien jūs nepārprotami neiesniedzat veidlapu. Jūs varat tos izdzēst jebkurā laikā, notīrot pārlūkprogrammas lokālo krātuvi vai izmantojot konta iestatījumus.",
        "mk": "Кога давате телефонски број на платформата (на пр. при поднесување барање за услуга), привремено го зачувуваме во локалното складирање на вашиот прелистувач под клучот nevumo_phone. Ова овозможува автоматско пополнување при следните посети. Правна основа: чл. 6(1)(е) GDPR - легитимен интерес за намалување на фрикцијата и подобрување на корисничкото искуство. Овие податоци никогаш не ги напуштаат вашиот уред освен ако изрично не поднесете формулар. Можете да ги избришете во секое време со чистење на локалното складирање или преку поставките на профилот.",
        "mt": "Meta tipprovdi numru ta' telefon fuq il-pjattaforma (eż. meta tibgħat talba għal servizz), naħżnuh temporanjament fil-ħażna lokali tal-browser tiegħek taħt iċ-ċavetta nevumo_phone. Dan jippermetti l-mili awtomatiku f'żjarat sussegwenti. Bażi legali: Art. 6(1)(f) GDPR - interess leġittimu fit-tnaqqis tal-frizzjoni u t-titjib tal-esperjenza tal-utent. Dawn id-data qatt ma jitilqu mill-apparat tiegħek sakemm ma tibgħatx formola espliċitament. Tista' tħassarhom fi kwalunkwe ħin billi tneħħi l-ħażna lokali tal-browser jew permezz tas-settings tal-kont.",
        "nl": "Wanneer u een telefoonnummer op het platform opgeeft (bijv. bij het indienen van een serviceverzoek), slaan we het tijdelijk op in de lokale opslag van uw browser onder de sleutel nevumo_phone. Dit maakt automatisch invullen bij volgende bezoeken mogelijk. Rechtsgrondslag: Art. 6(1)(f) AVG - gerechtvaardigd belang bij het verminderen van wrijving en het verbeteren van de gebruikerservaring. Deze gegevens verlaten uw apparaat nooit tenzij u expliciet een formulier indient. U kunt ze op elk gewenst moment verwijderen door de lokale opslag van uw browser te wissen of via uw accountinstellingen.",
        "no": "Når du oppgir et telefonnummer på plattformen (f.eks. ved innsending av en tjenesteforespørsel), lagrer vi det midlertidig i nettleserens lokale lagring under nøkkelen nevumo_phone. Dette muliggjør automatisk utfylling ved påfølgende besøk. Rettsgrunnlag: Art. 6(1)(f) GDPR - berettiget interesse i å redusere friksjon og forbedre brukeropplevelsen. Disse dataene forlater aldri enheten din med mindre du eksplisitt sender inn et skjema. Du kan slette dem når som helst ved å tømme nettleserens lokale lagring eller via kontoinnstillingene.",
        "pl": "Gdy podajesz numer telefonu na platformie (np. przy składaniu wniosku o usługę), tymczasowo przechowujemy go w lokalnej pamięci Twojej przeglądarki pod kluczem nevumo_phone. Umożliwia to autouzupełnianie przy kolejnych wizytach. Podstawa prawna: Art. 6(1)(f) RODO - uzasadniony interes w zmniejszeniu tarcia i poprawie doświadczenia użytkownika. Te dane nigdy nie opuszczają Twojego urządzenia, chyba że jawnie wyślesz formularz. Możesz je usunąć w dowolnym momencie, czyszcząc lokalną pamięć przeglądarki lub poprzez ustawienia konta.",
        "pt": "Quando você fornece um número de telefone na plataforma (ex. ao enviar uma solicitação de serviço), o armazenamos temporariamente no armazenamento local do seu navegador sob a chave nevumo_phone. Isso permite o preenchimento automático em visitas subsequentes. Base jurídica: Art. 6(1)(f) RGPD - interesse legítimo em reduzir o atrito e melhorar a experiência do usuário. Esses dados nunca saem do seu dispositivo a menos que você envie explicitamente um formulário. Você pode excluí-los a qualquer momento limpando o armazenamento local do navegador ou nas configurações da conta.",
        "pt-PT": "Quando fornece um número de telefone na plataforma (ex. ao submeter um pedido de serviço), armazenamo-lo temporariamente no armazenamento local do seu navegador sob a chave nevumo_phone. Isso permite o preenchimento automático em visitas subsequentes. Base jurídica: Art. 6(1)(f) RGPD - interesse legítimo na redução do atrito e melhoria da experiência do utilizador. Estes dados nunca saem do seu dispositivo a não ser que submeta um formulário explicitamente. Pode eliminá-los a qualquer momento limpando o armazenamento local do navegador ou através das definições da conta.",
        "ro": "Când furnizați un număr de telefon pe platformă (de ex. la trimiterea unei cereri de serviciu), îl stocăm temporar în memoria locală a browserului dvs. sub cheia nevumo_phone. Aceasta permite completarea automată la vizitele ulterioare. Temei juridic: Art. 6(1)(f) GDPR - interes legitim în reducerea fricțiunii și îmbunătățirea experienței utilizatorului. Aceste date nu părăsesc niciodată dispozitivul dvs. dacă nu trimiteți în mod explicit un formular. Le puteți șterge oricând ștergând memoria locală a browserului sau prin setările contului.",
        "ru": "Когда вы указываете номер телефона на платформе (напр. при отправке заявки на услугу), мы временно сохраняем его в локальном хранилище вашего браузера под ключом nevumo_phone. Это позволяет автоматически заполнять его при последующих посещениях. Правовая основа: Ст. 6(1)(f) GDPR - законный интерес в сокращении неудобств и улучшении пользовательского опыта. Эти данные никогда не покидают ваше устройство, если вы явно не отправите форму. Вы можете удалить их в любое время, очистив локальное хранилище браузера или через настройки аккаунта.",
        "sk": "Keď na platforme zadáte telefónne číslo (napr. pri odosielaní žiadosti o službu), dočasne ho uložíme do lokálneho úložiska vášho prehliadača pod kľúčom nevumo_phone. To umožňuje automatické vyplnenie pri ďalších návštevách. Právny základ: Čl. 6(1)(f) GDPR - oprávnený záujem na znížení záťaže a zlepšení používateľského zážitku. Tieto dáta nikdy neopustia vaše zariadenie, pokiaľ výslovne neodošlete formulár. Kedykoľvek ich môžete odstrániť vymazaním lokálneho úložiska prehliadača alebo v nastaveniach účtu.",
        "sl": "Ko na platformi navedete telefonsko številko (npr. pri oddaji prošnje za storitev), jo začasno shranimo v lokalno shrambo vašega brskalnika pod ključem nevumo_phone. To omogoča samodejno izpolnjevanje pri naslednjih obiskih. Pravna podlaga: čl. 6(1)(f) GDPR - zakoniti interes za zmanjšanje trenja in izboljšanje uporabniške izkušnje. Ti podatki nikoli ne zapustijo vaše naprave, razen če izrecno oddate obrazec. Kadarkoli jih lahko izbrišete s čiščenjem lokalne shrambe brskalnika ali prek nastavitev računa.",
        "sq": "Kur jepni një numër telefoni në platformë (p.sh. kur dërgoni një kërkesë shërbimi), e ruajmë përkohësisht në ruajtjen lokale të shfletuesit tuaj nën çelësin nevumo_phone. Kjo mundëson plotësimin automatik në vizitat pasuese. Baza ligjore: Neni 6(1)(f) GDPR - interes legjitim në uljen e fërkimit dhe përmirësimin e përvojës së përdoruesit. Këto të dhëna nuk e lënë kurrë pajisjen tuaj nëse nuk dorëzoni një formular në mënyrë eksplicite. Mund t'i fshini në çdo kohë duke pastruar ruajtjen lokale të shfletuesit ose përmes cilësimeve të llogarisë.",
        "sr": "Када наведете телефонски број на платформи (нпр. при слању захтева за услугом), привремено га чувамо у локалном складишту вашег прегледача под кључем nevumo_phone. Ово омогућава аутоматско попуњавање при наредним посетама. Правни основ: чл. 6(1)(е) GDPR - легитимни интерес у смањењу трења и побољшању корисничког искуства. Ови подаци никада не напуштају ваш уређај осим ако изричито не поднесете образац. Можете их избрисати у свако доба брисањем локалног складишта прегледача или преко поставки налога.",
        "sv": "När du anger ett telefonnummer på plattformen (t.ex. vid inlämning av en serviceförfrågan) lagrar vi det tillfälligt i webbläsarens lokala lagring under nyckeln nevumo_phone. Detta möjliggör automatisk ifyllning vid efterföljande besök. Rättslig grund: Art. 6(1)(f) GDPR - berättigat intresse av att minska friktion och förbättra användarupplevelsen. Dessa uppgifter lämnar aldrig din enhet om du inte uttryckligen skickar in ett formulär. Du kan radera dem när som helst genom att rensa webbläsarens lokala lagring eller via kontoinställningarna.",
        "tr": "Platformda bir telefon numarası sağladığınızda (örn. bir hizmet talebi gönderirken), bunu nevumo_phone anahtarı altında tarayıcınızın yerel depolama alanında geçici olarak saklarız. Bu, sonraki ziyaretlerde otomatik doldurma yapılmasını sağlar. Hukuki dayanak: GDPR Madde 6(1)(f) - sürtünmeyi azaltma ve kullanıcı deneyimini iyileştirme konusunda meşru menfaat. Bu veriler, açıkça bir form göndermediğiniz sürece cihazınızı asla terk etmez. Tarayıcınızın yerel depolamasını temizleyerek veya hesap ayarları aracılığıyla istediğiniz zaman silebilirsiniz.",
        "uk": "Коли ви вказуєте номер телефону на платформі (наприклад, при надсиланні запиту на послугу), ми тимчасово зберігаємо його у локальному сховищі вашого браузера під ключем nevumo_phone. Це дозволяє автоматично заповнювати його при наступних відвідуваннях. Правова основа: Ст. 6(1)(f) GDPR - законний інтерес у зменшенні незручностей і покращенні користувацького досвіду. Ці дані ніколи не залишають ваш пристрій, якщо ви явно не надішлете форму. Ви можете видалити їх будь-коли, очистивши локальне сховище браузера або через налаштування облікового запису.",
    },
    "cookies.s5_title": {
        "en": "5. Full List of Cookies and Browser Storage Entries",
        "bg": "5. Пълен списък на бисквитките и записите в браузърното хранилище",
        "cs": "5. Úplný seznam souborů cookie a záznamů v úložišti prohlížeče",
        "da": "5. Komplet liste over cookies og browserlagringsposter",
        "de": "5. Vollständige Liste der Cookies und Browser-Speichereinträge",
        "el": "5. Πλήρης λίστα Cookies και καταχωρίσεων αποθήκευσης προγράμματος περιήγησης",
        "es": "5. Lista completa de cookies y entradas de almacenamiento del navegador",
        "et": "5. Küpsiste ja brauseri salvestusruumi kirjete täielik loend",
        "fi": "5. Täydellinen luettelo evästeistä ja selaimen tallennustilan merkinnöistä",
        "fr": "5. Liste complète des cookies et entrées de stockage du navigateur",
        "ga": "5. Liosta Iomlán Fianán agus Iontrálacha Stórála Brabhsálaí",
        "hr": "5. Cjelovit popis kolačića i zapisa pohrane preglednika",
        "hu": "5. Sütik és böngészőtárhely-bejegyzések teljes listája",
        "is": "5. Fullur listi yfir vafrakökur og færslur í vafrageymslu",
        "it": "5. Elenco completo di cookie e voci di archiviazione del browser",
        "lb": "5. Vollstänneg Lëscht vu Cookies a Browser-Späicheraschreiwungen",
        "lt": "5. Pilnas slapukų ir naršyklės saugyklos įrašų sąrašas",
        "lv": "5. Pilns sīkdatņu un pārlūkprogrammas krātuves ierakstu saraksts",
        "mk": "5. Целосен список на колачиња и записи во складирање на прелистувачот",
        "mt": "5. Lista Sħiħa ta' Cookies u Entrati tal-Ħażna tal-Browser",
        "nl": "5. Volledige lijst van cookies en browseropslagvermeldingen",
        "no": "5. Fullstendig liste over informasjonskapsler og nettleserlagringsoppføringer",
        "pl": "5. Pełna lista plików cookie i wpisów w pamięci przeglądarki",
        "pt": "5. Lista completa de cookies e entradas de armazenamento do navegador",
        "pt-PT": "5. Lista completa de cookies e entradas de armazenamento do navegador",
        "ro": "5. Lista completă de cookie-uri și înregistrări de stocare în browser",
        "ru": "5. Полный список файлов cookie и записей в хранилище браузера",
        "sk": "5. Úplný zoznam súborov cookie a záznamov v úložisku prehliadača",
        "sl": "5. Popoln seznam piškotkov in vnosov v shrambi brskalnika",
        "sq": "5. Lista e plotë e cookies-ave dhe hyrjeve të ruajtjes së shfletuesit",
        "sr": "5. Потпуна листа колачића и уноса у складиштење прегледача",
        "sv": "5. Fullständig lista över cookies och webbläsarlagringsuppgifter",
        "tr": "5. Çerezlerin ve Tarayıcı Depolama Girişlerinin Tam Listesi",
        "uk": "5. Повний список файлів cookie та записів у сховищі браузера",
    },
    "cookies.s5_col_name": {
        "en": "Name / Key",
        "bg": "Наименование / Ключ",
        "cs": "Název / Klíč",
        "da": "Navn / Nøgle",
        "de": "Name / Schlüssel",
        "el": "Όνομα / Κλειδί",
        "es": "Nombre / Clave",
        "et": "Nimi / Võti",
        "fi": "Nimi / Avain",
        "fr": "Nom / Clé",
        "ga": "Ainm / Eochair",
        "hr": "Naziv / Ključ",
        "hu": "Név / Kulcs",
        "is": "Nafn / Lykill",
        "it": "Nome / Chiave",
        "lb": "Numm / Schlëssel",
        "lt": "Pavadinimas / Raktas",
        "lv": "Nosaukums / Atslēga",
        "mk": "Назив / Клуч",
        "mt": "Isem / Ċavetta",
        "nl": "Naam / Sleutel",
        "no": "Navn / Nøkkel",
        "pl": "Nazwa / Klucz",
        "pt": "Nome / Chave",
        "pt-PT": "Nome / Chave",
        "ro": "Nume / Cheie",
        "ru": "Имя / Ключ",
        "sk": "Názov / Kľúč",
        "sl": "Ime / Ključ",
        "sq": "Emri / Çelësi",
        "sr": "Назив / Кључ",
        "sv": "Namn / Nyckel",
        "tr": "Ad / Anahtar",
        "uk": "Назва / Ключ",
    },
    "cookies.s5_col_type": {
        "en": "Storage Type",
        "bg": "Тип хранилище",
        "cs": "Typ úložiště",
        "da": "Lagringstype",
        "de": "Speichertyp",
        "el": "Τύπος αποθήκευσης",
        "es": "Tipo de almacenamiento",
        "et": "Salvestusruumi tüüp",
        "fi": "Tallennustyyppi",
        "fr": "Type de stockage",
        "ga": "Cineál Stórála",
        "hr": "Vrsta pohrane",
        "hu": "Tárolási típus",
        "is": "Geymslutegund",
        "it": "Tipo di archiviazione",
        "lb": "Späichertyp",
        "lt": "Saugyklos tipas",
        "lv": "Krātuves veids",
        "mk": "Тип на складирање",
        "mt": "Tip ta' Ħażna",
        "nl": "Opslagtype",
        "no": "Lagringstype",
        "pl": "Typ pamięci",
        "pt": "Tipo de armazenamento",
        "pt-PT": "Tipo de armazenamento",
        "ro": "Tip de stocare",
        "ru": "Тип хранилища",
        "sk": "Typ úložiska",
        "sl": "Vrsta shrambe",
        "sq": "Lloji i ruajtjes",
        "sr": "Врста складишта",
        "sv": "Lagringstyp",
        "tr": "Depolama Türü",
        "uk": "Тип сховища",
    },
    "cookies.s5_col_purpose": {
        "en": "Purpose",
        "bg": "Цел",
        "cs": "Účel",
        "da": "Formål",
        "de": "Zweck",
        "el": "Σκοπός",
        "es": "Finalidad",
        "et": "Eesmärk",
        "fi": "Tarkoitus",
        "fr": "Finalité",
        "ga": "Cuspóir",
        "hr": "Svrha",
        "hu": "Cél",
        "is": "Tilgangur",
        "it": "Scopo",
        "lb": "Zweck",
        "lt": "Tikslas",
        "lv": "Mērķis",
        "mk": "Цел",
        "mt": "Skop",
        "nl": "Doel",
        "no": "Formål",
        "pl": "Cel",
        "pt": "Finalidade",
        "pt-PT": "Finalidade",
        "ro": "Scop",
        "ru": "Цель",
        "sk": "Účel",
        "sl": "Namen",
        "sq": "Qëllimi",
        "sr": "Сврха",
        "sv": "Syfte",
        "tr": "Amaç",
        "uk": "Мета",
    },
}


def seed():
    with engine.begin() as conn:
        for key, translations in TRANSLATIONS.items():
            for lang, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (key, lang, value)
                        VALUES (:key, :lang, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"key": key, "lang": lang, "value": value},
                )
    print(f"Seeded {len(TRANSLATIONS)} keys x 34 languages")


if __name__ == "__main__":
    seed()