"""Seed profile_strength_email translations — Package 3 (no, pl, pt, pt-PT, ro, ru, sk, sl, sq, sr, sv, tr, uk)"""
import os
from sqlalchemy import create_engine, text

engine = create_engine(os.environ["DATABASE_URL"])

NAMESPACE = "profile_strength_email"

TRANSLATIONS = {
    "no": {
        "subject":           "{n} ting hindrer kunder fra å velge deg",
        "preview":           "Profilen din er aktiv — her er nøyaktig hva du trenger å legge til.",
        "hero_for":          "Til:",
        "hero_active":       "Nevumo-profilen din er aktiv. ✓",
        "hero_found":        "Jeg sjekket den og fant {n} ting som kunder ser på før de velger en spesialist — og du mangler dem.",
        "hero_time":         "Det tar 3 minutter å legge dem til.",
        "block1_title":      "Profilbilde",
        "block1_body":       "Profiler uten bilde mottar betydelig færre henvendelser. Kunder vil vite hvem de jobber med.",
        "block1_cta":        "Legg til bilde",
        "block2_title":      "Bilder av arbeidet ditt",
        "block2_body":       "Du har plass til 8 bilder. Kunder bestemmer seg med øynene — ekte arbeid overbeviser mer enn noen beskrivelse.",
        "block2_cta":        "Legg til bilder",
        "block3_title":      "Beskrivelse",
        "block3_body":       "Kunder leser beskrivelsen før de tar kontakt. Selv 2 setninger gjør en forskjell.",
        "block3_ex_cleaning": '„Rengjøringsspesialist med 8 års erfaring. Boliger og kontorer. Jeg bruker miljøvennlige produkter."',
        "block3_ex_plumbing": '„VVS-spesialist med 10 års erfaring. Nødreparasjoner 24/7. Gratis befaring på stedet."',
        "block3_ex_massage": '„Massør med 5 års erfaring. Sports- og avslapningsmassasje. Hjemmebesøk."',
        "block3_cta":        "Forbedre beskrivelsen",
        "block4_title":      "Telefonnummer",
        "block4_body":       "Legg til telefon.",
        "block4_cta":        "Legg til",
        "cta_main":          "Åpne profilen min →",
        "footer_text":       "Du mottar denne e-posten fordi du er en registrert leverandør på Nevumo.",
        "footer_unsub":      "Meld av",
    },
    "pl": {
        "subject":           "{n} rzeczy powstrzymują klientów przed wybraniem ciebie",
        "preview":           "Twój profil jest aktywny — oto dokładnie co musisz dodać.",
        "hero_for":          "Dla:",
        "hero_active":       "Twój profil na Nevumo jest aktywny. ✓",
        "hero_found":        "Sprawdziłem go i znalazłem {n} rzeczy, na które klienci zwracają uwagę przed wyborem specjalisty — i ich nie masz.",
        "hero_time":         "Dodanie ich zajmuje 3 minuty.",
        "block1_title":      "Zdjęcie profilowe",
        "block1_body":       "Profile bez zdjęcia otrzymują znacznie mniej zapytań. Klienci chcą wiedzieć, z kim pracują.",
        "block1_cta":        "Dodaj zdjęcie",
        "block2_title":      "Zdjęcia z twojej pracy",
        "block2_body":       "Masz miejsce na 8 zdjęć. Klienci decydują oczami — prawdziwa praca przekonuje bardziej niż jakikolwiek opis.",
        "block2_cta":        "Dodaj zdjęcia",
        "block3_title":      "Opis",
        "block3_body":       "Klienci czytają opis przed kontaktem. Nawet 2 zdania robią różnicę.",
        "block3_ex_cleaning": '„Specjalista ds. sprzątania z 8-letnim doświadczeniem. Mieszkania i biura. Pracuję z ekologicznymi środkami."',
        "block3_ex_plumbing": '„Hydraulik z 10-letnim doświadczeniem. Awarie 24/7. Bezpłatna wycena na miejscu."',
        "block3_ex_massage": '„Masażysta z 5-letnim doświadczeniem. Masaż sportowy i relaksacyjny. Wizyty domowe."',
        "block3_cta":        "Popraw opis",
        "block4_title":      "Numer telefonu",
        "block4_body":       "Dodaj telefon.",
        "block4_cta":        "Dodaj",
        "cta_main":          "Otwórz swój profil →",
        "footer_text":       "Otrzymujesz ten e-mail, ponieważ jesteś zarejestrowanym dostawcą na Nevumo.",
        "footer_unsub":      "Wypisz się",
    },
    "pt": {
        "subject":           "{n} coisas estão impedindo clientes de escolhê-lo",
        "preview":           "Seu perfil está ativo — aqui está exatamente o que você precisa adicionar.",
        "hero_for":          "Para:",
        "hero_active":       "Seu perfil no Nevumo está ativo. ✓",
        "hero_found":        "Eu o verifiquei e encontrei {n} coisas que os clientes observam antes de escolher um especialista — e você não as tem.",
        "hero_time":         "Leva 3 minutos para adicioná-las.",
        "block1_title":      "Foto de perfil",
        "block1_body":       "Perfis sem foto recebem significativamente menos consultas. Os clientes querem saber com quem estão trabalhando.",
        "block1_cta":        "Adicionar foto",
        "block2_title":      "Fotos do seu trabalho",
        "block2_body":       "Você tem espaço para 8 fotos. Os clientes decidem com os olhos — o trabalho real convence mais do que qualquer descrição.",
        "block2_cta":        "Adicionar fotos",
        "block3_title":      "Descrição",
        "block3_body":       "Os clientes leem a descrição antes de entrar em contato. Mesmo 2 frases fazem a diferença.",
        "block3_ex_cleaning": '„Especialista em limpeza com 8 anos de experiência. Residencial e escritórios. Trabalho com produtos ecológicos."',
        "block3_ex_plumbing": '„Encanador com 10 anos de experiência. Emergências 24/7. Avaliação gratuita no local."',
        "block3_ex_massage": '„Massoterapeuta com 5 anos de experiência. Massagem esportiva e relaxante. Atendimento domiciliar."',
        "block3_cta":        "Melhorar descrição",
        "block4_title":      "Número de telefone",
        "block4_body":       "Adicione telefone.",
        "block4_cta":        "Adicionar",
        "cta_main":          "Abrir meu perfil →",
        "footer_text":       "Você está recebendo este e-mail porque é um fornecedor registrado no Nevumo.",
        "footer_unsub":      "Cancelar inscrição",
    },
    "pt-PT": {
        "subject":           "{n} coisas estão a impedir clientes de o escolherem",
        "preview":           "O seu perfil está ativo — eis exatamente o que precisa de adicionar.",
        "hero_for":          "Para:",
        "hero_active":       "O seu perfil no Nevumo está ativo. ✓",
        "hero_found":        "Verifiquei-o e encontrei {n} coisas que os clientes observam antes de escolher um especialista — e o senhor não as tem.",
        "hero_time":         "Demora 3 minutos a adicioná-las.",
        "block1_title":      "Fotografia de perfil",
        "block1_body":       "Os perfis sem fotografia recebem significativamente menos pedidos. Os clientes querem saber com quem estão a trabalhar.",
        "block1_cta":        "Adicionar fotografia",
        "block2_title":      "Fotografias do seu trabalho",
        "block2_body":       "Tem espaço para 8 fotografias. Os clientes decidem com os olhos — o trabalho real convence mais do que qualquer descrição.",
        "block2_cta":        "Adicionar fotografias",
        "block3_title":      "Descrição",
        "block3_body":       "Os clientes leem a descrição antes de entrar em contacto. Mesmo 2 frases fazem a diferença.",
        "block3_ex_cleaning": '„Especialista em limpeza com 8 anos de experiência. Residencial e escritórios. Trabalho com produtos ecológicos."',
        "block3_ex_plumbing": '„Canalizador com 10 anos de experiência. Emergências 24/7. Avaliação gratuita no local."',
        "block3_ex_massage": '„Massagista com 5 anos de experiência. Massagem desportiva e relaxante. Visitas ao domicílio."',
        "block3_cta":        "Melhorar descrição",
        "block4_title":      "Número de telefone",
        "block4_body":       "Adicione telefone.",
        "block4_cta":        "Adicionar",
        "cta_main":          "Abrir o meu perfil →",
        "footer_text":       "Está a receber este e-mail porque é um fornecedor registado no Nevumo.",
        "footer_unsub":      "Cancelar subscrição",
    },
    "ro": {
        "subject":           "{n} lucruri îi împiedică pe clienți să te aleagă",
        "preview":           "Profilul tău este activ — iată exact ce trebuie să adaugi.",
        "hero_for":          "Pentru:",
        "hero_active":       "Profilul tău pe Nevumo este activ. ✓",
        "hero_found":        "L-am verificat și am găsit {n} lucruri pe care clienții le privesc înainte de a alege un specialist — și tu nu le ai.",
        "hero_time":         "Durează 3 minute să le adaugi.",
        "block1_title":      "Fotografie de profil",
        "block1_body":       "Profilurile fără fotografie primesc semnificativ mai puține solicitări. Clienții vor să știe cu cine lucrează.",
        "block1_cta":        "Adaugă fotografie",
        "block2_title":      "Fotografii din munca ta",
        "block2_body":       "Ai loc pentru 8 fotografii. Clienții decid cu ochii — munca reală convinge mai mult decât orice descriere.",
        "block2_cta":        "Adaugă fotografii",
        "block3_title":      "Descriere",
        "block3_body":       "Clienții citesc descrierea înainte de a lua legătura. Chiar și 2 propoziții fac diferența.",
        "block3_ex_cleaning": '„Specialist în curățenie cu 8 ani experiență. Locuințe și birouri. Lucrez cu produse ecologice."',
        "block3_ex_plumbing": '„Instalator cu 10 ani experiență. Urgențe 24/7. Evaluare gratuită la fața locului."',
        "block3_ex_massage": '„Maseur cu 5 ani experiență. Masaj sportiv și de relaxare. Vizite la domiciliu."',
        "block3_cta":        "Îmbunătățește descrierea",
        "block4_title":      "Număr de telefon",
        "block4_body":       "Adaugă telefon.",
        "block4_cta":        "Adaugă",
        "cta_main":          "Deschide profilul meu →",
        "footer_text":       "Primești acest e-mail deoarece ești un furnizor înregistrat pe Nevumo.",
        "footer_unsub":      "Dezabonare",
    },
    "ru": {
        "subject":           "{n} вещи мешают клиентам выбрать вас",
        "preview":           "Ваш профиль активен — вот именно то, что нужно добавить.",
        "hero_for":          "Для:",
        "hero_active":       "Ваш профиль на Nevumo активен. ✓",
        "hero_found":        "Я проверил его и нашёл {n} вещи, на которые клиенты смотрят перед выбором специалиста — и их у вас нет.",
        "hero_time":         "Их добавление займёт 3 минуты.",
        "block1_title":      "Фото профиля",
        "block1_body":       "Профили без фото получают значительно меньше запросов. Клиенты хотят знать, с кем они работают.",
        "block1_cta":        "Добавить фото",
        "block2_title":      "Фотографии вашей работы",
        "block2_body":       "У вас есть место для 8 фотографий. Клиенты решают глазами — реальная работа убеждает больше, чем любое описание.",
        "block2_cta":        "Добавить фотографии",
        "block3_title":      "Описание",
        "block3_body":       "Клиенты читают описание перед тем, как связаться. Даже 2 предложения делают разницу.",
        "block3_ex_cleaning": '„Специалист по уборке с 8-летним опытом. Жилые помещения и офисы. Работаю с экологичными средствами."',
        "block3_ex_plumbing": '„Сантехник с 10-летним опытом. Аварии 24/7. Бесплатная оценка на месте."',
        "block3_ex_massage": '„Массажист с 5-летним опытом. Спортивный и расслабляющий массаж. Выезд на дом."',
        "block3_cta":        "Улучшить описание",
        "block4_title":      "Номер телефона",
        "block4_body":       "Добавьте телефон.",
        "block4_cta":        "Добавить",
        "cta_main":          "Открыть мой профиль →",
        "footer_text":       "Вы получаете это письмо, потому что являетесь зарегистрированным поставщиком услуг на Nevumo.",
        "footer_unsub":      "Отписаться",
    },
    "sk": {
        "subject":           "{n} vecí bráni klientom vybrať si vás",
        "preview":           "Váš profil je aktívny — tu je presne to, čo musíte pridať.",
        "hero_for":          "Pre:",
        "hero_active":       "Váš profil na Nevumo je aktívny. ✓",
        "hero_found":        "Skontroloval som ho a našiel {n} vecí, na ktoré sa klienti pozrú pred výberom špecialistu — a vy ich nemáte.",
        "hero_time":         "Ich pridanie trvá 3 minúty.",
        "block1_title":      "Profilová fotografia",
        "block1_body":       "Profily bez fotografie dostávajú výrazne menej dopytov. Klienti chcú vedieť, s kým pracujú.",
        "block1_cta":        "Pridať fotografiu",
        "block2_title":      "Fotografie vašej práce",
        "block2_body":       "Máte miesto pre 8 fotografií. Klienti rozhodujú pohľadom — skutočná práca presvedčí viac ako akýkoľvek popis.",
        "block2_cta":        "Pridať fotografie",
        "block3_title":      "Popis",
        "block3_body":       "Klienti čítajú popis pred kontaktovaním. Dokonca aj 2 vety robia rozdiel.",
        "block3_ex_cleaning": '„Špecialista na upratovanie s 8-ročnou praxou. Byty a kancelárie. Pracujem s ekologickými prostriedkami."',
        "block3_ex_plumbing": '„Inštalatér s 10-ročnou praxou. Havárie 24/7. Bezplatná obhliadka na mieste."',
        "block3_ex_massage": '„Masér s 5-ročnou praxou. Športová a relaxačná masáž. Domáce návštevy."',
        "block3_cta":        "Vylepšiť popis",
        "block4_title":      "Telefónne číslo",
        "block4_body":       "Pridajte telefón.",
        "block4_cta":        "Pridať",
        "cta_main":          "Otvoriť môj profil →",
        "footer_text":       "Tento e-mail dostávate, pretože ste registrovaný poskytovateľ na Nevumo.",
        "footer_unsub":      "Odhlásiť sa",
    },
    "sl": {
        "subject":           "{n} stvari preprečuje strankam, da vas izberejo",
        "preview":           "Vaš profil je aktiven — tukaj je natanko to, kar morate dodati.",
        "hero_for":          "Za:",
        "hero_active":       "Vaš profil na Nevumo je aktiven. ✓",
        "hero_found":        "Preveril sem ga in našel {n} stvari, ki si jih stranke ogledajo pred izbiro strokovnjaka — in teh nimate.",
        "hero_time":         "Dodajanje jih traja 3 minute.",
        "block1_title":      "Profilna fotografija",
        "block1_body":       "Profili brez fotografije prejmejo bistveno manj povpraševanj. Stranke želijo vedeti, s kom delajo.",
        "block1_cta":        "Dodaj fotografijo",
        "block2_title":      "Fotografije vašega dela",
        "block2_body":       "Imate prostor za 8 fotografij. Stranke se odločajo z očmi — pravo delo prepriča bolj kot kakršen koli opis.",
        "block2_cta":        "Dodaj fotografije",
        "block3_title":      "Opis",
        "block3_body":       "Stranke preberejo opis, preden stopijo v stik. Celo 2 stavka naredita razliko.",
        "block3_ex_cleaning": '„Specialist za čiščenje z 8-letnimi izkušnjami. Stanovanja in pisarne. Delam z ekološkimi sredstvi."',
        "block3_ex_plumbing": '„Vodovodar z 10-letnimi izkušnjami. Nujni primeri 24/7. Brezplačna ocena na kraju samem."',
        "block3_ex_massage": '„Masažist z 5-letnimi izkušnjami. Športna in sproščujoča masaža. Domači obiski."',
        "block3_cta":        "Izboljšaj opis",
        "block4_title":      "Telefonska številka",
        "block4_body":       "Dodajte telefon.",
        "block4_cta":        "Dodaj",
        "cta_main":          "Odpri moj profil →",
        "footer_text":       "Ta e-pošto prejemate, ker ste registriran ponudnik na Nevumo.",
        "footer_unsub":      "Odjava",
    },
    "sq": {
        "subject":           "{n} gjëra po pengojnë klientët të të zgjedhin",
        "preview":           "Profili yt është aktiv — ja saktësisht çfarë duhet të shtosh.",
        "hero_for":          "Për:",
        "hero_active":       "Profili yt në Nevumo është aktiv. ✓",
        "hero_found":        "E kontrollova dhe gjeta {n} gjëra që klientët shikojnë para zgjedhjes së një specialisti — dhe ti nuk i ke.",
        "hero_time":         "Duhen 3 minuta t'i shtosh.",
        "block1_title":      "Foto e profilit",
        "block1_body":       "Profilet pa foto marrin ndjeshëm më pak kërkesa. Klientët duan të dinin me kë po punojnë.",
        "block1_cta":        "Shto foto",
        "block2_title":      "Foto nga puna jote",
        "block2_body":       "Ke vend për 8 foto. Klientët vendosin me sytë — puna e vërtetë bind më shumë se çdo përshkrim.",
        "block2_cta":        "Shto foto",
        "block3_title":      "Përshkrim",
        "block3_body":       "Klientët lexojnë përshkrimin para se të kontaktojnë. Edhe 2 fjali bëjnë ndryshim.",
        "block3_ex_cleaning": '„Specialist pastrimi me 8 vjet përvojë. Banesa dhe zyra. Punoj me produkte ekologjike."',
        "block3_ex_plumbing": '„Hidraulik me 10 vjet përvojë. Urgjenca 24/7. Vlerësim falas në vendngjarje."',
        "block3_ex_massage": '„Masazhist me 5 vjet përvojë. Masazh sportiv dhe relaksues. Vizita në shtëpi."',
        "block3_cta":        "Përmirëso përshkrimin",
        "block4_title":      "Numër telefoni",
        "block4_body":       "Shto telefon.",
        "block4_cta":        "Shto",
        "cta_main":          "Hap profilin tim →",
        "footer_text":       "Po e merr këtë email sepse je ofrues i regjistruar në Nevumo.",
        "footer_unsub":      "Çabonohu",
    },
    "sr": {
        "subject":           "{n} ствари спречавају клијенте да те изаберу",
        "preview":           "Профил ти је активан — ево тачно шта треба да додаш.",
        "hero_for":          "За:",
        "hero_active":       "Профил ти на Nevumo је активан. ✓",
        "hero_found":        "Проверио сам га и нашао {n} ствари које клијенти гледају пре него што изаберу специјалисту — а ти их немаш.",
        "hero_time":         "Потребне су 3 минута да их додаш.",
        "block1_title":      "Профилна слика",
        "block1_body":       "Профили без слике добијају знатно мање упита. Клијенти желе да знају с ким раде.",
        "block1_cta":        "Додај слику",
        "block2_title":      "Слике твог рада",
        "block2_body":       "Имаш места за 8 слика. Клијенти одлучују очима — прави рад убеђује више од сваког описа.",
        "block2_cta":        "Додај слике",
        "block3_title":      "Опис",
        "block3_body":       "Клијенти читају опис пре него што се јаве. Чак и 2 реченице праве разлику.",
        "block3_ex_cleaning": '„Специјалиста за чишћење са 8г. искуства. Стамбени и пословни простори. Радим са еко средствима."',
        "block3_ex_plumbing": '„ВиК специјалиста са 10г. искуства. Хаварије 24/7. Бесплатна процена на лицу места."',
        "block3_ex_massage": '„Масажиста са 5г. искуства. Спортска и опуштајућа масажа. Кућне посете."',
        "block3_cta":        "Побољшај опис",
        "block4_title":      "Број телефона",
        "block4_body":       "Додај телефон.",
        "block4_cta":        "Додај",
        "cta_main":          "Отвори профил →",
        "footer_text":       "Добијаш овај имејл јер си регистровани пружалац услуга на Nevumo.",
        "footer_unsub":      "Одјави се",
    },
    "sv": {
        "subject":           "{n} saker hindrar kunder från att välja dig",
        "preview":           "Din profil är aktiv — här är exakt vad du behöver lägga till.",
        "hero_for":          "Till:",
        "hero_active":       "Din Nevumo-profil är aktiv. ✓",
        "hero_found":        "Jag kontrollerade den och hittade {n} saker som kunder tittar på innan de väljer en specialist — och du saknar dem.",
        "hero_time":         "Det tar 3 minuter att lägga till dem.",
        "block1_title":      "Profilbild",
        "block1_body":       "Profiler utan bild får avsevärt färre förfrågningar. Kunder vill veta vem de arbetar med.",
        "block1_cta":        "Lägg till bild",
        "block2_title":      "Bilder av ditt arbete",
        "block2_body":       "Du har plats för 8 bilder. Kunder bestämmer sig med ögonen — riktigt arbete övertalar mer än någon beskrivning.",
        "block2_cta":        "Lägg till bilder",
        "block3_title":      "Beskrivning",
        "block3_body":       "Kunder läser beskrivningen innan de kontaktar dig. Även 2 meningar gör skillnad.",
        "block3_ex_cleaning": '„Städspecialist med 8 års erfarenhet. Bostäder och kontor. Jag arbetar med miljövänliga produkter."',
        "block3_ex_plumbing": '„VVS-specialist med 10 års erfarenhet. Akutreparationer 24/7. Kostnadsfri besiktning på plats."',
        "block3_ex_massage": '„Massör med 5 års erfarenhet. Sport- och avslappningsmassage. Hembesök."',
        "block3_cta":        "Förbättra beskrivningen",
        "block4_title":      "Telefonnummer",
        "block4_body":       "Lägg till telefon.",
        "block4_cta":        "Lägg till",
        "cta_main":          "Öppna min profil →",
        "footer_text":       "Du får detta e-postmeddelande eftersom du är en registrerad leverantör på Nevumo.",
        "footer_unsub":      "Avprenumerera",
    },
    "tr": {
        "subject":           "Müşterilerin sizi seçmesini engelleyen {n} şey var",
        "preview":           "Profiliniz aktif — işte tam olarak eklemeniz gerekenler.",
        "hero_for":          "Kime:",
        "hero_active":       "Nevumo profiliniz aktif. ✓",
        "hero_found":        "Kontrol ettim ve müşterilerin bir uzman seçmeden önce baktığı {n} şey buldum — ve bunlar sizde yok.",
        "hero_time":         "Bunları eklemek 3 dakika alır.",
        "block1_title":      "Profil fotoğrafı",
        "block1_body":       "Fotoğrafsız profiller önemli ölçüde daha az talep alır. Müşteriler kiminle çalıştıklarını bilmek ister.",
        "block1_cta":        "Fotoğraf ekle",
        "block2_title":      "Çalışmalarınızın fotoğrafları",
        "block2_body":       "8 fotoğraf için yeriniz var. Müşteriler gözleriyle karar verir — gerçek iş her türlü açıklamadan daha ikna edicidir.",
        "block2_cta":        "Fotoğraf ekle",
        "block3_title":      "Açıklama",
        "block3_body":       "Müşteriler iletişime geçmeden önce açıklamayı okur. 2 cümle bile fark yaratır.",
        "block3_ex_cleaning": '„8 yıllık deneyime sahip temizlik uzmanı. Konutlar ve ofisler. Ekolojik ürünlerle çalışıyorum."',
        "block3_ex_plumbing": '„10 yıllık deneyime sahip tesisatçı. Acil durumlar 24/7. Yerinde ücretsiz keşif."',
        "block3_ex_massage": '„5 yıllık deneyime sahip masör. Spor ve rahatlatıcı masaj. Ev ziyaretleri."',
        "block3_cta":        "Açıklamayı geliştir",
        "block4_title":      "Telefon numarası",
        "block4_body":       "Telefon ekleyin.",
        "block4_cta":        "Ekle",
        "cta_main":          "Profilimi aç →",
        "footer_text":       "Nevumo'da kayıtlı bir sağlayıcı olduğunuz için bu e-postayı alıyorsunuz.",
        "footer_unsub":      "Aboneliği iptal et",
    },
    "uk": {
        "subject":           "{n} речей заважають клієнтам вибрати вас",
        "preview":           "Ваш профіль активний — ось саме те, що потрібно додати.",
        "hero_for":          "Для:",
        "hero_active":       "Ваш профіль на Nevumo активний. ✓",
        "hero_found":        "Я перевірив його і знайшов {n} речей, на які клієнти дивляться перед вибором спеціаліста — і їх у вас немає.",
        "hero_time":         "Їх додавання займе 3 хвилини.",
        "block1_title":      "Фото профілю",
        "block1_body":       "Профілі без фото отримують значно менше запитів. Клієнти хочуть знати, з ким вони працюють.",
        "block1_cta":        "Додати фото",
        "block2_title":      "Фотографії вашої роботи",
        "block2_body":       "У вас є місце для 8 фотографій. Клієнти вирішують очима — реальна робота переконує більше, ніж будь-який опис.",
        "block2_cta":        "Додати фотографії",
        "block3_title":      "Опис",
        "block3_body":       "Клієнти читають опис перед тим, як зв'язатися. Навіть 2 речення роблять різницю.",
        "block3_ex_cleaning": '„Спеціаліст з прибирання з 8-річним досвідом. Житлові приміщення та офіси. Працюю з екологічними засобами."',
        "block3_ex_plumbing": '„Сантехнік з 10-річним досвідом. Аварії 24/7. Безкоштовна оцінка на місці."',
        "block3_ex_massage": '„Масажист з 5-річним досвідом. Спортивний та розслаблюючий масаж. Виїзд додому."',
        "block3_cta":        "Покращити опис",
        "block4_title":      "Номер телефону",
        "block4_body":       "Додайте телефон.",
        "block4_cta":        "Додати",
        "cta_main":          "Відкрити мій профіль →",
        "footer_text":       "Ви отримуєте цей лист, тому що є зареєстрованим постачальником послуг на Nevumo.",
        "footer_unsub":      "Відписатися",
    },
}

def main() -> None:
    rows = [
        {"lang": lang, "key": f"{NAMESPACE}.{key}", "value": value}
        for lang, keys in TRANSLATIONS.items()
        for key, value in keys.items()
    ]
    with engine.begin() as conn:
        for row in rows:
            conn.execute(
                text("""
                    INSERT INTO translations (lang, key, value)
                    VALUES (:lang, :key, :value)
                    ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                """),
                row,
            )
    print(f"✅ Seeded {len(rows)} rows ({len(TRANSLATIONS)} languages)")

if __name__ == "__main__":
    main()
