"""
seed_terms_p4_bodies.py  —  Nevumo | namespace: terms
Key: art4_body (34 езика)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_terms_p4_bodies
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "art4_body": {
        "en": (
            '4.1 In compliance with the EU Platform-to-Business Regulation (2019/1150) and '
            'the Omnibus Directive (2019/2161), Nevumo discloses the main parameters that '
            'determine the ranking and ordering of service providers displayed to clients:\n\n'
            '• Location relevance — providers operating in the city or area matching your '
            'request are ranked higher.\n'
            '• Category match — providers whose listed services match the requested category '
            'are prioritised.\n'
            '• Profile completeness — providers with complete profiles (photo, description, '
            'verified contact details) rank higher.\n'
            '• Review score — average rating from verified client reviews.\n'
            '• Response rate — providers who respond promptly to leads are ranked higher.\n'
            '• Activity — recently active providers are ranked higher than inactive ones.\n\n'
            '4.2 At the current stage of the platform, paid placement does not affect ranking. '
            'If this changes, it will be disclosed clearly.\n\n'
            '4.3 Providers who are identified as traders (professional businesses) are labelled '
            'accordingly on their profile page. Providers who have not confirmed their trader '
            'status are displayed as private individuals. You should verify a provider\'s '
            'professional status before contracting for regulated services.'
        ),
        "pl": (
            '6.1 Zgodnie z wymogami rozporządzenia P2B (2019/1150) oraz Dyrektywy Omnibus '
            '(2019/2161), Nevumo ujawnia główne parametry wpływające na kolejność wyświetlania '
            'Usługodawców:\n\n'
            '• Lokalizacja — Usługodawcy działający w mieście lub obszarze odpowiadającym '
            'zapytaniu Klienta są wyświetlani wyżej.\n'
            '• Dopasowanie kategorii — Usługodawcy oferujący usługi odpowiadające wyszukiwanej '
            'kategorii są priorytetyzowani.\n'
            '• Kompletność profilu — profile zawierające zdjęcie, opis i zweryfikowane dane '
            'kontaktowe są wyżej rankingowane.\n'
            '• Ocena — średnia ocena z potwierdzonych opinii Klientów.\n'
            '• Czas odpowiedzi — Usługodawcy reagujący szybko na zapytania są wyżej '
            'rankingowani.\n'
            '• Aktywność — aktywni Usługodawcy są rankingowani wyżej niż nieaktywni.\n\n'
            '6.2 Na obecnym etapie działania platformy opłaty nie wpływają na pozycję w '
            'rankingu. W przypadku zmiany tej zasady zostanie ona wyraźnie ujawniona.\n\n'
            '6.3 Usługodawcy posiadający status przedsiębiorcy (trader) są oznaczeni na swoich '
            'profilach. Usługodawcy, którzy nie potwierdzili statusu przedsiębiorcy, '
            'prezentowani są jako osoby prywatne. Przed zawarciem umowy dotyczącej usług '
            'wymagających uprawnień zawodowych, Klient powinien samodzielnie zweryfikować '
            'status i uprawnienia Usługodawcy.'
        ),
        "bg": (
            '4.1 В съответствие с Регламент P2B (2019/1150) и Директивата „Омнибус" '
            '(2019/2161), Nevumo оповестява основните параметри, определящи реда на показване '
            'на Доставчиците:\n\n'
            '• Местоположение — Доставчици, работещи в търсения град или район, са показани '
            'по-напред.\n'
            '• Съответствие на категорията — Доставчици, предлагащи услуги в търсената '
            'категория, са приоритизирани.\n'
            '• Пълнота на профила — профили с профилна снимка, описание и верифицирани '
            'контактни данни са по-високо класирани.\n'
            '• Оценка — средна оценка от верифицирани отзиви на Клиенти.\n'
            '• Скорост на отговор — Доставчици, реагиращи бързо на запитвания, са по-високо '
            'класирани.\n'
            '• Активност — активните Доставчици са класирани по-високо от неактивните.\n\n'
            '4.2 На текущия етап заплащането не влияе на класирането. При промяна на тази '
            'политика тя ще бъде изрично оповестена.\n\n'
            '4.3 Доставчиците, идентифицирани като търговци, са обозначени в профила им. '
            'Доставчици, непотвърдили търговски статус, са показани като физически лица. '
            'Клиентът трябва сам да провери статуса на Доставчика преди сключване на договор '
            'за регулирани услуги.'
        ),
        "cs": (
            '4.1 V souladu s nařízením EU P2B (2019/1150) a směrnicí Omnibus (2019/2161) '
            'Nevumo zveřejňuje hlavní parametry určující pořadí a řazení poskytovatelů '
            'zobrazených klientům:\n\n'
            '• Místní relevance — poskytovatelé působící v městě nebo oblasti odpovídající '
            'vašemu požadavku jsou řazeni výše.\n'
            '• Shoda kategorie — poskytovatelé, jejichž služby odpovídají požadované kategorii, '
            'jsou upřednostňováni.\n'
            '• Úplnost profilu — poskytovatelé s úplným profilem (foto, popis, ověřené '
            'kontaktní údaje) jsou řazeni výše.\n'
            '• Hodnocení — průměrné hodnocení z ověřených recenzí klientů.\n'
            '• Rychlost odpovědi — poskytovatelé, kteří rychle reagují, jsou řazeni výše.\n'
            '• Aktivita — nedávno aktivní poskytovatelé jsou řazeni výše než neaktivní.\n\n'
            '4.2 V současné fázi platformy placené umístění neovlivňuje pořadí. Pokud se to '
            'změní, bude to jasně zveřejněno.\n\n'
            '4.3 Poskytovatelé identifikovaní jako obchodníci jsou na svém profilu příslušně '
            'označeni. Poskytovatelé, kteří svůj status obchodníka nepotvrdili, jsou zobrazeni '
            'jako soukromé osoby. Před uzavřením smlouvy o regulovaných službách byste si měli '
            'ověřit profesní status poskytovatele.'
        ),
        "da": (
            '4.1 I overensstemmelse med EU\'s P2B-forordning (2019/1150) og Omnibus-direktivet '
            '(2019/2161) offentliggør Nevumo de vigtigste parametre, der bestemmer rangordningen '
            'af serviceudbydere vist til klienter:\n\n'
            '• Lokalrelevans — udbydere, der opererer i den by eller det område, der matcher '
            'din anmodning, rangeres højere.\n'
            '• Kategorimatch — udbydere, hvis tjenester matcher den ønskede kategori, '
            'prioriteres.\n'
            '• Profilfuldstændighed — udbydere med komplette profiler (foto, beskrivelse, '
            'verificerede kontaktoplysninger) rangeres højere.\n'
            '• Anmeldelsesscore — gennemsnitlig vurdering fra verificerede klientanmeldelser.\n'
            '• Svarprocent — udbydere, der reagerer hurtigt på leads, rangeres højere.\n'
            '• Aktivitet — nyligt aktive udbydere rangeres højere end inaktive.\n\n'
            '4.2 På den nuværende platform påvirker betalt placering ikke rangordningen. Hvis '
            'dette ændres, vil det blive tydeligt offentliggjort.\n\n'
            '4.3 Udbydere identificeret som erhvervsdrivende er mærket på deres profilside. '
            'Udbydere, der ikke har bekræftet deres handelsstatus, vises som privatpersoner. '
            'Du bør verificere en udbyders professionelle status inden kontraktindgåelse for '
            'regulerede tjenester.'
        ),
        "de": (
            '4.1 In Übereinstimmung mit der EU-P2B-Verordnung (2019/1150) und der Omnibus-'
            'Richtlinie (2019/2161) legt Nevumo die wichtigsten Parameter offen, die das '
            'Ranking der Dienstleister bestimmen:\n\n'
            '• Standortrelevanz — Anbieter, die in der Stadt oder Region tätig sind, die Ihrer '
            'Anfrage entspricht, werden höher eingestuft.\n'
            '• Kategorieübereinstimmung — Anbieter, deren Dienstleistungen zur angefragten '
            'Kategorie passen, werden priorisiert.\n'
            '• Profilvollständigkeit — Anbieter mit vollständigen Profilen (Foto, Beschreibung, '
            'verifizierte Kontaktdaten) werden höher eingestuft.\n'
            '• Bewertungspunkte — Durchschnittsbewertung aus verifizierten Kundenbewertungen.\n'
            '• Antwortrate — Anbieter, die schnell auf Anfragen reagieren, werden höher '
            'eingestuft.\n'
            '• Aktivität — kürzlich aktive Anbieter werden höher eingestuft als inaktive.\n\n'
            '4.2 In der aktuellen Phase der Plattform beeinflusst bezahlte Platzierung das '
            'Ranking nicht. Sollte sich dies ändern, wird es klar kommuniziert.\n\n'
            '4.3 Anbieter, die als Händler (gewerbliche Unternehmen) identifiziert werden, '
            'sind auf ihrer Profilseite entsprechend gekennzeichnet. Anbieter, die ihren '
            'Händlerstatus nicht bestätigt haben, werden als Privatpersonen angezeigt. Sie '
            'sollten den professionellen Status eines Anbieters vor Vertragsschluss für '
            'regulierte Dienstleistungen überprüfen.'
        ),
        "el": (
            '4.1 Σύμφωνα με τον Κανονισμό P2B της ΕΕ (2019/1150) και την Οδηγία Omnibus '
            '(2019/2161), το Nevumo γνωστοποιεί τις κύριες παραμέτρους που καθορίζουν την '
            'κατάταξη των παρόχων υπηρεσιών:\n\n'
            '• Τοπική συνάφεια — πάροχοι που δραστηριοποιούνται στην πόλη ή περιοχή που '
            'αντιστοιχεί στο αίτημά σας κατατάσσονται υψηλότερα.\n'
            '• Αντιστοίχιση κατηγορίας — πάροχοι των οποίων οι υπηρεσίες ταιριάζουν με την '
            'αιτούμενη κατηγορία προτεραιοποιούνται.\n'
            '• Πληρότητα προφίλ — πάροχοι με πλήρες προφίλ (φωτογραφία, περιγραφή, '
            'επαληθευμένα στοιχεία επικοινωνίας) κατατάσσονται υψηλότερα.\n'
            '• Βαθμολογία κριτικών — μέση αξιολόγηση από επαληθευμένες κριτικές πελατών.\n'
            '• Ποσοστό απόκρισης — πάροχοι που ανταποκρίνονται άμεσα κατατάσσονται '
            'υψηλότερα.\n'
            '• Δραστηριότητα — πρόσφατα ενεργοί πάροχοι κατατάσσονται υψηλότερα.\n\n'
            '4.2 Στο τρέχον στάδιο της πλατφόρμας, η πληρωμένη τοποθέτηση δεν επηρεάζει '
            'την κατάταξη. Εάν αυτό αλλάξει, θα ανακοινωθεί ρητά.\n\n'
            '4.3 Πάροχοι που ταυτοποιούνται ως έμποροι επισημαίνονται στη σελίδα προφίλ τους. '
            'Πάροχοι που δεν έχουν επιβεβαιώσει την εμπορική τους ιδιότητα εμφανίζονται ως '
            'ιδιώτες. Θα πρέπει να επαληθεύσετε την επαγγελματική ιδιότητα ενός παρόχου '
            'πριν από τη σύναψη σύμβασης για ρυθμιζόμενες υπηρεσίες.'
        ),
        "es": (
            '4.1 En cumplimiento del Reglamento P2B de la UE (2019/1150) y la Directiva '
            'Omnibus (2019/2161), Nevumo divulga los principales parámetros que determinan '
            'la clasificación de los proveedores de servicios:\n\n'
            '• Relevancia de ubicación — los proveedores que operan en la ciudad o área que '
            'coincide con su solicitud se clasifican más alto.\n'
            '• Coincidencia de categoría — se priorizan los proveedores cuyas servicios '
            'coinciden con la categoría solicitada.\n'
            '• Completitud del perfil — los proveedores con perfiles completos (foto, '
            'descripción, datos de contacto verificados) se clasifican más alto.\n'
            '• Puntuación de reseñas — valoración media de reseñas verificadas de clientes.\n'
            '• Tasa de respuesta — los proveedores que responden rápidamente se clasifican '
            'más alto.\n'
            '• Actividad — los proveedores activos recientemente se clasifican más alto.\n\n'
            '4.2 En la fase actual de la plataforma, la colocación de pago no afecta al '
            'ranking. Si esto cambia, se comunicará claramente.\n\n'
            '4.3 Los proveedores identificados como comerciantes están etiquetados en su '
            'perfil. Los proveedores que no han confirmado su condición de comerciante se '
            'muestran como particulares. Debe verificar el estatus profesional de un proveedor '
            'antes de contratar servicios regulados.'
        ),
        "et": (
            '4.1 Kooskõlas EL-i P2B-määrusega (2019/1150) ja Omnibus-direktiiviga (2019/2161) '
            'avalikustab Nevumo peamised parameetrid, mis määravad teenusepakkujate järjestuse:\n\n'
            '• Asukohaasjakohasus — kõrgemale järjestatakse pakkujad, kes tegutsevad teie '
            'päringule vastavas linnas või piirkonnas.\n'
            '• Kategooria vastavus — eelistatakse pakkujaid, kelle teenused vastavad '
            'soovitud kategooriale.\n'
            '• Profiili täielikkus — kõrgemale järjestatakse pakkujad täieliku profiiliga '
            '(foto, kirjeldus, kontrollitud kontaktandmed).\n'
            '• Hinnang — kinnitatud kliendiarvustuste keskmine hinnang.\n'
            '• Vastuse kiirus — kõrgemale järjestatakse pakkujad, kes vastavad kiiresti.\n'
            '• Aktiivsus — hiljuti aktiivsed pakkujad järjestatakse kõrgemale kui mitteaktiivsed.\n\n'
            '4.2 Platvormi praeguses etapis ei mõjuta tasuline paigutus järjestust. Kui see '
            'muutub, teatatakse sellest selgelt.\n\n'
            '4.3 Kauplejatena tuvastatud pakkujad on oma profiililehel vastavalt märgistatud. '
            'Pakkujad, kes pole oma kaupleja staatust kinnitanud, kuvatakse eraisikutena. '
            'Enne reguleeritud teenuste lepingu sõlmimist peaksite kontrollima pakkuja '
            'professionaalset staatust.'
        ),
        "fi": (
            '4.1 EU:n P2B-asetuksen (2019/1150) ja Omnibus-direktiivin (2019/2161) mukaisesti '
            'Nevumo julkaisee tärkeimmät parametrit, jotka määräävät palveluntarjoajien '
            'järjestyksen:\n\n'
            '• Sijaintiasiaankuuluvuus — pyyntöäsi vastaavassa kaupungissa tai alueella '
            'toimivat tarjoajat sijoittuvat korkeammalle.\n'
            '• Kategoriayhteensopivuus — palvelut, jotka vastaavat pyydettyjä kategorioita, '
            'priorisoidaan.\n'
            '• Profiilin täydellisyys — täydellisellä profiililla (kuva, kuvaus, varmennetut '
            'yhteystiedot) olevat tarjoajat sijoittuvat korkeammalle.\n'
            '• Arvostelupistemäärä — varmennettujen asiakasarvostelujen keskiarvo.\n'
            '• Vastausnopeus — nopeasti vastaavat tarjoajat sijoittuvat korkeammalle.\n'
            '• Aktiivisuus — äskettäin aktiiviset tarjoajat sijoittuvat passiivisia korkeammalle.\n\n'
            '4.2 Alustan nykyisessä vaiheessa maksettu sijoittelu ei vaikuta järjestykseen. '
            'Jos tämä muuttuu, siitä ilmoitetaan selkeästi.\n\n'
            '4.3 Elinkeinonharjoittajiksi tunnistetut tarjoajat on merkitty profiilisivullaan. '
            'Tarjoajat, jotka eivät ole vahvistaneet kauppiasstatustaan, näkyvät yksityishenkilöinä. '
            'Sinun tulee tarkistaa tarjoajan ammatillinen status ennen säänneltyjen palvelujen '
            'sopimusta.'
        ),
        "fr": (
            '4.1 Conformément au Règlement P2B de l\'UE (2019/1150) et à la Directive Omnibus '
            '(2019/2161), Nevumo divulgue les principaux paramètres déterminant le classement '
            'des prestataires de services affichés aux clients :\n\n'
            '• Pertinence géographique — les prestataires opérant dans la ville ou la zone '
            'correspondant à votre demande sont mieux classés.\n'
            '• Correspondance de catégorie — les prestataires dont les services correspondent '
            'à la catégorie demandée sont prioritaires.\n'
            '• Complétude du profil — les prestataires avec des profils complets (photo, '
            'description, coordonnées vérifiées) sont mieux classés.\n'
            '• Score d\'avis — note moyenne des avis clients vérifiés.\n'
            '• Taux de réponse — les prestataires qui répondent rapidement sont mieux classés.\n'
            '• Activité — les prestataires récemment actifs sont mieux classés que les inactifs.\n\n'
            '4.2 Au stade actuel de la plateforme, le placement payant n\'affecte pas le '
            'classement. Si cela change, cela sera clairement divulgué.\n\n'
            '4.3 Les prestataires identifiés comme commerçants sont étiquetés sur leur page de '
            'profil. Les prestataires n\'ayant pas confirmé leur statut de commerçant sont '
            'affichés comme particuliers. Vous devez vérifier le statut professionnel d\'un '
            'prestataire avant de contracter pour des services réglementés.'
        ),
        "ga": (
            '4.1 De réir Rialachán P2B an AE (2019/1150) agus Treoir Omnibus (2019/2161), '
            'nochtann Nevumo na príomhpharaiméadair a chinneann rangú soláthróirí seirbhíse:\n\n'
            '• Ábharthacht suímh — soláthróirí a oibríonn sa chathair nó sa cheantar a '
            'fhreagraíonn do d\'iarratas rangaítear níos airde.\n'
            '• Meaitseáil catagóire — soláthróirí a bhfuil a gcuid seirbhísí ag teacht leis '
            'an gcatagóir iarrtha tugtar tosaíocht dóibh.\n'
            '• Iomláine próifíle — soláthróirí le próifílí iomlána (grianghraf, cur síos, '
            'sonraí teagmhála fíoraithe) rangaítear níos airde.\n'
            '• Scór léirmheasanna — meánmharcáil ó léirmheasanna fíoraithe cliant.\n'
            '• Ráta freagra — soláthróirí a fhreagraíonn go pras rangaítear níos airde.\n'
            '• Gníomhaíocht — soláthróirí gníomhacha le déanaí rangaítear níos airde.\n\n'
            '4.2 Ag céim reatha na hardáin, ní théann íocaíocht i bhfeidhm ar rangú. Má '
            'athraíonn sé seo, nochtfar é go soiléir.\n\n'
            '4.3 Tá soláthróirí a aithnítear mar thrádálaithe lipéadaithe ar a leathanach '
            'próifíle. Taispeántar soláthróirí nár dheimhnigh a stádas trádálaí mar '
            'dhaoine príobháideacha. Ba cheart duit stádas gairmiúil soláthróra a fhíorú '
            'roimh chonradh a dhéanamh do sheirbhísí rialaithe.'
        ),
        "hr": (
            '4.1 U skladu s EU Uredbom P2B (2019/1150) i Omnibus Direktivom (2019/2161), '
            'Nevumo objavljuje glavne parametre koji određuju rang davatelja usluga:\n\n'
            '• Relevantnost lokacije — davatelji koji djeluju u gradu ili području koje odgovara '
            'vašem zahtjevu rangirani su više.\n'
            '• Podudaranje kategorije — davatelji čije usluge odgovaraju traženoj kategoriji '
            'imaju prioritet.\n'
            '• Potpunost profila — davatelji s potpunim profilima (fotografija, opis, '
            'verificirani kontaktni podaci) rangirani su više.\n'
            '• Ocjena recenzija — prosječna ocjena iz verificiranih recenzija klijenata.\n'
            '• Stopa odgovora — davatelji koji brzo reagiraju rangirani su više.\n'
            '• Aktivnost — nedavno aktivni davatelji rangirani su više od neaktivnih.\n\n'
            '4.2 U trenutnoj fazi platforme, plaćeno postavljanje ne utječe na rang. Ako se to '
            'promijeni, bit će jasno objavljeno.\n\n'
            '4.3 Davatelji identificirani kao trgovci označeni su na svojoj profilnoj stranici. '
            'Davatelji koji nisu potvrdili status trgovca prikazuju se kao privatne osobe. '
            'Trebali biste provjeriti profesionalni status davatelja prije sklapanja ugovora '
            'za regulirane usluge.'
        ),
        "hu": (
            '4.1 Az EU P2B-rendeletnek (2019/1150) és az Omnibus-irányelvnek (2019/2161) '
            'megfelelően a Nevumo közzéteszi azokat a főbb paramétereket, amelyek meghatározzák '
            'a szolgáltatók rangsorát:\n\n'
            '• Helyi relevancia — a kérésének megfelelő városban vagy területen működő '
            'szolgáltatók magasabb helyen szerepelnek.\n'
            '• Kategória-egyezés — azok a szolgáltatók, akiknek listázott szolgáltatásai '
            'megfelelnek a kért kategóriának, előnyt élveznek.\n'
            '• Profil teljessége — a teljes profillal rendelkező szolgáltatók (fotó, leírás, '
            'ellenőrzött elérhetőségek) magasabb helyen szerepelnek.\n'
            '• Értékelési pontszám — az ellenőrzött ügyfélértékelések átlagos osztályzata.\n'
            '• Válaszarány — a gyorsan reagáló szolgáltatók magasabb helyen szerepelnek.\n'
            '• Aktivitás — a nemrég aktív szolgáltatók magasabb helyen szerepelnek az '
            'inaktívaknál.\n\n'
            '4.2 A platform jelenlegi szakaszában a fizetett elhelyezés nem befolyásolja a '
            'rangsort. Ha ez megváltozik, egyértelműen közlik.\n\n'
            '4.3 A kereskedőként azonosított szolgáltatók profiloldalukon ennek megfelelően '
            'vannak jelölve. Azok a szolgáltatók, akik nem erősítették meg kereskedői '
            'státuszukat, magánszemélyként jelennek meg. Szabályozott szolgáltatásokra '
            'vonatkozó szerződéskötés előtt ellenőrizze a szolgáltató szakmai státuszát.'
        ),
        "is": (
            '4.1 Í samræmi við P2B-reglugerð ESB (2019/1150) og Omnibus-tilskipun (2019/2161) '
            'birtir Nevumo helstu breyturnar sem ákvarða röðun þjónustuaðila:\n\n'
            '• Staðsetningarleg þýðing — þjónustuaðilar sem starfa í borg eða svæði sem '
            'samsvarar beiðni þinni eru raðaðir hærra.\n'
            '• Flokkasamsvörun — þjónustuaðilar sem bjóða þjónustu sem passar við umbeðinn '
            'flokk fá forgang.\n'
            '• Heilleiki prófíls — þjónustuaðilar með fullkominn prófíl (ljósmynd, lýsing, '
            'staðfest tengiliðaupplýsingar) eru raðaðir hærra.\n'
            '• Umsagnarskor — meðaleinkun frá staðfestum umsögnum viðskiptavina.\n'
            '• Svarhlutfall — þjónustuaðilar sem svara fljótt eru raðaðir hærra.\n'
            '• Virkni — nýlega virkir þjónustuaðilar eru raðaðir hærra en óvirkir.\n\n'
            '4.2 Á núverandi stigi vettvangsins hefur greitt staðsetning ekki áhrif á röðun. '
            'Ef þetta breytist verður það birt skýrt.\n\n'
            '4.3 Þjónustuaðilar sem þekkjast sem kaupmenn eru merktar á prófílsíðu sinni. '
            'Þjónustuaðilar sem hafa ekki staðfest kaupmennsku sína birtast sem einstaklingar. '
            'Þú ættir að staðfesta faglega stöðu þjónustuaðila áður en samningur er gerður '
            'um eftirlitsskyldar þjónustur.'
        ),
        "it": (
            '4.1 In conformità al Regolamento P2B dell\'UE (2019/1150) e alla Direttiva '
            'Omnibus (2019/2161), Nevumo divulga i principali parametri che determinano il '
            'posizionamento dei prestatori di servizi:\n\n'
            '• Rilevanza geografica — i prestatori che operano nella città o area corrispondente '
            'alla richiesta sono posizionati più in alto.\n'
            '• Corrispondenza di categoria — i prestatori i cui servizi corrispondono alla '
            'categoria richiesta sono prioritari.\n'
            '• Completezza del profilo — i prestatori con profili completi (foto, descrizione, '
            'dati di contatto verificati) sono posizionati più in alto.\n'
            '• Punteggio recensioni — valutazione media delle recensioni clienti verificate.\n'
            '• Tasso di risposta — i prestatori che rispondono prontamente sono posizionati '
            'più in alto.\n'
            '• Attività — i prestatori recentemente attivi sono posizionati più in alto.\n\n'
            '4.2 Nella fase attuale della piattaforma, il posizionamento a pagamento non '
            'influisce sulla classifica. Se questo cambia, sarà chiaramente comunicato.\n\n'
            '4.3 I prestatori identificati come commercianti sono etichettati sulla loro pagina '
            'di profilo. I prestatori che non hanno confermato il loro status di commerciante '
            'sono visualizzati come privati. Si consiglia di verificare lo status professionale '
            'di un prestatore prima di stipulare contratti per servizi regolamentati.'
        ),
        "lb": (
            '4.1 Entspriechend der EU P2B-Verordnung (2019/1150) an der Omnibus-Direktiv '
            '(2019/2161) publizéiert Nevumo d\'Haaptparameteren, déi d\'Ranking vun '
            'Serviceprestatairen bestëmmen:\n\n'
            '• Lokalrelevanz — Prestatairë, déi an der Stad oder Regioun funktionéieren, déi '
            'Ärer Ufro entsprécht, ginn héijer klasséiert.\n'
            '• Kategorieübereinstimmung — Prestatairë, deenen hir Servicer der gefuerderter '
            'Kategorie entspréchen, ginn prioritiséiert.\n'
            '• Vollständigkeit des Profils — Prestatairë mat vollständigen Profiler (Foto, '
            'Beschreiwung, verifizéiert Kontaktdaten) ginn héijer klasséiert.\n'
            '• Bewäertungspunkte — Duerchschnëttsbewäertung aus verifizéierten Clientsbewäertungen.\n'
            '• Äntwertquote — Prestatairë déi schnell äntwerten ginn héijer klasséiert.\n'
            '• Aktivitéit — kuerzem aktiv Prestatairë ginn héijer wéi inaktiv klasséiert.\n\n'
            '4.2 An der aktueller Phase vun der Plattform beaflosst bezuelte Plazéierung d\'Ranking '
            'net. Wann dat ännert, gëtt et kloer kommunizéiert.\n\n'
            '4.3 Prestatairë déi als Händler identifizéiert goufen, si op hirer Profilsäit '
            'entspriechend markéiert. Prestatairë déi hire Händlerstatus net bestätegt hunn, '
            'ginn als Privatpersounen affichéiert. Dir sollt de professionelle Status vum '
            'Prestataire iwwerpréiwen ier Dir e Kontrakt fir reguléiert Servicer ofschléisst.'
        ),
        "lt": (
            '4.1 Laikydamasis ES P2B reglamento (2019/1150) ir Omnibus direktyvos (2019/2161), '
            'Nevumo atskleidžia pagrindinius parametrus, lemiančius paslaugų teikėjų reitingą:\n\n'
            '• Vietos aktualumas — aukščiau reitinguojami teikėjai, veikiantys jūsų prašymą '
            'atitinkančiame mieste ar regione.\n'
            '• Kategorijos atitikimas — teikėjai, kurių paslaugos atitinka prašomą kategoriją, '
            'teikiami pirmenybė.\n'
            '• Profilio išsamumas — teikėjai su išsamiais profiliais (nuotrauka, aprašymas, '
            'patvirtinti kontaktai) reitinguojami aukščiau.\n'
            '• Atsiliepimų balas — vidutinis įvertinimas iš patikrintų klientų atsiliepimų.\n'
            '• Atsakymo greitis — teikėjai, greitai atsakantys į užklausas, reitinguojami '
            'aukščiau.\n'
            '• Aktyvumas — neseniai aktyvūs teikėjai reitinguojami aukščiau nei neaktyvūs.\n\n'
            '4.2 Dabartiniame platformos etape mokamas patalpinimas neturi įtakos reitingui. '
            'Jei tai pasikeis, bus aiškiai pranešta.\n\n'
            '4.3 Teikėjai, identifikuoti kaip verslininkai, pažymimi savo profilio puslapyje. '
            'Teikėjai, nepatvirtinę prekybininko statuso, rodomi kaip privatūs asmenys. Prieš '
            'sudarant sutartį dėl reguliuojamų paslaugų, turėtumėte patikrinti teikėjo '
            'profesinį statusą.'
        ),
        "lv": (
            '4.1 Saskaņā ar ES P2B regulu (2019/1150) un Omnibus direktīvu (2019/2161) Nevumo '
            'atklāj galvenos parametrus, kas nosaka pakalpojumu sniedzēju ranžējumu:\n\n'
            '• Atrašanās vietas aktualitāte — augstāk tiek ranžēti sniedzēji, kas darbojas '
            'jūsu pieprasījumam atbilstošajā pilsētā vai reģionā.\n'
            '• Kategorijas atbilstība — tiek prioritizēti sniedzēji, kuru pakalpojumi atbilst '
            'pieprasītajai kategorijai.\n'
            '• Profila pilnīgums — augstāk tiek ranžēti sniedzēji ar pilnīgu profilu (foto, '
            'apraksts, verificēti kontaktdati).\n'
            '• Atsauksmju vērtējums — verificēto klientu atsauksmju vidējais vērtējums.\n'
            '• Atbildes ātrums — sniedzēji, kas ātri atbild, tiek ranžēti augstāk.\n'
            '• Aktivitāte — nesen aktīvie sniedzēji tiek ranžēti augstāk nekā neaktīvie.\n\n'
            '4.2 Platformas pašreizējā posmā apmaksāta izvietošana neietekmē ranžējumu. '
            'Ja tas mainīsies, tas tiks skaidri paziņots.\n\n'
            '4.3 Sniedzēji, kas identificēti kā tirgotāji, ir attiecīgi apzīmēti savā profila '
            'lapā. Sniedzēji, kas nav apstiprinājuši savu tirgotāja statusu, tiek rādīti kā '
            'privātpersonas. Pirms līguma noslēgšanas par regulētiem pakalpojumiem jums '
            'jāpārbauda sniedzēja profesionālais statuss.'
        ),
        "mk": (
            '4.1 Во согласност со Регулативата P2B на ЕУ (2019/1150) и Директивата Omnibus '
            '(2019/2161), Nevumo ги откriva главните параметри кои го одредуваат рангирањето '
            'на давателите на услуги:\n\n'
            '• Локациска релевантност — повисоко се рангираат даватели кои работат во градот '
            'или областа што одговара на вашето барање.\n'
            '• Совпаѓање на категорија — даватели чии услуги одговараат на бараната категорија '
            'добиваат приоритет.\n'
            '• Комплетност на профилот — даватели со комплетни профили (фото, опис, '
            'верифицирани контакти) се рангираат повисоко.\n'
            '• Оценка на рецензии — просечна оценка од верифицирани рецензии на клиенти.\n'
            '• Стапка на одговор — даватели кои брзо одговараат се рангираат повисоко.\n'
            '• Активност — неодамна активните даватели се рангираат повисоко.\n\n'
            '4.2 На тековниот етап на платформата, платеното поставување не влијае на '
            'рангирањето. Ако тоа се промени, јавно ќе биде оповестено.\n\n'
            '4.3 Давателите идентификувани како трговци се означени на нивната профилна '
            'страница. Давателите кои не го потврдиле трговскиот статус се прикажуваат '
            'како физички лица. Треба да го верифицирате професионалниот статус на давателот '
            'пред да склучите договор за регулирани услуги.'
        ),
        "mt": (
            '4.1 Konformi mar-Regolament P2B tal-UE (2019/1150) u d-Direttiva Omnibus '
            '(2019/2161), Nevumo jiżvela l-parametri ewlenin li jiddeterminaw il-klassifikazzjoni '
            'tal-fornituri:\n\n'
            '• Rilevanza tal-post — fornituri li joperaw fil-belt jew żona li taqbel mat-talba '
            'tiegħek jiġu klassifikati ogħla.\n'
            '• Tqabbil tal-kategorija — fornituri li s-servizzi tagħhom jaqblu mal-kategorija '
            'mitluba jingħataw prijorità.\n'
            '• Kompletezza tal-profil — fornituri b\'profili sħaħ (ritratt, deskrizzjoni, '
            'dettalji ta\' kuntatt ivverifikati) jiġu klassifikati ogħla.\n'
            '• Skor tal-reviżjonijiet — valutazzjoni medja minn reviżjonijiet ivverifikati.\n'
            '• Rata ta\' risposta — fornituri li jirrispondu malajr jiġu klassifikati ogħla.\n'
            '• Attività — fornituri attivi reċentement jiġu klassifikati ogħla mill-inattivi.\n\n'
            '4.2 Fl-istadju attwali tal-pjattaforma, il-pożizzjonament imħallas ma jaffettwax '
            'il-klassifikazzjoni. Jekk dan jinbidel, jiġi żvelat b\'mod ċar.\n\n'
            '4.3 Fornituri identifikati bħala negozjanti huma ttikettjati fuq il-paġna tal-profil '
            'tagħhom. Fornituri li ma kkonfermax l-istatus ta\' negozjant tagħhom jidhru bħala '
            'individwi privati. Għandek tivverifika l-istatus professjonali ta\' fornitur qabel '
            'ma tikkonkludi kuntratt għal servizzi regolati.'
        ),
        "nl": (
            '4.1 In overeenstemming met de EU P2B-verordening (2019/1150) en de Omnibus-richtlijn '
            '(2019/2161) maakt Nevumo de belangrijkste parameters bekend die de rangschikking '
            'van serviceproviders bepalen:\n\n'
            '• Locatierelevantie — providers die actief zijn in de stad of regio die overeenkomt '
            'met uw verzoek worden hoger gerangschikt.\n'
            '• Categorieovereenkomst — providers wier diensten overeenkomen met de gevraagde '
            'categorie krijgen prioriteit.\n'
            '• Profielvolledigheid — providers met volledige profielen (foto, beschrijving, '
            'geverifieerde contactgegevens) worden hoger gerangschikt.\n'
            '• Beoordelingsscore — gemiddelde beoordeling uit geverifieerde klantrecensies.\n'
            '• Responspercentage — providers die snel reageren worden hoger gerangschikt.\n'
            '• Activiteit — recent actieve providers worden hoger gerangschikt dan inactieve.\n\n'
            '4.2 In de huidige fase van het platform heeft betaalde plaatsing geen invloed op '
            'de rangschikking. Als dit verandert, wordt dit duidelijk bekendgemaakt.\n\n'
            '4.3 Providers die als handelaren zijn geïdentificeerd, zijn op hun profielpagina '
            'dienovereenkomstig gelabeld. Providers die hun handelsstatus niet hebben bevestigd, '
            'worden weergegeven als particulieren. U dient de professionele status van een '
            'provider te verifiëren voordat u een contract sluit voor gereguleerde diensten.'
        ),
        "no": (
            '4.1 I samsvar med EUs P2B-forordning (2019/1150) og Omnibus-direktivet (2019/2161) '
            'avslører Nevumo de viktigste parameterne som bestemmer rangeringen av '
            'tjenesteleverandører:\n\n'
            '• Stedlig relevans — leverandører som opererer i byen eller området som samsvarer '
            'med forespørselen din, rangeres høyere.\n'
            '• Kategorisamsvar — leverandører hvis tjenester samsvarer med den ønskede '
            'kategorien prioriteres.\n'
            '• Profilkomplethet — leverandører med fullstendige profiler (foto, beskrivelse, '
            'verifiserte kontaktopplysninger) rangeres høyere.\n'
            '• Anmeldelsespoeng — gjennomsnittlig vurdering fra verifiserte kundeanmeldelser.\n'
            '• Svarprosent — leverandører som svarer raskt rangeres høyere.\n'
            '• Aktivitet — nylig aktive leverandører rangeres høyere enn inaktive.\n\n'
            '4.2 På det nåværende stadiet av plattformen påvirker betalt plassering ikke '
            'rangeringen. Hvis dette endres, vil det bli tydelig kommunisert.\n\n'
            '4.3 Leverandører identifisert som næringsdrivende er merket på profilsiden sin. '
            'Leverandører som ikke har bekreftet sin næringsstatus vises som privatpersoner. '
            'Du bør verifisere en leverandørs profesjonelle status før du inngår kontrakt '
            'for regulerte tjenester.'
        ),
        "pt": (
            '4.1 Em conformidade com o Regulamento P2B da UE (2019/1150) e a Diretiva Omnibus '
            '(2019/2161), o Nevumo divulga os principais parâmetros que determinam a '
            'classificação dos prestadores de serviços:\n\n'
            '• Relevância de localização — prestadores que operam na cidade ou área '
            'correspondente ao seu pedido são classificados mais alto.\n'
            '• Correspondência de categoria — prestadores cujos serviços correspondem à '
            'categoria solicitada são priorizados.\n'
            '• Completude do perfil — prestadores com perfis completos (foto, descrição, '
            'dados de contacto verificados) são classificados mais alto.\n'
            '• Pontuação de avaliações — avaliação média de avaliações de clientes verificadas.\n'
            '• Taxa de resposta — prestadores que respondem rapidamente são classificados '
            'mais alto.\n'
            '• Atividade — prestadores recentemente ativos são classificados mais alto.\n\n'
            '4.2 Na fase atual da plataforma, o posicionamento pago não afeta a classificação. '
            'Se isso mudar, será claramente divulgado.\n\n'
            '4.3 Prestadores identificados como comerciantes são rotulados na sua página de '
            'perfil. Prestadores que não confirmaram o status de comerciante são exibidos como '
            'particulares. Você deve verificar o status profissional de um prestador antes de '
            'contratar serviços regulamentados.'
        ),
        "pt-PT": (
            '4.1 Em conformidade com o Regulamento P2B da UE (2019/1150) e a Directiva '
            'Omnibus (2019/2161), o Nevumo divulga os principais parâmetros que determinam a '
            'classificação dos prestadores de serviços:\n\n'
            '• Relevância de localização — prestadores que operam na cidade ou área '
            'correspondente ao seu pedido são classificados mais alto.\n'
            '• Correspondência de categoria — prestadores cujos serviços correspondem à '
            'categoria solicitada são priorizados.\n'
            '• Completude do perfil — prestadores com perfis completos (foto, descrição, '
            'dados de contacto verificados) são classificados mais alto.\n'
            '• Pontuação de avaliações — avaliação média de avaliações de clientes verificadas.\n'
            '• Taxa de resposta — prestadores que respondem rapidamente são classificados '
            'mais alto.\n'
            '• Actividade — prestadores recentemente activos são classificados mais alto.\n\n'
            '4.2 Na fase actual da plataforma, o posicionamento pago não afecta a '
            'classificação. Se isso mudar, será claramente divulgado.\n\n'
            '4.3 Prestadores identificados como comerciantes são rotulados na sua página de '
            'perfil. Prestadores que não confirmaram o estatuto de comerciante são apresentados '
            'como particulares. Deve verificar o estatuto profissional de um prestador antes '
            'de contratar serviços regulamentados.'
        ),
        "ro": (
            '4.1 În conformitate cu Regulamentul P2B al UE (2019/1150) și Directiva Omnibus '
            '(2019/2161), Nevumo dezvăluie principalii parametri care determină clasificarea '
            'prestatorilor de servicii:\n\n'
            '• Relevanța locației — prestatorii care operează în orașul sau zona care '
            'corespunde cererii dvs. sunt clasificați mai sus.\n'
            '• Potrivirea categoriei — prestatorii ale căror servicii corespund categoriei '
            'solicitate sunt prioritizați.\n'
            '• Completitudinea profilului — prestatorii cu profiluri complete (foto, descriere, '
            'date de contact verificate) sunt clasificați mai sus.\n'
            '• Scorul recenziilor — evaluarea medie din recenziile verificate ale clienților.\n'
            '• Rata de răspuns — prestatorii care răspund prompt sunt clasificați mai sus.\n'
            '• Activitatea — prestatorii recent activi sunt clasificați mai sus decât inactivi.\n\n'
            '4.2 În faza actuală a platformei, plasamentul plătit nu afectează clasificarea. '
            'Dacă acest lucru se schimbă, va fi comunicat clar.\n\n'
            '4.3 Prestatorii identificați ca și comercianți sunt etichetați pe pagina lor de '
            'profil. Prestatorii care nu și-au confirmat statutul de comerciant sunt afișați '
            'ca persoane fizice. Ar trebui să verificați statutul profesional al unui prestator '
            'înainte de a contracta servicii reglementate.'
        ),
        "ru": (
            '4.1 В соответствии с Регламентом ЕС P2B (2019/1150) и Директивой Omnibus '
            '(2019/2161) Nevumo раскрывает основные параметры, определяющие ранжирование '
            'исполнителей:\n\n'
            '• Геолокация — исполнители, работающие в городе или районе, соответствующем '
            'вашему запросу, получают более высокий ранг.\n'
            '• Соответствие категории — исполнители, чьи услуги соответствуют запрошенной '
            'категории, имеют приоритет.\n'
            '• Полнота профиля — исполнители с полными профилями (фото, описание, '
            'верифицированные контакты) ранжируются выше.\n'
            '• Оценка отзывов — средняя оценка по верифицированным отзывам клиентов.\n'
            '• Скорость ответа — исполнители, быстро реагирующие на запросы, ранжируются '
            'выше.\n'
            '• Активность — недавно активные исполнители ранжируются выше неактивных.\n\n'
            '4.2 На текущем этапе работы платформы платное размещение не влияет на ранжирование. '
            'В случае изменения это будет чётко объявлено.\n\n'
            '4.3 Исполнители, идентифицированные как предприниматели, имеют соответствующую '
            'отметку на странице профиля. Исполнители, не подтвердившие статус предпринимателя, '
            'отображаются как физические лица. Перед заключением договора на регулируемые '
            'услуги рекомендуем проверить профессиональный статус исполнителя.'
        ),
        "sk": (
            '4.1 V súlade s nariadením EÚ P2B (2019/1150) a smernicou Omnibus (2019/2161) '
            'Nevumo zverejňuje hlavné parametre určujúce poradie poskytovateľov služieb:\n\n'
            '• Miestna relevancia — poskytovatelia pôsobiaci v meste alebo oblasti zodpovedajúcej '
            'vašej požiadavke sú zoradení vyššie.\n'
            '• Zhoda kategórie — poskytovatelia, ktorých služby zodpovedajú požadovanej '
            'kategórii, sú uprednostnení.\n'
            '• Úplnosť profilu — poskytovatelia s úplným profilom (foto, popis, overené '
            'kontaktné údaje) sú zoradení vyššie.\n'
            '• Skóre hodnotení — priemerné hodnotenie z overených recenzií klientov.\n'
            '• Miera odozvy — poskytovatelia, ktorí rýchlo reagujú, sú zoradení vyššie.\n'
            '• Aktivita — nedávno aktívni poskytovatelia sú zoradení vyššie ako neaktívni.\n\n'
            '4.2 V súčasnej fáze platformy platené umiestnenie neovplyvňuje poradie. Ak sa '
            'to zmení, bude to jasne oznámené.\n\n'
            '4.3 Poskytovatelia identifikovaní ako obchodníci sú označení na svojej profilovej '
            'stránke. Poskytovatelia, ktorí nepotvrdili obchodný status, sú zobrazení ako '
            'súkromné osoby. Pred uzatvorením zmluvy o regulovaných službách by ste mali '
            'overiť profesionálny status poskytovateľa.'
        ),
        "sl": (
            '4.1 V skladu z uredbo EU P2B (2019/1150) in direktivo Omnibus (2019/2161) Nevumo '
            'razkrije glavne parametre, ki določajo razvrstitev ponudnikov storitev:\n\n'
            '• Krajevna ustreznost — ponudniki, ki delujejo v mestu ali območju, ki ustreza '
            'vaši zahtevi, so razvrščeni višje.\n'
            '• Ujemanje kategorije — ponudniki, katerih storitve ustrezajo zahtevani kategoriji, '
            'dobijo prednost.\n'
            '• Popolnost profila — ponudniki s popolnimi profili (fotografija, opis, preverjeni '
            'kontaktni podatki) so razvrščeni višje.\n'
            '• Ocena mnenj — povprečna ocena iz preverjenih mnenj strank.\n'
            '• Stopnja odzivnosti — ponudniki, ki se hitro odzivajo, so razvrščeni višje.\n'
            '• Dejavnost — nedavno aktivni ponudniki so razvrščeni višje kot neaktivni.\n\n'
            '4.2 V trenutni fazi platforme plačano uvrščanje ne vpliva na razvrstitev. Če se '
            'to spremeni, bo jasno objavljeno.\n\n'
            '4.3 Ponudniki, identificirani kot trgovci, so označeni na svoji profilni strani. '
            'Ponudniki, ki niso potrdili statusa trgovca, so prikazani kot zasebniki. Preden '
            'sklenete pogodbo za regulirane storitve, preverite poklicni status ponudnika.'
        ),
        "sq": (
            '4.1 Në përputhje me Rregulloren P2B të BE-së (2019/1150) dhe Direktivën Omnibus '
            '(2019/2161), Nevumo zbulon parametrat kryesorë që përcaktojnë renditjen e '
            'ofruesve të shërbimeve:\n\n'
            '• Rëndësia e vendndodhjes — ofruesit që operojnë në qytetin ose zonën që '
            'përputhet me kërkesën tuaj renditen më lart.\n'
            '• Përputhja e kategorisë — ofruesit shërbimet e të cilëve përputhen me kategorinë '
            'e kërkuar i jepet prioritet.\n'
            '• Plotësia e profilit — ofruesit me profile të plota (foto, përshkrim, kontakte '
            'të verifikuara) renditen më lart.\n'
            '• Nota e vlerësimeve — vlerësimi mesatar nga vlerësimet e verifikuara të klientëve.\n'
            '• Shkalla e përgjigjes — ofruesit që i përgjigjen shpejt renditen më lart.\n'
            '• Aktiviteti — ofruesit të fundit aktivë renditen më lart se ata joaktivë.\n\n'
            '4.2 Në fazën aktuale të platformës, vendosja e paguar nuk ndikon në renditje. '
            'Nëse kjo ndryshon, do të zbulohet qartë.\n\n'
            '4.3 Ofruesit e identifikuar si tregtarë janë etiketuar në faqen e profilit të tyre. '
            'Ofruesit që nuk e kanë konfirmuar statusin e tregtarit shfaqen si individë privatë. '
            'Duhet të verifikoni statusin profesional të një ofruesi para se të lidhni kontratë '
            'për shërbime të rregulluara.'
        ),
        "sr": (
            '4.1 U skladu sa Uredbom EU P2B (2019/1150) i Omnibus Direktivom (2019/2161), '
            'Nevumo otkriva glavne parametre koji određuju rangiranje pružalaca usluga:\n\n'
            '• Relevantnost lokacije — pružaoci koji deluju u gradu ili oblasti koja odgovara '
            'vašem zahtevu rangirani su više.\n'
            '• Podudaranje kategorije — pružaoci čije usluge odgovaraju traženoj kategoriji '
            'imaju prioritet.\n'
            '• Potpunost profila — pružaoci sa potpunim profilima (fotografija, opis, '
            'verifikovani kontakt podaci) rangirani su više.\n'
            '• Ocena recenzija — prosečna ocena iz verifikovanih recenzija klijenata.\n'
            '• Stopa odgovora — pružaoci koji brzo reaguju rangirani su više.\n'
            '• Aktivnost — nedavno aktivni pružaoci rangirani su više od neaktivnih.\n\n'
            '4.2 U trenutnoj fazi platforme, plaćeno postavljanje ne utiče na rang. Ako se '
            'to promeni, biće jasno objavljeno.\n\n'
            '4.3 Pružaoci identifikovani kao trgovci su označeni na svojoj profilnoj stranici. '
            'Pružaoci koji nisu potvrdili status trgovca prikazuju se kao privatna lica. '
            'Trebalo bi da proverite profesionalni status pružaoca pre zaključivanja ugovora '
            'za regulisane usluge.'
        ),
        "sv": (
            '4.1 I enlighet med EU:s P2B-förordning (2019/1150) och Omnibus-direktivet '
            '(2019/2161) offentliggör Nevumo de viktigaste parametrarna som bestämmer '
            'rangordningen av tjänsteleverantörer:\n\n'
            '• Platsrelevans — leverantörer som verkar i staden eller området som matchar din '
            'förfrågan rangordnas högre.\n'
            '• Kategorimatchning — leverantörer vars tjänster matchar den begärda kategorin '
            'prioriteras.\n'
            '• Profilkomplethet — leverantörer med fullständiga profiler (foto, beskrivning, '
            'verifierade kontaktuppgifter) rangordnas högre.\n'
            '• Recensionspoäng — genomsnittligt betyg från verifierade kundrecensioner.\n'
            '• Svarsprocent — leverantörer som svarar snabbt rangordnas högre.\n'
            '• Aktivitet — nyligen aktiva leverantörer rangordnas högre än inaktiva.\n\n'
            '4.2 I plattformens nuvarande fas påverkar betald placering inte rangordningen. '
            'Om detta ändras kommer det att tydligt kommuniceras.\n\n'
            '4.3 Leverantörer som identifieras som handlare är märkta på sin profilsida. '
            'Leverantörer som inte har bekräftat sin handelsstatus visas som privatpersoner. '
            'Du bör verifiera en leverantörs yrkesmässiga status innan du ingår avtal om '
            'reglerade tjänster.'
        ),
        "tr": (
            '4.1 AB P2B Yönetmeliği (2019/1150) ve Omnibus Direktifi (2019/2161) uyarınca '
            'Nevumo, hizmet sağlayıcıların sıralamasını belirleyen temel parametreleri '
            'açıklar:\n\n'
            '• Konum alaka düzeyi — talebinizle eşleşen şehir veya bölgede faaliyet gösteren '
            'sağlayıcılar daha yüksek sıralanır.\n'
            '• Kategori eşleşmesi — hizmetleri talep edilen kategoriye uyan sağlayıcılara '
            'öncelik verilir.\n'
            '• Profil eksiksizliği — eksiksiz profili (fotoğraf, açıklama, doğrulanmış iletişim '
            'bilgileri) olan sağlayıcılar daha yüksek sıralanır.\n'
            '• İnceleme puanı — doğrulanmış müşteri incelemelerinden alınan ortalama puan.\n'
            '• Yanıt hızı — hızlı yanıt veren sağlayıcılar daha yüksek sıralanır.\n'
            '• Etkinlik — yakın zamanda aktif olan sağlayıcılar pasiflerden daha yüksek '
            'sıralanır.\n\n'
            '4.2 Platformun mevcut aşamasında ücretli yerleştirme sıralamayı etkilemez. Bu '
            'değişirse açıkça duyurulacaktır.\n\n'
            '4.3 Tüccar olarak tanımlanan sağlayıcılar profil sayfalarında uygun şekilde '
            'etiketlenir. Tüccar statüsünü onaylamayan sağlayıcılar özel şahıs olarak görünür. '
            'Düzenlenmiş hizmetler için sözleşme yapmadan önce sağlayıcının mesleki statüsünü '
            'doğrulamalısınız.'
        ),
        "uk": (
            '4.1 Відповідно до Регламенту ЄС P2B (2019/1150) та Директиви Omnibus (2019/2161) '
            'Nevumo розкриває основні параметри, що визначають ранжування виконавців послуг:\n\n'
            '• Геолокація — виконавці, що працюють у місті або регіоні, що відповідає вашому '
            'запиту, отримують вищий ранг.\n'
            '• Відповідність категорії — виконавці, чиї послуги відповідають запитуваній '
            'категорії, мають пріоритет.\n'
            '• Повнота профілю — виконавці з повними профілями (фото, опис, верифіковані '
            'контакти) ранжуються вище.\n'
            '• Оцінка відгуків — середня оцінка за верифікованими відгуками клієнтів.\n'
            '• Швидкість відповіді — виконавці, які швидко реагують на запити, ранжуються '
            'вище.\n'
            '• Активність — нещодавно активні виконавці ранжуються вище за неактивних.\n\n'
            '4.2 На поточному етапі роботи платформи платне розміщення не впливає на '
            'ранжування. У разі зміни це буде чітко оголошено.\n\n'
            '4.3 Виконавці, ідентифіковані як підприємці, мають відповідну позначку на '
            'сторінці профілю. Виконавці, які не підтвердили підприємницький статус, '
            'відображаються як фізичні особи. Перед укладенням договору на регульовані '
            'послуги рекомендуємо перевірити професійний статус виконавця.'
        ),
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_p4_bodies: {count} rows upserted ({NAMESPACE}, art4_body × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()
