#!/usr/bin/env python3
"""Seed auth hero namespace translations into the translations table."""

import os
import psycopg2
from psycopg2.extras import execute_values

# Database connection string
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@localhost:5432/nevumo_leads")

# Translations: language -> list of values in order
TRANSLATIONS = {
    "bg":    ["Вход | Nevumo", "Влез или създай акаунт в Nevumo. Намери и поръчай местни услуги.", "Намери услуга за минути", "Безплатно • Без ангажимент", "Започни да получаваш клиенти", "← Назад", "Ще създадем акаунт автоматично", "Забравена парола?", "Вход", "Забравена парола", "Ще изпратим линк за нова парола", "Изпрати линк", "Кликни тук за генериране на парола", "Парола", "Изпратено", "Провери имейла си", "Проверка...", "Влизане...", "Създаване...", "Изпращане...", "Грешна парола", "Възникна грешка. Опитай отново.", "Твърде много опити. Опитай по-късно.", "Акаунтът е деактивиран.", "Този имейл вече е регистриран.", "Акаунтът е създаден успешно", "Очаквайте скоро"],
    "cs":    ["Přihlášení | Nevumo", "Přihlaste se nebo vytvořte účet Nevumo. Najděte a objednejte místní služby.", "Najdi službu za minuty", "Zdarma • Bez závazků", "Začni získávat klienty", "← Zpět", "Automaticky vytvoříme účet", "Zapomenuté heslo?", "Přihlásit se", "Zapomenuté heslo", "Pošleme vám odkaz pro nové heslo", "Odeslat odkaz", "Klikněte pro vygenerování hesla", "Heslo", "Odesláno", "Zkontrolujte svůj e-mail", "Kontrola...", "Přihlašování...", "Vytváření...", "Odesílání...", "Nesprávné heslo", "Došlo k chybě. Zkuste to znovu.", "Příliš mnoho pokusů. Zkuste to později.", "Účet je deaktivován.", "Tento e-mail je již zaregistrován.", "Účet byl úspěšně vytvořen", "Připravujeme"],
    "da":    ["Log ind | Nevumo", "Log ind eller opret din Nevumo-konto. Find og book lokale tjenester.", "Find en service på få minutter", "Gratis • Ingen forpligtelse", "Begynd at få kunder", "← Tilbage", "Vi opretter automatisk en konto", "Glemt adgangskode?", "Log ind", "Glemt adgangskode", "Vi sender dig et link til en ny adgangskode", "Send link", "Klik for at generere adgangskode", "Adgangskode", "Sendt", "Tjek din e-mail", "Kontrollerer...", "Logger ind...", "Opretter...", "Sender...", "Forkert adgangskode", "Der opstod en fejl. Prøv igen.", "For mange forsøg. Prøv igen senere.", "Kontoen er deaktiveret.", "Denne e-mail er allerede registreret.", "Konto oprettet succesfuldt", "Kommer snart"],
    "de":    ["Anmelden | Nevumo", "Melde dich an oder erstelle dein Nevumo-Konto. Finde und buche lokale Dienstleistungen.", "Finde einen Service in Minuten", "Kostenlos • Unverbindlich", "Fang an, Kunden zu gewinnen", "← Zurück", "Wir erstellen automatisch ein Konto", "Passwort vergessen?", "Anmelden", "Passwort vergessen", "Wir senden dir einen Link für ein neues Passwort", "Link senden", "Klicken, um Passwort zu generieren", "Passwort", "Gesendet", "Überprüfe deine E-Mail", "Überprüfung...", "Anmeldung...", "Erstellen...", "Senden...", "Falsches Passwort", "Ein Fehler ist aufgetreten. Versuche es erneut.", "Zu viele Versuche. Versuche es später.", "Konto ist deaktiviert.", "Diese E-Mail ist bereits registriert.", "Konto erfolgreich erstellt", "Demnächst verfügbar"],
    "el":    ["Σύνδεση | Nevumo", "Συνδεθείτε ή δημιουργήστε τον λογαριασμό σας Nevumo. Βρείτε και κλείστε τοπικές υπηρεσίες.", "Βρες υπηρεσία σε λεπτά", "Δωρεάν • Χωρίς δέσμευση", "Ξεκίνα να αποκτάς πελάτες", "← Πίσω", "Θα δημιουργήσουμε αυτόματα έναν λογαριασμό", "Ξεχάσατε τον κωδικό;", "Σύνδεση", "Ξεχάσατε τον κωδικό", "Θα σας στείλουμε σύνδεσμο για νέο κωδικό", "Αποστολή συνδέσμου", "Κάντε κλικ για δημιουργία κωδικού", "Κωδικός", "Εστάλη", "Ελέγξτε το email σας", "Έλεγχος...", "Σύνδεση...", "Δημιουργία...", "Αποστολή...", "Λάθος κωδικός", "Παρουσιάστηκε σφάλμα. Δοκιμάστε ξανά.", "Πάρα πολλές προσπάθειες. Δοκιμάστε αργότερα.", "Ο λογαριασμός είναι απενεργοποιημένος.", "Αυτό το email είναι ήδη καταχωρημένο.", "Ο λογαριασμός δημιουργήθηκε επιτυχώς", "Σύντομα διαθέσιμο"],
    "en":    ["Login | Nevumo", "Sign in or create your Nevumo account. Find and book local services.", "Find a service in minutes", "Free • No obligation", "Start getting clients", "← Back", "We'll create an account automatically", "Forgot password?", "Sign in", "Forgot password", "We'll send you a link for a new password", "Send link", "Click to generate a password", "Password", "Sent", "Check your email", "Checking...", "Signing in...", "Creating...", "Sending...", "Wrong password", "An error occurred. Please try again.", "Too many attempts. Please try later.", "Account is disabled.", "This email is already registered.", "Account created successfully", "Coming soon"],
    "es":    ["Iniciar sesión | Nevumo", "Inicia sesión o crea tu cuenta Nevumo. Encuentra y reserva servicios locales.", "Encuentra un servicio en minutos", "Gratis • Sin compromiso", "Empieza a conseguir clientes", "← Atrás", "Crearemos una cuenta automáticamente", "¿Olvidaste tu contraseña?", "Iniciar sesión", "Contraseña olvidada", "Te enviaremos un enlace para una nueva contraseña", "Enviar enlace", "Haz clic para generar contraseña", "Contraseña", "Enviado", "Revisa tu correo electrónico", "Verificando...", "Iniciando sesión...", "Creando...", "Enviando...", "Contraseña incorrecta", "Ocurrió un error. Inténtalo de nuevo.", "Demasiados intentos. Inténtalo más tarde.", "La cuenta está desactivada.", "Este correo ya está registrado.", "Cuenta creada con éxito", "Próximamente"],
    "et":    ["Logi sisse | Nevumo", "Logi sisse või loo oma Nevumo konto. Leia ja broneeri kohalikke teenuseid.", "Leia teenus minutite jooksul", "Tasuta • Kohustuseta", "Hakka kliente saama", "← Tagasi", "Loome konto automaatselt", "Unustasid parooli?", "Logi sisse", "Unustatud parool", "Saadame sulle lingi uue parooli jaoks", "Saada link", "Klõpsa parooli loomiseks", "Parool", "Saadetud", "Kontrolli oma e-posti", "Kontrollimine...", "Sisselogimine...", "Loomine...", "Saatmine...", "Vale parool", "Tekkis viga. Proovi uuesti.", "Liiga palju katseid. Proovi hiljem.", "Konto on deaktiveeritud.", "See e-post on juba registreeritud.", "Konto loodud edukalt", "Tulemas"],
    "fi":    ["Kirjaudu | Nevumo", "Kirjaudu sisään tai luo Nevumo-tilisi. Etsi ja varaa paikallisia palveluita.", "Löydä palvelu minuuteissa", "Ilmainen • Ei sitoumuksia", "Ala hankkia asiakkaita", "← Takaisin", "Luomme tilin automaattisesti", "Unohditko salasanan?", "Kirjaudu sisään", "Unohtunut salasana", "Lähetämme sinulle linkin uudelle salasanalle", "Lähetä linkki", "Klikkaa luodaksesi salasanan", "Salasana", "Lähetetty", "Tarkista sähköpostisi", "Tarkistetaan...", "Kirjaudutaan...", "Luodaan...", "Lähetetään...", "Väärä salasana", "Tapahtui virhe. Yritä uudelleen.", "Liian monta yritystä. Yritä myöhemmin.", "Tili on poistettu käytöstä.", "Tämä sähköposti on jo rekisteröity.", "Tili luotu onnistuneesti", "Tulossa pian"],
    "fr":    ["Connexion | Nevumo", "Connectez-vous ou créez votre compte Nevumo. Trouvez et réservez des services locaux.", "Trouvez un service en quelques minutes", "Gratuit • Sans engagement", "Commencez à obtenir des clients", "← Retour", "Nous créerons un compte automatiquement", "Mot de passe oublié ?", "Se connecter", "Mot de passe oublié", "Nous vous enverrons un lien pour un nouveau mot de passe", "Envoyer le lien", "Cliquez pour générer un mot de passe", "Mot de passe", "Envoyé", "Vérifiez votre e-mail", "Vérification...", "Connexion...", "Création...", "Envoi...", "Mot de passe incorrect", "Une erreur s'est produite. Réessayez.", "Trop de tentatives. Réessayez plus tard.", "Le compte est désactivé.", "Cet e-mail est déjà enregistré.", "Compte créé avec succès", "Bientôt disponible"],
    "ga":    ["Logáil isteach | Nevumo", "Logáil isteach nó cruthaigh do chuntas Nevumo. Aimsigh agus áirithigh seirbhísí áitiúla.", "Faigh seirbhís i gceann cúpla nóiméad", "Saor in aisce • Gan aon cheangaltas", "Tosaigh ag fáil cliantanna", "← Ar ais", "Cruthóimid cuntas go huathoibríoch", "Focal faire dearmadta?", "Logáil isteach", "Focal faire dearmadta", "Seolfaimid nasc chugat le haghaidh focal faire nua", "Seol nasc", "Cliceáil chun focal faire a ghiniúint", "Focal faire", "Seolta", "Seiceáil do ríomhphost", "Ag seiceáil...", "Ag logáil isteach...", "Ag cruthú...", "Ag seoladh...", "Focal faire mícheart", "Tharla earráid. Bain triail as arís.", "An iomarca iarrachtaí. Bain triail as níos déanaí.", "Tá an cuntas díchumasaithe.", "Tá an ríomhphost seo cláraithe cheana féin.", "Cruthaíodh an cuntas go rathúil", "Ag teacht go luath"],
    "hr":    ["Prijava | Nevumo", "Prijavite se ili stvorite svoj Nevumo račun. Pronađite i rezervirajte lokalne usluge.", "Pronađi uslugu za nekoliko minuta", "Besplatno • Bez obveza", "Počni dobivati klijente", "← Natrag", "Automatski ćemo stvoriti račun", "Zaboravljena lozinka?", "Prijavi se", "Zaboravljena lozinka", "Poslat ćemo ti link za novu lozinku", "Pošalji link", "Klikni za generiranje lozinke", "Lozinka", "Poslano", "Provjeri svoju e-poštu", "Provjera...", "Prijava...", "Izrada...", "Slanje...", "Pogrešna lozinka", "Došlo je do pogreške. Pokušajte ponovo.", "Previše pokušaja. Pokušajte kasnije.", "Račun je deaktiviran.", "Ova e-pošta je već registrirana.", "Račun uspješno stvoren", "Uskoro"],
    "hu":    ["Bejelentkezés | Nevumo", "Jelentkezzen be vagy hozza létre Nevumo fiókját. Keressen és foglaljon helyi szolgáltatásokat.", "Találj szolgáltatást percek alatt", "Ingyenes • Kötelezettség nélkül", "Kezdj el ügyfeleket szerezni", "← Vissza", "Automatikusan létrehozunk egy fiókot", "Elfelejtett jelszó?", "Bejelentkezés", "Elfelejtett jelszó", "Küldünk egy linket az új jelszóhoz", "Link küldése", "Kattints jelszó generálásához", "Jelszó", "Elküldve", "Ellenőrizd az e-mailodat", "Ellenőrzés...", "Bejelentkezés...", "Létrehozás...", "Küldés...", "Helytelen jelszó", "Hiba történt. Próbálja újra.", "Túl sok próbálkozás. Próbálja később.", "A fiók le van tiltva.", "Ez az e-mail már regisztrálva van.", "Fiók sikeresen létrehozva", "Hamarosan"],
    "is":    ["Innskráning | Nevumo", "Skráðu þig inn eða búðu til Nevumo reikninginn þinn. Finndu og bókaðu staðbundna þjónustu.", "Finndu þjónustu á nokkrum mínútum", "Ókeypis • Án skuldbindinga", "Byrjaðu að fá viðskiptavini", "← Til baka", "Við stofnum reikning sjálfkrafa", "Gleymt lykilorð?", "Skrá inn", "Gleymt lykilorð", "Við sendum þér hlekk fyrir nýtt lykilorð", "Senda hlekk", "Smelltu til að búa til lykilorð", "Lykilorð", "Sent", "Athugaðu tölvupóstinn þinn", "Athuga...", "Skrá inn...", "Stofna...", "Sendi...", "Rangt lykilorð", "Villa kom upp. Reyndu aftur.", "Of margar tilraunir. Reyndu aftur síðar.", "Reikningurinn er óvirkur.", "Þetta netfang er þegar skráð.", "Reikningur búinn til", "Kemur fljótlega"],
    "it":    ["Accedi | Nevumo", "Accedi o crea il tuo account Nevumo. Trova e prenota servizi locali.", "Trova un servizio in pochi minuti", "Gratuito • Senza impegno", "Inizia ad acquisire clienti", "← Indietro", "Creeremo automaticamente un account", "Password dimenticata?", "Accedi", "Password dimenticata", "Ti invieremo un link per una nuova password", "Invia link", "Clicca per generare una password", "Password", "Inviato", "Controlla la tua email", "Verifica...", "Accesso...", "Creazione...", "Invio...", "Password errata", "Si è verificato un errore. Riprova.", "Troppi tentativi. Riprova più tardi.", "L'account è disattivato.", "Questa email è già registrata.", "Account creato con successo", "Prossimamente"],
    "lb":    ["Aloggen | Nevumo", "Aloggen oder erstelle deen Nevumo Kont. Fannt a buchen lokal Servicer.", "Fannt e Service a Minutten", "Gratis • Ouni Verpflichtung", "Fang un Clienten ze kréien", "← Zréck", "Mir erstellen automatesch e Kont", "Passwuert vergiess?", "Aloggen", "Passwuert vergiess", "Mir schécken dir e Link fir e neit Passwuert", "Link schécken", "Klick fir e Passwuert ze generéieren", "Passwuert", "Geschéckt", "Kontrolléier deng E-Mail", "Iwwerpréiwung...", "Aloggen...", "Erstellen...", "Schécken...", "Falsche Passwuert", "E Feeler ass opgetrueden. Probéier et nach eng Kéier.", "Ze vill Versich. Probéier et méi spéit.", "De Kont ass deaktivéiert.", "Dës E-Mail ass schonn registréiert.", "Kont erfolgräich erstallt", "Bäldst verfügbar"],
    "lt":    ["Prisijungti | Nevumo", "Prisijunkite arba sukurkite savo Nevumo paskyrą. Raskite ir užsakykite vietines paslaugas.", "Rask paslaugą per kelias minutes", "Nemokama • Be įsipareigojimų", "Pradėk gauti klientų", "← Atgal", "Sukursime paskyrą automatiškai", "Pamiršote slaptažodį?", "Prisijungti", "Pamirštas slaptažodis", "Atsiųsime jums nuorodą naujam slaptažodžiui", "Siųsti nuorodą", "Spustelėkite slaptažodžiui sugeneruoti", "Slaptažodis", "Išsiųsta", "Patikrinkite savo el. paštą", "Tikrinama...", "Jungiamasi...", "Kuriama...", "Siunčiama...", "Neteisingas slaptažodis", "Įvyko klaida. Bandykite dar kartą.", "Per daug bandymų. Bandykite vėliau.", "Paskyra yra išjungta.", "Šis el. paštas jau užregistruotas.", "Paskyra sėkmingai sukurta", "Greitai"],
    "lv":    ["Pieteikties | Nevumo", "Pieteikties vai izveidot savu Nevumo kontu. Atrodiet un rezervējiet vietējos pakalpojumus.", "Atrod pakalpojumu dažu minūšu laikā", "Bezmaksas • Bez saistībām", "Sāc piesaistīt klientus", "← Atpakaļ", "Mēs automātiski izveidosim kontu", "Aizmirsi paroli?", "Pieteikties", "Aizmirsta parole", "Mēs nosūtīsim jums saiti jaunai parolei", "Nosūtīt saiti", "Noklikšķini, lai ģenerētu paroli", "Parole", "Nosūtīts", "Pārbaudiet savu e-pastu", "Pārbauda...", "Pieteikšanās...", "Izveide...", "Sūtīšana...", "Nepareiza parole", "Radās kļūda. Mēģiniet vēlreiz.", "Pārāk daudz mēģinājumu. Mēģiniet vēlāk.", "Konts ir deaktivizēts.", "Šis e-pasts jau ir reģistrēts.", "Konts veiksmīgi izveidots", "Drīzumā"],
    "mk":    ["Најава | Nevumo", "Најавете се или креирајте го вашиот Nevumo профил. Најдете и резервирајте локални услуги.", "Најди услуга за неколку минути", "Бесплатно • Без обврски", "Почни да добиваш клиенти", "← Назад", "Автоматски ќе создадеме сметка", "Заборавена лозинка?", "Најави се", "Заборавена лозинка", "Ќе ви испратиме линк за нова лозинка", "Прати линк", "Кликни за генерирање лозинка", "Лозинка", "Испратено", "Провери го твојот е-маил", "Проверка...", "Најавување...", "Создавање...", "Испраќање...", "Погрешна лозинка", "Настана грешка. Обидете се повторно.", "Премногу обиди. Обидете се подоцна.", "Сметката е деактивирана.", "Оваа е-пошта е веќе регистрирана.", "Сметката е успешно создадена", "Наскоро"],
    "mt":    ["Idħol | Nevumo", "Idħol jew oħloq il-kont Nevumo tiegħek. Sib u bbukkja servizzi lokali.", "Sib servizz fi ftit minuti", "B'xejn • Mingħajr obbligu", "Ibda tikseb klijenti", "← Lura", "Ser noħolqu kont awtomatikament", "Password minsija?", "Idħol", "Password minsija", "Nibagħtulok link għal password ġdida", "Ibgħat link", "Ikklikkja biex tiġġenera password", "Password", "Mibgħut", "Iċċekkja l-email tiegħek", "Qiegħed jivverifika...", "Qiegħed jidħol...", "Qiegħed joħloq...", "Qiegħed jibgħat...", "Password ħażina", "Seħħet żball. Erġa' pprova.", "Wisq tentattivi. Erġa' pprova aktar tard.", "Il-kont huwa disattivat.", "Dan l-email diġà huwa reġistrat.", "Il-kont inħoloq b'suċċess", "Dalwaqt"],
    "nl":    ["Inloggen | Nevumo", "Log in of maak je Nevumo-account aan. Vind en boek lokale diensten.", "Vind een dienst in minuten", "Gratis • Vrijblijvend", "Begin met het krijgen van klanten", "← Terug", "We maken automatisch een account aan", "Wachtwoord vergeten?", "Inloggen", "Wachtwoord vergeten", "We sturen je een link voor een nieuw wachtwoord", "Link sturen", "Klik om een wachtwoord te genereren", "Wachtwoord", "Verzonden", "Controleer je e-mail", "Controleren...", "Inloggen...", "Aanmaken...", "Verzenden...", "Verkeerd wachtwoord", "Er is een fout opgetreden. Probeer het opnieuw.", "Te veel pogingen. Probeer het later opnieuw.", "Account is gedeactiveerd.", "Dit e-mailadres is al geregistreerd.", "Account succesvol aangemaakt", "Binnenkort beschikbaar"],
    "no":    ["Logg inn | Nevumo", "Logg inn eller opprett din Nevumo-konto. Finn og bestill lokale tjenester.", "Finn en tjeneste på noen minutter", "Gratis • Ingen forpliktelse", "Begynn å få kunder", "← Tilbake", "Vi oppretter en konto automatisk", "Glemt passord?", "Logg inn", "Glemt passord", "Vi sender deg en lenke for et nytt passord", "Send lenke", "Klikk for å generere passord", "Passord", "Sendt", "Sjekk e-posten din", "Sjekker...", "Logger inn...", "Oppretter...", "Sender...", "Feil passord", "Det oppsto en feil. Prøv igjen.", "For mange forsøk. Prøv igjen senere.", "Kontoen er deaktivert.", "Denne e-posten er allerede registrert.", "Konto opprettet", "Kommer snart"],
    "pl":    ["Logowanie | Nevumo", "Zaloguj się lub utwórz konto Nevumo. Znajdź i zamów lokalne usługi.", "Znajdź usługę w kilka minut", "Bezpłatnie • Bez zobowiązań", "Zacznij pozyskiwać klientów", "← Wróć", "Automatycznie utworzymy konto", "Zapomniałeś hasła?", "Zaloguj się", "Zapomniane hasło", "Wyślemy ci link do nowego hasła", "Wyślij link", "Kliknij, aby wygenerować hasło", "Hasło", "Wysłano", "Sprawdź swoją skrzynkę", "Sprawdzanie...", "Logowanie...", "Tworzenie...", "Wysyłanie...", "Błędne hasło", "Wystąpił błąd. Spróbuj ponownie.", "Zbyt wiele prób. Spróbuj później.", "Konto jest dezaktywowane.", "Ten e-mail jest już zarejestrowany.", "Konto zostało pomyślnie utworzone", "Wkrótce"],
    "pt":    ["Entrar | Nevumo", "Entre ou crie sua conta Nevumo. Encontre e reserve serviços locais.", "Encontre um serviço em minutos", "Grátis • Sem compromisso", "Comece a conseguir clientes", "← Voltar", "Criaremos uma conta automaticamente", "Esqueceu a senha?", "Entrar", "Senha esquecida", "Enviaremos um link para uma nova senha", "Enviar link", "Clique para gerar uma senha", "Senha", "Enviado", "Verifique seu e-mail", "Verificando...", "Entrando...", "Criando...", "Enviando...", "Senha incorreta", "Ocorreu um erro. Tente novamente.", "Muitas tentativas. Tente mais tarde.", "A conta está desativada.", "Este e-mail já está registrado.", "Conta criada com sucesso", "Em breve"],
    "pt-PT": ["Entrar | Nevumo", "Entre ou crie a sua conta Nevumo. Encontre e reserve serviços locais.", "Encontre um serviço em minutos", "Grátis • Sem compromisso", "Comece a conseguir clientes", "← Voltar", "Criaremos uma conta automaticamente", "Esqueceu a palavra-passe?", "Entrar", "Palavra-passe esquecida", "Enviaremos um link para uma nova palavra-passe", "Enviar link", "Clique para gerar uma palavra-passe", "Palavra-passe", "Enviado", "Verifique o seu e-mail", "A verificar...", "A entrar...", "A criar...", "A enviar...", "Palavra-passe incorreta", "Ocorreu um erro. Tente novamente.", "Demasiadas tentativas. Tente mais tarde.", "A conta está desativada.", "Este e-mail já está registado.", "Conta criada com sucesso", "Em breve"],
    "ro":    ["Autentificare | Nevumo", "Autentifică-te sau creează-ți contul Nevumo. Găsește și rezervă servicii locale.", "Găsește un serviciu în câteva minute", "Gratuit • Fără obligații", "Începe să obții clienți", "← Înapoi", "Vom crea automat un cont", "Ai uitat parola?", "Autentificare", "Parolă uitată", "Îți vom trimite un link pentru o nouă parolă", "Trimite link", "Faceți clic pentru a genera o parolă", "Parolă", "Trimis", "Verificați e-mailul", "Se verifică...", "Autentificare...", "Se creează...", "Se trimite...", "Parolă greșită", "A apărut o eroare. Încercați din nou.", "Prea multe încercări. Încercați mai târziu.", "Contul este dezactivat.", "Acest e-mail este deja înregistrat.", "Cont creat cu succes", "În curând"],
    "ru":    ["Вход | Nevumo", "Войдите или создайте свой аккаунт Nevumo. Найдите и забронируйте местные услуги.", "Найдите услугу за минуты", "Бесплатно • Без обязательств", "Начни получать клиентов", "← Назад", "Мы автоматически создадим аккаунт", "Забыли пароль?", "Войти", "Забытый пароль", "Мы отправим вам ссылку для нового пароля", "Отправить ссылку", "Нажмите для генерации пароля", "Пароль", "Отправлено", "Проверьте вашу почту", "Проверка...", "Вход...", "Создание...", "Отправка...", "Неверный пароль", "Произошла ошибка. Попробуйте снова.", "Слишком много попыток. Попробуйте позже.", "Аккаунт деактивирован.", "Этот email уже зарегистрирован.", "Аккаунт успешно создан", "Скоро"],
    "sk":    ["Prihlásiť sa | Nevumo", "Prihláste sa alebo vytvorte svoj účet Nevumo. Nájdite a rezervujte miestne služby.", "Nájdi službu za pár minút", "Zadarmo • Bez záväzkov", "Začni získavať klientov", "← Späť", "Automaticky vytvoríme účet", "Zabudnuté heslo?", "Prihlásiť sa", "Zabudnuté heslo", "Pošleme vám odkaz na nové heslo", "Odoslať odkaz", "Kliknite pre vygenerovanie hesla", "Heslo", "Odoslané", "Skontrolujte svoj e-mail", "Kontrola...", "Prihlasovanie...", "Vytváranie...", "Odosielanie...", "Nesprávne heslo", "Došlo k chybe. Skúste to znova.", "Príliš veľa pokusov. Skúste to neskôr.", "Účet je deaktivovaný.", "Tento e-mail je už zaregistrovaný.", "Účet bol úspešne vytvorený", "Čoskoro"],
    "sl":    ["Prijava | Nevumo", "Prijavite se ali ustvarite svoj račun Nevumo. Poiščite in rezervirajte lokalne storitve.", "Poišči storitev v nekaj minutah", "Brezplačno • Brez obveznosti", "Začni pridobivati stranke", "← Nazaj", "Samodejno bomo ustvarili račun", "Ste pozabili geslo?", "Prijava", "Pozabljeno geslo", "Poslali vam bomo povezavo za novo geslo", "Pošlji povezavo", "Kliknite za ustvarjanje gesla", "Geslo", "Poslano", "Preverite svojo e-pošto", "Preverjanje...", "Prijavljanje...", "Ustvarjanje...", "Pošiljanje...", "Napačno geslo", "Prišlo je do napake. Poskusite znova.", "Preveč poskusov. Poskusite kasneje.", "Račun je deaktiviran.", "Ta e-poštni naslov je že registriran.", "Račun uspešno ustvarjen", "Kmalu"],
    "sq":    ["Hyr | Nevumo", "Hyni ose krijoni llogarinë tuaj Nevumo. Gjeni dhe rezervoni shërbime lokale.", "Gjej një shërbim në minuta", "Falas • Pa detyrime", "Fillo të marrësh klientë", "← Kthehu", "Do të krijojmë automatikisht një llogari", "Keni harruar fjalëkalimin?", "Hyr", "Fjalëkalim i harruar", "Do t'ju dërgojmë një lidhje për fjalëkalim të ri", "Dërgo lidhjen", "Klikoni për të gjeneruar fjalëkalim", "Fjalëkalim", "Dërguar", "Kontrolloni emailin tuaj", "Duke kontrolluar...", "Duke hyrë...", "Duke krijuar...", "Duke dërguar...", "Fjalëkalim i gabuar", "Ndodhi një gabim. Provo përsëri.", "Shumë përpjekje. Provoni më vonë.", "Llogaria është çaktivizuar.", "Ky email është tashmë i regjistruar.", "Llogaria u krijua me sukses", "Së shpejti"],
    "sr":    ["Пријава | Nevumo", "Пријавите се или креирајте свој Nevumo налог. Пронађите и резервишите локалне услуге.", "Пронађи услугу за неколико минута", "Бесплатно • Без обавеза", "Почни да добијаш клијенте", "← Назад", "Аутоматски ћемо направити налог", "Заборављена лозинка?", "Пријави се", "Заборављена лозинка", "Послаћемо вам линк за нову лозинку", "Пошаљи линк", "Кликни за генерисање лозинке", "Лозинка", "Послато", "Проверите свој е-маил", "Провера...", "Пријављивање...", "Прављење...", "Слање...", "Погрешна лозинка", "Дошло је до грешке. Покушајте поново.", "Превише покушаја. Покушајте касније.", "Налог је деактивиран.", "Овај е-маил је већ регистрован.", "Налог је успешно направљен", "Ускоро"],
    "sv":    ["Logga in | Nevumo", "Logga in eller skapa ditt Nevumo-konto. Hitta och boka lokala tjänster.", "Hitta en tjänst på några minuter", "Gratis • Ingen förpliktelse", "Börja skaffa kunder", "← Tillbaka", "Vi skapar automatiskt ett konto", "Glömt lösenord?", "Logga in", "Glömt lösenord", "Vi skickar dig en länk för ett nytt lösenord", "Skicka länk", "Klicka för att generera lösenord", "Lösenord", "Skickat", "Kontrollera din e-post", "Kontrollerar...", "Loggar in...", "Skapar...", "Skickar...", "Fel lösenord", "Ett fel inträffade. Försök igen.", "För många försök. Försök igen senare.", "Kontot är inaktiverat.", "Denna e-postadress är redan registrerad.", "Konto skapat", "Kommer snart"],
    "tr":    ["Giriş Yap | Nevumo", "Giriş yapın veya Nevumo hesabınızı oluşturun. Yerel hizmetleri bulun ve rezerve edin.", "Dakikalar içinde bir hizmet bul", "Ücretsiz • Yükümlülük yok", "Müşteri almaya başla", "← Geri", "Otomatik olarak bir hesap oluşturacağız", "Şifreni mi unuttun?", "Giriş yap", "Şifre unutuldu", "Yeni şifre için bir bağlantı göndereceğiz", "Bağlantı gönder", "Şifre oluşturmak için tıklayın", "Şifre", "Gönderildi", "E-postanı kontrol et", "Kontrol ediliyor...", "Giriş yapılıyor...", "Oluşturuluyor...", "Gönderiliyor...", "Yanlış şifre", "Bir hata oluştu. Lütfen tekrar deneyin.", "Çok fazla deneme. Lütfen daha sonra deneyin.", "Hesap devre dışı bırakılmış.", "Bu e-posta zaten kayıtlı.", "Hesap başarıyla oluşturuldu", "Yakında"],
    "uk":    ["Вхід | Nevumo", "Увійдіть або створіть свій обліковий запис Nevumo. Знайдіть та забронюйте місцеві послуги.", "Знайди послугу за хвилини" "Безкоштовно • Без зобов'язань", "Починай отримувати клієнтів", "← Назад", "Ми автоматично створимо обліковий запис", "Забули пароль?", "Увійти", "Забутий пароль", "Ми надішлемо вам посилання для нового пароля", "Надіслати посилання", "Натисніть для генерації пароля", "Пароль", "Надіслано", "Перевірте свою пошту", "Перевірка...", "Вхід...", "Створення...", "Надсилання...", "Неправильний пароль", "Сталася помилка. Спробуйте ще раз.", "Занадто багато спроб. Спробуйте пізніше.", "Акаунт деактивовано.", "Ця електронна пошта вже зареєстрована.", "Акаунт успішно створено", "Незабаром"]
}

# Keys in order corresponding to the values per language
KEYS = [
    "auth.page_title",
    "auth.meta_description",
    "auth.hero_title_client",
    "auth.hero_subtitle_client",
    "auth.hero_title_provider",
    "auth.back_btn",
    "auth.register_subtitle",
    "auth.forgot_password_link",
    "auth.login_btn",
    "auth.forgot_title",
    "auth.forgot_subtitle",
    "auth.forgot_send_btn",
    "auth.password_placeholder_register",
    "auth.password_placeholder_login",
    "auth.forgot_sent_btn",
    "auth.forgot_check_email",
    "auth.checking_btn",
    "auth.logging_in_btn",
    "auth.registering_btn",
    "auth.sending_btn",
    "auth.error_wrong_password",
    "auth.error_generic",
    "auth.error_rate_limit",
    "auth.error_account_disabled",
    "auth.error_email_exists",
    "auth.register_success",
    "auth.coming_soon",
]


def seed_translations() -> int:
    """Seed auth hero translations and return the number of rows upserted."""
    conn = psycopg2.connect(DATABASE_URL)
    cursor = conn.cursor()

    rows_to_upsert = []
    for lang, values in TRANSLATIONS.items():
        for key, value in zip(KEYS, values):
            rows_to_upsert.append((lang, key, value))

    execute_values(
        cursor,
        """
        INSERT INTO translations (lang, key, value)
        VALUES %s
        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
        """,
        rows_to_upsert,
        template="(%s, %s, %s)",
    )

    conn.commit()
    cursor.close()
    conn.close()

    return len(rows_to_upsert)


if __name__ == "__main__":
    count = seed_translations()
    print(f"Upserted {count} rows (25 keys × 34 languages)")
