#!/usr/bin/env python3
"""Seed claim v2_p1 namespace translations into the translations table."""

import os
import psycopg2
from psycopg2.extras import execute_values

# Database connection string
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@localhost:5433/nevumo_leads")

# Translations: language -> dict of keys
TRANSLATIONS = {
    "bg": {
        "urgency": "Профилът ви е видим за клиенти — но заявките им отиват към конкуренти",
        "kicker": "Намерихме вашата фирма в Nevumo",
        "hero_title": "Той е тук. Трябва само вие да го вземете.",
        "your_profile_badge": "Вашият профил",
        "leads_title": "Последни заявки от клиенти",
        "leads_overlay": "Заяви профила за да виждаш заявките",
        "leads_overlay_sub": "Безплатно · Без комисионна",
        "benefit_1_title": "Заявки директно",
        "benefit_1_sub": "Без посредник",
        "benefit_2_title": "Видимост в Google",
        "benefit_2_sub": "SEO профил",
        "benefit_3_title": "Нула комисионна!",
        "benefit_3_sub": "Завинаги!",
        "vs_bad_1": "Плащаш за всяка заявка",
        "vs_bad_2": "Дори клиентът да откаже",
        "vs_good_1": "Клиентите те виждат и идват при теб",
        "vs_good_2": "Без посредник, без комисионна",
        "time_signal": "Отнема само 2 минути",
        "login_hint": "Вече имаш акаунт? Влез и заяви →",
        "social_proof_zero": "Стани един от първите доставчици в {city} — колкото по-рано толкова по-видим ще бъдеш!",
        "social_proof_few": "Вече {count} доставчика в {city} са на Nevumo — колкото по-рано толкова по-видим ще бъдеш!",
        "social_proof_many": "{count} доставчика в {city} вече получават заявки",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Без абонамент",
        "trust_cancel": "Анулирай по всяко време",
        "free_badge": "Безплатно за доставчици",
        "notfound_title": "Линкът е невалиден или вече е изтекъл",
        "notfound_desc": "Профилът, към който сочи този линк, не е намерен. Може да сте получили грешен линк или той вече е бил използван.",
        "notfound_support": "Получихте имейл от нас? Свържете се на support@nevumo.com — ще ви изпратим нов линк.",
        "notfound_cta": "Добави фирмата си в Nevumo",
        "notfound_ghost": "Търсиш услуга? Намери доставчик →",
        "claimed_title": "Профилът вече е активиран",
        "claimed_desc": "Този профил вече е заявен и активен в Nevumo. Ако сте собственикът, влезте в акаунта си.",
        "claimed_cta": "Влез в акаунта си",
        "claimed_support": "Не сте вие, а трябва да е? Свържете се на support@nevumo.com",
    },
    "cs": {
        "urgency": "Váš profil je viditelný pro klienty — ale jejich poptávky jdou ke konkurenci",
        "kicker": "Našli jsme vaši firmu na Nevumo",
        "hero_title": "Je tady. Potřebuje jen vás.",
        "your_profile_badge": "Váš profil",
        "leads_title": "Poslední poptávky od klientů",
        "leads_overlay": "Převezměte profil a zobrazte si poptávky",
        "leads_overlay_sub": "Zdarma · Bez provize",
        "benefit_1_title": "Poptávky přímo",
        "benefit_1_sub": "Bez prostředníka",
        "benefit_2_title": "Viditelnost na Google",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nulová provize!",
        "benefit_3_sub": "Navždy!",
        "vs_bad_1": "Platíte za každou poptávku",
        "vs_bad_2": "I když klient odmítne",
        "vs_good_1": "Klienti vás vidí a přicházejí přímo k vám",
        "vs_good_2": "Bez prostředníka, bez provize",
        "time_signal": "Trvá jen 2 minuty",
        "login_hint": "Máte účet? Přihlaste se a převezměte →",
        "social_proof_zero": "Staňte se jedním z prvních poskytovatelů v {city} — čím dříve, tím více budete viditelní!",
        "social_proof_few": "Již {count} poskytovatelé v {city} jsou na Nevumo — čím dříve, tím více budete viditelní!",
        "social_proof_many": "{count} poskytovatelů v {city} již přijímá poptávky",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Bez předplatného",
        "trust_cancel": "Zrušte kdykoli",
        "free_badge": "Zdarma pro poskytovatele",
        "notfound_title": "Odkaz je neplatný nebo vypršel",
        "notfound_desc": "Profil, na který tento odkaz odkazuje, nebyl nalezen. Možná jste obdrželi nesprávný odkaz nebo byl již použit.",
        "notfound_support": "Dostali jste od nás e-mail? Kontaktujte nás na support@nevumo.com — pošleme vám nový odkaz.",
        "notfound_cta": "Přidejte svou firmu na Nevumo",
        "notfound_ghost": "Hledáte službu? Najděte poskytovatele →",
        "claimed_title": "Profil je již aktivován",
        "claimed_desc": "Tento profil je již přijat a aktivní na Nevumo. Pokud jste vlastníkem, přihlaste se ke svému účtu.",
        "claimed_cta": "Přihlásit se k účtu",
        "claimed_support": "Nejste to vy, ale mělo by to být? Kontaktujte nás na support@nevumo.com",
    },
    "da": {
        "urgency": "Din profil er synlig for kunder — men deres anmodninger går til konkurrenter",
        "kicker": "Vi fandt din virksomhed på Nevumo",
        "hero_title": "Den er her. Den venter bare på dig.",
        "your_profile_badge": "Din profil",
        "leads_title": "Seneste kundeforespørgsler",
        "leads_overlay": "Tag profilen for at se forespørgsler",
        "leads_overlay_sub": "Gratis · Ingen provision",
        "benefit_1_title": "Direkte forespørgsler",
        "benefit_1_sub": "Ingen mellemled",
        "benefit_2_title": "Synlighed på Google",
        "benefit_2_sub": "SEO-profil",
        "benefit_3_title": "Nul provision!",
        "benefit_3_sub": "For altid!",
        "vs_bad_1": "Du betaler for hver forespørgsel",
        "vs_bad_2": "Selv hvis kunden siger nej",
        "vs_good_1": "Kunderne ser dig og kommer direkte til dig",
        "vs_good_2": "Ingen mellemled, ingen provision",
        "time_signal": "Det tager kun 2 minutter",
        "login_hint": "Har du allerede en konto? Log ind og tag profilen →",
        "social_proof_zero": "Bliv en af de første udbydere i {city} — jo tidligere, jo mere synlig!",
        "social_proof_few": "Allerede {count} udbydere i {city} er på Nevumo — jo tidligere, jo mere synlig!",
        "social_proof_many": "{count} udbydere i {city} modtager allerede forespørgsler",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Intet abonnement",
        "trust_cancel": "Annuller når som helst",
        "free_badge": "Gratis for udbydere",
        "notfound_title": "Linket er ugyldigt eller udløbet",
        "notfound_desc": "Profilen, som dette link peger på, blev ikke fundet. Du har muligvis modtaget et forkert link, eller det er allerede brugt.",
        "notfound_support": "Modtog du en e-mail fra os? Kontakt os på support@nevumo.com — vi sender dig et nyt link.",
        "notfound_cta": "Tilføj din virksomhed til Nevumo",
        "notfound_ghost": "Leder du efter en ydelse? Find en udbyder →",
        "claimed_title": "Profilen er allerede aktiveret",
        "claimed_desc": "Denne profil er allerede taget og aktiv på Nevumo. Hvis du er ejeren, skal du logge ind på din konto.",
        "claimed_cta": "Log ind på din konto",
        "claimed_support": "Er det ikke dig, men burde det være? Kontakt os på support@nevumo.com",
    },
    "de": {
        "urgency": "Ihr Profil ist für Kunden sichtbar — aber deren Anfragen gehen an Ihre Konkurrenz",
        "kicker": "Wir haben Ihr Unternehmen auf Nevumo gefunden",
        "hero_title": "Es ist da. Es wartet nur auf Sie.",
        "your_profile_badge": "Ihr Profil",
        "leads_title": "Neueste Kundenanfragen",
        "leads_overlay": "Profil übernehmen, um Anfragen zu sehen",
        "leads_overlay_sub": "Kostenlos · Ohne Provision",
        "benefit_1_title": "Direkte Anfragen",
        "benefit_1_sub": "Kein Vermittler",
        "benefit_2_title": "Sichtbarkeit auf Google",
        "benefit_2_sub": "SEO-Profil",
        "benefit_3_title": "Null Provision!",
        "benefit_3_sub": "Für immer!",
        "vs_bad_1": "Sie zahlen für jede Anfrage",
        "vs_bad_2": "Auch wenn der Kunde ablehnt",
        "vs_good_1": "Kunden sehen Sie und kommen direkt zu Ihnen",
        "vs_good_2": "Kein Vermittler, keine Provision",
        "time_signal": "Dauert nur 2 Minuten",
        "login_hint": "Haben Sie bereits ein Konto? Anmelden und übernehmen →",
        "social_proof_zero": "Werden Sie einer der ersten Anbieter in {city} — je früher, desto sichtbarer!",
        "social_proof_few": "Bereits {count} Anbieter in {city} sind auf Nevumo — je früher, desto sichtbarer!",
        "social_proof_many": "{count} Anbieter in {city} erhalten bereits Anfragen",
        "trust_gdpr": "DSGVO",
        "trust_no_sub": "Kein Abonnement",
        "trust_cancel": "Jederzeit kündigen",
        "free_badge": "Kostenlos für Anbieter",
        "notfound_title": "Der Link ist ungültig oder abgelaufen",
        "notfound_desc": "Das Profil, auf das dieser Link verweist, wurde nicht gefunden. Möglicherweise haben Sie einen falschen Link erhalten oder er wurde bereits verwendet.",
        "notfound_support": "Haben Sie eine E-Mail von uns erhalten? Kontaktieren Sie uns unter support@nevumo.com — wir senden Ihnen einen neuen Link.",
        "notfound_cta": "Fügen Sie Ihr Unternehmen zu Nevumo hinzu",
        "notfound_ghost": "Suchen Sie eine Dienstleistung? Anbieter finden →",
        "claimed_title": "Das Profil ist bereits aktiviert",
        "claimed_desc": "Dieses Profil wurde bereits beansprucht und ist auf Nevumo aktiv. Wenn Sie der Inhaber sind, melden Sie sich in Ihrem Konto an.",
        "claimed_cta": "In Konto einloggen",
        "claimed_support": "Nicht Ihres, sollte es aber sein? Kontaktieren Sie uns unter support@nevumo.com",
    },
    "el": {
        "urgency": "Το προφίλ σας είναι ορατό στους πελάτες — αλλά τα αιτήματά τους πηγαίνουν στους ανταγωνιστές",
        "kicker": "Βρήκαμε την επιχείρησή σας στο Nevumo",
        "hero_title": "Είναι εδώ. Περιμένει μόνο εσάς.",
        "your_profile_badge": "Το προφίλ σας",
        "leads_title": "Τελευταία αιτήματα πελατών",
        "leads_overlay": "Αξιώστε το προφίλ για να δείτε τα αιτήματα",
        "leads_overlay_sub": "Δωρεάν · Χωρίς προμήθεια",
        "benefit_1_title": "Αιτήματα απευθείας",
        "benefit_1_sub": "Χωρίς μεσάζοντα",
        "benefit_2_title": "Ορατότητα στο Google",
        "benefit_2_sub": "SEO προφίλ",
        "benefit_3_title": "Μηδέν προμήθεια!",
        "benefit_3_sub": "Για πάντα!",
        "vs_bad_1": "Πληρώνετε για κάθε αίτημα",
        "vs_bad_2": "Ακόμα και αν ο πελάτης αρνηθεί",
        "vs_good_1": "Οι πελάτες σας βλέπουν και έρχονται απευθείας σε εσάς",
        "vs_good_2": "Χωρίς μεσάζοντα, χωρίς προμήθεια",
        "time_signal": "Διαρκεί μόνο 2 λεπτά",
        "login_hint": "Έχετε ήδη λογαριασμό; Συνδεθείτε και αξιώστε →",
        "social_proof_zero": "Γίνετε ένας από τους πρώτους παρόχους στην {city} — όσο νωρίτερα, τόσο πιο ορατοί!",
        "social_proof_few": "Ήδη {count} πάροχοι στην {city} είναι στο Nevumo — όσο νωρίτερα, τόσο πιο ορατοί!",
        "social_proof_many": "{count} πάροχοι στην {city} λαμβάνουν ήδη αιτήματα",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Χωρίς συνδρομή",
        "trust_cancel": "Ακυρώστε ανά πάσα στιγμή",
        "free_badge": "Δωρεάν για παρόχους",
        "notfound_title": "Ο σύνδεσμος δεν είναι έγκυρος ή έχει λήξει",
        "notfound_desc": "Το προφίλ στο οποίο παραπέμπει αυτός ο σύνδεσμος δεν βρέθηκε. Ίσως λάβατε λανθασμένο σύνδεσμο ή έχει ήδη χρησιμοποιηθεί.",
        "notfound_support": "Λάβατε email από εμάς; Επικοινωνήστε μαζί μας στο support@nevumo.com — θα σας στείλουμε νέο σύνδεσμο.",
        "notfound_cta": "Προσθέστε την επιχείρησή σας στο Nevumo",
        "notfound_ghost": "Ψάχνετε υπηρεσία; Βρείτε πάροχο →",
        "claimed_title": "Το προφίλ έχει ήδη ενεργοποιηθεί",
        "claimed_desc": "Αυτό το προφίλ έχει ήδη αξιωθεί και είναι ενεργό στο Nevumo. Εάν είστε ο ιδιοκτήτης, συνδεθείτε στον λογαριασμό σας.",
        "claimed_cta": "Είσοδος στον λογαριασμό",
        "claimed_support": "Δεν είναι δικό σας, αλλά θα έπρεπε να είναι; Επικοινωνήστε στο support@nevumo.com",
    },
    "en": {
        "urgency": "Your profile is visible to clients — but their requests are going to your competitors",
        "kicker": "We found your business on Nevumo",
        "hero_title": "It's here. It just needs you.",
        "your_profile_badge": "Your profile",
        "leads_title": "Latest client requests",
        "leads_overlay": "Claim your profile to see requests",
        "leads_overlay_sub": "Free · No commission",
        "benefit_1_title": "Direct requests",
        "benefit_1_sub": "No middleman",
        "benefit_2_title": "Google visibility",
        "benefit_2_sub": "SEO profile",
        "benefit_3_title": "Zero commission!",
        "benefit_3_sub": "Forever!",
        "vs_bad_1": "You pay for every request",
        "vs_bad_2": "Even if the client says no",
        "vs_good_1": "Clients see you and come directly to you",
        "vs_good_2": "No middleman, no commission",
        "time_signal": "Takes only 2 minutes",
        "login_hint": "Already have an account? Log in and claim →",
        "social_proof_zero": "Be one of the first providers in {city} — the earlier you join, the more visible you'll be!",
        "social_proof_few": "Already {count} providers in {city} are on Nevumo — the earlier you join, the more visible you'll be!",
        "social_proof_many": "{count} providers in {city} are already receiving requests",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "No subscription",
        "trust_cancel": "Cancel anytime",
        "free_badge": "Free for providers",
        "notfound_title": "This link is invalid or has expired",
        "notfound_desc": "The profile this link points to was not found. You may have received an incorrect link or it has already been used.",
        "notfound_support": "Did you receive an email from us? Contact us at support@nevumo.com — we'll send you a new link.",
        "notfound_cta": "Add your business to Nevumo",
        "notfound_ghost": "Looking for a service? Find a provider →",
        "claimed_title": "This profile has already been activated",
        "claimed_desc": "This profile has already been claimed and is active on Nevumo. If you are the owner, please log in to your account.",
        "claimed_cta": "Log in to your account",
        "claimed_support": "Not yours, but should be? Contact us at support@nevumo.com",
    },
    "es": {
        "urgency": "Tu perfil es visible para los clientes — pero sus solicitudes van a tus competidores",
        "kicker": "Encontramos tu empresa en Nevumo",
        "hero_title": "Está aquí. Solo te necesita a ti.",
        "your_profile_badge": "Tu perfil",
        "leads_title": "Últimas solicitudes de clientes",
        "leads_overlay": "Reclama el perfil para ver las solicitudes",
        "leads_overlay_sub": "Gratis · Sin comisión",
        "benefit_1_title": "Solicitudes directas",
        "benefit_1_sub": "Sin intermediario",
        "benefit_2_title": "Visibilidad en Google",
        "benefit_2_sub": "Perfil SEO",
        "benefit_3_title": "¡Cero comisión!",
        "benefit_3_sub": "¡Para siempre!",
        "vs_bad_1": "Pagas por cada solicitud",
        "vs_bad_2": "Incluso si el cliente rechaza",
        "vs_good_1": "Los clientes te ven y vienen directamente a ti",
        "vs_good_2": "Sin intermediario, sin comisión",
        "time_signal": "Solo toma 2 minutos",
        "login_hint": "¿Ya tienes cuenta? Inicia sesión y reclama →",
        "social_proof_zero": "Sé uno de los primeros proveedores en {city} — ¡cuanto antes, más visible serás!",
        "social_proof_few": "Ya {count} proveedores en {city} están en Nevumo — ¡cuanto antes, más visible serás!",
        "social_proof_many": "{count} proveedores en {city} ya reciben solicitudes",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Sin suscripción",
        "trust_cancel": "Cancela cuando quieras",
        "free_badge": "Gratis para proveedores",
        "notfound_title": "Este enlace no es válido o ha expirado",
        "notfound_desc": "El perfil al que apunta este enlace no fue encontrado. Es posible que hayas recibido un enlace incorrecto o ya se haya utilizado.",
        "notfound_support": "¿Recibiste un correo nuestro? Contáctanos en support@nevumo.com — te enviaremos un nuevo enlace.",
        "notfound_cta": "Añade tu empresa a Nevumo",
        "notfound_ghost": "¿Buscas un servicio? Encuentra un proveedor →",
        "claimed_title": "Este perfil ya ha sido activado",
        "claimed_desc": "Este perfil ya fue reclamado y está activo en Nevumo. Si eres el propietario, inicia sesión en tu cuenta.",
        "claimed_cta": "Iniciar sesión en tu cuenta",
        "claimed_support": "¿No es tuyo pero debería serlo? Contáctanos en support@nevumo.com",
    },
    "et": {
        "urgency": "Teie profiil on klientidele nähtav — kuid nende päringud lähevad konkurentidele",
        "kicker": "Leidsime teie ettevõtte Nevumolt",
        "hero_title": "See on siin. See ootab ainult teid.",
        "your_profile_badge": "Teie profiil",
        "leads_title": "Viimased klientide päringud",
        "leads_overlay": "Võtke profiil üle, et näha päringuid",
        "leads_overlay_sub": "Tasuta · Ilma komisjonitasuta",
        "benefit_1_title": "Otse päringud",
        "benefit_1_sub": "Ilma vahendajata",
        "benefit_2_title": "Nähtavus Google'is",
        "benefit_2_sub": "SEO profiil",
        "benefit_3_title": "Null komisjonitasu!",
        "benefit_3_sub": "Igavesti!",
        "vs_bad_1": "Maksate iga päringu eest",
        "vs_bad_2": "Isegi kui klient keeldub",
        "vs_good_1": "Kliendid näevad teid ja tulevad otse teie juurde",
        "vs_good_2": "Ilma vahendajata, ilma komisjonitasuta",
        "time_signal": "Võtab ainult 2 minutit",
        "login_hint": "Kas teil on juba konto? Logige sisse ja võtke üle →",
        "social_proof_zero": "Olge üks esimesi teenusepakkujaid {city}s — mida varem, seda nähtavam!",
        "social_proof_few": "Juba {count} teenusepakkujat {city}s on Nevumol — mida varem, seda nähtavam!",
        "social_proof_many": "{count} teenusepakkujat {city}s saavad juba päringuid",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Ilma tellimuseta",
        "trust_cancel": "Tühista igal ajal",
        "free_badge": "Tasuta teenusepakkujatele",
        "notfound_title": "See link on kehtetu või aegunud",
        "notfound_desc": "Profiili, millele see link viitab, ei leitud. Võimalik, et saite vale lingi või seda on juba kasutatud.",
        "notfound_support": "Kas saite meilt e-kirja? Võtke meiega ühendust aadressil support@nevumo.com — saadame teile uue lingi.",
        "notfound_cta": "Lisa oma ettevõte Nevumosse",
        "notfound_ghost": "Otsite teenust? Leidke teenusepakkuja →",
        "claimed_title": "See profiil on juba aktiveeritud",
        "claimed_desc": "See profiil on juba üle võetud ja aktiivne Nevumol. Kui olete omanik, logige oma kontole sisse.",
        "claimed_cta": "Logi oma kontole sisse",
        "claimed_support": "Pole teie oma, aga peaks olema? Võtke meiega ühendust aadressil support@nevumo.com",
    },
    "fi": {
        "urgency": "Profiilisi on asiakkaiden näkyvissä — mutta heidän pyyntönsä menevät kilpailijoillesi",
        "kicker": "Löysimme yrityksesi Nevumosta",
        "hero_title": "Se on täällä. Se odottaa vain sinua.",
        "your_profile_badge": "Sinun profiilisi",
        "leads_title": "Viimeisimmät asiakaspyynnöt",
        "leads_overlay": "Ota profiili haltuun nähdäksesi pyynnöt",
        "leads_overlay_sub": "Ilmainen · Ei komissiota",
        "benefit_1_title": "Suorat pyynnöt",
        "benefit_1_sub": "Ei välikäsiä",
        "benefit_2_title": "Näkyvyys Googlessa",
        "benefit_2_sub": "SEO-profiili",
        "benefit_3_title": "Nolla komissiota!",
        "benefit_3_sub": "Ikuisesti!",
        "vs_bad_1": "Maksat jokaisesta pyynnöstä",
        "vs_bad_2": "Vaikka asiakas kieltäytyisi",
        "vs_good_1": "Asiakkaat näkevät sinut ja tulevat suoraan sinulle",
        "vs_good_2": "Ei välikäsiä, ei komissiota",
        "time_signal": "Vie vain 2 minuuttia",
        "login_hint": "Onko sinulla jo tili? Kirjaudu sisään ja ota →",
        "social_proof_zero": "Ole yksi ensimmäisistä palveluntarjoajista {city}ssa — mitä aiemmin, sitä näkyvämpi!",
        "social_proof_few": "Jo {count} palveluntarjoajaa {city}ssa on Nevumossa — mitä aiemmin, sitä näkyvämpi!",
        "social_proof_many": "{count} palveluntarjoajaa {city}ssa vastaanottaa jo pyyntöjä",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Ei tilausta",
        "trust_cancel": "Peruuta milloin tahansa",
        "free_badge": "Ilmainen palveluntarjoajille",
        "notfound_title": "Linkki on virheellinen tai vanhentunut",
        "notfound_desc": "Profiilia, johon tämä linkki osoittaa, ei löydy. Olet ehkä saanut virheellisen linkin tai sitä on jo käytetty.",
        "notfound_support": "Saitko meiltä sähköpostin? Ota yhteyttä osoitteessa support@nevumo.com — lähetämme sinulle uuden linkin.",
        "notfound_cta": "Lisää yrityksesi Nevumoon",
        "notfound_ghost": "Etsitkö palvelua? Löydä palveluntarjoaja →",
        "claimed_title": "Tämä profiili on jo aktivoitu",
        "claimed_desc": "Tämä profiili on jo otettu haltuun ja on aktiivinen Nevumossa. Jos olet omistaja, kirjaudu sisään tilillesi.",
        "claimed_cta": "Kirjaudu tilillesi",
        "claimed_support": "Ei sinun, mutta pitäisi olla? Ota yhteyttä osoitteessa support@nevumo.com",
    },
    "fr": {
        "urgency": "Votre profil est visible par les clients — mais leurs demandes vont à vos concurrents",
        "kicker": "Nous avons trouvé votre entreprise sur Nevumo",
        "hero_title": "Il est là. Il n'attend que vous.",
        "your_profile_badge": "Votre profil",
        "leads_title": "Dernières demandes de clients",
        "leads_overlay": "Revendiquez le profil pour voir les demandes",
        "leads_overlay_sub": "Gratuit · Sans commission",
        "benefit_1_title": "Demandes directes",
        "benefit_1_sub": "Sans intermédiaire",
        "benefit_2_title": "Visibilité sur Google",
        "benefit_2_sub": "Profil SEO",
        "benefit_3_title": "Zéro commission !",
        "benefit_3_sub": "Pour toujours !",
        "vs_bad_1": "Vous payez pour chaque demande",
        "vs_bad_2": "Même si le client refuse",
        "vs_good_1": "Les clients vous voient et viennent directement à vous",
        "vs_good_2": "Sans intermédiaire, sans commission",
        "time_signal": "Prend seulement 2 minutes",
        "login_hint": "Vous avez déjà un compte ? Connectez-vous et revendiquez →",
        "social_proof_zero": "Soyez l'un des premiers prestataires à {city} — plus tôt vous rejoignez, plus vous serez visible !",
        "social_proof_few": "Déjà {count} prestataires à {city} sont sur Nevumo — plus tôt vous rejoignez, plus vous serez visible !",
        "social_proof_many": "{count} prestataires à {city} reçoivent déjà des demandes",
        "trust_gdpr": "RGPD",
        "trust_no_sub": "Sans abonnement",
        "trust_cancel": "Annulez à tout moment",
        "free_badge": "Gratuit pour les prestataires",
        "notfound_title": "Ce lien est invalide ou a expiré",
        "notfound_desc": "Le profil auquel ce lien renvoie n'a pas été trouvé. Vous avez peut-être reçu un lien incorrect ou il a déjà été utilisé.",
        "notfound_support": "Vous avez reçu un e-mail de notre part ? Contactez-nous à support@nevumo.com — nous vous enverrons un nouveau lien.",
        "notfound_cta": "Ajoutez votre entreprise sur Nevumo",
        "notfound_ghost": "Vous cherchez un service ? Trouvez un prestataire →",
        "claimed_title": "Ce profil a déjà été activé",
        "claimed_desc": "Ce profil a déjà été revendiqué et est actif sur Nevumo. Si vous en êtes le propriétaire, connectez-vous à votre compte.",
        "claimed_cta": "Se connecter à mon compte",
        "claimed_support": "Pas le vôtre, mais ça devrait l'être ? Contactez-nous à support@nevumo.com",
    },
    "ga": {
        "urgency": "Tá do phróifíl le feiceáil ag cliaint — ach téann a n-iarratais chuig do chuid iomaitheoirí",
        "kicker": "Fuaireamar do ghnólacht ar Nevumo",
        "hero_title": "Tá sé anseo. Níl uaidh ach thú.",
        "your_profile_badge": "Do phróifíl",
        "leads_title": "Na hiarratais is déanaí ó chliaint",
        "leads_overlay": "Éiligh an phróifíl chun iarratais a fheiceáil",
        "leads_overlay_sub": "Saor in aisce · Gan choimisiún",
        "benefit_1_title": "Iarratais dhíreacha",
        "benefit_1_sub": "Gan idirghabhálaí",
        "benefit_2_title": "Infheictheacht ar Google",
        "benefit_2_sub": "Próifíl SEO",
        "benefit_3_title": "Náid coimisiúin!",
        "benefit_3_sub": "Go deo!",
        "vs_bad_1": "Íocann tú as gach iarratas",
        "vs_bad_2": "Fiú má dhiúltaíonn an cliant",
        "vs_good_1": "Feiceann cliaint thú agus tagann siad díreach chugat",
        "vs_good_2": "Gan idirghabhálaí, gan choimisiún",
        "time_signal": "Ní thógann sé ach 2 nóiméad",
        "login_hint": "An bhfuil cuntas agat cheana? Logáil isteach agus éiligh →",
        "social_proof_zero": "Bí ar cheann de na chéad soláthróirí i {city} — dá luaithe, is amhlaidh is feiceálaí a bheidh tú!",
        "social_proof_few": "Tá {count} soláthróir i {city} ar Nevumo cheana féin — dá luaithe, is amhlaidh is feiceálaí a bheidh tú!",
        "social_proof_many": "Tá {count} soláthróir i {city} ag fáil iarratas cheana féin",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Gan síntiús",
        "trust_cancel": "Cealaigh am ar bith",
        "free_badge": "Saor in aisce do sholáthróirí",
        "notfound_title": "Tá an nasc neamhbhailí nó éagtha",
        "notfound_desc": "Níor aimsíodh an phróifíl a dtugann an nasc seo léi. B'fhéidir gur fuair tú nasc mícheart nó gur úsáideadh é cheana.",
        "notfound_support": "An bhfuair tú ríomhphost uainn? Déan teagmháil linn ag support@nevumo.com — seolfaimid nasc nua chugat.",
        "notfound_cta": "Cuir do ghnólacht le Nevumo",
        "notfound_ghost": "Ag lorg seirbhíse? Aimsigh soláthróir →",
        "claimed_title": "Tá an phróifíl seo gníomhachtaithe cheana",
        "claimed_desc": "Tá an phróifíl seo éilithe agus gníomhach ar Nevumo cheana féin. Más tú an t-úinéir, logáil isteach i do chuntas.",
        "claimed_cta": "Logáil isteach i do chuntas",
        "claimed_support": "Ní leatsa é, ach ba chóir dó a bheith? Déan teagmháil linn ag support@nevumo.com",
    },
    "hr": {
        "urgency": "Vaš profil je vidljiv klijentima — ali njihovi zahtjevi idu konkurenciji",
        "kicker": "Pronašli smo vašu tvrtku na Nevumo",
        "hero_title": "Ovdje je. Čeka samo vas.",
        "your_profile_badge": "Vaš profil",
        "leads_title": "Najnoviji zahtjevi klijenata",
        "leads_overlay": "Preuzmite profil za prikaz zahtjeva",
        "leads_overlay_sub": "Besplatno · Bez provizije",
        "benefit_1_title": "Izravni zahtjevi",
        "benefit_1_sub": "Bez posrednika",
        "benefit_2_title": "Vidljivost na Googleu",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nula provizije!",
        "benefit_3_sub": "Zauvijek!",
        "vs_bad_1": "Plaćate za svaki zahtjev",
        "vs_bad_2": "Čak i kad klijent odbije",
        "vs_good_1": "Klijenti vas vide i dolaze izravno k vama",
        "vs_good_2": "Bez posrednika, bez provizije",
        "time_signal": "Traje samo 2 minute",
        "login_hint": "Već imate račun? Prijavite se i preuzmite →",
        "social_proof_zero": "Budite jedan od prvih pružatelja usluga u {city} — što prije, to vidljiviji!",
        "social_proof_few": "Već {count} pružatelja usluga u {city} su na Nevumo — što prije, to vidljiviji!",
        "social_proof_many": "{count} pružatelja usluga u {city} već prima zahtjeve",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Bez pretplate",
        "trust_cancel": "Otkazite u bilo kojem trenutku",
        "free_badge": "Besplatno za pružatelje usluga",
        "notfound_title": "Ova veza nije važeća ili je istekla",
        "notfound_desc": "Profil na koji ova veza upućuje nije pronađen. Možda ste primili pogrešnu vezu ili je već korištena.",
        "notfound_support": "Primili ste e-mail od nas? Kontaktirajte nas na support@nevumo.com — poslat ćemo vam novu vezu.",
        "notfound_cta": "Dodajte svoju tvrtku na Nevumo",
        "notfound_ghost": "Tražite uslugu? Pronađite pružatelja →",
        "claimed_title": "Ovaj profil je već aktiviran",
        "claimed_desc": "Ovaj profil je već preuzet i aktivan na Nevumo. Ako ste vlasnik, prijavite se na svoj račun.",
        "claimed_cta": "Prijavite se na račun",
        "claimed_support": "Nije vaš, a trebao bi biti? Kontaktirajte nas na support@nevumo.com",
    },
    "hu": {
        "urgency": "Profilja látható az ügyfelek számára — de kéréseik a versenytársakhoz mennek",
        "kicker": "Megtaláltuk vállalkozását a Nevumón",
        "hero_title": "Már itt van. Csak önre vár.",
        "your_profile_badge": "Az ön profilja",
        "leads_title": "Legutóbbi ügyfélkérések",
        "leads_overlay": "Igényelje a profilt a kérések megtekintéséhez",
        "leads_overlay_sub": "Ingyenes · Jutalék nélkül",
        "benefit_1_title": "Közvetlen kérések",
        "benefit_1_sub": "Közvetítő nélkül",
        "benefit_2_title": "Google láthatóság",
        "benefit_2_sub": "SEO profil",
        "benefit_3_title": "Nulla jutalék!",
        "benefit_3_sub": "Örökre!",
        "vs_bad_1": "Minden kérésért fizet",
        "vs_bad_2": "Még ha az ügyfél nem is fogadja el",
        "vs_good_1": "Az ügyfelek megtalálják önt és közvetlenül önhöz jönnek",
        "vs_good_2": "Közvetítő nélkül, jutalék nélkül",
        "time_signal": "Csak 2 percet vesz igénybe",
        "login_hint": "Már van fiókja? Jelentkezzen be és igényelje →",
        "social_proof_zero": "Legyen az egyik első szolgáltató {city}ban — minél korábban csatlakozik, annál láthatóbb lesz!",
        "social_proof_few": "Már {count} szolgáltató {city}ban van a Nevumón — minél korábban csatlakozik, annál láthatóbb lesz!",
        "social_proof_many": "{count} szolgáltató {city}ban már fogad kéréseket",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Előfizetés nélkül",
        "trust_cancel": "Bármikor lemondható",
        "free_badge": "Ingyenes a szolgáltatóknak",
        "notfound_title": "Ez a link érvénytelen vagy lejárt",
        "notfound_desc": "A link által mutatott profil nem található. Lehetséges, hogy helytelen linket kapott, vagy azt már felhasználták.",
        "notfound_support": "Kapott tőlünk e-mailt? Lépjen kapcsolatba velünk a support@nevumo.com címen — új linket küldünk.",
        "notfound_cta": "Adja hozzá vállalkozását a Nevumóhoz",
        "notfound_ghost": "Szolgáltatást keres? Találjon szolgáltatót →",
        "claimed_title": "Ez a profil már aktiválva van",
        "claimed_desc": "Ez a profil már igényelve és aktív a Nevumón. Ha ön a tulajdonos, jelentkezzen be fiókjába.",
        "claimed_cta": "Bejelentkezés a fiókba",
        "claimed_support": "Nem az öné, de annak kellene lennie? Lépjen kapcsolatba velünk a support@nevumo.com címen",
    },
    "is": {
        "urgency": "Prófíllinn þinn er sýnilegur viðskiptavinum — en beiðnir þeirra fara til keppinautanna",
        "kicker": "Við fundum fyrirtæki þitt á Nevumo",
        "hero_title": "Hann er hér. Hann bíður bara eftir þér.",
        "your_profile_badge": "Prófíllinn þinn",
        "leads_title": "Nýjustu beiðnir viðskiptavina",
        "leads_overlay": "Taktu yfir prófílinn til að sjá beiðnir",
        "leads_overlay_sub": "Ókeypis · Án þóknunar",
        "benefit_1_title": "Beinar beiðnir",
        "benefit_1_sub": "Enginn milliliður",
        "benefit_2_title": "Sýnileiki á Google",
        "benefit_2_sub": "SEO prófíll",
        "benefit_3_title": "Núll þóknun!",
        "benefit_3_sub": "Að eilífu!",
        "vs_bad_1": "Þú borgar fyrir hverja beiðni",
        "vs_bad_2": "Jafnvel þótt viðskiptavinurinn hafni",
        "vs_good_1": "Viðskiptavinir sjá þig og koma beint til þín",
        "vs_good_2": "Enginn milliliður, engin þóknun",
        "time_signal": "Tekur aðeins 2 mínútur",
        "login_hint": "Ertu þegar með reikning? Skráðu þig inn og taktu yfir →",
        "social_proof_zero": "Vertu einn af fyrstu þjónustuaðilunum í {city} — því fyrr sem þú bætist við, því sýnilegri verður þú!",
        "social_proof_few": "Þegar {count} þjónustuaðilar í {city} eru á Nevumo — því fyrr sem þú bætist við, því sýnilegri verður þú!",
        "social_proof_many": "{count} þjónustuaðilar í {city} fá þegar beiðnir",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Ekkert áskrift",
        "trust_cancel": "Hætta hvenær sem er",
        "free_badge": "Ókeypis fyrir þjónustuaðila",
        "notfound_title": "Þessi tengill er ógildur eða útrunninn",
        "notfound_desc": "Prófíllinn sem þessi tengill vísar til fannst ekki. Þú gætir hafa fengið rangan tengil eða hann hefur þegar verið notaður.",
        "notfound_support": "Fékkstu tölvupóst frá okkur? Hafðu samband við okkur á support@nevumo.com — við sendum þér nýjan tengil.",
        "notfound_cta": "Bættu fyrirtæki þínu við Nevumo",
        "notfound_ghost": "Ertu að leita að þjónustu? Finndu þjónustuaðila →",
        "claimed_title": "Þessi prófíll hefur þegar verið virkjaður",
        "claimed_desc": "Þessi prófíll hefur þegar verið tekinn yfir og er virkur á Nevumo. Ef þú ert eigandinn skaltu skrá þig inn á reikninginn þinn.",
        "claimed_cta": "Skrá þig inn á reikninginn",
        "claimed_support": "Ekki þinn en ætti að vera? Hafðu samband við okkur á support@nevumo.com",
    },
    "it": {
        "urgency": "Il tuo profilo è visibile ai clienti — ma le loro richieste vanno ai tuoi concorrenti",
        "kicker": "Abbiamo trovato la tua azienda su Nevumo",
        "hero_title": "È qui. Aspetta solo te.",
        "your_profile_badge": "Il tuo profilo",
        "leads_title": "Ultime richieste dei clienti",
        "leads_overlay": "Rivendica il profilo per vedere le richieste",
        "leads_overlay_sub": "Gratuito · Senza commissioni",
        "benefit_1_title": "Richieste dirette",
        "benefit_1_sub": "Senza intermediari",
        "benefit_2_title": "Visibilità su Google",
        "benefit_2_sub": "Profilo SEO",
        "benefit_3_title": "Zero commissioni!",
        "benefit_3_sub": "Per sempre!",
        "vs_bad_1": "Paghi per ogni richiesta",
        "vs_bad_2": "Anche se il cliente rifiuta",
        "vs_good_1": "I clienti ti vedono e vengono direttamente da te",
        "vs_good_2": "Nessun intermediario, nessuna commissione",
        "time_signal": "Bastano solo 2 minuti",
        "login_hint": "Hai già un account? Accedi e rivendica →",
        "social_proof_zero": "Sii uno dei primi fornitori a {city} — prima ti unisci, più sarai visibile!",
        "social_proof_few": "Già {count} fornitori a {city} sono su Nevumo — prima ti unisci, più sarai visibile!",
        "social_proof_many": "{count} fornitori a {city} stanno già ricevendo richieste",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Senza abbonamento",
        "trust_cancel": "Annulla in qualsiasi momento",
        "free_badge": "Gratuito per i fornitori",
        "notfound_title": "Questo link non è valido o è scaduto",
        "notfound_desc": "Il profilo a cui punta questo link non è stato trovato. Potresti aver ricevuto un link errato o è già stato utilizzato.",
        "notfound_support": "Hai ricevuto un'email da noi? Contattaci a support@nevumo.com — ti invieremo un nuovo link.",
        "notfound_cta": "Aggiungi la tua azienda a Nevumo",
        "notfound_ghost": "Cerchi un servizio? Trova un fornitore →",
        "claimed_title": "Questo profilo è già stato attivato",
        "claimed_desc": "Questo profilo è già stato rivendicato ed è attivo su Nevumo. Se sei il proprietario, accedi al tuo account.",
        "claimed_cta": "Accedi al tuo account",
        "claimed_support": "Non è tuo, ma dovrebbe esserlo? Contattaci a support@nevumo.com",
    },
    "lb": {
        "urgency": "Äre Profil ass fir Clienten siichtbar — mä hir Ufroe ginn un d'Konkurrenz",
        "kicker": "Mir hunn Äre Betrib op Nevumo fonnt",
        "hero_title": "Hien ass do. Hien waert nëmmen op Iech.",
        "your_profile_badge": "Äre Profil",
        "leads_title": "Lescht Ufroe vun Clienten",
        "leads_overlay": "Huel de Profil fir d'Ufroe ze gesinn",
        "leads_overlay_sub": "Gratis · Ouni Provisioun",
        "benefit_1_title": "Direkt Ufroe",
        "benefit_1_sub": "Ouni Mëttelmann",
        "benefit_2_title": "Visibilitéit op Google",
        "benefit_2_sub": "SEO Profil",
        "benefit_3_title": "Null Provisioun!",
        "benefit_3_sub": "Fir ëmmer!",
        "vs_bad_1": "Dir bezuelt fir all Ufro",
        "vs_bad_2": "Och wann de Client refuséiert",
        "vs_good_1": "Clienten gesinn Iech a komme direkt bei Iech",
        "vs_good_2": "Ouni Mëttelmann, ouni Provisioun",
        "time_signal": "Dauert nëmmen 2 Minutten",
        "login_hint": "Hutt Dir schonn e Kont? Loggt Iech an a huelt →",
        "social_proof_zero": "Gitt ee vun den éischten Ubidder a {city} — wat méi fréi, wat méi siichtbar!",
        "social_proof_few": "Schonn {count} Ubidder a {city} sinn op Nevumo — wat méi fréi, wat méi siichtbar!",
        "social_proof_many": "{count} Ubidder a {city} kréien schonn Ufroe",
        "trust_gdpr": "GDPR",
        "trust_no_sub": "Ouni Abonnement",
        "trust_cancel": "Jidder Zäit kännegen",
        "free_badge": "Gratis fir Ubidder",
        "notfound_title": "Dëse Link ass ongëlteg oder ofgelaf",
        "notfound_desc": "De Profil, op deen dëse Link weist, gouf net fonnt. Dir hutt vläicht e falschen Link kritt oder hie gouf schonn benotzt.",
        "notfound_support": "Hutt Dir eng E-Mail vun eis kritt? Kontaktéiert eis op support@nevumo.com — mir schécken Iech e neie Link.",
        "notfound_cta": "Füügt Äre Betrib zu Nevumo bäi",
        "notfound_ghost": "Sicht Dir e Service? Fannt e Ubidder →",
        "claimed_title": "Dëse Profil ass schonn aktivéiert",
        "claimed_desc": "Dëse Profil gouf schonn geholl a ass aktiv op Nevumo. Wann Dir den Eegentümer sidd, loggt Iech a Äre Kont an.",
        "claimed_cta": "Loggt Iech an Äre Kont an",
        "claimed_support": "Net Äres, mä sollt et sinn? Kontaktéiert eis op support@nevumo.com",
    },
    "lt": {
        "urgency": "Jūsų profilis matomas klientams — tačiau jų užklausos atitenka konkurentams",
        "kicker": "Radome jūsų įmonę Nevumo",
        "hero_title": "Jis čia. Laukia tik jūsų.",
        "your_profile_badge": "Jūsų profilis",
        "leads_title": "Naujausios klientų užklausos",
        "leads_overlay": "Perimkite profilį, kad matytumėte užklausas",
        "leads_overlay_sub": "Nemokamai · Be komisinių",
        "benefit_1_title": "Tiesioginės užklausos",
        "benefit_1_sub": "Be tarpininkų",
        "benefit_2_title": "Matomumas Google",
        "benefit_2_sub": "SEO profilis",
        "benefit_3_title": "Nulis komisinių!",
        "benefit_3_sub": "Amžinai!",
        "vs_bad_1": "Mokate už kiekvieną užklausą",
        "vs_bad_2": "Net jei klientas atsisako",
        "vs_good_1": "Klientai jus mato ir ateina tiesiai pas jus",
        "vs_good_2": "Be tarpininkų, be komisinių",
        "time_signal": "Užtrunka tik 2 minutes",
        "login_hint": "Jau turite paskyrą? Prisijunkite ir perimkite →",
        "social_proof_zero": "Tapkite vienu iš pirmųjų paslaugų teikėjų {city} — kuo anksčiau, tuo matomesni būsite!",
        "social_proof_few": "Jau {count} paslaugų teikėjų {city} yra Nevumo — kuo anksčiau, tuo matomesni būsite!",
        "social_proof_many": "{count} paslaugų teikėjų {city} jau gauna užklausas",
        "trust_gdpr": "BDAR",
        "trust_no_sub": "Be prenumeratos",
        "trust_cancel": "Atsisakykite bet kada",
        "free_badge": "Nemokamai paslaugų teikėjams",
        "notfound_title": "Ši nuoroda negalioja arba nebegalioja",
        "notfound_desc": "Profilis, į kurį nukreipia ši nuoroda, nerastas. Galbūt gavote neteisingą nuorodą arba ji jau buvo panaudota.",
        "notfound_support": "Gavote iš mūsų el. laišką? Susisiekite su mumis adresu support@nevumo.com — atsiųsime naują nuorodą.",
        "notfound_cta": "Pridėkite savo įmonę į Nevumo",
        "notfound_ghost": "Ieškote paslaugos? Raskite paslaugų teikėją →",
        "claimed_title": "Šis profilis jau aktyvuotas",
        "claimed_desc": "Šis profilis jau perimtas ir aktyvus Nevumo. Jei esate savininkas, prisijunkite prie savo paskyros.",
        "claimed_cta": "Prisijungti prie paskyros",
        "claimed_support": "Ne jūsų, bet turėtų būti? Susisiekite su mumis adresu support@nevumo.com",
    },
    "lv": {
        "urgency": "Jūsu profils ir redzams klientiem — taču viņu pieprasījumi nonāk pie konkurentiem",
        "kicker": "Mēs atradām jūsu uzņēmumu Nevumo",
        "hero_title": "Tas ir šeit. Tas tikai gaida jūs.",
        "your_profile_badge": "Jūsu profils",
        "leads_title": "Jaunākie klientu pieprasījumi",
        "leads_overlay": "Pārņemiet profilu, lai redzētu pieprasījumus",
        "leads_overlay_sub": "Bezmaksas · Bez komisijas",
        "benefit_1_title": "Tiešie pieprasījumi",
        "benefit_1_sub": "Bez starpnieka",
        "benefit_2_title": "Redzamība Google",
        "benefit_2_sub": "SEO profils",
        "benefit_3_title": "Nulle komisijas!",
        "benefit_3_sub": "Uz visiem laikiem!",
        "vs_bad_1": "Jūs maksājat par katru pieprasījumu",
        "vs_bad_2": "Pat ja klients atsakās",
        "vs_good_1": "Klienti jūs redz un nāk tieši pie jums",
        "vs_good_2": "Bez starpnieka, bez komisijas",
        "time_signal": "Aizņem tikai 2 minūtes",
        "login_hint": "Jums jau ir konts? Piesakieties un pārņemiet →",
        "social_proof_zero": "Kļūstiet viens no pirmajiem pakalpojumu sniedzējiem {city} — jo agrāk, jo redzamāks!",
        "social_proof_few": "Jau {count} pakalpojumu sniedzēji {city} ir Nevumo — jo agrāk, jo redzamāks!",
        "social_proof_many": "{count} pakalpojumu sniedzēji {city} jau saņem pieprasījumus",
        "trust_gdpr": "VDAR",
        "trust_no_sub": "Bez abonēšanas",
        "trust_cancel": "Atcelt jebkurā laikā",
        "free_badge": "Bezmaksas pakalpojumu sniedzējiem",
        "notfound_title": "Šī saite ir nederīga vai ir beigusi derēt",
        "notfound_desc": "Profils, uz kuru norāda šī saite, netika atrasts. Iespējams, saņēmāt nepareizu saiti vai tā jau ir izmantota.",
        "notfound_support": "Saņēmāt mūsu e-pastu? Sazinieties ar mums uz support@nevumo.com — mēs nosūtīsim jaunu saiti.",
        "notfound_cta": "Pievienojiet savu uzņēmumu Nevumo",
        "notfound_ghost": "Meklējat pakalpojumu? Atrodiet sniedzēju →",
        "claimed_title": "Šis profils jau ir aktivizēts",
        "claimed_desc": "Šis profils jau ir pārņemts un aktīvs Nevumo. Ja esat īpašnieks, piesakieties savā kontā.",
        "claimed_cta": "Pieteikties kontā",
        "claimed_support": "Nav jūsējs, bet vajadzētu būt? Sazinieties ar mums uz support@nevumo.com",
    },
}


def seed_translations() -> int:
    """Seed translations into the database."""
    conn = psycopg2.connect(DATABASE_URL)
    cursor = conn.cursor()

    rows_to_upsert = []
    total_count = 0

    for lang, keys in TRANSLATIONS.items():
        for key, value in keys.items():
            full_key = f"claim.{key}"
            rows_to_upsert.append((lang, full_key, value))
        print(f"Seeded {lang}: {len(keys)} keys")
        total_count += len(keys)

    execute_values(
        cursor,
        """
        INSERT INTO translations (lang, key, value)
        VALUES %s
        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
        """,
        rows_to_upsert,
        template="(%s, %s, %s)",
    )

    conn.commit()
    cursor.close()
    conn.close()

    return total_count


if __name__ == "__main__":
    count = seed_translations()
    print(f"✅ Done: {count} translations inserted/updated")
