# -*- coding: utf-8 -*-
"""
seed_cookies_p16.py - namespace 'cookies'
cookies.s3_3_text, cookies.s3_4_text
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p16
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL")
engine = create_engine(DATABASE_URL)

TRANSLATIONS = {
    "cookies.s3_3_text": {
        "en": "Help us understand how visitors use Nevumo - which pages are visited, how long users stay, and where they come from. We use Google Analytics 4 (GA4) with Advanced Consent Mode v2. If you decline analytics cookies, GA4 still loads but sends only anonymised, cookieless pings. Google uses statistical modelling to estimate traffic trends without identifying you personally. No analytics cookies are placed without your explicit consent. Legal basis: Art. 6(1)(a) GDPR - your consent.",
        "bg": "Помагат ни да разберем как посетителите използват Nevumo - кои страници се посещават, колко дълго остават потребителите и откъде идват. Използваме Google Analytics 4 (GA4) с Advanced Consent Mode v2. Ако откажете аналитичните бисквитки, GA4 все още се зарежда, но изпраща само анонимизирани сигнали без бисквитки. Google използва статистическо моделиране за оценка на тенденциите в трафика без лично идентифициране. Никакви аналитични бисквитки не се поставят без вашето изрично съгласие. Правно основание: Чл. 6, ал. 1, б. а) GDPR - вашето съгласие.",
        "cs": "Pomáhají nám pochopit, jak návštěvníci používají Nevumo - které stránky jsou navštěvovány, jak dlouho uživatelé zůstávají a odkud přicházejí. Používáme Google Analytics 4 (GA4) s Advanced Consent Mode v2. Pokud odmítnete analytické cookies, GA4 se stále načítá, ale odesílá pouze anonymizované signály bez cookies. Google využívá statistické modelování k odhadu trendů provozu bez osobní identifikace. Žádné analytické cookies se neumísťují bez vašeho výslovného souhlasu. Právní základ: Čl. 6(1)(a) GDPR - váš souhlas.",
        "da": "Hjælper os med at forstå, hvordan besøgende bruger Nevumo - hvilke sider der besøges, hvor længe brugerne forbliver, og hvorfra de kommer. Vi bruger Google Analytics 4 (GA4) med Advanced Consent Mode v2. Hvis du afviser analytiske cookies, indlæses GA4 stadig, men sender kun anonymiserede pings uden cookies. Google bruger statistisk modellering til at estimere trafiktrends uden personlig identifikation. Ingen analytiske cookies placeres uden dit udtrykkelige samtykke. Retsgrundlag: Art. 6(1)(a) GDPR - dit samtykke.",
        "de": "Helfen uns zu verstehen, wie Besucher Nevumo nutzen - welche Seiten besucht werden, wie lange Nutzer bleiben und woher sie kommen. Wir verwenden Google Analytics 4 (GA4) mit Advanced Consent Mode v2. Wenn Sie Analyse-Cookies ablehnen, lädt GA4 trotzdem, sendet jedoch nur anonymisierte, cookielose Pings. Google nutzt statistische Modellierung zur Schätzung von Traffic-Trends, ohne Sie persönlich zu identifizieren. Es werden keine Analyse-Cookies ohne Ihre ausdrückliche Einwilligung gesetzt. Rechtsgrundlage: Art. 6(1)(a) DSGVO - Ihre Einwilligung.",
        "el": "Μας βοηθούν να κατανοήσουμε πώς οι επισκέπτες χρησιμοποιούν το Nevumo - ποιες σελίδες επισκέπτονται, πόσο καιρό παραμένουν οι χρήστες και από πού έρχονται. Χρησιμοποιούμε το Google Analytics 4 (GA4) με Advanced Consent Mode v2. Εάν αρνηθείτε τα αναλυτικά cookies, το GA4 εξακολουθεί να φορτώνει αλλά αποστέλλει μόνο ανώνυμα σήματα χωρίς cookie. Η Google χρησιμοποιεί στατιστική μοντελοποίηση για την εκτίμηση τάσεων κυκλοφορίας χωρίς προσωπική ταυτοποίηση. Κανένα αναλυτικό cookie δεν τοποθετείται χωρίς τη ρητή συγκατάθεσή σας. Νομική βάση: Άρθρο 6(1)(α) GDPR - η συγκατάθεσή σας.",
        "es": "Nos ayudan a entender cómo los visitantes usan Nevumo - qué páginas se visitan, cuánto tiempo permanecen los usuarios y de dónde vienen. Utilizamos Google Analytics 4 (GA4) con Advanced Consent Mode v2. Si rechaza las cookies analíticas, GA4 sigue cargando pero solo envía pings anónimos sin cookies. Google utiliza modelado estadístico para estimar tendencias de tráfico sin identificarle personalmente. No se colocan cookies analíticas sin su consentimiento explícito. Base jurídica: Art. 6(1)(a) RGPD - su consentimiento.",
        "et": "Aitab meil mõista, kuidas külastajad Nevumot kasutavad - milliseid lehti külastatakse, kui kaua kasutajad viibivad ja kust nad tulevad. Kasutame Google Analytics 4 (GA4) koos Advanced Consent Mode v2-ga. Kui keeldute analüütilistest küpsistest, laadib GA4 ikkagi, kuid saadab ainult anonümiseeritud, küpsisevabad signaale. Google kasutab statistilist modelleerimist liiklustrende hindamiseks ilma teid isiklikult tuvastamata. Ilma teie selgesõnalise nõusolekuta ei paigutata ühtegi analüütilist küpsist. Õiguslik alus: Art. 6(1)(a) GDPR - teie nõusolek.",
        "fi": "Auttaa meitä ymmärtämään, miten kävijät käyttävät Nevumoa - mitä sivuja vieraillaan, kuinka kauan käyttäjät viipyvät ja mistä he tulevat. Käytämme Google Analytics 4:ää (GA4) Advanced Consent Mode v2:n kanssa. Jos kieltäydyt analytiikkaeva steistä, GA4 latautuu silti, mutta lähettää vain anonyymejä, evästeettömiä signaaleja. Google käyttää tilastollista mallintamista liikennetrendien arvioimiseen tunnistamatta sinua henkilökohtaisesti. Mitään analytiikkaevästeitä ei aseteta ilman nimenomaista suostumustasi. Oikeusperuste: Art. 6(1)(a) GDPR - suostumuksesi.",
        "fr": "Nous aident à comprendre comment les visiteurs utilisent Nevumo - quelles pages sont visitées, combien de temps les utilisateurs restent et d'où ils viennent. Nous utilisons Google Analytics 4 (GA4) avec Advanced Consent Mode v2. Si vous refusez les cookies analytiques, GA4 se charge quand même mais n'envoie que des signaux anonymisés sans cookies. Google utilise la modélisation statistique pour estimer les tendances de trafic sans vous identifier personnellement. Aucun cookie analytique n'est déposé sans votre consentement explicite. Base juridique : Art. 6(1)(a) RGPD - votre consentement.",
        "ga": "Cuidíonn siad linn a thuiscint conas a úsáideann cuairteoirí Nevumo - cé na leathanaigh a dtugtar cuairt orthu, cé chomh fada a fhanann úsáideoirí, agus cad as dóibh. Úsáidimid Google Analytics 4 (GA4) le Advanced Consent Mode v2. Má dhiúltaíonn tú fianáin anailísíochta, luchtaíonn GA4 fós ach seolann sé comharthaí gan fianáin amháin. Úsáideann Google samhaltú staitistiúil chun treochtaí tráchta a mheas gan tú a aithint go pearsanta. Ní chuirtear fianáin anailísíochta gan do thoiliú sainráite. Bunús dlí: Alt 6(1)(a) GDPR - do thoiliú.",
        "hr": "Pomažu nam razumjeti kako posjetitelji koriste Nevumo - koje se stranice posjećuju, koliko dugo korisnici ostaju i odakle dolaze. Koristimo Google Analytics 4 (GA4) s Advanced Consent Mode v2. Ako odbijete analitičke kolačiće, GA4 se i dalje učitava, ali šalje samo anonimne signale bez kolačića. Google koristi statističko modeliranje za procjenu trendova prometa bez osobne identifikacije. Ni jedan analitički kolačić se ne postavlja bez vašeg izričitog pristanka. Pravna osnova: čl. 6(1)(a) GDPR - vaš pristanak.",
        "hu": "Segítenek megérteni, hogyan használják a látogatók a Nevumót - mely oldalakat látogatják, mennyi ideig maradnak a felhasználók, és honnan érkeznek. A Google Analytics 4 (GA4) alkalmazást használjuk az Advanced Consent Mode v2-vel. Ha elutasítja az analitikai sütiket, a GA4 akkor is betöltődik, de csak anonimizált, sütimentes pingeket küld. A Google statisztikai modellezést alkalmaz a forgalmi trendek becslésére anélkül, hogy személyesen azonosítaná Önt. Az Ön kifejezett hozzájárulása nélkül semmilyen analitikai süti nem kerül elhelyezésre. Jogalap: 6. cikk (1) bek. a) pont GDPR - az Ön hozzájárulása.",
        "is": "Hjálpar okkur að skilja hvernig gestir nota Nevumo - hvaða síður eru heimsóttar, hve lengi notendur eru og hvaðan þeir koma. Við notum Google Analytics 4 (GA4) með Advanced Consent Mode v2. Ef þú hafnar greiningarvafrakökum hleður GA4 engu að síður en sendir aðeins nafnlægar, vafrakökulausar merkingar. Google notar tölfræðilega líkanagerð til að meta umferðarþróun án þess að bera þig kennsl á persónulega. Engar greiningarvafrakökur eru settar án þíns skýra samþykkis. Lagagrundvöllur: Gr. 6(1)(a) GDPR - þitt samþykki.",
        "it": "Ci aiutano a capire come i visitatori usano Nevumo - quali pagine vengono visitate, quanto a lungo gli utenti rimangono e da dove provengono. Utilizziamo Google Analytics 4 (GA4) con Advanced Consent Mode v2. Se rifiuti i cookie analitici, GA4 si carica comunque ma invia solo segnali anonimi, senza cookie. Google utilizza la modellazione statistica per stimare le tendenze del traffico senza identificarti personalmente. Nessun cookie analitico viene impostato senza il tuo consenso esplicito. Base giuridica: Art. 6(1)(a) GDPR - il tuo consenso.",
        "lb": "Hëllefen eis ze verstoen, wéi Besucher Nevumo benotzen - wéi Säiten besicht ginn, wéi laang Benotzer bleiwen an wou si hierkommen. Mir benotzen Google Analytics 4 (GA4) mat Advanced Consent Mode v2. Wann Dir Analyse-Cookies ofleent, gëtt GA4 trotzdem gelueden, awer schéckt nëmmen anonymiséierte, cookielose Signaler. Google benotzt statistesch Modellierung fir Verkéierstendenzen ouni perséinlech Identifikatioun ze schätzen. Keng Analyse-Cookies ginn ouni Äre explizite Consent gesat. Rechtlech Basis: Art. 6(1)(a) DSGVO - Ären Consent.",
        "lt": "Padeda mums suprasti, kaip lankytojai naudoja Nevumo - kurie puslapiai lankomi, kiek laiko vartotojai lieka ir iš kur jie ateina. Naudojame Google Analytics 4 (GA4) su Advanced Consent Mode v2. Jei atsisakote analitinių slapukų, GA4 vis tiek įkeliamas, bet siunčia tik anonimizuotus, be slapukų signalus. Google naudoja statistinį modeliavimą eismo tendencijoms įvertinti neasmeniniu jūsų atpažinimu. Jokie analitiniai slapukai nededami be jūsų aiškaus sutikimo. Teisinis pagrindas: BDAR 6 str. 1 d. a p. - jūsų sutikimas.",
        "lv": "Palīdz mums saprast, kā apmeklētāji izmanto Nevumo - kuras lapas tiek apmeklētas, cik ilgi lietotāji uzturas un no kurienes viņi nāk. Mēs izmantojam Google Analytics 4 (GA4) ar Advanced Consent Mode v2. Ja atsakāties no analītiskajām sīkdatnēm, GA4 joprojām ielādējas, bet sūta tikai anonimizētus, bez sīkdatnēm signālus. Google izmanto statistisko modelēšanu, lai novērtētu satiksmes tendences bez personiskas identifikācijas. Nekādas analītiskās sīkdatnes netiek ievietotas bez jūsų tiešas piekrišanas. Juridiskais pamats: VDAR 6. panta 1. punkta a) apakšpunkts - jūsu piekrišana.",
        "mk": "Ни помагаат да разбереме kako посетителите го користат Nevumo - кои страници се посетуваат, колку долго остануваат корисниците и од каде доаѓаат. Го користиме Google Analytics 4 (GA4) со Advanced Consent Mode v2. Ако ги одбиете аналитичките колачиња, GA4 сепак се вчитува, но испраќа само анонимизирани сигнали без колачиња. Google користи статистичко моделирање за проценка на трендовите во сообраќајот без лична идентификација. Никакви аналитички колачиња не се поставуваат без вашата изрична согласност. Правна основа: чл. 6(1)(а) GDPR - вашата согласност.",
        "mt": "Jgħinuna nifhmu kif il-viżitaturi jużaw Nevumo - liema paġni jiġu żżurati, kemm idum l-utenti u minn fejn ġejjin. Nużaw Google Analytics 4 (GA4) b'Advanced Consent Mode v2. Jekk tirrifjuta l-cookies analitiċi, GA4 xorta jitgħabba iżda jibgħat biss pings anonimizzati bla cookies. Google juża mudelli statitiċi biex jistima t-tendenzi tat-traffiku mingħajr ma jidentifika lek personalment. L-ebda cookie analitiku ma jitqiegħed mingħajr il-kunsens espliċitu tiegħek. Bażi legali: Art. 6(1)(a) GDPR - il-kunsens tiegħek.",
        "nl": "Helpen ons te begrijpen hoe bezoekers Nevumo gebruiken - welke pagina's worden bezocht, hoe lang gebruikers blijven en waar ze vandaan komen. We gebruiken Google Analytics 4 (GA4) met Advanced Consent Mode v2. Als u analytische cookies weigert, laadt GA4 toch, maar stuurt alleen geanonimiseerde, cookieloze pings. Google gebruikt statistische modellering om verkeerstendensen te schatten zonder u persoonlijk te identificeren. Er worden geen analytische cookies geplaatst zonder uw uitdrukkelijke toestemming. Rechtsgrondslag: Art. 6(1)(a) AVG - uw toestemming.",
        "no": "Hjelper oss å forstå hvordan besøkende bruker Nevumo - hvilke sider som besøkes, hvor lenge brukere er og hvor de kommer fra. Vi bruker Google Analytics 4 (GA4) med Advanced Consent Mode v2. Hvis du avviser analytiske informasjonskapsler, laster GA4 likevel, men sender bare anonymiserte, informasjonskapselløse signaler. Google bruker statistisk modellering for å estimere trafikktrender uten å identifisere deg personlig. Ingen analytiske informasjonskapsler plasseres uten ditt uttrykkelige samtykke. Rettsgrunnlag: Art. 6(1)(a) GDPR - ditt samtykke.",
        "pl": "Pomagają nam zrozumieć, jak odwiedzający korzystają z Nevumo - które strony są odwiedzane, jak długo użytkownicy pozostają i skąd przychodzą. Używamy Google Analytics 4 (GA4) z Advanced Consent Mode v2. Jeśli odrzucisz analityczne pliki cookie, GA4 nadal się ładuje, ale wysyła tylko anonimowe sygnały bez plików cookie. Google wykorzystuje modelowanie statystyczne do szacowania trendów ruchu bez osobistej identyfikacji. Żadne analityczne pliki cookie nie są umieszczane bez Twojej wyraźnej zgody. Podstawa prawna: Art. 6(1)(a) RODO - Twoja zgoda.",
        "pt": "Ajudam-nos a entender como os visitantes usam o Nevumo - quais páginas são visitadas, quanto tempo os usuários ficam e de onde vêm. Usamos o Google Analytics 4 (GA4) com Advanced Consent Mode v2. Se você recusar os cookies analíticos, o GA4 ainda carrega, mas envia apenas pings anônimos sem cookies. O Google usa modelagem estatística para estimar tendências de tráfego sem identificá-lo pessoalmente. Nenhum cookie analítico é colocado sem o seu consentimento explícito. Base jurídica: Art. 6(1)(a) RGPD - seu consentimento.",
        "pt-PT": "Ajudam-nos a compreender como os visitantes utilizam o Nevumo - quais as páginas visitadas, quanto tempo os utilizadores ficam e de onde provêm. Utilizamos o Google Analytics 4 (GA4) com Advanced Consent Mode v2. Se recusar os cookies analíticos, o GA4 continua a carregar mas envia apenas sinais anónimos sem cookies. O Google utiliza modelação estatística para estimar tendências de tráfego sem identificá-lo pessoalmente. Nenhum cookie analítico é colocado sem o seu consentimento explícito. Base jurídica: Art. 6(1)(a) RGPD - o seu consentimento.",
        "ro": "Ne ajută să înțelegem cum folosesc vizitatorii Nevumo - ce pagini sunt vizitate, cât timp stau utilizatorii și de unde vin. Folosim Google Analytics 4 (GA4) cu Advanced Consent Mode v2. Dacă refuzați cookie-urile analitice, GA4 se încarcă în continuare, dar trimite doar semnale anonimizate fără cookie-uri. Google folosește modelarea statistică pentru a estima tendințele de trafic fără a vă identifica personal. Niciun cookie analitic nu este plasat fără consimțământul dvs. explicit. Temei juridic: Art. 6(1)(a) GDPR - consimțământul dvs.",
        "ru": "Помогают нам понять, как посетители используют Nevumo - какие страницы посещаются, как долго пользователи остаются и откуда они приходят. Мы используем Google Analytics 4 (GA4) с Advanced Consent Mode v2. Если вы отказываетесь от аналитических cookies, GA4 всё равно загружается, но отправляет только анонимизированные сигналы без cookies. Google использует статистическое моделирование для оценки тенденций трафика без личной идентификации. Без вашего явного согласия аналитические cookies не устанавливаются. Правовая основа: Ст. 6(1)(a) GDPR - ваше согласие.",
        "sk": "Pomáhajú nám pochopiť, ako návštevníci používajú Nevumo - ktoré stránky sú navštevované, ako dlho používatelia zostávajú a odkiaľ prichádzajú. Používame Google Analytics 4 (GA4) s Advanced Consent Mode v2. Ak odmietnete analytické cookies, GA4 sa stále načíta, ale odosiela iba anonymizované signály bez cookies. Google využíva štatistické modelovanie na odhadovanie trendov prevádzky bez osobnej identifikácie. Žiadne analytické cookies sa neumiesťňujú bez vášho výslovného súhlasu. Právny základ: Čl. 6(1)(a) GDPR - váš súhlas.",
        "sl": "Pomagajo nam razumeti, kako obiskovalci uporabljajo Nevumo - katere strani so obiskane, kako dolgo ostajajo uporabniki in od kod prihajajo. Uporabljamo Google Analytics 4 (GA4) z Advanced Consent Mode v2. Če zavrnete analitične piškotke, se GA4 vseeno naloži, a pošilja samo anonimne signale brez piškotkov. Google uporablja statistično modeliranje za ocenjevanje prometnih trendov brez osebne identifikacije. Brez vašega izrecnega soglasja se ne postavljajo nobeni analitični piškotki. Pravna podlaga: čl. 6(1)(a) GDPR - vaše soglasje.",
        "sq": "Na ndihmojnë të kuptojmë si vizitorët përdorin Nevumo - cilat faqe vizitohen, sa kohë qëndrojnë përdoruesit dhe nga vijnë. Përdorim Google Analytics 4 (GA4) me Advanced Consent Mode v2. Nëse refuzoni cookies analitike, GA4 ngarkojnë gjithsesi por dërgon vetëm sinjale anonime pa cookies. Google përdor modelimin statistikor për të vlerësuar tendencat e trafikut pa ju identifikuar personalisht. Asnjë cookie analitike nuk vendoset pa pëlqimin tuaj eksplicit. Baza ligjore: Neni 6(1)(a) GDPR - pëlqimi juaj.",
        "sr": "Помажу нам да разумемо како посетиоци користе Nevumo - које странице се посећују, колико дуго корисници остају и одакле долазе. Користимо Google Analytics 4 (GA4) са Advanced Consent Mode v2. Ако одбијете аналитичке колачиће, GA4 се ипак учитава, али шаље само анонимизоване сигнале без колачића. Google користи статистичко моделовање за процену трендова саобраћаја без личне идентификације. Ниједан аналитички колачић се не поставља без вашег изричитог пристанка. Правни основ: чл. 6(1)(а) GDPR - ваш пристанак.",
        "sv": "Hjälper oss förstå hur besökare använder Nevumo - vilka sidor som besöks, hur länge användare stannar och varifrån de kommer. Vi använder Google Analytics 4 (GA4) med Advanced Consent Mode v2. Om du avvisar analytiska cookies laddas GA4 ändå men skickar bara anonymiserade, cookielösa signaler. Google använder statistisk modellering för att uppskatta trafiktrender utan att identifiera dig personligen. Inga analytiska cookies placeras utan ditt uttryckliga samtycke. Rättslig grund: Art. 6(1)(a) GDPR - ditt samtycke.",
        "tr": "Ziyaretçilerin Nevumo'yu nasıl kullandığını anlamamıza yardımcı olur - hangi sayfaların ziyaret edildiği, kullanıcıların ne kadar kaldığı ve nereden geldikleri. Advanced Consent Mode v2 ile Google Analytics 4 (GA4) kullanıyoruz. Analitik çerezleri reddederseniz GA4 yine de yüklenir, ancak yalnızca anonimleştirilmiş, çerez içermeyen sinyaller gönderir. Google, sizi kişisel olarak tanımlamadan trafik eğilimlerini tahmin etmek için istatistiksel modelleme kullanır. Açık rızanız olmadan analitik çerez yerleştirilmez. Hukuki dayanak: GDPR Madde 6(1)(a) - rızanız.",
        "uk": "Допомагають нам зрозуміти, як відвідувачі використовують Nevumo - які сторінки відвідуються, скільки часу залишаються користувачі та звідки вони приходять. Ми використовуємо Google Analytics 4 (GA4) з Advanced Consent Mode v2. Якщо ви відмовляєтесь від аналітичних файлів cookie, GA4 все одно завантажується, але надсилає лише анонімізовані сигнали без cookie. Google використовує статистичне моделювання для оцінки тенденцій трафіку без особистої ідентифікації. Без вашої явної згоди аналітичні cookie не встановлюються. Правова основа: Ст. 6(1)(a) GDPR - ваша згода.",
    },
    "cookies.s3_4_text": {
        "en": "Currently, Nevumo does not use marketing or advertising cookies. This category is reserved for future features (e.g., retargeting). No marketing cookies are set at this time. Legal basis (when used): Art. 6(1)(a) GDPR - your consent.",
        "bg": "В момента Nevumo не използва маркетингови или рекламни бисквитки. Тази категория е запазена за бъдещи функции (напр. ремаркетинг). В момента не се поставят маркетингови бисквитки. Правно основание (при използване): Чл. 6, ал. 1, б. а) GDPR - вашето съгласие.",
        "cs": "V současné době Nevumo nepoužívá marketingové ani reklamní soubory cookie. Tato kategorie je vyhrazena pro budoucí funkce (např. remarketing). V tuto chvíli nejsou nastaveny žádné marketingové soubory cookie. Právní základ (při použití): Čl. 6(1)(a) GDPR - váš souhlas.",
        "da": "I øjeblikket bruger Nevumo ikke marketing- eller reklamecookies. Denne kategori er forbeholdt fremtidige funktioner (f.eks. retargeting). Der er i øjeblikket ingen marketingcookies sat. Retsgrundlag (når det bruges): Art. 6(1)(a) GDPR - dit samtykke.",
        "de": "Derzeit verwendet Nevumo keine Marketing- oder Werbe-Cookies. Diese Kategorie ist für zukünftige Funktionen vorbehalten (z. B. Retargeting). Derzeit werden keine Marketing-Cookies gesetzt. Rechtsgrundlage (bei Verwendung): Art. 6(1)(a) DSGVO - Ihre Einwilligung.",
        "el": "Επί του παρόντος, η Nevumo δεν χρησιμοποιεί cookies μάρκετινγκ ή διαφήμισης. Αυτή η κατηγορία προορίζεται για μελλοντικές λειτουργίες (π.χ. επαναστόχευση). Αυτή τη στιγμή δεν τοποθετούνται cookies μάρκετινγκ. Νομική βάση (όταν χρησιμοποιείται): Άρθρο 6(1)(α) GDPR - η συγκατάθεσή σας.",
        "es": "Actualmente, Nevumo no utiliza cookies de marketing o publicidad. Esta categoría está reservada para funciones futuras (p. ej., retargeting). Actualmente no hay cookies de marketing configuradas. Base jurídica (cuando se usen): Art. 6(1)(a) RGPD - su consentimiento.",
        "et": "Praegu ei kasuta Nevumo turundus- ega reklaamiküpsiseid. See kategooria on reserveeritud tulevasteks funktsioonideks (nt ümbersuunamine). Praegu ei ole ühtegi turundusküpsist seadistatud. Õiguslik alus (kasutamisel): Art. 6(1)(a) GDPR - teie nõusolek.",
        "fi": "Tällä hetkellä Nevumo ei käytä markkinointi- tai mainosevästeitä. Tämä kategoria on varattu tuleville ominaisuuksille (esim. uudelleenkohdistaminen). Tällä hetkellä markkinointieva steita ei ole asetettu. Oikeusperuste (käytettäessä): Art. 6(1)(a) GDPR - suostumuksesi.",
        "fr": "Actuellement, Nevumo n'utilise pas de cookies de marketing ou de publicité. Cette catégorie est réservée pour de futures fonctionnalités (p. ex. le reciblage). Aucun cookie marketing n'est actuellement défini. Base juridique (lorsqu'utilisés) : Art. 6(1)(a) RGPD - votre consentement.",
        "ga": "Faoi láthair, ní úsáideann Nevumo fianáin margaíochta ná fógraíochta. Tá an chatagóir seo curtha i leataobh le haghaidh gnéithe amach anseo (m.sh. athdhíriú). Níl aon fianáin margaíochta socraithe faoi láthair. Bunús dlí (nuair a úsáidtear): Alt 6(1)(a) GDPR - do thoiliú.",
        "hr": "Trenutno Nevumo ne koristi marketinške ili oglašivačke kolačiće. Ova kategorija je rezervirana za buduće značajke (npr. retargeting). Trenutno nisu postavljeni nikakvi marketinški kolačići. Pravna osnova (kada se koristi): čl. 6(1)(a) GDPR - vaš pristanak.",
        "hu": "Jelenleg a Nevumo nem használ marketing vagy hirdetési sütiket. Ez a kategória jövőbeli funkciókra van fenntartva (pl. remarketing). Jelenleg nincsenek marketing sütik beállítva. Jogalap (használatkor): 6. cikk (1) bek. a) pont GDPR - az Ön hozzájárulása.",
        "is": "Eins og er notar Nevumo ekki markaðssetningar- eða auglýsingavafrakökur. Þessi flokkur er frátekinn fyrir framtíðareiginleika (t.d. endurmiðun). Engar markaðssetningarvafrakökur eru stilltar eins og er. Lagagrundvöllur (þegar notaður): Gr. 6(1)(a) GDPR - þitt samþykki.",
        "it": "Attualmente, Nevumo non utilizza cookie di marketing o pubblicitari. Questa categoria è riservata per funzionalità future (es. retargeting). Al momento non sono impostati cookie di marketing. Base giuridica (quando utilizzati): Art. 6(1)(a) GDPR - il tuo consenso.",
        "lb": "Aktuell benotzt Nevumo keng Marketing- oder Reklamecookies. Dës Kategorie ass fir zukünfteg Funktiounen reservéiert (z.B. Retargeting). Aktuell gi keng Marketing-Cookies gesat. Rechtlech Basis (wann benotzt): Art. 6(1)(a) DSGVO - Ären Consent.",
        "lt": "Šiuo metu Nevumo nenaudoja rinkodaros ar reklaminių slapukų. Ši kategorija skirta būsimiems funkcionalumams (pvz., pakartotinei rinkodarai). Šiuo metu nenustatyti jokie rinkodaros slapukai. Teisinis pagrindas (naudojant): BDAR 6 str. 1 d. a p. - jūsų sutikimas.",
        "lv": "Pašlaik Nevumo neizmanto mārketinga vai reklāmas sīkdatnes. Šī kategorija ir rezervēta nākotnei paredzētajam (piem., atkārtotai mērķēšanai). Pašlaik nav iestatītas nekādas mārketinga sīkdatnes. Juridiskais pamats (lietojot): VDAR 6. panta 1. punkta a) apakšpunkts - jūsu piekrišana.",
        "mk": "Во моментов, Nevumo не користи маркетиншки или рекламни колачиња. Оваа категорија е резервирана за идни функции (напр. ретаргетирање). Во моментов не се поставени маркетиншки колачиња. Правна основа (при употреба): чл. 6(1)(а) GDPR - вашата согласност.",
        "mt": "Bħalissa, Nevumo ma tuża l-ebda cookies ta' marketing jew reklamar. Din il-kategorija hija riżervata għal karatteristiċi futuri (eż. retargeting). Bħalissa ma jitqiegħdu l-ebda cookies ta' marketing. Bażi legali (meta jintuża): Art. 6(1)(a) GDPR - il-kunsens tiegħek.",
        "nl": "Momenteel gebruikt Nevumo geen marketing- of advertentiecookies. Deze categorie is gereserveerd voor toekomstige functies (bijv. retargeting). Er zijn momenteel geen marketingcookies ingesteld. Rechtsgrondslag (bij gebruik): Art. 6(1)(a) AVG - uw toestemming.",
        "no": "For øyeblikket bruker Nevumo ingen markedsførings- eller reklameinformasjonskapsler. Denne kategorien er reservert for fremtidige funksjoner (f.eks. retargeting). Det er for øyeblikket ingen markedsføringsinformasjonskapsler angitt. Rettsgrunnlag (ved bruk): Art. 6(1)(a) GDPR - ditt samtykke.",
        "pl": "Obecnie Nevumo nie używa plików cookie marketingowych ani reklamowych. Ta kategoria jest zarezerwowana na przyszłe funkcje (np. retargeting). Obecnie nie są ustawione żadne marketingowe pliki cookie. Podstawa prawna (gdy używane): Art. 6(1)(a) RODO - Twoja zgoda.",
        "pt": "Atualmente, a Nevumo não usa cookies de marketing ou publicidade. Esta categoria está reservada para funcionalidades futuras (ex. retargeting). Nenhum cookie de marketing está configurado no momento. Base jurídica (quando utilizado): Art. 6(1)(a) RGPD - seu consentimento.",
        "pt-PT": "Atualmente, a Nevumo não utiliza cookies de marketing ou publicidade. Esta categoria está reservada para funcionalidades futuras (ex. retargeting). Não estão configurados cookies de marketing neste momento. Base jurídica (quando utilizados): Art. 6(1)(a) RGPD - o seu consentimento.",
        "ro": "În prezent, Nevumo nu folosește cookie-uri de marketing sau publicitate. Această categorie este rezervată pentru funcționalități viitoare (de ex., retargeting). În prezent nu sunt configurate cookie-uri de marketing. Temei juridic (când sunt utilizate): Art. 6(1)(a) GDPR - consimțământul dvs.",
        "ru": "В настоящее время Nevumo не использует маркетинговые или рекламные cookies. Эта категория зарезервирована для будущих функций (например, ретаргетинга). В настоящее время маркетинговые cookies не установлены. Правовая основа (при использовании): Ст. 6(1)(a) GDPR - ваше согласие.",
        "sk": "V súčasnosti Nevumo nepoužíva marketingové ani reklamné cookies. Táto kategória je vyhradená pre budúce funkcie (napr. retargeting). V súčasnosti nie sú nastavené žiadne marketingové cookies. Právny základ (pri použití): Čl. 6(1)(a) GDPR - váš súhlas.",
        "sl": "Trenutno Nevumo ne uporablja marketinških ali oglaševalskih piškotkov. Ta kategorija je rezervirana za prihodnje funkcije (npr. ponovni marketing). Trenutno ni nastavljenih marketinških piškotkov. Pravna podlaga (pri uporabi): čl. 6(1)(a) GDPR - vaše soglasje.",
        "sq": "Aktualisht, Nevumo nuk përdor cookies marketingu apo reklamuese. Kjo kategori është rezervuar për veçori të ardhshme (p.sh. retargeting). Aktualisht nuk janë vendosur cookies marketingu. Baza ligjore (kur përdoret): Neni 6(1)(a) GDPR - pëlqimi juaj.",
        "sr": "Тренутно, Nevumo не користи маркетиншке или рекламне колачиће. Ова категорија је резервисана за будуће функције (нпр. ретаргетинг). Тренутно нису постављени никакви маркетиншки колачићи. Правни основ (при употреби): чл. 6(1)(а) GDPR - ваш пристанак.",
        "sv": "För närvarande använder Nevumo inga marknadsförings- eller reklamcookies. Denna kategori är reserverad för framtida funktioner (t.ex. återmarknadsföring). Inga marknadsföringscookies är inställda för tillfället. Rättslig grund (vid användning): Art. 6(1)(a) GDPR - ditt samtycke.",
        "tr": "Şu anda Nevumo, pazarlama veya reklam çerezleri kullanmamaktadır. Bu kategori gelecekteki özellikler için ayrılmıştır (örn. yeniden hedefleme). Şu anda pazarlama çerezi ayarlanmamıştır. Hukuki dayanak (kullanıldığında): GDPR Madde 6(1)(a) - rızanız.",
        "uk": "Наразі Nevumo не використовує маркетингові або рекламні файли cookie. Ця категорія зарезервована для майбутніх функцій (наприклад, ретаргетингу). Наразі маркетингові файли cookie не встановлені. Правова основа (при використанні): Ст. 6(1)(a) GDPR - ваша згода.",
    },
}


def seed():
    with engine.begin() as conn:
        for key, translations in TRANSLATIONS.items():
            for lang, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (key, lang, value)
                        VALUES (:key, :lang, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"key": key, "lang": lang, "value": value},
                )
    print(f"Seeded {len(TRANSLATIONS)} keys x 34 languages")


if __name__ == "__main__":
    seed()