#!/usr/bin/env python3
"""
Seed contact DSA translations.
Namespace: contact_dsa
Keys: 16 | Languages: 34
Run: docker exec nevumo-api python -m apps.api.scripts.seed_contact_dsa_p1
"""

import os

from sqlalchemy import create_engine, text

NAMESPACE = "contact_dsa"

# Language dictionaries with full keys (including namespace)
TRANSLATIONS_BY_LANG = {
    "en": {
        "contact_dsa.page_title": "DSA Contact Point",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "About This Page",
        "contact_dsa.s1_body": "Nevumo is operated by \"ФИЛИПС ЦЕНТЬР БЪЛГАРИЯ\" ООД (EIK: 175369610), registered in Sofia, Bulgaria. This page serves as our single point of contact under Article 11 of the Digital Services Act (Regulation (EU) 2022/2065), applicable from 17 February 2024.",
        "contact_dsa.s2_title": "Single Point of Contact",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacy & GDPR matters:",
        "contact_dsa.s2_email_legal": "Illegal content reports & law enforcement:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "bg": {
        "contact_dsa.page_title": "Точка за контакт по DSA",
        "contact_dsa.meta_description": "Точка за контакт с власти и потребители по Закона за цифровите услуги (DSA). Сигнализирайте за незаконно съдържание или се свържете с Nevumo.",
        "contact_dsa.s1_title": "За тази страница",
        "contact_dsa.s1_body": "Nevumo се управлява от \"ФИЛИПС ЦЕНТЬР БЪЛГАРИЯ\" ООД (ЕИК: 175369610), регистрирано в София, България. Тази страница представлява нашата единна точка за контакт съгласно чл. 11 от Закона за цифровите услуги (Регламент (ЕС) 2022/2065), приложим от 17 февруари 2024 г.",
        "contact_dsa.s2_title": "Единна точка за контакт",
        "contact_dsa.s2_body": "Всички комуникации, свързани с DSA — включително сигнали за незаконно съдържание, запитвания от правоохранителни органи и компетентни власти — следва да бъдат изпращани на:",
        "contact_dsa.s2_email_privacy": "Въпроси за поверителност и GDPR:",
        "contact_dsa.s2_email_legal": "Сигнали за незаконно съдържание и запитвания от власти:",
        "contact_dsa.s3_title": "Сигнализиране за незаконно съдържание",
        "contact_dsa.s3_body": "Ако смятате, че съдържанието в Nevumo е незаконно, можете да го сигнализирате чрез нашата единна точка за контакт. Ние ще прегледаме сигналите и ще предприемем съответни действия съгласно DSA.",
        "contact_dsa.s3_what_to_include_title": "Какво да включите в сигнала",
        "contact_dsa.s3_what_to_include_body": "Ясно описание на съдържанието, което смятате за незаконно\nТочния URL или местоположение на съдържанието\nВашата контактна информация за обратна връзка\nПравното основание за твърдението ви (ако е известно)",
        "contact_dsa.s4_title": "Срокове за отговор",
        "contact_dsa.s4_body": "• Потвърждаваме получаването на сигналите в рамките на 48 часа\n• Преглеждаме сигналите и предприемаме действия в рамките на 7 дни\n• За сложни случаи може да се наложи допълнително време\n• Предоставяме решение с обосновка",
        "contact_dsa.s5_title": "Контактна информация",
        "contact_dsa.s5_body": "За всякакви въпроси, свързани с DSA, моля използвайте имейл адресите, посочени по-горе. Нашият екип е на разположение да помогне на властите и потребителите по въпроси, свързани със Закона за цифровите услуги.",
        "contact_dsa.back_to_home": "Назад към началото",
    },
    "cs": {
        "contact_dsa.page_title": "Kontaktní místo DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "O této stránce",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Jednotné kontaktní místo",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Ochrana soukromí a GDPR:",
        "contact_dsa.s2_email_legal": "Hlášení nelegálního obsahu a orgány:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "da": {
        "contact_dsa.page_title": "DSA-kontaktpunkt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Om denne side",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Enkelt kontaktpunkt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatlivs- og GDPR-spørgsmål:",
        "contact_dsa.s2_email_legal": "Rapportering af ulovligt indhold og myndigheder:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "de": {
        "contact_dsa.page_title": "DSA-Kontaktstelle",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Über diese Seite",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Einheitliche Kontaktstelle",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Datenschutz & DSGVO:",
        "contact_dsa.s2_email_legal": "Meldungen rechtswidriger Inhalte & Behördenanfragen:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "el": {
        "contact_dsa.page_title": "Σημείο επαφής DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Σχετικά με αυτή τη σελίδα",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Ενιαίο σημείο επαφής",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Θέματα απορρήτου & GDPR:",
        "contact_dsa.s2_email_legal": "Αναφορές παράνομου περιεχομένου & αρχές:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "es": {
        "contact_dsa.page_title": "Punto de contacto DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Acerca de esta página",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Punto único de contacto",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacidad y RGPD:",
        "contact_dsa.s2_email_legal": "Informes de contenido ilegal y autoridades:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "et": {
        "contact_dsa.page_title": "DSA kontaktpunkt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Sellest lehest",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Ühtne kontaktpunkt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privaatsus ja GDPR:",
        "contact_dsa.s2_email_legal": "Ebaseadusliku sisu teatised ja õiguskaitse:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "fi": {
        "contact_dsa.page_title": "DSA-yhteystaho",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Tietoja tästä sivusta",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Yhteinen yhteystaho",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Tietosuoja ja GDPR:",
        "contact_dsa.s2_email_legal": "Laittoman sisällön ilmoitukset ja viranomaiset:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "fr": {
        "contact_dsa.page_title": "Point de contact DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "À propos de cette page",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Point de contact unique",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Confidentialité et RGPD :",
        "contact_dsa.s2_email_legal": "Signalements de contenus illicites et autorités :",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "ga": {
        "contact_dsa.page_title": "Pointe Teagmhála DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Maidir leis an Leathanach Seo",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Pointe Aonair Teagmhála",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Príobháideacht & GDPR:",
        "contact_dsa.s2_email_legal": "Tuairiscí ábhair neamhdhleathach & forfheidhmiú dlí:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "hr": {
        "contact_dsa.page_title": "DSA kontaktna točka",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "O ovoj stranici",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Jedinstvena kontaktna točka",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatnost i GDPR:",
        "contact_dsa.s2_email_legal": "Prijave nezakonitog sadržaja i tijela kaznenog progona:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "hu": {
        "contact_dsa.page_title": "DSA kapcsolattartási pont",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Az oldalról",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Egypontos kapcsolatfelvétel",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Adatvédelem és GDPR:",
        "contact_dsa.s2_email_legal": "Illegális tartalom bejelentése és hatóságok:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "is": {
        "contact_dsa.page_title": "DSA tengiliður",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Um þessa síðu",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Einn tengiliður",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Persónuvernd og GDPR:",
        "contact_dsa.s2_email_legal": "Tilkynningar um ólöglegt efni og löggæsla:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "it": {
        "contact_dsa.page_title": "Punto di contatto DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Informazioni su questa pagina",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Punto di contatto unico",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacy e GDPR:",
        "contact_dsa.s2_email_legal": "Segnalazioni di contenuti illegali e autorità:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "lb": {
        "contact_dsa.page_title": "DSA Kontaktpunkt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Iwwer dës Säit",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Eenzegen Kontaktpunkt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Dateschutz & GDPR:",
        "contact_dsa.s2_email_legal": "Meldunge vun illegalen Inhalter & Behörden:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "lt": {
        "contact_dsa.page_title": "DSA kontaktinis punktas",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Apie šį puslapį",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Vienintelis kontaktinis punktas",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatumas ir BDAR:",
        "contact_dsa.s2_email_legal": "Pranešimai apie neteisėtą turinį ir teisėsauga:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "lv": {
        "contact_dsa.page_title": "DSA kontaktpunkts",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Par šo lapu",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Vienots kontaktpunkts",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privātums un GDPR:",
        "contact_dsa.s2_email_legal": "Nelikumīga satura ziņojumi un iestādes:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "mk": {
        "contact_dsa.page_title": "DSA контактна точка",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "За оваа страница",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Единствена контактна точка",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Приватност и GDPR:",
        "contact_dsa.s2_email_legal": "Пријави за незаконита содржина и органи:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "mt": {
        "contact_dsa.page_title": "Punt ta' kuntatt DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Dwar din il-Paġna",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Punt ta' kuntatt uniku",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatezza u GDPR:",
        "contact_dsa.s2_email_legal": "Rapporti ta' kontenut illegali u awtoritajiet:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "nl": {
        "contact_dsa.page_title": "DSA-contactpunt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Over deze pagina",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Enkel contactpunt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacy & AVG:",
        "contact_dsa.s2_email_legal": "Meldingen illegale inhoud en autoriteiten:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "no": {
        "contact_dsa.page_title": "DSA-kontaktpunkt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Om denne siden",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Enkelt kontaktpunkt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Personvern og GDPR:",
        "contact_dsa.s2_email_legal": "Rapporter om ulovlig innhold og myndigheter:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "pl": {
        "contact_dsa.page_title": "Punkt kontaktowy DSA",
        "contact_dsa.meta_description": "Punkt kontaktowy dla organów i użytkowników zgodnie z Aktem o usługach cyfrowych (DSA). Zgłoś nielegalne treści lub skontaktuj się z Nevumo.",
        "contact_dsa.s1_title": "O tej stronie",
        "contact_dsa.s1_body": "Nevumo jest obsługiwane przez \"ФИЛИПС ЦЕНТЬР БЪЛГАРИЯ\" ООД (EIK: 175369610), zarejestrowaną w Sofii, w Bułgarii. Niniejsza strona stanowi nasz pojedynczy punkt kontaktowy zgodnie z art. 11 Aktu o usługach cyfrowych (Rozporządzenie (UE) 2022/2065), stosowanego od 17 lutego 2024 r.",
        "contact_dsa.s2_title": "Pojedynczy punkt kontaktowy",
        "contact_dsa.s2_body": "Wszelka komunikacja związana z DSA — w tym zgłoszenia nielegalnych treści, wnioski organów ścigania oraz zapytania właściwych organów — powinna być kierowana na adres:",
        "contact_dsa.s2_email_privacy": "Prywatność i RODO:",
        "contact_dsa.s2_email_legal": "Zgłoszenia nielegalnych treści i organy ścigania:",
        "contact_dsa.s3_title": "Zgłaszanie nielegalnych treści",
        "contact_dsa.s3_body": "Jeśli uważasz, że treści w Nevumo są nielegalne, możesz je zgłosić za pośrednictwem naszego pojedynczego punktu kontaktowego. Przeanalizujemy zgłoszenia i podejmiemy odpowiednie działania zgodnie z DSA.",
        "contact_dsa.s3_what_to_include_title": "Co uwzględnić w zgłoszeniu",
        "contact_dsa.s3_what_to_include_body": "Jasny opis treści, które uważasz za nielegalne\nDokładny adres URL lub lokalizację treści\nTwoje dane kontaktowe w celu dalszego kontaktu\nPodstawę prawną Twojego roszczenia (jeśli jest znana)",
        "contact_dsa.s4_title": "Czasy odpowiedzi",
        "contact_dsa.s4_body": "• Potwierdzamy otrzymanie zgłoszeń w ciągu 48 godzin\n• Analizujemy zgłoszenia i podejmujemy działania w ciągu 7 dni\n• W złożonych przypadkach może być wymagany dodatkowy czas\n• Przedstawiamy decyzję z uzasadnieniem",
        "contact_dsa.s5_title": "Informacje kontaktowe",
        "contact_dsa.s5_body": "W przypadku jakichkolwiek pytań związanych z DSA prosimy o korzystanie z adresów e-mail wymienionych powyżej. Nasz zespół jest dostępny, aby pomóc organom i użytkownikom w sprawach związanych z Aktem o usługach cyfrowych.",
        "contact_dsa.back_to_home": "Powrót do strony głównej",
    },
    "pt": {
        "contact_dsa.page_title": "Ponto de Contato DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Sobre Esta Página",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Ponto Único de Contato",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacidade e GDPR:",
        "contact_dsa.s2_email_legal": "Relatórios de conteúdo ilegal e autoridades:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "pt_PT": {
        "contact_dsa.page_title": "Ponto de Contacto DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Sobre Esta Página",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Ponto Único de Contacto",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privacidade e RGPD:",
        "contact_dsa.s2_email_legal": "Relatórios de conteúdo ilegal e autoridades:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "ro": {
        "contact_dsa.page_title": "Punct de contact DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Despre această pagină",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Punct unic de contact",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Confidențialitate și GDPR:",
        "contact_dsa.s2_email_legal": "Raportări de conținut ilegal și autorități:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "ru": {
        "contact_dsa.page_title": "Контактная точка DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Об этой странице",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Единая контактная точка",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Конфиденциальность и GDPR:",
        "contact_dsa.s2_email_legal": "Сообщения о незаконном контенте и органы:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "sk": {
        "contact_dsa.page_title": "Kontaktné miesto DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "O tejto stránke",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Jediné kontaktné miesto",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Ochrana súkromia a GDPR:",
        "contact_dsa.s2_email_legal": "Hlásenia nelegálneho obsahu a orgány:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "sl": {
        "contact_dsa.page_title": "Kontaktna točka DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "O tej strani",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Enotna kontaktna točka",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Zasebnost in GDPR:",
        "contact_dsa.s2_email_legal": "Prijave nezakonite vsebine in organi:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "sq": {
        "contact_dsa.page_title": "Pika e kontaktit DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Rreth kësaj faqeje",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Pika e vetme e kontaktit",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatësia dhe GDPR:",
        "contact_dsa.s2_email_legal": "Raportet e përmbajtjes ilegale dhe autoritetet:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "sr": {
        "contact_dsa.page_title": "DSA kontaktna tačka",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "O ovoj stranici",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Jedinstvena kontaktna tačka",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Privatnost i GDPR:",
        "contact_dsa.s2_email_legal": "Prijave nezakonitog sadržaja i organi:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "sv": {
        "contact_dsa.page_title": "DSA-kontaktpunkt",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Om den här sidan",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Enda kontaktpunkt",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Integritet och GDPR:",
        "contact_dsa.s2_email_legal": "Rapporter om olagligt innehåll och myndigheter:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "tr": {
        "contact_dsa.page_title": "DSA İletişim Noktası",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Bu Sayfa Hakkında",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Tek İletişim Noktası",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Gizlilik ve GDPR:",
        "contact_dsa.s2_email_legal": "Yasadışı içerik bildirimleri ve yetkililer:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
    "uk": {
        "contact_dsa.page_title": "Контактна точка DSA",
        "contact_dsa.meta_description": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s1_title": "Про цю сторінку",
        "contact_dsa.s1_body": "Contact point for authorities and users under the Digital Services Act (DSA). Report illegal content or contact Nevumo for DSA-related matters.",
        "contact_dsa.s2_title": "Єдина контактна точка",
        "contact_dsa.s2_body": "All DSA-related communications — including reports of illegal content, law enforcement requests, and authority enquiries — should be directed to:",
        "contact_dsa.s2_email_privacy": "Конфіденційність і GDPR:",
        "contact_dsa.s2_email_legal": "Повідомлення про незаконний вміст та органи:",
        "contact_dsa.s3_title": "Reporting Illegal Content",
        "contact_dsa.s3_body": "If you believe that content on Nevumo is illegal, you may report it through our single point of contact. We will assess reports and take appropriate action in accordance with the DSA.",
        "contact_dsa.s3_what_to_include_title": "What to Include in Your Report",
        "contact_dsa.s3_what_to_include_body": "A clear description of the content you believe is illegal\nThe exact URL or location of the content\nYour contact information for follow-up\nThe legal basis for your claim (if known)",
        "contact_dsa.s4_title": "Response Times",
        "contact_dsa.s4_body": "• We acknowledge receipt of reports within 48 hours\n• We assess reports and take action within 7 days\n• For complex cases, we may require additional time\n• We provide a decision with reasoning",
        "contact_dsa.s5_title": "Contact Information",
        "contact_dsa.s5_body": "For any DSA-related inquiries, please use the email addresses listed above. Our team is available to assist authorities and users with matters related to the Digital Services Act.",
        "contact_dsa.back_to_home": "Back to home",
    },
}


def get_database_url() -> str:
    """Get database URL from environment or use default."""
    return os.getenv("DATABASE_URL", "postgresql://nevumo:nevumo@localhost:5432/nevumo_leads")


def seed_translations() -> None:
    """Seed all contact DSA translations into the database."""
    engine = create_engine(get_database_url())

    with engine.connect() as conn:
        count = 0
        for lang, translations in TRANSLATIONS_BY_LANG.items():
            for key, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (lang, key, value)
                        VALUES (:lang, :key, :value)
                        ON CONFLICT (lang, key)
                        DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"lang": lang, "key": key, "value": value}
                )
                count += 1

        conn.commit()
        print(f"Inserted/updated {count} translation rows for namespace '{NAMESPACE}'")


def verify_translations() -> None:
    """Verify the translations were inserted correctly."""
    engine = create_engine(get_database_url())

    with engine.connect() as conn:
        result = conn.execute(
            text("""
                SELECT lang, COUNT(*) as keys
                FROM translations
                WHERE key LIKE :pattern
                GROUP BY lang
                ORDER BY lang
            """),
            {"pattern": f"{NAMESPACE}.%"}
        )
        rows = result.fetchall()
        print(f"\nVerification for namespace '{NAMESPACE}':")
        for row in rows:
            print(f"  {row[0]}: {row[1]} keys")


if __name__ == "__main__":
    seed_translations()
    verify_translations()
