# -*- coding: utf-8 -*-
"""
seed_cookies_p11.py — namespace 'cookies', keys 1-5
cookies.page_title, cookies.effective_date, cookies.s1_title,
cookies.s2_title, cookies.s3_title
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p11
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL")
engine = create_engine(DATABASE_URL)

TRANSLATIONS = {
    "cookies.page_title": {
        "en": "Cookie Policy",
        "bg": "Политика за бисквитки",
        "cs": "Zásady cookies",
        "da": "Cookiepolitik",
        "de": "Cookie-Richtlinie",
        "el": "Πολιτική Cookies",
        "es": "Política de cookies",
        "et": "Küpsiste poliitika",
        "fi": "Evästekäytäntö",
        "fr": "Politique des cookies",
        "ga": "Polasaí Fianán",
        "hr": "Pravila o kolačićima",
        "hu": "Sütikezelési szabályzat",
        "is": "Vafrakökustefna",
        "it": "Politica sui cookie",
        "lb": "Cookie-Politik",
        "lt": "Slapukų politika",
        "lv": "Sīkdatņu politika",
        "mk": "Политика за колачиња",
        "mt": "Politika tal-Cookies",
        "nl": "Cookiebeleid",
        "no": "Informasjonskapselpolicy",
        "pl": "Polityka plików cookie",
        "pt": "Política de Cookies",
        "pt-PT": "Política de Cookies",
        "ro": "Politica privind cookie-urile",
        "ru": "Политика использования cookies",
        "sk": "Zásady cookies",
        "sl": "Politika piškotkov",
        "sq": "Politika e Cookies",
        "sr": "Политика колачића",
        "sv": "Cookiepolicy",
        "tr": "Çerez Politikası",
        "uk": "Політика використання файлів cookie",
    },
    "cookies.effective_date": {
        "en": "Effective date: 1 May 2026 | Version: 2.0",
        "bg": "Дата на влизане в сила: 1 май 2026 г. | Версия: 2.0",
        "cs": "Datum účinnosti: 1. května 2026 | Verze: 2.0",
        "da": "Ikrafttrædelsesdato: 1. maj 2026 | Version: 2.0",
        "de": "Datum des Inkrafttretens: 1. Mai 2026 | Version: 2.0",
        "el": "Ημερομηνία ισχύος: 1 Μαΐου 2026 | Έκδοση: 2.0",
        "es": "Fecha de entrada en vigor: 1 de mayo de 2026 | Versión: 2.0",
        "et": "Jõustumiskuupäev: 1. mai 2026 | Versioon: 2.0",
        "fi": "Voimaantulopäivä: 1. toukokuuta 2026 | Versio: 2.0",
        "fr": "Date d'entrée en vigueur : 1er mai 2026 | Version : 2.0",
        "ga": "Dáta éifeachtach: 1 Bealtaine 2026 | Leagan: 2.0",
        "hr": "Datum stupanja na snagu: 1. svibnja 2026. | Verzija: 2.0",
        "hu": "Hatályba lépés: 2026. május 1. | Verzió: 2.0",
        "is": "Gildistökudagur: 1. maí 2026 | Útgáfa: 2.0",
        "it": "Data di entrata in vigore: 1 maggio 2026 | Versione: 2.0",
        "lb": "Datum vum Inkraafttriede: 1. Mee 2026 | Versioun: 2.0",
        "lt": "Įsigaliojimo data: 2026 m. gegužės 1 d. | Versija: 2.0",
        "lv": "Spēkā stāšanās datums: 2026. gada 1. maijs | Versija: 2.0",
        "mk": "Датум на влегување во сила: 1 мај 2026 | Верзија: 2.0",
        "mt": "Data ta' dhul fis-sehh: 1 ta' Mejju 2026 | Verzjoni: 2.0",
        "nl": "Datum van inwerkingtreding: 1 mei 2026 | Versie: 2.0",
        "no": "Ikrafttredelsesdato: 1. mai 2026 | Versjon: 2.0",
        "pl": "Data wejścia w życie: 1 maja 2026 r. | Wersja: 2.0",
        "pt": "Data de entrada em vigor: 1 de maio de 2026 | Versão: 2.0",
        "pt-PT": "Data de entrada em vigor: 1 de maio de 2026 | Versão: 2.0",
        "ro": "Data intrării în vigoare: 1 mai 2026 | Versiunea: 2.0",
        "ru": "Дата вступления в силу: 1 мая 2026 г. | Версия: 2.0",
        "sk": "Dátum účinnosti: 1. mája 2026 | Verzia: 2.0",
        "sl": "Datum začetka veljavnosti: 1. maj 2026 | Različica: 2.0",
        "sq": "Data e hyrjes në fuqi: 1 maj 2026 | Versioni: 2.0",
        "sr": "Датум ступања на снагу: 1. мај 2026. | Верзија: 2.0",
        "sv": "Ikraftträdandedatum: 1 maj 2026 | Version: 2.0",
        "tr": "Yürürlük tarihi: 1 Mayıs 2026 | Sürüm: 2.0",
        "uk": "Дата набрання чинності: 1 травня 2026 р. | Версія: 2.0",
    },
    "cookies.s1_title": {
        "en": "What Are Cookies and Browser Storage?",
        "bg": "Какво представляват бисквитките и браузърното хранилище?",
        "cs": "Co jsou soubory cookie a úložiště prohlížeče?",
        "da": "Hvad er cookies og browserlagring?",
        "de": "Was sind Cookies und Browser-Speicher?",
        "el": "Τι είναι τα Cookies και η Αποθήκευση Προγράμματος Περιήγησης;",
        "es": "¿Qué son las cookies y el almacenamiento del navegador?",
        "et": "Mis on küpsised ja brauseri salvestusruum?",
        "fi": "Mitä ovat evästeet ja selaimen tallennustila?",
        "fr": "Que sont les cookies et le stockage du navigateur ?",
        "ga": "Cad is Fianáin agus Stóráil Brabhsálaí ann?",
        "hr": "Što su kolačići i pohrana preglednika?",
        "hu": "Mik a sütik és a böngésző tárhelye?",
        "is": "Hvað eru vafrakökur og vafrageymsla?",
        "it": "Cosa sono i cookie e l'archiviazione del browser?",
        "lb": "Was sinn Cookies a Browser-Späicher?",
        "lt": "Kas yra slapukai ir naršyklės saugykla?",
        "lv": "Kas ir sīkdatnes un pārlūkprogrammas krātuve?",
        "mk": "Што се колачиња и складирање во прелистувачот?",
        "mt": "X'inhuma l-Cookies u l-Hazna tal-Browser?",
        "nl": "Wat zijn cookies en browseropslag?",
        "no": "Hva er informasjonskapsler og nettleserlagring?",
        "pl": "Czym są pliki cookie i pamięć przeglądarki?",
        "pt": "O que são cookies e armazenamento do navegador?",
        "pt-PT": "O que são cookies e armazenamento do navegador?",
        "ro": "Ce sunt cookie-urile și stocarea în browser?",
        "ru": "Что такое файлы cookie и хранилище браузера?",
        "sk": "Čo sú súbory cookie a úložisko prehliadača?",
        "sl": "Kaj so piškotki in shranjevanje brskalnika?",
        "sq": "Çfarë janë cookies-at dhe ruajtja e shfletuesit?",
        "sr": "Шта су колачићи и складиштење прегледача?",
        "sv": "Vad är cookies och webbläsarlagring?",
        "tr": "Çerezler ve Tarayıcı Depolama Nedir?",
        "uk": "Що таке файли cookie та сховище браузера?",
    },
    "cookies.s2_title": {
        "en": "2. Who Uses These Technologies?",
        "bg": "2. Кой използва тези технологии?",
        "cs": "2. Kdo tyto technologie používá?",
        "da": "2. Hvem bruger disse teknologier?",
        "de": "2. Wer verwendet diese Technologien?",
        "el": "2. Ποιος χρησιμοποιεί αυτές τις τεχνολογίες;",
        "es": "2. ¿Quién utiliza estas tecnologías?",
        "et": "2. Kes neid tehnoloogiaid kasutab?",
        "fi": "2. Kuka käyttää näitä teknologioita?",
        "fr": "2. Qui utilise ces technologies ?",
        "ga": "2. Cé a Úsáideann na Teicneolaíochtaí Seo?",
        "hr": "2. Tko koristi ove tehnologije?",
        "hu": "2. Ki használja ezeket a technológiákat?",
        "is": "2. Hver notar þessar tækni?",
        "it": "2. Chi utilizza queste tecnologie?",
        "lb": "2. Wien benotzt dës Technologien?",
        "lt": "2. Kas naudoja šias technologijas?",
        "lv": "2. Kas izmanto šīs tehnoloģijas?",
        "mk": "2. Кој ги користи овие технологии?",
        "mt": "2. Min Juza Dawn it-Teknologiji?",
        "nl": "2. Wie gebruikt deze technologieën?",
        "no": "2. Hvem bruker disse teknologiene?",
        "pl": "2. Kto używa tych technologii?",
        "pt": "2. Quem usa essas tecnologias?",
        "pt-PT": "2. Quem utiliza estas tecnologias?",
        "ro": "2. Cine utilizează aceste tehnologii?",
        "ru": "2. Кто использует эти технологии?",
        "sk": "2. Kto používa tieto technológie?",
        "sl": "2. Kdo uporablja te tehnologije?",
        "sq": "2. Kush i përdor këto teknologji?",
        "sr": "2. Ко користи ове технологије?",
        "sv": "2. Vem använder dessa teknologier?",
        "tr": "2. Bu Teknolojileri Kim Kullanıyor?",
        "uk": "2. Хто використовує ці технології?",
    },
    "cookies.s3_title": {
        "en": "3. Categories of Cookies We Use",
        "bg": "3. Категории бисквитки, които използваме",
        "cs": "3. Kategorie souborů cookie, které používáme",
        "da": "3. Kategorier af cookies, vi bruger",
        "de": "3. Kategorien der von uns verwendeten Cookies",
        "el": "3. Κατηγορίες Cookies που Χρησιμοποιούμε",
        "es": "3. Categorías de cookies que utilizamos",
        "et": "3. Meie kasutatavate küpsiste kategooriad",
        "fi": "3. Käyttämiemme evästeiden kategoriat",
        "fr": "3. Catégories de cookies que nous utilisons",
        "ga": "3. Catagóirí Fianán a Úsáidimid",
        "hr": "3. Kategorije kolačića koje koristimo",
        "hu": "3. Az általunk használt sütik kategóriái",
        "is": "3. Flokkar vafrakaka sem við notum",
        "it": "3. Categorie di cookie che utilizziamo",
        "lb": "3. Kategorien vu Cookies, déi mir benotzen",
        "lt": "3. Mūsų naudojamų slapukų kategorijos",
        "lv": "3. Mūsu izmantoto sīkdatņu kategorijas",
        "mk": "3. Категории колачиња кои ги користиме",
        "mt": "3. Kategoriji ta' Cookies li Nuzaw",
        "nl": "3. Categorieën cookies die wij gebruiken",
        "no": "3. Kategorier av informasjonskapsler vi bruker",
        "pl": "3. Kategorie plików cookie, których używamy",
        "pt": "3. Categorias de cookies que usamos",
        "pt-PT": "3. Categorias de cookies que utilizamos",
        "ro": "3. Categoriile de cookie-uri pe care le folosim",
        "ru": "3. Категории используемых файлов cookie",
        "sk": "3. Kategórie súborov cookie, ktoré používame",
        "sl": "3. Kategorije piškotkov, ki jih uporabljamo",
        "sq": "3. Kategoritë e cookies-ave që përdorim",
        "sr": "3. Категорије колачића које користимо",
        "sv": "3. Kategorier av cookies vi använder",
        "tr": "3. Kullandığımız Çerez Kategorileri",
        "uk": "3. Категорії файлів cookie, які ми використовуємо",
    },
}


def seed():
    with engine.begin() as conn:
        for key, translations in TRANSLATIONS.items():
            for lang, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (key, lang, value)
                        VALUES (:key, :lang, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"key": key, "lang": lang, "value": value},
                )
    print(f"Seeded {len(TRANSLATIONS)} keys x 34 languages")


if __name__ == "__main__":
    seed()