#!/usr/bin/env python3
"""Seed claim namespace translations into the translations table."""

import os
import psycopg2
from psycopg2.extras import execute_values

# Database connection string
DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@localhost:5433/nevumo_leads")

# Translations: language -> dict of keys
TRANSLATIONS = {
    "bg": {"title": "Заяви профила си", "subtitle": "Тази фирма ваша ли е в Nevumo?", "description": "Заяви профила и започни да получаваш заявки от клиенти безплатно.", "cta_login": "Вход за да заявиш профила", "cta_register": "Вземи профила безплатно!", "cta_claim": "Заяви профила безплатно", "category_label": "Категория", "city_label": "Град", "not_found": "Профилът не е намерен или вече е взет.", "already_claimed": "Профилът вече е взет.", "success": "Профилът е ваш! Пренасочване към таблото...", "error": "Грешка. Опитайте отново."},
    "cs": {"title": "Převezměte svůj profil", "subtitle": "Je tato firma vaše na Nevumo?", "description": "Převezměte profil a začněte přijímat poptávky od klientů zdarma.", "cta_login": "Přihlaste se a převezměte profil", "cta_register": "Vezmi si profil zdarma!", "cta_claim": "Převzít profil zdarma", "category_label": "Kategorie", "city_label": "Město", "not_found": "Profil nebyl nalezen nebo byl již převzat.", "already_claimed": "Tento profil byl již převzat.", "success": "Profil je váš! Přesměrování na nástěnku...", "error": "Chyba. Zkuste to znovu."},
    "da": {"title": "Tag din profil", "subtitle": "Er denne virksomhed din på Nevumo?", "description": "Tag profilen og begynd at modtage kundeforespørgsler gratis.", "cta_login": "Log ind for at tage profilen", "cta_register": "Få profilen gratis!", "cta_claim": "Tag profilen gratis", "category_label": "Kategori", "city_label": "By", "not_found": "Profilen blev ikke fundet eller er allerede taget.", "already_claimed": "Denne profil er allerede taget.", "success": "Profilen er din! Omdirigerer til dit dashboard...", "error": "Der opstod en fejl. Prøv igen."},
    "de": {"title": "Profil übernehmen", "subtitle": "Gehört dieses Unternehmen Ihnen auf Nevumo?", "description": "Übernehmen Sie das Profil und erhalten Sie kostenlos Kundenanfragen.", "cta_login": "Anmelden, um das Profil zu übernehmen", "cta_register": "Profil kostenlos holen!", "cta_claim": "Profil kostenlos übernehmen", "category_label": "Kategorie", "city_label": "Stadt", "not_found": "Das Profil wurde nicht gefunden oder wurde bereits übernommen.", "already_claimed": "Dieses Profil wurde bereits übernommen.", "success": "Profil übernommen! Weiterleitung zum Dashboard...", "error": "Ein Fehler ist aufgetreten. Bitte erneut versuchen."},
    "el": {"title": "Αξιώστε το προφίλ σας", "subtitle": "Ανήκει αυτή η επιχείρηση σε εσάς στο Nevumo;", "description": "Αξιώστε το προφίλ και αρχίστε να λαμβάνετε αιτήματα πελατών δωρεάν.", "cta_login": "Συνδεθείτε για να αξιώσετε το προφίλ", "cta_register": "Πάρτε το προφίλ δωρεάν!", "cta_claim": "Αξίωση προφίλ δωρεάν", "category_label": "Κατηγορία", "city_label": "Πόλη", "not_found": "Το προφίλ δεν βρέθηκε ή έχει ήδη αξιωθεί.", "already_claimed": "Αυτό το προφίλ έχει ήδη αξιωθεί.", "success": "Το προφίλ είναι δικό σας! Ανακατεύθυνση στον πίνακα...", "error": "Παρουσιάστηκε σφάλμα. Δοκιμάστε ξανά."},
    "en": {"title": "Claim your profile", "subtitle": "Is this your business on Nevumo?", "description": "Claim this profile and start receiving client requests for free.", "cta_login": "Log in to claim this profile", "cta_register": "Get the profile for free!", "cta_claim": "Claim your profile for free", "category_label": "Category", "city_label": "City", "not_found": "This profile was not found or has already been claimed.", "already_claimed": "This profile has already been claimed.", "success": "Profile claimed! Redirecting to your dashboard...", "error": "An error occurred. Please try again."},
    "es": {"title": "Reclamar tu perfil", "subtitle": "¿Es tu empresa en Nevumo?", "description": "Reclama este perfil y empieza a recibir solicitudes de clientes gratis.", "cta_login": "Inicia sesión para reclamar el perfil", "cta_register": "¡Obtén el perfil gratis!", "cta_claim": "Reclamar perfil gratis", "category_label": "Categoría", "city_label": "Ciudad", "not_found": "El perfil no se encontró o ya ha sido reclamado.", "already_claimed": "Este perfil ya ha sido reclamado.", "success": "¡Perfil reclamado! Redirigiendo al panel...", "error": "Ocurrió un error. Inténtalo de nuevo."},
    "et": {"title": "Võta profiil üle", "subtitle": "Kas see ettevõte kuulub sulle Nevumos?", "description": "Võta profiil üle ja hakka tasuta klientide päringuid saama.", "cta_login": "Logi sisse, et profiil üle võtta", "cta_register": "Hangi profiil tasuta!", "cta_claim": "Võta profiil tasuta üle", "category_label": "Kategooria", "city_label": "Linn", "not_found": "Profiili ei leitud või see on juba üle võetud.", "already_claimed": "See profiil on juba üle võetud.", "success": "Profiil on sinu! Suunamine armatuurlauale...", "error": "Ilmnes viga. Palun proovi uuesti."},
    "fi": {"title": "Ota profiili haltuun", "subtitle": "Onko tämä yritys sinun Nevumossa?", "description": "Ota profiili haltuun ja ala vastaanottaa asiakaspyyntöjä ilmaiseksi.", "cta_login": "Kirjaudu sisään ottaaksesi profiilin haltuun", "cta_register": "Hanki profiili ilmaiseksi!", "cta_claim": "Ota profiili haltuun ilmaiseksi", "category_label": "Kategoria", "city_label": "Kaupunki", "not_found": "Profiilia ei löydy tai se on jo otettu haltuun.", "already_claimed": "Tämä profiili on jo otettu haltuun.", "success": "Profiili on sinun! Ohjataan kojelautaan...", "error": "Tapahtui virhe. Yritä uudelleen."},
    "fr": {"title": "Revendiquer votre profil", "subtitle": "Cette entreprise vous appartient-elle sur Nevumo ?", "description": "Revendiquez ce profil et commencez à recevoir des demandes de clients gratuitement.", "cta_login": "Connectez-vous pour revendiquer ce profil", "cta_register": "Obtenez le profil gratuitement!", "cta_claim": "Revendiquer le profil gratuitement", "category_label": "Catégorie", "city_label": "Ville", "not_found": "Ce profil n'a pas été trouvé ou a déjà été revendiqué.", "already_claimed": "Ce profil a déjà été revendiqué.", "success": "Profil revendiqué ! Redirection vers le tableau de bord...", "error": "Une erreur s'est produite. Veuillez réessayer."},
    "ga": {"title": "Éiligh do phróifíl", "subtitle": "An leatsa an gnólacht seo ar Nevumo?", "description": "Éiligh an próifíl seo agus tosaigh ag fáil iarrataí ó chliaint saor in aisce.", "cta_login": "Logáil isteach chun an phróifíl a éileamh", "cta_register": "Faigh an próifíl saor in aisce!", "cta_claim": "Éiligh an phróifíl saor in aisce", "category_label": "Catagóir", "city_label": "Cathair", "not_found": "Níor aimsíodh an phróifíl seo nó tá sí éilithe cheana féin.", "already_claimed": "Tá an phróifíl seo éilithe cheana féin.", "success": "Próifíl éilithe! Ag atreorú chuig an deais...", "error": "Tharla earráid. Bain triail as arís."},
    "hr": {"title": "Preuzmite svoj profil", "subtitle": "Je li ovo vaša tvrtka na Nevumo?", "description": "Preuzmite profil i počnite primati zahtjeve klijenata besplatno.", "cta_login": "Prijavite se i preuzmite profil", "cta_register": "Preuzmi profil besplatno!", "cta_claim": "Preuzmi profil besplatno", "category_label": "Kategorija", "city_label": "Grad", "not_found": "Profil nije pronađen ili je već preuzet.", "already_claimed": "Ovaj profil je već preuzet.", "success": "Profil je vaš! Preusmjerava na nadzornu ploču...", "error": "Došlo je do greške. Pokušajte ponovo."},
    "hu": {"title": "Igényelje profilját", "subtitle": "Ez az Ön vállalkozása a Nevumón?", "description": "Igényelje ezt a profilt, és kezdjen el ingyenesen ügyféligényeket fogadni.", "cta_login": "Jelentkezzen be a profil igényléséhez", "cta_register": "Szerezd meg a profilt ingyen!", "cta_claim": "Profil igénylése ingyenesen", "category_label": "Kategória", "city_label": "Város", "not_found": "A profil nem található vagy már igényelték.", "already_claimed": "Ezt a profilt már igényelték.", "success": "Profil igényelve! Átirányítás az irányítópultra...", "error": "Hiba történt. Kérjük, próbálja újra."},
    "is": {"title": "Taktu yfir prófílinn þinn", "subtitle": "Er þetta fyrirtæki þitt á Nevumo?", "description": "Taktu yfir þennan prófíl og byrjaðu að fá beiðnir frá viðskiptavinum ókeypis.", "cta_login": "Skráðu þig inn til að taka yfir prófílinn", "cta_register": "Fáðu prófílinn ókeypis!", "cta_claim": "Taka yfir prófíl ókeypis", "category_label": "Flokkur", "city_label": "Borg", "not_found": "Prófíllinn fannst ekki eða hefur þegar verið tekinn yfir.", "already_claimed": "Þessi prófíll hefur þegar verið tekinn yfir.", "success": "Prófíll yfirtekinn! Beini á mælaborðið...", "error": "Villa kom upp. Reyndu aftur."},
    "it": {"title": "Rivendica il tuo profilo", "subtitle": "Questa azienda è la tua su Nevumo?", "description": "Rivendica questo profilo e inizia a ricevere richieste dai clienti gratuitamente.", "cta_login": "Accedi per rivendicare il profilo", "cta_register": "Ottieni il profilo gratuitamente!", "cta_claim": "Rivendica il profilo gratuitamente", "category_label": "Categoria", "city_label": "Città", "not_found": "Il profilo non è stato trovato o è già stato rivendicato.", "already_claimed": "Questo profilo è già stato rivendicato.", "success": "Profilo rivendicato! Reindirizzamento alla dashboard...", "error": "Si è verificato un errore. Riprova."},
    "lb": {"title": "Huel Äre Profil", "subtitle": "Gehéiert dëst Betrib Iech op Nevumo?", "description": "Huel dëse Profil a fang gratis Ufroe vu Clienten ze kréien.", "cta_login": "Loggt Iech an fir de Profil ze huelen", "cta_register": "Kritt de Profil gratis!", "cta_claim": "Profil gratis huelen", "category_label": "Kategorie", "city_label": "Stad", "not_found": "De Profil gouf net fonnt oder ass scho geholl.", "already_claimed": "Dëse Profil ass schonn geholl.", "success": "Profil geholl! Weiderleitung zum Dashboard...", "error": "E Feeler ass geschitt. Versicht et nach eng Kéier."},
    "lt": {"title": "Perimkite savo profilį", "subtitle": "Ar ši įmonė jūsų Nevumo?", "description": "Perimkite šį profilį ir pradėkite nemokamai gauti klientų užklausas.", "cta_login": "Prisijunkite norėdami perimti profilį", "cta_register": "Gaukite profilį nemokamai!", "cta_claim": "Perimti profilį nemokamai", "category_label": "Kategorija", "city_label": "Miestas", "not_found": "Profilis nerastas arba jau perimtas.", "already_claimed": "Šis profilis jau perimtas.", "success": "Profilis perimtas! Nukreipiama į prietaisų skydelį...", "error": "Įvyko klaida. Bandykite dar kartą."},
    "lv": {"title": "Pārņemiet savu profilu", "subtitle": "Vai šis uzņēmums ir jūsu Nevumo?", "description": "Pārņemiet šo profilu un sāciet saņemt klientu pieprasījumus bez maksas.", "cta_login": "Piesakieties, lai pārņemtu profilu", "cta_register": "Iegūstiet profilu bez maksas!", "cta_claim": "Pārņemt profilu bez maksas", "category_label": "Kategorija", "city_label": "Pilsēta", "not_found": "Profils nav atrasts vai ir jau pārņemts.", "already_claimed": "Šis profils ir jau pārņemts.", "success": "Profils pārņemts! Novirza uz informācijas paneli...", "error": "Radās kļūda. Lūdzu, mēģiniet vēlreiz."},
    "mk": {"title": "Преземете го вашиот профил", "subtitle": "Дали оваа фирма е ваша на Nevumo?", "description": "Преземете го профилот и почнете да добивате барања од клиенти бесплатно.", "cta_login": "Пријавете се за да го преземете профилот", "cta_register": "Земете го профилот бесплатно!", "cta_claim": "Преземи го профилот бесплатно", "category_label": "Категорија", "city_label": "Град", "not_found": "Профилот не е пронајден или веќе е преземен.", "already_claimed": "Овој профил веќе е преземен.", "success": "Профилот е ваш! Пренасочување кон контролната табла...", "error": "Се случи грешка. Обидете се повторно."},
    "mt": {"title": "Ħu l-profil tiegħek", "subtitle": "Din l-intrapriża hija tiegħek fuq Nevumo?", "description": "Ħu dan il-profil u ibda tirċievi talbiet minn klijenti b'xejn.", "cta_login": "Idħol biex tieħu l-profil", "cta_register": "Ikseb il-profil b'xejn!", "cta_claim": "Ħu l-profil b'xejn", "category_label": "Kategorija", "city_label": "Belt", "not_found": "Il-profil ma nstabx jew diġà ittieħed.", "already_claimed": "Dan il-profil diġà ittieħed.", "success": "Profil meħud! Qed nirediġi lejn id-dashboard...", "error": "Seħħ żball. Erġa' pprova."},
    "nl": {"title": "Claim uw profiel", "subtitle": "Is dit uw bedrijf op Nevumo?", "description": "Claim dit profiel en begin gratis klantverzoeken te ontvangen.", "cta_login": "Log in om het profiel te claimen", "cta_register": "Haal het profiel gratis!", "cta_claim": "Profiel gratis claimen", "category_label": "Categorie", "city_label": "Stad", "not_found": "Het profiel is niet gevonden of al geclaimd.", "already_claimed": "Dit profiel is al geclaimd.", "success": "Profiel geclaimd! Doorsturen naar dashboard...", "error": "Er is een fout opgetreden. Probeer het opnieuw."},
    "no": {"title": "Ta over profilen din", "subtitle": "Er dette bedriften din på Nevumo?", "description": "Ta over dette profilet og begynn å motta kundeforespørsler gratis.", "cta_login": "Logg inn for å ta over profilen", "cta_register": "Få profilen gratis!", "cta_claim": "Ta over profil gratis", "category_label": "Kategori", "city_label": "By", "not_found": "Profilen ble ikke funnet eller er allerede tatt over.", "already_claimed": "Denne profilen er allerede tatt over.", "success": "Profil overtatt! Omdirigerer til dashboard...", "error": "Det oppstod en feil. Prøv igjen."},
    "pl": {"title": "Przejmij swój profil", "subtitle": "Czy ta firma jest Twoja na Nevumo?", "description": "Przejmij ten profil i zacznij bezpłatnie otrzymywać zapytania od klientów.", "cta_login": "Zaloguj się, aby przejąć profil", "cta_register": "Odbierz profil bezpłatnie!", "cta_claim": "Przejmij profil bezpłatnie", "category_label": "Kategoria", "city_label": "Miasto", "not_found": "Profil nie został znaleziony lub jest już przejęty.", "already_claimed": "Ten profil został już przejęty.", "success": "Profil przejęty! Przekierowanie do panelu...", "error": "Wystąpił błąd. Spróbuj ponownie."},
    "pt": {"title": "Reivindicar seu perfil", "subtitle": "Esta empresa é sua no Nevumo?", "description": "Reivindique este perfil e comece a receber solicitações de clientes gratuitamente.", "cta_login": "Entre para reivindicar o perfil", "cta_register": "Obtenha o perfil gratuitamente!", "cta_claim": "Reivindicar perfil gratuitamente", "category_label": "Categoria", "city_label": "Cidade", "not_found": "O perfil não foi encontrado ou já foi reivindicado.", "already_claimed": "Este perfil já foi reivindicado.", "success": "Perfil reivindicado! Redirecionando para o painel...", "error": "Ocorreu um erro. Tente novamente."},
    "pt-PT": {"title": "Reclamar o seu perfil", "subtitle": "Esta empresa é sua no Nevumo?", "description": "Reclame este perfil e comece a receber pedidos de clientes gratuitamente.", "cta_login": "Iniciar sessão para reclamar o perfil", "cta_register": "Obtenha o perfil gratuitamente!", "cta_claim": "Reclamar perfil gratuitamente", "category_label": "Categoria", "city_label": "Cidade", "not_found": "O perfil não foi encontrado ou já foi reclamado.", "already_claimed": "Este perfil já foi reclamado.", "success": "Perfil reclamado! A redirecionar para o painel...", "error": "Ocorreu um erro. Tente novamente."},
    "ro": {"title": "Revendicați profilul dvs.", "subtitle": "Această companie este a dvs. pe Nevumo?", "description": "Revendicați acest profil și începeți să primiți cereri de la clienți gratuit.", "cta_login": "Conectați-vă pentru a revendica profilul", "cta_register": "Obțineți profilul gratuit!", "cta_claim": "Revendicați profilul gratuit", "category_label": "Categorie", "city_label": "Oraș", "not_found": "Profilul nu a fost găsit sau a fost deja revendicat.", "already_claimed": "Acest profil a fost deja revendicat.", "success": "Profil revendicat! Redirecționare către panou...", "error": "A apărut o eroare. Încercați din nou."},
    "ru": {"title": "Получите ваш профиль", "subtitle": "Это ваша компания на Nevumo?", "description": "Получите этот профиль и начните получать заявки от клиентов бесплатно.", "cta_login": "Войдите, чтобы получить профиль", "cta_register": "Получите профиль бесплатно!", "cta_claim": "Получить профиль бесплатно", "category_label": "Категория", "city_label": "Город", "not_found": "Профиль не найден или уже получен.", "already_claimed": "Этот профиль уже получен.", "success": "Профиль получен! Перенаправление на панель управления...", "error": "Произошла ошибка. Попробуйте снова."},
    "sk": {"title": "Prevezmite si svoj profil", "subtitle": "Je táto firma vaša na Nevumo?", "description": "Prevezmite tento profil a začnite bezplatne prijímať požiadavky od klientov.", "cta_login": "Prihláste sa a prevezmite profil", "cta_register": "Získaj profil zadarmo!", "cta_claim": "Prevziať profil zdarma", "category_label": "Kategória", "city_label": "Mesto", "not_found": "Profil sa nenašiel alebo bol už prevzatý.", "already_claimed": "Tento profil bol už prevzatý.", "success": "Profil prevzatý! Presmerovanie na ovládací panel...", "error": "Vyskytla sa chyba. Skúste to znova."},
    "sl": {"title": "Prevzemite svoj profil", "subtitle": "Je to vaše podjetje na Nevumo?", "description": "Prevzemite ta profil in začnite brezplačno prejemati zahteve strank.", "cta_login": "Prijavite se za prevzem profila", "cta_register": "Pridobi profil brezplačno!", "cta_claim": "Prevzemi profil brezplačno", "category_label": "Kategorija", "city_label": "Mesto", "not_found": "Profil ni bil najden ali je že prevzet.", "already_claimed": "Ta profil je že prevzet.", "success": "Profil prevzet! Preusmerjanje na nadzorno ploščo...", "error": "Prišlo je do napake. Poskusite znova."},
    "sq": {"title": "Merr profilin tënd", "subtitle": "A është ky biznesi juaj në Nevumo?", "description": "Merr këtë profil dhe fillo të marrësh kërkesa nga klientët falas.", "cta_login": "Identifikohu për të marrë profilin", "cta_register": "Merr profilin falas!", "cta_claim": "Merr profilin falas", "category_label": "Kategoria", "city_label": "Qyteti", "not_found": "Profili nuk u gjet ose është marrë tashmë.", "already_claimed": "Ky profil është marrë tashmë.", "success": "Profili u mor! Po ridrejton në panel...", "error": "Ndodhi një gabim. Provo përsëri."},
    "sr": {"title": "Preuzmite vaš profil", "subtitle": "Da li je ova firma vaša na Nevumo?", "description": "Preuzmite ovaj profil i počnite besplatno da primate zahteve od klijenata.", "cta_login": "Prijavite se da biste preuzeli profil", "cta_register": "Preuzmi profil besplatno!", "cta_claim": "Preuzmite profil besplatno", "category_label": "Kategorija", "city_label": "Grad", "not_found": "Profil nije pronađen ili je već preuzet.", "already_claimed": "Ovaj profil je već preuzet.", "success": "Profil preuzet! Preusmeravanje na kontrolnu tablu...", "error": "Došlo je do greške. Pokušajte ponovo."},
    "sv": {"title": "Ta över din profil", "subtitle": "Är detta ditt företag på Nevumo?", "description": "Ta över den här profilen och börja ta emot kundförfrågningar gratis.", "cta_login": "Logga in för att ta över profilen", "cta_register": "Hämta profilen gratis!", "cta_claim": "Ta över profil gratis", "category_label": "Kategori", "city_label": "Stad", "not_found": "Profilen hittades inte eller har redan tagits över.", "already_claimed": "Den här profilen har redan tagits över.", "success": "Profil övertagen! Omdirigerar till instrumentpanelen...", "error": "Ett fel inträffade. Försök igen."},
    "tr": {"title": "Profilinizi talep edin", "subtitle": "Bu işletme Nevumo'daki sizin mi?", "description": "Bu profili talep edin ve müşterilerden ücretsiz talep almaya başlayın.", "cta_login": "Profili talep etmek için giriş yapın", "cta_register": "Profili ücretsiz al!", "cta_claim": "Profili ücretsiz talep et", "category_label": "Kategori", "city_label": "Şehir", "not_found": "Profil bulunamadı veya zaten talep edildi.", "already_claimed": "Bu profil zaten talep edildi.", "success": "Profil talep edildi! Panele yönlendiriliyor...", "error": "Bir hata oluştu. Lütfen tekrar deneyin."},
    "uk": {"title": "Отримайте свій профіль", "subtitle": "Ця компанія ваша на Nevumo?", "description": "Отримайте цей профіль і починайте безкоштовно отримувати запити від клієнтів.", "cta_login": "Увійдіть, щоб отримати профіль", "cta_register": "Отримайте профіль безкоштовно!", "cta_claim": "Отримати профіль безкоштовно", "category_label": "Категорія", "city_label": "Місто", "not_found": "Профіль не знайдено або вже отримано.", "already_claimed": "Цей профіль вже отримано.", "success": "Профіль отримано! Перенаправлення на панель управління...", "error": "Сталася помилка. Спробуйте знову."},
}


def seed_translations() -> int:
    """Seed claim translations and return the number of rows upserted."""
    conn = psycopg2.connect(DATABASE_URL)
    cursor = conn.cursor()

    rows_to_upsert = []
    total_keys = 0

    for lang, keys_dict in TRANSLATIONS.items():
        for key, value in keys_dict.items():
            full_key = f"claim.{key}"
            rows_to_upsert.append((lang, full_key, value))
        print(f"Seeded {lang}: {len(keys_dict)} keys")
        total_keys += len(keys_dict)

    execute_values(
        cursor,
        """
        INSERT INTO translations (lang, key, value)
        VALUES %s
        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
        """,
        rows_to_upsert,
        template="(%s, %s, %s)",
    )

    conn.commit()
    cursor.close()
    conn.close()

    return len(rows_to_upsert)


if __name__ == "__main__":
    count = seed_translations()
    print(f"✅ Done: {count} translations inserted/updated")
