from apps.api.database import SessionLocal
from sqlalchemy import text

def seed():
    db = SessionLocal()
    try:
        rows = [
            ('en', 'provider_dashboard.widget_site_title', 'Add the widget to your website'),
            ('en', 'provider_dashboard.widget_site_wordpress', 'In WordPress: add a Custom HTML block and paste the code above.'),
            ('en', 'provider_dashboard.widget_site_wix', 'In Wix: add Embed → Embed HTML element and paste the code above.'),
            ('en', 'provider_dashboard.widget_site_squarespace', 'In Squarespace: add a Code Block and paste the code above.'),
            ('bg', 'provider_dashboard.widget_site_title', 'Вградете widget на вашия сайт'),
            ('bg', 'provider_dashboard.widget_site_wordpress', 'В WordPress: добавете блок Custom HTML и поставете кода по-горе.'),
            ('bg', 'provider_dashboard.widget_site_wix', 'В Wix: добавете Embed → Embed HTML елемент и поставете кода по-горе.'),
            ('bg', 'provider_dashboard.widget_site_squarespace', 'В Squarespace: добавете Code Block и поставете кода по-горе.'),
            ('pl', 'provider_dashboard.widget_site_title', 'Dodaj widget do swojej strony'),
            ('pl', 'provider_dashboard.widget_site_wordpress', 'W WordPress: dodaj blok Custom HTML i wklej powyższy kod.'),
            ('pl', 'provider_dashboard.widget_site_wix', 'W Wix: dodaj element Embed → Embed HTML i wklej powyższy kod.'),
            ('pl', 'provider_dashboard.widget_site_squarespace', 'W Squarespace: dodaj Code Block i wklej powyższy kod.'),
            ('de', 'provider_dashboard.widget_site_title', 'Widget auf Ihrer Website einbetten'),
            ('de', 'provider_dashboard.widget_site_wordpress', 'In WordPress: fügen Sie einen Custom HTML-Block hinzu und fügen Sie den Code oben ein.'),
            ('de', 'provider_dashboard.widget_site_wix', 'In Wix: fügen Sie Embed → Embed HTML-Element hinzu und fügen Sie den Code oben ein.'),
            ('de', 'provider_dashboard.widget_site_squarespace', 'In Squarespace: fügen Sie einen Code Block hinzu und fügen Sie den Code oben ein.'),
            ('fr', 'provider_dashboard.widget_site_title', 'Ajouter le widget à votre site'),
            ('fr', 'provider_dashboard.widget_site_wordpress', 'Dans WordPress: ajoutez un bloc Custom HTML et collez le code ci-dessus.'),
            ('fr', 'provider_dashboard.widget_site_wix', 'Dans Wix: ajoutez Embed → Embed HTML et collez le code ci-dessus.'),
            ('fr', 'provider_dashboard.widget_site_squarespace', 'Dans Squarespace: ajoutez un Code Block et collez le code ci-dessus.'),
            ('es', 'provider_dashboard.widget_site_title', 'Añade el widget a tu sitio web'),
            ('es', 'provider_dashboard.widget_site_wordpress', 'En WordPress: añade un bloque Custom HTML y pega el código de arriba.'),
            ('es', 'provider_dashboard.widget_site_wix', 'En Wix: añade Embed → Embed HTML y pega el código de arriba.'),
            ('es', 'provider_dashboard.widget_site_squarespace', 'En Squarespace: añade un Code Block y pega el código de arriba.'),
            ('it', 'provider_dashboard.widget_site_title', 'Aggiungi il widget al tuo sito'),
            ('it', 'provider_dashboard.widget_site_wordpress', 'In WordPress: aggiungi un blocco Custom HTML e incolla il codice sopra.'),
            ('it', 'provider_dashboard.widget_site_wix', 'In Wix: aggiungi Embed → Embed HTML e incolla il codice sopra.'),
            ('it', 'provider_dashboard.widget_site_squarespace', 'In Squarespace: aggiungi un Code Block e incolla il codice sopra.'),
            ('pt', 'provider_dashboard.widget_site_title', 'Adicione o widget ao seu site'),
            ('pt', 'provider_dashboard.widget_site_wordpress', 'No WordPress: adicione um bloco Custom HTML e cole o código acima.'),
            ('pt', 'provider_dashboard.widget_site_wix', 'No Wix: adicione Embed → Embed HTML e cole o código acima.'),
            ('pt', 'provider_dashboard.widget_site_squarespace', 'No Squarespace: adicione um Code Block e cole o código acima.'),
            ('pt-PT', 'provider_dashboard.widget_site_title', 'Adicione o widget ao seu site'),
            ('pt-PT', 'provider_dashboard.widget_site_wordpress', 'No WordPress: adicione um bloco Custom HTML e cole o código acima.'),
            ('pt-PT', 'provider_dashboard.widget_site_wix', 'No Wix: adicione Embed → Embed HTML e cole o código acima.'),
            ('pt-PT', 'provider_dashboard.widget_site_squarespace', 'No Squarespace: adicione um Code Block e cole o código acima.'),
            ('nl', 'provider_dashboard.widget_site_title', 'Voeg de widget toe aan uw website'),
            ('nl', 'provider_dashboard.widget_site_wordpress', 'In WordPress: voeg een Custom HTML-blok toe en plak de bovenstaande code.'),
            ('nl', 'provider_dashboard.widget_site_wix', 'In Wix: voeg Embed → Embed HTML-element toe en plak de bovenstaande code.'),
            ('nl', 'provider_dashboard.widget_site_squarespace', 'In Squarespace: voeg een Code Block toe en plak de bovenstaande code.'),
            ('cs', 'provider_dashboard.widget_site_title', 'Přidejte widget na váš web'),
            ('cs', 'provider_dashboard.widget_site_wordpress', 'Ve WordPress: přidejte blok Custom HTML a vložte výše uvedený kód.'),
            ('cs', 'provider_dashboard.widget_site_wix', 'Ve Wix: přidejte Embed → Embed HTML element a vložte výše uvedený kód.'),
            ('cs', 'provider_dashboard.widget_site_squarespace', 'Ve Squarespace: přidejte Code Block a vložte výše uvedený kód.'),
            ('sk', 'provider_dashboard.widget_site_title', 'Pridajte widget na vašu stránku'),
            ('sk', 'provider_dashboard.widget_site_wordpress', 'Vo WordPress: pridajte blok Custom HTML a vložte vyššie uvedený kód.'),
            ('sk', 'provider_dashboard.widget_site_wix', 'Vo Wix: pridajte Embed → Embed HTML element a vložte vyššie uvedený kód.'),
            ('sk', 'provider_dashboard.widget_site_squarespace', 'Vo Squarespace: pridajte Code Block a vložte vyššie uvedený kód.'),
            ('ro', 'provider_dashboard.widget_site_title', 'Adaugă widget-ul pe site-ul tău'),
            ('ro', 'provider_dashboard.widget_site_wordpress', 'În WordPress: adaugă un bloc Custom HTML și lipește codul de mai sus.'),
            ('ro', 'provider_dashboard.widget_site_wix', 'În Wix: adaugă Embed → Embed HTML și lipește codul de mai sus.'),
            ('ro', 'provider_dashboard.widget_site_squarespace', 'În Squarespace: adaugă un Code Block și lipește codul de mai sus.'),
            ('hu', 'provider_dashboard.widget_site_title', 'Widget hozzáadása a weboldalhoz'),
            ('hu', 'provider_dashboard.widget_site_wordpress', 'WordPressben: adj hozzá egy Custom HTML blokkot és illeszd be a fenti kódot.'),
            ('hu', 'provider_dashboard.widget_site_wix', 'Wixben: adj hozzá Embed → Embed HTML elemet és illeszd be a fenti kódot.'),
            ('hu', 'provider_dashboard.widget_site_squarespace', 'Squarespaceban: adj hozzá egy Code Blockot és illeszd be a fenti kódot.'),
            ('hr', 'provider_dashboard.widget_site_title', 'Dodajte widget na svoju web stranicu'),
            ('hr', 'provider_dashboard.widget_site_wordpress', 'U WordPressu: dodajte Custom HTML blok i zalijepite gornji kod.'),
            ('hr', 'provider_dashboard.widget_site_wix', 'U Wixu: dodajte Embed → Embed HTML element i zalijepite gornji kod.'),
            ('hr', 'provider_dashboard.widget_site_squarespace', 'U Squarespaceу: dodajte Code Block i zalijepite gornji kod.'),
            ('sl', 'provider_dashboard.widget_site_title', 'Dodajte widget na svojo spletno stran'),
            ('sl', 'provider_dashboard.widget_site_wordpress', 'V WordPressu: dodajte blok Custom HTML in prilepite zgornjo kodo.'),
            ('sl', 'provider_dashboard.widget_site_wix', 'V Wixu: dodajte Embed → Embed HTML element in prilepite zgornjo kodo.'),
            ('sl', 'provider_dashboard.widget_site_squarespace', 'V Squarespaceу: dodajte Code Block in prilepite zgornjo kodo.'),
            ('da', 'provider_dashboard.widget_site_title', 'Tilføj widget til dit websted'),
            ('da', 'provider_dashboard.widget_site_wordpress', 'I WordPress: tilføj en Custom HTML-blok og indsæt koden ovenfor.'),
            ('da', 'provider_dashboard.widget_site_wix', 'I Wix: tilføj Embed → Embed HTML-element og indsæt koden ovenfor.'),
            ('da', 'provider_dashboard.widget_site_squarespace', 'I Squarespace: tilføj en Code Block og indsæt koden ovenfor.'),
            ('sv', 'provider_dashboard.widget_site_title', 'Lägg till widget på din webbplats'),
            ('sv', 'provider_dashboard.widget_site_wordpress', 'I WordPress: lägg till ett Custom HTML-block och klistra in koden ovan.'),
            ('sv', 'provider_dashboard.widget_site_wix', 'I Wix: lägg till Embed → Embed HTML-element och klistra in koden ovan.'),
            ('sv', 'provider_dashboard.widget_site_squarespace', 'I Squarespace: lägg till ett Code Block och klistra in koden ovan.'),
            ('no', 'provider_dashboard.widget_site_title', 'Legg til widget på nettstedet ditt'),
            ('no', 'provider_dashboard.widget_site_wordpress', 'I WordPress: legg til en Custom HTML-blokk og lim inn koden ovenfor.'),
            ('no', 'provider_dashboard.widget_site_wix', 'I Wix: legg til Embed → Embed HTML-element og lim inn koden ovenfor.'),
            ('no', 'provider_dashboard.widget_site_squarespace', 'I Squarespace: legg til en Code Block og lim inn koden ovenfor.'),
            ('fi', 'provider_dashboard.widget_site_title', 'Lisää widget verkkosivustollesi'),
            ('fi', 'provider_dashboard.widget_site_wordpress', 'WordPressissä: lisää Custom HTML -lohko ja liitä yllä oleva koodi.'),
            ('fi', 'provider_dashboard.widget_site_wix', 'Wixissä: lisää Embed → Embed HTML -elementti ja liitä yllä oleva koodi.'),
            ('fi', 'provider_dashboard.widget_site_squarespace', 'Squarespaceessa: lisää Code Block ja liitä yllä oleva koodi.'),
            ('et', 'provider_dashboard.widget_site_title', 'Lisa vidin oma veebisaidile'),
            ('et', 'provider_dashboard.widget_site_wordpress', 'WordPressis: lisa Custom HTML plokk ja kleebi ülalolev kood.'),
            ('et', 'provider_dashboard.widget_site_wix', 'Wixis: lisa Embed → Embed HTML element ja kleebi ülalolev kood.'),
            ('et', 'provider_dashboard.widget_site_squarespace', 'Squarespaces: lisa Code Block ja kleebi ülalolev kood.'),
            ('lv', 'provider_dashboard.widget_site_title', 'Pievienojiet logrīku savai vietnei'),
            ('lv', 'provider_dashboard.widget_site_wordpress', 'WordPress: pievienojiet Custom HTML bloku un ielīmējiet augstāk esošo kodu.'),
            ('lv', 'provider_dashboard.widget_site_wix', 'Wix: pievienojiet Embed → Embed HTML elementu un ielīmējiet augstāk esošo kodu.'),
            ('lv', 'provider_dashboard.widget_site_squarespace', 'Squarespace: pievienojiet Code Block un ielīmējiet augstāk esošo kodu.'),
            ('lt', 'provider_dashboard.widget_site_title', 'Pridėkite valdiklį prie savo svetainės'),
            ('lt', 'provider_dashboard.widget_site_wordpress', 'WordPress: pridėkite Custom HTML bloką ir įklijuokite aukščiau esantį kodą.'),
            ('lt', 'provider_dashboard.widget_site_wix', 'Wix: pridėkite Embed → Embed HTML elementą ir įklijuokite aukščiau esantį kodą.'),
            ('lt', 'provider_dashboard.widget_site_squarespace', 'Squarespace: pridėkite Code Block ir įklijuokite aukščiau esantį kodą.'),
            ('el', 'provider_dashboard.widget_site_title', 'Προσθέστε το widget στον ιστότοπό σας'),
            ('el', 'provider_dashboard.widget_site_wordpress', 'Στο WordPress: προσθέστε μπλοκ Custom HTML και επικολλήστε τον παραπάνω κώδικα.'),
            ('el', 'provider_dashboard.widget_site_wix', 'Στο Wix: προσθέστε Embed → Embed HTML και επικολλήστε τον παραπάνω κώδικα.'),
            ('el', 'provider_dashboard.widget_site_squarespace', 'Στο Squarespace: προσθέστε Code Block και επικολλήστε τον παραπάνω κώδικα.'),
            ('ru', 'provider_dashboard.widget_site_title', 'Добавьте виджет на ваш сайт'),
            ('ru', 'provider_dashboard.widget_site_wordpress', 'В WordPress: добавьте блок Custom HTML и вставьте код выше.'),
            ('ru', 'provider_dashboard.widget_site_wix', 'В Wix: добавьте Embed → Embed HTML элемент и вставьте код выше.'),
            ('ru', 'provider_dashboard.widget_site_squarespace', 'В Squarespace: добавьте Code Block и вставьте код выше.'),
            ('uk', 'provider_dashboard.widget_site_title', 'Додайте віджет на ваш сайт'),
            ('uk', 'provider_dashboard.widget_site_wordpress', 'У WordPress: додайте блок Custom HTML і вставте код вище.'),
            ('uk', 'provider_dashboard.widget_site_wix', 'У Wix: додайте Embed → Embed HTML елемент і вставте код вище.'),
            ('uk', 'provider_dashboard.widget_site_squarespace', 'У Squarespace: додайте Code Block і вставте код вище.'),
            ('sr', 'provider_dashboard.widget_site_title', 'Dodajte widget na vaš sajt'),
            ('sr', 'provider_dashboard.widget_site_wordpress', 'U WordPressu: dodajte Custom HTML blok i nalepite gornji kod.'),
            ('sr', 'provider_dashboard.widget_site_wix', 'U Wixu: dodajte Embed → Embed HTML element i nalepite gornji kod.'),
            ('sr', 'provider_dashboard.widget_site_squarespace', 'U Squarespaceу: dodajte Code Block i nalepite gornji kod.'),
            ('mk', 'provider_dashboard.widget_site_title', 'Додајте виџет на вашиот сајт'),
            ('mk', 'provider_dashboard.widget_site_wordpress', 'Во WordPress: додајте Custom HTML блок и залепете го горниот код.'),
            ('mk', 'provider_dashboard.widget_site_wix', 'Во Wix: додајте Embed → Embed HTML елемент и залепете го горниот код.'),
            ('mk', 'provider_dashboard.widget_site_squarespace', 'Во Squarespace: додајте Code Block и залепете го горниот код.'),
            ('sq', 'provider_dashboard.widget_site_title', 'Shtoni widget-in në faqen tuaj'),
            ('sq', 'provider_dashboard.widget_site_wordpress', 'Në WordPress: shtoni një bllok Custom HTML dhe ngjisni kodin e mësipërm.'),
            ('sq', 'provider_dashboard.widget_site_wix', 'Në Wix: shtoni Embed → Embed HTML dhe ngjisni kodin e mësipërm.'),
            ('sq', 'provider_dashboard.widget_site_squarespace', 'Në Squarespace: shtoni një Code Block dhe ngjisni kodin e mësipërm.'),
            ('ga', 'provider_dashboard.widget_site_title', 'Cuir an ghiuirléid le do láithreán gréasáin'),
            ('ga', 'provider_dashboard.widget_site_wordpress', 'In WordPress: cuir bloc Custom HTML leis agus greamaigh an cód thuas.'),
            ('ga', 'provider_dashboard.widget_site_wix', 'In Wix: cuir Embed → Embed HTML leis agus greamaigh an cód thuas.'),
            ('ga', 'provider_dashboard.widget_site_squarespace', 'In Squarespace: cuir Code Block leis agus greamaigh an cód thuas.'),
            ('is', 'provider_dashboard.widget_site_title', 'Bættu widget við vefsíðuna þína'),
            ('is', 'provider_dashboard.widget_site_wordpress', 'Í WordPress: bættu við Custom HTML blokk og límdu kóðann hér að ofan.'),
            ('is', 'provider_dashboard.widget_site_wix', 'Í Wix: bættu við Embed → Embed HTML og límdu kóðann hér að ofan.'),
            ('is', 'provider_dashboard.widget_site_squarespace', 'Í Squarespace: bættu við Code Block og límdu kóðann hér að ofan.'),
            ('lb', 'provider_dashboard.widget_site_title', 'Widget op Är Websäit abannen'),
            ('lb', 'provider_dashboard.widget_site_wordpress', 'A WordPress: füge e Custom HTML-Block an a kopéiert de Code vun uewen.'),
            ('lb', 'provider_dashboard.widget_site_wix', 'A Wix: füge Embed → Embed HTML un a kopéiert de Code vun uewen.'),
            ('lb', 'provider_dashboard.widget_site_squarespace', 'A Squarespace: füge e Code Block un a kopéiert de Code vun uewen.'),
            ('mt', 'provider_dashboard.widget_site_title', 'Żid il-widget fuq is-sit tiegħek'),
            ('mt', 'provider_dashboard.widget_site_wordpress', 'Fil-WordPress: żid blokk Custom HTML u daqqa l-kodiċi ta\' hawn fuq.'),
            ('mt', 'provider_dashboard.widget_site_wix', 'Fil-Wix: żid Embed → Embed HTML u daqqa l-kodiċi ta\' hawn fuq.'),
            ('mt', 'provider_dashboard.widget_site_squarespace', 'Fil-Squarespace: żid Code Block u daqqa l-kodiċi ta\' hawn fuq.'),
            ('tr', 'provider_dashboard.widget_site_title', 'Widget\'ı web sitenize ekleyin'),
            ('tr', 'provider_dashboard.widget_site_wordpress', 'WordPress\'te: Custom HTML bloğu ekleyin ve yukarıdaki kodu yapıştırın.'),
            ('tr', 'provider_dashboard.widget_site_wix', 'Wix\'te: Embed → Embed HTML elementi ekleyin ve yukarıdaki kodu yapıştırın.'),
            ('tr', 'provider_dashboard.widget_site_squarespace', 'Squarespace\'te: Code Block ekleyin ve yukarıdaki kodu yapıştırın.'),
        ]
        for lang, key, value in rows:
            db.execute(text("""
                INSERT INTO translations (lang, key, value)
                VALUES (:lang, :key, :value)
                ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
            """), {"lang": lang, "key": key, "value": value})
        db.commit()
        print(f"Seeded {len(rows)} rows.")
    finally:
        db.close()

if __name__ == "__main__":
    seed()
