"""
Seed script: cookies namespace — p23
Keys: s9_title, s9_text, s10_title, s10_text,
      s11_title, s11_authority_bg, s11_authority_pl, last_updated
34 languages × 8 keys = 272 rows
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p23
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL", "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads")
engine = create_engine(DATABASE_URL)

NAMESPACE = "cookies"

TRANSLATIONS = {
    "s9_title": {
        "en": "9. Re-consent",
        "pl": "9. Ponowna zgoda",
        "bg": "9. Ново съгласие",
        "de": "9. Erneute Einwilligung",
        "fr": "9. Renouvellement du consentement",
        "es": "9. Nuevo consentimiento",
        "it": "9. Nuovo consenso",
        "pt": "9. Novo consentimento",
        "pt-PT": "9. Novo consentimento",
        "nl": "9. Hernieuwde toestemming",
        "cs": "9. Opětovný souhlas",
        "sk": "9. Opätovný súhlas",
        "hu": "9. Ismételt hozzájárulás",
        "ro": "9. Reconsimțământ",
        "hr": "9. Ponovni pristanak",
        "sr": "9. Ponovni pristanak",
        "sl": "9. Ponovna privolitev",
        "uk": "9. Повторна згода",
        "ru": "9. Повторное согласие",
        "tr": "9. Yeniden Onay",
        "el": "9. Επανασυγκατάθεση",
        "da": "9. Fornyet samtykke",
        "sv": "9. Förnyat samtycke",
        "no": "9. Fornyet samtykke",
        "fi": "9. Uusi suostumus",
        "et": "9. Uuesti nõusolek",
        "lv": "9. Atkārtota piekrišana",
        "lt": "9. Pakartotinis sutikimas",
        "ga": "9. Ath-thoiliú",
        "is": "9. Endurnýjað samþykki",
        "lb": "9. Nees-Zoustëmmung",
        "mk": "9. Повторна согласност",
        "sq": "9. Ri-pëlqim",
        "mt": "9. Re-kunsens",
    },
    "s9_text": {
        "en": "We will ask for your consent again after 12 months, or sooner if we make material changes to the types of cookies we use.",
        "pl": "Poprosimy o ponowną zgodę po 12 miesiącach lub wcześniej, jeśli dokonamy istotnych zmian w rodzajach stosowanych przez nas cookies.",
        "bg": "Ще поискаме ново съгласие след 12 месеца или по-рано, ако направим съществени промени в видовете бисквитки, които използваме.",
        "de": "Wir werden Sie nach 12 Monaten erneut um Ihre Einwilligung bitten oder früher, wenn wir wesentliche Änderungen an den von uns verwendeten Cookie-Typen vornehmen.",
        "fr": "Nous vous demanderons à nouveau votre consentement après 12 mois, ou plus tôt si nous apportons des modifications substantielles aux types de cookies que nous utilisons.",
        "es": "Le solicitaremos su consentimiento de nuevo después de 12 meses, o antes si realizamos cambios materiales en los tipos de cookies que utilizamos.",
        "it": "Ti chiederemo nuovamente il consenso dopo 12 mesi, o prima se apportiamo modifiche sostanziali ai tipi di cookie che utilizziamo.",
        "pt": "Solicitaremos novamente o seu consentimento após 12 meses, ou antes se realizarmos alterações materiais nos tipos de cookies que utilizamos.",
        "pt-PT": "Solicitaremos novamente o seu consentimento após 12 meses, ou antes se realizarmos alterações materiais nos tipos de cookies que utilizamos.",
        "nl": "We zullen u na 12 maanden opnieuw om toestemming vragen, of eerder als we wezenlijke wijzigingen aanbrengen in de soorten cookies die we gebruiken.",
        "cs": "O souhlas vás požádáme znovu po 12 měsících nebo dříve, pokud provedeme podstatné změny v typech cookies, které používáme.",
        "sk": "O súhlas vás požiadame znovu po 12 mesiacoch alebo skôr, ak vykonáme podstatné zmeny v typoch cookies, ktoré používame.",
        "hu": "12 hónap elteltével ismét kérjük hozzájárulását, vagy korábban, ha lényeges változtatásokat eszközlünk az általunk használt cookie-típusokban.",
        "ro": "Vă vom solicita din nou consimțământul după 12 luni sau mai devreme dacă aducem modificări semnificative tipurilor de cookie-uri pe care le folosim.",
        "hr": "Zatražit ćemo vaš pristanak ponovo nakon 12 mjeseci, ili ranije ako napravimo bitne promjene u vrstama kolačića koje koristimo.",
        "sr": "Zatražićemo vaš pristanak ponovo nakon 12 meseci, ili ranije ako napravimo bitne promene u vrstama kolačića koje koristimo.",
        "sl": "Vašo privolitev bomo znova zahtevali po 12 mesecih ali prej, če bomo naredili bistvene spremembe vrst piškotkov, ki jih uporabljamo.",
        "uk": "Ми знову запитаємо вашу згоду через 12 місяців або раніше, якщо внесемо суттєві зміни до типів файлів cookie, які ми використовуємо.",
        "ru": "Мы снова запросим ваше согласие через 12 месяцев или раньше, если мы внесём существенные изменения в типы используемых файлов cookie.",
        "tr": "12 ay sonra veya kullandığımız çerez türlerinde önemli değişiklikler yaparsak daha önce tekrar onayınızı isteyeceğiz.",
        "el": "Θα ζητήσουμε ξανά τη συγκατάθεσή σας μετά από 12 μήνες, ή νωρίτερα εάν κάνουμε ουσιαστικές αλλαγές στους τύπους cookies που χρησιμοποιούμε.",
        "da": "Vi vil bede om dit samtykke igen efter 12 måneder, eller tidligere hvis vi foretager væsentlige ændringer i de typer af cookies, vi bruger.",
        "sv": "Vi kommer att be om ditt samtycke igen efter 12 månader, eller tidigare om vi gör väsentliga förändringar av de typer av cookies vi använder.",
        "no": "Vi vil be om samtykket ditt igjen etter 12 måneder, eller tidligere hvis vi gjør vesentlige endringer i typen informasjonskapsler vi bruker.",
        "fi": "Pyydämme suostumuksesi uudelleen 12 kuukauden kuluttua tai aikaisemmin, jos teemme olennaisia muutoksia käyttämiimme evästetyyppeihin.",
        "et": "Küsime teie nõusolekut uuesti 12 kuu pärast või varem, kui teeme olulisi muudatusi kasutatavate küpsiste tüüpides.",
        "lv": "Mēs lūgsim jūsu piekrišanu atkārtoti pēc 12 mēnešiem vai agrāk, ja mēs veiksim būtiskas izmaiņas mūsu izmantoto sīkdatņu veidos.",
        "lt": "Paprašysime jūsų sutikimo dar kartą po 12 mėnesių arba anksčiau, jei atliksime esminius naudojamų slapukų rūšių pakeitimus.",
        "ga": "Iarrfaimid do thoiliú arís tar éis 12 mhí, nó níos luaithe má dhéanaimid athruithe ábhartha ar na cineálacha fianán a úsáidimid.",
        "is": "Við munum biðja þig um samþykki aftur eftir 12 mánuði, eða fyrr ef við gerum verulegar breytingar á þeim tegundum vafrakaka sem við notum.",
        "lb": "Mir wäerte Är Zoustëmmung no 12 Méint erëm froen, oder fréier wann mir wesentlech Ännerungen un den Cookie-Typen maachen, déi mir benotzen.",
        "mk": "Ќе побараме вашa согласност повторно по 12 месеци, или порано ако направиме суштински промени во видовите колачиња кои ги користиме.",
        "sq": "Do të kërkojmë pëlqimin tuaj përsëri pas 12 muajsh, ose më herët nëse bëjmë ndryshime materiale në llojet e skedarëve të personalizimit që përdorim.",
        "mt": "Nitolbu l-kunsens tiegħek mill-ġdid wara 12-il xahar, jew aktar kmieni jekk nagħmlu bidliet materjali fit-tipi ta' cookies li nużaw.",
    },
    "s10_title": {
        "en": "10. Changes to This Policy",
        "pl": "10. Zmiany niniejszej polityki",
        "bg": "10. Промени в тази политика",
        "de": "10. Änderungen dieser Richtlinie",
        "fr": "10. Modifications de la présente politique",
        "es": "10. Cambios en esta política",
        "it": "10. Modifiche alla presente informativa",
        "pt": "10. Alterações a esta política",
        "pt-PT": "10. Alterações a esta política",
        "nl": "10. Wijzigingen in dit beleid",
        "cs": "10. Změny těchto zásad",
        "sk": "10. Zmeny týchto zásad",
        "hu": "10. A szabályzat módosításai",
        "ro": "10. Modificări ale acestei politici",
        "hr": "10. Izmjene ove politike",
        "sr": "10. Izmene ove politike",
        "sl": "10. Spremembe te politike",
        "uk": "10. Зміни до цієї політики",
        "ru": "10. Изменения в данной политике",
        "tr": "10. Bu Politikadaki Değişiklikler",
        "el": "10. Αλλαγές σε αυτήν την πολιτική",
        "da": "10. Ændringer i denne politik",
        "sv": "10. Ändringar av denna policy",
        "no": "10. Endringer i denne policyen",
        "fi": "10. Muutokset tähän käytäntöön",
        "et": "10. Muudatused selles poliitikas",
        "lv": "10. Izmaiņas šajā politikā",
        "lt": "10. Šios politikos pakeitimai",
        "ga": "10. Athruithe ar an Mbeartas seo",
        "is": "10. Breytingar á þessari stefnu",
        "lb": "10. Ännerungen un dëser Richtlinn",
        "mk": "10. Промени на оваа политика",
        "sq": "10. Ndryshimet e kësaj politike",
        "mt": "10. Bidliet f'din il-Politika",
    },
    "s10_text": {
        "en": 'We may update this Cookie Policy from time to time. The "Effective date" at the top of this page will always show the date of the latest version. Significant changes will be communicated via the cookie consent banner.',
        "pl": 'Niniejsza Polityka cookies może być od czasu do czasu aktualizowana. „Data wejścia w życie" widoczna na górze strony zawsze wskazuje datę najnowszej wersji. O istotnych zmianach poinformujemy poprzez baner zgody na cookies.',
        "bg": '„Датата на влизане в сила" в началото на страницата винаги показва датата на последната версия. За съществени промени ще бъдете уведомени чрез банера за съгласие с бисквитките.',
        "de": 'Diese Cookie-Richtlinie kann von Zeit zu Zeit aktualisiert werden. Das "Gültigkeitsdatum" am Anfang dieser Seite gibt immer das Datum der neuesten Version an. Wesentliche Änderungen werden über das Cookie-Einwilligungsbanner mitgeteilt.',
        "fr": "Nous pouvons mettre à jour cette Politique de cookies de temps en temps. La « Date d'entrée en vigueur » en haut de cette page indiquera toujours la date de la dernière version. Les modifications importantes seront communiquées via la bannière de consentement aux cookies.",
        "es": "Podemos actualizar esta Política de cookies de vez en cuando. La «Fecha de entrada en vigor» en la parte superior de esta página siempre mostrará la fecha de la última versión. Los cambios significativos se comunicarán a través del banner de consentimiento de cookies.",
        "it": 'Potremmo aggiornare questa Informativa sui cookie di tanto in tanto. La "Data di entrata in vigore" nella parte superiore di questa pagina mostrerà sempre la data dell\'ultima versione. Le modifiche significative saranno comunicate tramite il banner per il consenso ai cookie.',
        "pt": "Podemos atualizar esta Política de cookies periodicamente. A «Data de entrada em vigor» no topo desta página indicará sempre a data da versão mais recente. As alterações significativas serão comunicadas através do banner de consentimento de cookies.",
        "pt-PT": "Podemos atualizar esta Política de cookies periodicamente. A «Data de entrada em vigor» no topo desta página indicará sempre a data da versão mais recente. As alterações significativas serão comunicadas através do banner de consentimento de cookies.",
        "nl": 'We kunnen dit Cookiebeleid van tijd tot tijd bijwerken. De "Ingangsdatum" bovenaan deze pagina toont altijd de datum van de nieuwste versie. Significante wijzigingen worden meegedeeld via de cookie-toestemmingsbanner.',
        "cs": 'Tyto Zásady používání cookies mohou být čas od času aktualizovány. „Datum účinnosti" v horní části této stránky vždy ukazuje datum nejnovější verze. Podstatné změny budou oznámeny prostřednictvím banneru pro souhlas s cookies.',
        "sk": 'Tieto Zásady používania cookies môžu byť čas od času aktualizované. „Dátum účinnosti" v hornej časti tejto stránky vždy zobrazuje dátum najnovšej verzie. O podstatných zmenách budete informovaní prostredníctvom bannera so súhlasom so cookies.',
        "hu": 'A Cookie-szabályzatot időről időre frissíthetjük. Az oldal tetején lévő „Hatályba lépés dátuma" mindig a legújabb verzió dátumát mutatja. A lényeges változásokról a cookie-hozzájárulási bannerben értesítjük Önt.',
        "ro": 'Această Politică de cookies poate fi actualizată periodic. „Data intrării în vigoare" din partea de sus a acestei pagini va indica întotdeauna data ultimei versiuni. Modificările semnificative vor fi comunicate prin bannerul de consimțământ pentru cookies.',
        "hr": 'Ovu Politiku kolačića možemo s vremena na vrijeme ažurirati. "Datum stupanja na snagu" na vrhu ove stranice uvijek će prikazivati datum najnovije verzije. O značajnim promjenama bit ćete obaviješteni putem bannera za pristanak na kolačiće.',
        "sr": 'Ovu Politiku kolačića možemo s vremena na vreme ažurirati. "Datum stupanja na snagu" na vrhu ove stranice uvek će prikazivati datum najnovije verzije. O značajnim promenama bićete obavešteni putem banera za pristanak na kolačiće.',
        "sl": 'To politiko piškotkov lahko občasno posodobimo. "Datum začetka veljavnosti" na vrhu te strani bo vedno prikazoval datum najnovejše različice. Bistvene spremembe bodo sporočene prek pasice za privolitev k piškotkom.',
        "uk": "Ця Політика щодо файлів cookie може оновлюватися час від часу. «Дата набуття чинності» у верхній частині цієї сторінки завжди відображатиме дату останньої версії. Про суттєві зміни буде повідомлено через банер згоди на файли cookie.",
        "ru": "Настоящая Политика в отношении файлов cookie может периодически обновляться. «Дата вступления в силу» в верхней части страницы всегда будет показывать дату последней версии. Об существенных изменениях будет сообщаться через баннер согласия на файлы cookie.",
        "tr": 'Bu Çerez Politikasını zaman zaman güncelleyebiliriz. Bu sayfanın üstündeki "Yürürlük tarihi" her zaman en son sürümün tarihini gösterecektir. Önemli değişiklikler çerez onay başlığı aracılığıyla iletilecektir.',
        "el": "Ενδέχεται να ενημερώνουμε αυτήν την Πολιτική Cookies κατά καιρούς. Η «Ημερομηνία έναρξης ισχύος» στην κορυφή αυτής της σελίδας θα δείχνει πάντα την ημερομηνία της τελευταίας έκδοσης. Οι σημαντικές αλλαγές θα κοινοποιούνται μέσω του banner συγκατάθεσης cookies.",
        "da": 'Vi kan opdatere denne Cookiepolitik fra tid til anden. "Ikrafttrædelsesdatoen" øverst på denne side vil altid vise datoen for den seneste version. Væsentlige ændringer vil blive kommunikeret via cookiesamtykkebanneret.',
        "sv": 'Vi kan uppdatera denna Cookiepolicy från tid till annan. "Ikraftträdandedatumet" längst upp på denna sida visar alltid datumet för den senaste versionen. Väsentliga ändringar meddelas via cookiesamtyckesbandern.',
        "no": 'Vi kan oppdatere denne Informasjonskapselspolicyen fra tid til annen. "Ikrafttredelsesdatoen" øverst på denne siden vil alltid vise datoen for den nyeste versjonen. Vesentlige endringer vil bli kommunisert via samtykkebannteret for informasjonskapsler.',
        "fi": 'Saatamme päivittää tätä Evästekäytäntöä ajoittain. Sivun yläosassa oleva "Voimaantulopäivä" näyttää aina viimeisimmän version päivämäärän. Merkittävistä muutoksista ilmoitetaan evästeiden suostumuksen kautta.',
        "et": 'Võime seda küpsiste poliitikat aeg-ajalt uuendada. Selle lehe ülaosas olev "Jõustumiskuupäev" näitab alati viimase versiooni kuupäeva. Olulistest muudatustest teavitatakse küpsiste nõusolekubänneriga.',
        "lv": 'Mēs varam laiku pa laikam atjaunināt šo sīkdatņu politiku. "Spēkā stāšanās datums" šīs lapas augšdaļā vienmēr parādīs jaunākās versijas datumu. Par būtiskām izmaiņām tiks paziņots caur sīkdatņu piekrišanas reklāmkarogu.',
        "lt": 'Galime periodiškai atnaujinti šią slapukų politiką. „Įsigaliojimo data" šio puslapio viršuje visada rodys naujausios versijos datą. Apie reikšmingus pakeitimus bus pranešama per slapukų sutikimo reklamjuostę.',
        "ga": "Féadfaimid an Beartas Fianán seo a nuashonrú ó am go ham. Léireoidh an \"Dáta éifeachtach\" ag barr an leathanaigh seo dáta an leagain is déanaí i gcónaí. Cuirfear athruithe suntasacha in iúl trí bhainéar toilithe na fianán.",
        "is": "Við gætum uppfært þessa vafrakakastefnu af og til. „Gildisdagsetningin\" efst á þessari síðu mun alltaf sýna dagsetningu nýjustu útgáfunnar. Verulegar breytingar verða tilkynntar í gegnum samþykkisbaner vafrakakanna.",
        "lb": "Mir kënnen dës Cookie-Richtlinn vun Zäit zu Zäit aktualiséieren. D'„Gëltegkeetsdatum\" uewen op dëser Säit weist ëmmer d'Datum vun der neuester Versioun. Wesentlech Ännerungen ginn iwwer de Cookie-Zoustëmmungsbanner matgedeelt.",
        "mk": 'Оваа Политика за колачиња може периодично да се ажурира. „Датумот на влегување во сила" на врвот на оваа страница секогаш ќе го прикажува датумот на последната верзија. За значајни промени ќе бидете известени преку банерот за согласност за колачиња.',
        "sq": 'Ne mund të përditësojmë periodikisht këtë Politikë të Skedarëve të Personalizimit. "Data e hyrjes në fuqi" në krye të kësaj faqeje do të tregojë gjithmonë datën e versionit më të fundit. Ndryshimet e rëndësishme do të komunikohen përmes banerit të miratimit të skedarëve të personalizimit.',
        "mt": "Nistgħu naġġornaw din il-Politika tal-Cookies minn żmien għal żmien. Id-\"Data tas-seħħ\" fl-aqwa ta' din il-paġna se turi dejjem id-data tal-aħħar verżjoni. Bidliet sinifikanti jiġu kkomunikati permezz tal-baner tal-kunsens tal-cookies.",
    },
    "s11_title": {
        "en": "11. Contact and Complaints",
        "pl": "11. Kontakt i skargi",
        "bg": "11. Контакт и жалби",
        "de": "11. Kontakt und Beschwerden",
        "fr": "11. Contact et réclamations",
        "es": "11. Contacto y reclamaciones",
        "it": "11. Contatti e reclami",
        "pt": "11. Contacto e reclamações",
        "pt-PT": "11. Contacto e reclamações",
        "nl": "11. Contact en klachten",
        "cs": "11. Kontakt a stížnosti",
        "sk": "11. Kontakt a sťažnosti",
        "hu": "11. Kapcsolat és panaszok",
        "ro": "11. Contact și reclamații",
        "hr": "11. Kontakt i pritužbe",
        "sr": "11. Kontakt i pritužbe",
        "sl": "11. Stik in pritožbe",
        "uk": "11. Контакт та скарги",
        "ru": "11. Контакт и жалобы",
        "tr": "11. İletişim ve Şikayetler",
        "el": "11. Επικοινωνία και παράπονα",
        "da": "11. Kontakt og klager",
        "sv": "11. Kontakt och klagomål",
        "no": "11. Kontakt og klager",
        "fi": "11. Yhteystiedot ja valitukset",
        "et": "11. Kontakt ja kaebused",
        "lv": "11. Kontakti un sūdzības",
        "lt": "11. Kontaktai ir skundai",
        "ga": "11. Teagmháil agus Gearáin",
        "is": "11. Samskipti og kvartanir",
        "lb": "11. Kontakt a Beschwerden",
        "mk": "11. Контакт и жалби",
        "sq": "11. Kontakti dhe Ankesat",
        "mt": "11. Kuntatt u Ilmenti",
    },
    "s11_authority_bg": {
        "en": "Lead Supervisory Authority (Bulgaria):\nCommission for Personal Data Protection (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaria\nhttps://www.cpdp.bg",
        "pl": "Organ nadzorczy (Bułgaria — wiodący organ):\nKomisja Ochrony Danych Osobowych (CPDP / КЗЛД)\nul. Prof. Cvetan Lazarov 2, Sofia 1592, Bułgaria\nhttps://www.cpdp.bg",
        "bg": "Надзорен орган (България — водещ надзорен орган):\nКомисия за защита на личните данни (КЗЛД)\nбул. \"Проф. Цветан Лазаров\" No. 2, София 1592, България\nhttps://www.cpdp.bg",
        "de": "Federführende Aufsichtsbehörde (Bulgarien):\nKommission für den Schutz personenbezogener Daten (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgarien\nhttps://www.cpdp.bg",
        "fr": "Autorité de contrôle principale (Bulgarie):\nCommission de protection des données personnelles (CPDP / КЗЛД)\n2 blvd. Prof. Tsvetan Lazarov, Sofia 1592, Bulgarie\nhttps://www.cpdp.bg",
        "es": "Autoridad de supervisión principal (Bulgaria):\nComisión para la Protección de Datos Personales (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofía 1592, Bulgaria\nhttps://www.cpdp.bg",
        "it": "Autorità di controllo capofila (Bulgaria):\nCommissione per la protezione dei dati personali (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaria\nhttps://www.cpdp.bg",
        "pt": "Autoridade de supervisão principal (Bulgária):\nComissão para a Proteção de Dados Pessoais (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgária\nhttps://www.cpdp.bg",
        "pt-PT": "Autoridade de supervisão principal (Bulgária):\nComissão para a Proteção de Dados Pessoais (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgária\nhttps://www.cpdp.bg",
        "nl": "Leidende toezichthoudende autoriteit (Bulgarije):\nCommissie voor de bescherming van persoonsgegevens (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgarije\nhttps://www.cpdp.bg",
        "cs": "Vedoucí dozorový úřad (Bulharsko):\nKomise pro ochranu osobních údajů (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulharsko\nhttps://www.cpdp.bg",
        "sk": "Vedúci dozorný orgán (Bulharsko):\nKomisia na ochranu osobných údajov (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulharsko\nhttps://www.cpdp.bg",
        "hu": "Vezető felügyeleti hatóság (Bulgária):\nSzemélyesadat-védelmi Bizottság (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgária\nhttps://www.cpdp.bg",
        "ro": "Autoritate de supraveghere principală (Bulgaria):\nComisia pentru Protecția Datelor cu Caracter Personal (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaria\nhttps://www.cpdp.bg",
        "hr": "Nadležno nadzorno tijelo (Bugarska):\nPovjerenstvo za zaštitu osobnih podataka (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bugarska\nhttps://www.cpdp.bg",
        "sr": "Nadležni nadzorni organ (Bugarska):\nKomisija za zaštitu ličnih podataka (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bugarska\nhttps://www.cpdp.bg",
        "sl": "Pristojni nadzorni organ (Bolgarija):\nKomisija za varstvo osebnih podatkov (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bolgarija\nhttps://www.cpdp.bg",
        "uk": "Провідний наглядовий орган (Болгарія):\nКомісія із захисту персональних даних (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Софія 1592, Болгарія\nhttps://www.cpdp.bg",
        "ru": "Ведущий надзорный орган (Болгария):\nКомиссия по защите персональных данных (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., София 1592, Болгария\nhttps://www.cpdp.bg",
        "tr": "Baş Denetleyici Otorite (Bulgaristan):\nKişisel Veri Koruma Komisyonu (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaristan\nhttps://www.cpdp.bg",
        "el": "Κύρια εποπτική αρχή (Βουλγαρία):\nΕπιτροπή Προστασίας Προσωπικών Δεδομένων (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Σόφια 1592, Βουλγαρία\nhttps://www.cpdp.bg",
        "da": "Ledende tilsynsmyndighed (Bulgarien):\nKommissionen for beskyttelse af personoplysninger (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgarien\nhttps://www.cpdp.bg",
        "sv": "Ledande tillsynsmyndighet (Bulgarien):\nKommissionen för skydd av personuppgifter (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgarien\nhttps://www.cpdp.bg",
        "no": "Ledende tilsynsmyndighet (Bulgaria):\nKommisjon for personvernsbeskyttelse (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaria\nhttps://www.cpdp.bg",
        "fi": "Johtava valvontaviranomainen (Bulgaria):\nHenkilötietosuojakomissio (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaria\nhttps://www.cpdp.bg",
        "et": "Juhtiv järelevalveasutus (Bulgaaria):\nIsikuandmete kaitse komisjon (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgaaria\nhttps://www.cpdp.bg",
        "lv": "Vadošā uzraudzības iestāde (Bulgārija):\nPersonas datu aizsardzības komisija (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgārija\nhttps://www.cpdp.bg",
        "lt": "Pirmaujanti priežiūros institucija (Bulgarija):\nAsmens duomenų apsaugos komisija (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofija 1592, Bulgarija\nhttps://www.cpdp.bg",
        "ga": "Príomhúdarás Maoirseachta (an Bhulgáir):\nCoimisiún um Chosaint Sonraí Pearsanta (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, an Bhulgáir\nhttps://www.cpdp.bg",
        "is": "Leiðandi eftirlitsyfirvald (Búlgaría):\nPersónuverndarnefnd (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofía 1592, Búlgaría\nhttps://www.cpdp.bg",
        "lb": "Federführende Aufsichtsbehörde (Bulgarien):\nKommissioun zum Schutz vun perséinlechen Donnéeën (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bulgarien\nhttps://www.cpdp.bg",
        "mk": "Водечки надзорен орган (Бугарија):\nКомисија за заштита на личните податоци (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Софија 1592, Бугарија\nhttps://www.cpdp.bg",
        "sq": "Autoriteti kryesor mbikëqyrës (Bullgaria):\nKomisioni për Mbrojtjen e të Dhënave Personale (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, Bullgaria\nhttps://www.cpdp.bg",
        "mt": "Awtorità ta' Sorveljanza Ewlenija (il-Bulgarija):\nKummissjoni għall-Protezzjoni tad-Data Personali (CPDP / КЗЛД)\n2 Prof. Tsvetan Lazarov Blvd., Sofia 1592, il-Bulgarija\nhttps://www.cpdp.bg",
    },
    "s11_authority_pl": {
        "en": "Concerned Supervisory Authority (Poland):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "pl": "Organ nadzorczy (Polska — organ właściwy):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "bg": "Надзорен орган (Полша — засегнат орган):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "de": "Betroffene Aufsichtsbehörde (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "fr": "Autorité de contrôle concernée (Pologne):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "es": "Autoridad de supervisión competente (Polonia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "it": "Autorità di controllo competente (Polonia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "pt": "Autoridade de supervisão competente (Polónia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "pt-PT": "Autoridade de supervisão competente (Polónia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "nl": "Betrokken toezichthoudende autoriteit (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "cs": "Dotčený dozorový úřad (Polsko):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "sk": "Dotknutý dozorný orgán (Poľsko):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "hu": "Érintett felügyeleti hatóság (Lengyelország):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "ro": "Autoritate de supraveghere competentă (Polonia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "hr": "Nadležno nadzorno tijelo (Poljska):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "sr": "Nadležni nadzorni organ (Poljska):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "sl": "Pristojni nadzorni organ (Poljska):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "uk": "Відповідний наглядовий орган (Польща):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "ru": "Соответствующий надзорный орган (Польша):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "tr": "İlgili Denetleyici Otorite (Polonya):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "el": "Αρμόδια εποπτική αρχή (Πολωνία):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "da": "Berørt tilsynsmyndighed (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "sv": "Berörd tillsynsmyndighet (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "no": "Berørt tilsynsmyndighet (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "fi": "Asiaankuuluva valvontaviranomainen (Puola):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "et": "Asjakohane järelevalveasutus (Poola):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "lv": "Attiecīgā uzraudzības iestāde (Polija):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "lt": "Atitinkama priežiūros institucija (Lenkija):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "ga": "Údarás Maoirseachta Lena mBaineann (an Pholainn):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "is": "Viðkomandi eftirlitsyfirvald (Pólland):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "lb": "Betroffene Aufsichtsbehörde (Polen):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "mk": "Надлежен надзорен орган (Полска):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "sq": "Autoriteti mbikëqyrës kompetent (Polonia):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
        "mt": "Awtorità ta' Sorveljanza Kkonċernata (il-Polonja):\nUrząd Ochrony Danych Osobowych (UODO)\nul. Stawki 2, 00-193 Warszawa\nhttps://uodo.gov.pl",
    },
    "last_updated": {
        "en": "Last updated: May 2026",
        "pl": "Ostatnia aktualizacja: maj 2026",
        "bg": "Последна актуализация: май 2026 г.",
        "de": "Zuletzt aktualisiert: Mai 2026",
        "fr": "Dernière mise à jour : mai 2026",
        "es": "Última actualización: mayo de 2026",
        "it": "Ultimo aggiornamento: maggio 2026",
        "pt": "Última atualização: maio de 2026",
        "pt-PT": "Última atualização: maio de 2026",
        "nl": "Laatst bijgewerkt: mei 2026",
        "cs": "Poslední aktualizace: květen 2026",
        "sk": "Posledná aktualizácia: máj 2026",
        "hu": "Utolsó frissítés: 2026. május",
        "ro": "Ultima actualizare: mai 2026",
        "hr": "Zadnje ažuriranje: svibanj 2026.",
        "sr": "Poslednje ažuriranje: maj 2026.",
        "sl": "Zadnja posodobitev: maj 2026",
        "uk": "Останнє оновлення: травень 2026 р.",
        "ru": "Последнее обновление: май 2026 г.",
        "tr": "Son güncelleme: Mayıs 2026",
        "el": "Τελευταία ενημέρωση: Μάιος 2026",
        "da": "Sidst opdateret: maj 2026",
        "sv": "Senast uppdaterad: maj 2026",
        "no": "Sist oppdatert: mai 2026",
        "fi": "Viimeksi päivitetty: toukokuu 2026",
        "et": "Viimati uuendatud: mai 2026",
        "lv": "Pēdējo reizi atjaunināts: 2026. gada maijs",
        "lt": "Paskutinį kartą atnaujinta: 2026 m. gegužė",
        "ga": "Nuashonraithe go deireanach: Bealtaine 2026",
        "is": "Síðast uppfært: maí 2026",
        "lb": "Zuletzt aktualiséiert: Mee 2026",
        "mk": "Последно ажурирано: мај 2026",
        "sq": "Përditësuar së fundi: Maj 2026",
        "mt": "Aġġornat l-aħħar: Mejju 2026",
    },
}


def seed():
    with engine.begin() as conn:
        count = 0
        for key, lang_map in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_map.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (lang, key, value)
                        VALUES (:lang, :key, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        print(f"[seed_cookies_p23] Upserted {count} rows.")


if __name__ == "__main__":
    seed()
