"""
seed_terms_p2_bodies.py  —  Nevumo | namespace: terms
Key: art2_body (34 езика)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_terms_p2_bodies
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "art2_body": {
        "en": (
            '2.1 Nevumo is an intermediary platform. We connect clients with independent service '
            'providers. We do not provide the services listed on the platform ourselves, and we '
            'are not a party to the contract concluded between the client and the provider.\n\n'
            '2.2 The contract for the service (e.g. cleaning, plumbing, massage therapy) is '
            'concluded directly between you (the client) and the service provider. Nevumo '
            'facilitates this contact but bears no responsibility for the quality, timeliness, '
            'or result of the service unless otherwise stated.\n\n'
            '2.3 Nevumo acts as an information society service provider within the meaning of '
            'Directive 2000/31/EC and Regulation (EU) 2022/2065 (Digital Services Act — DSA). '
            'Nevumo stores third-party content (provider listings) and is not liable for that '
            'content provided it acts expeditiously to remove or disable access upon obtaining '
            'actual knowledge of its unlawful nature (DSA Article 6 safe harbour).\n\n'
            '2.4 Nevumo does not employ service providers and is not responsible for their '
            'professional qualifications, licences, insurance, or compliance with applicable '
            'professional regulations.'
        ),
        "pl": (
            '2.1 Nevumo jest platformą pośredniczącą. Nevumo umożliwia kontakt pomiędzy '
            'Klientami a niezależnymi Usługodawcami. Nevumo nie jest stroną umowy zawieranej '
            'pomiędzy Klientem a Usługodawcą o świadczenie konkretnej usługi.\n\n'
            '2.2 Umowa o świadczenie usługi (np. sprzątanie, hydraulika, masaż) jest zawierana '
            'bezpośrednio pomiędzy Klientem a Usługodawcą. Nevumo ponosi odpowiedzialność '
            'wyłącznie za prawidłowe działanie platformy, nie zaś za jakość, wynik ani '
            'terminowość świadczonej usługi.\n\n'
            '2.3 Nevumo jest dostawcą usługi hostingu w rozumieniu art. 14 UŚUDE oraz art. 6 '
            'rozporządzenia DSA (UE) 2022/2065. Nevumo przechowuje treści zamieszczane przez '
            'Usługodawców i nie ponosi za nie odpowiedzialności, jeżeli niezwłocznie podejmuje '
            'działania w celu usunięcia treści bezprawnych po uzyskaniu informacji o ich '
            'bezprawnym charakterze.\n\n'
            '2.4 Nevumo nie zatrudnia Usługodawców i nie ponosi odpowiedzialności za ich '
            'kwalifikacje zawodowe, posiadane uprawnienia, ubezpieczenia ani zgodność z '
            'obowiązującymi przepisami zawodowymi.'
        ),
        "bg": (
            '2.1 Nevumo е посредническа платформа. Дружеството осигурява свързаност между '
            'Клиенти и независими Доставчици на услуги. Nevumo не е страна по договора, '
            'сключен между Клиента и Доставчика за конкретна услуга.\n\n'
            '2.2 Договорът за услугата (напр. почистване, водопроводни услуги, масаж) се '
            'сключва пряко между Клиента и Доставчика. Nevumo улеснява тази връзка, но не '
            'носи отговорност за качеството, навременността или резултата от услугата.\n\n'
            '2.3 Nevumo е доставчик на услуги на информационното общество по смисъла на ЗЕТ '
            'и Регламент (ЕС) 2022/2065 (Акт за цифровите услуги — DSA). Nevumo съхранява '
            'съдържание, публикувано от Доставчиците, и не носи отговорност за него при '
            'условие, че действа своевременно за отстраняване на незаконно съдържание след '
            'узнаване.\n\n'
            '2.4 Nevumo не е работодател на Доставчиците и не носи отговорност за тяхната '
            'квалификация, лицензи, застраховки или спазване на приложимите регулаторни '
            'изисквания.'
        ),
        "cs": (
            '2.1 Nevumo je zprostředkovatelská platforma. Propojujeme klienty s nezávislými '
            'poskytovateli služeb. Sami služby uvedené na platformě neposkytujeme a nejsme '
            'stranou smlouvy uzavřené mezi klientem a poskytovatelem.\n\n'
            '2.2 Smlouva o poskytnutí služby (např. úklid, instalatérství, masáže) je uzavřena '
            'přímo mezi vámi (klientem) a poskytovatelem služby. Nevumo tento kontakt '
            'zprostředkovává, ale nenese odpovědnost za kvalitu, včasnost ani výsledek '
            'poskytnuté služby.\n\n'
            '2.3 Nevumo působí jako poskytovatel služeb informační společnosti ve smyslu '
            'směrnice 2000/31/ES a nařízení (EU) 2022/2065 (Akt o digitálních službách — DSA). '
            'Nevumo uchovává obsah třetích stran (nabídky poskytovatelů) a nenese odpovědnost '
            'za tento obsah, pokud bezodkladně jedná k jeho odstranění po zjištění jeho '
            'protiprávní povahy (bezpečný přístav dle čl. 6 DSA).\n\n'
            '2.4 Nevumo nezaměstnává poskytovatele služeb a nenese odpovědnost za jejich '
            'odbornou kvalifikaci, licence, pojištění ani dodržování platných profesních předpisů.'
        ),
        "da": (
            '2.1 Nevumo er en formidlingsplatform. Vi forbinder klienter med uafhængige '
            'serviceudbydere. Vi leverer ikke selv de tjenester, der er angivet på platformen, '
            'og vi er ikke part i kontrakten indgået mellem klienten og udbyderen.\n\n'
            '2.2 Kontrakten om tjenesteydelsen (f.eks. rengøring, VVS, massage) indgås direkte '
            'mellem dig (klienten) og tjenesteudbyderen. Nevumo faciliterer denne kontakt, men '
            'bærer intet ansvar for kvaliteten, rettidigheden eller resultatet af ydelsen.\n\n'
            '2.3 Nevumo fungerer som udbyder af informationssamfundstjenester i henhold til '
            'direktiv 2000/31/EF og forordning (EU) 2022/2065 (Digital Services Act — DSA). '
            'Nevumo opbevarer tredjepartsindhold (udbyderfortegnelser) og er ikke ansvarlig for '
            'dette indhold, forudsat at det handler hurtigt for at fjerne ulovligt indhold '
            'efter kendskab til dets ulovlige karakter (DSA art. 6 safe harbour).\n\n'
            '2.4 Nevumo ansætter ikke serviceudbydere og er ikke ansvarlig for deres faglige '
            'kvalifikationer, licenser, forsikringer eller overholdelse af gældende faglige regler.'
        ),
        "de": (
            '2.1 Nevumo ist eine Vermittlungsplattform. Wir verbinden Kunden mit unabhängigen '
            'Dienstleistern. Wir erbringen die auf der Plattform aufgeführten Dienste nicht '
            'selbst und sind nicht Partei des zwischen Kunden und Anbieter geschlossenen '
            'Vertrages.\n\n'
            '2.2 Der Vertrag über die Dienstleistung (z. B. Reinigung, Sanitärarbeiten, '
            'Massagetherapie) wird direkt zwischen Ihnen (dem Kunden) und dem Dienstleister '
            'abgeschlossen. Nevumo erleichtert diesen Kontakt, übernimmt jedoch keine '
            'Verantwortung für die Qualität, Pünktlichkeit oder das Ergebnis der Dienstleistung.\n\n'
            '2.3 Nevumo handelt als Anbieter von Diensten der Informationsgesellschaft im Sinne '
            'der Richtlinie 2000/31/EG und der Verordnung (EU) 2022/2065 (Digital Services Act '
            '— DSA). Nevumo speichert Inhalte Dritter (Anbietereinträge) und haftet nicht für '
            'diese Inhalte, sofern es unverzüglich handelt, um rechtswidrige Inhalte nach '
            'Kenntnis davon zu entfernen (sicherer Hafen nach Art. 6 DSA).\n\n'
            '2.4 Nevumo beschäftigt keine Dienstleister und übernimmt keine Verantwortung für '
            'deren fachliche Qualifikationen, Lizenzen, Versicherungen oder die Einhaltung '
            'geltender Berufsvorschriften.'
        ),
        "el": (
            '2.1 Το Nevumo είναι πλατφόρμα διαμεσολάβησης. Συνδέουμε πελάτες με ανεξάρτητους '
            'παρόχους υπηρεσιών. Δεν παρέχουμε οι ίδιοι τις υπηρεσίες που αναγράφονται στην '
            'πλατφόρμα και δεν είμαστε συμβαλλόμενο μέρος στη σύμβαση μεταξύ πελάτη και '
            'παρόχου.\n\n'
            '2.2 Η σύμβαση για την υπηρεσία (π.χ. καθαρισμός, υδραυλικές εργασίες, μασάζ) '
            'συνάπτεται απευθείας μεταξύ εσάς (του πελάτη) και του παρόχου υπηρεσιών. Το '
            'Nevumo διευκολύνει αυτή την επαφή αλλά δεν φέρει ευθύνη για την ποιότητα, την '
            'έγκαιρη εκτέλεση ή το αποτέλεσμα της υπηρεσίας.\n\n'
            '2.3 Το Nevumo λειτουργεί ως πάροχος υπηρεσιών της κοινωνίας της πληροφορίας '
            'κατά την έννοια της Οδηγίας 2000/31/ΕΚ και του Κανονισμού (ΕΕ) 2022/2065 '
            '(Πράξη για τις Ψηφιακές Υπηρεσίες — DSA). Το Nevumo αποθηκεύει περιεχόμενο '
            'τρίτων (καταχωρίσεις παρόχων) και δεν φέρει ευθύνη για αυτό, εφόσον ενεργεί '
            'άμεσα για την αφαίρεσή του μετά τη γνώση της παράνομης φύσης του '
            '(ασφαλής λιμένας άρθρου 6 DSA).\n\n'
            '2.4 Το Nevumo δεν απασχολεί παρόχους υπηρεσιών και δεν είναι υπεύθυνο για τα '
            'επαγγελματικά τους προσόντα, άδειες, ασφαλίσεις ή συμμόρφωση με τους ισχύοντες '
            'επαγγελματικούς κανονισμούς.'
        ),
        "es": (
            '2.1 Nevumo es una plataforma intermediaria. Conectamos a los clientes con '
            'proveedores de servicios independientes. No prestamos nosotros mismos los servicios '
            'listados en la plataforma y no somos parte del contrato celebrado entre el cliente '
            'y el proveedor.\n\n'
            '2.2 El contrato de servicio (p. ej. limpieza, fontanería, masaje terapéutico) se '
            'celebra directamente entre usted (el cliente) y el proveedor de servicios. Nevumo '
            'facilita este contacto pero no asume responsabilidad por la calidad, puntualidad '
            'o resultado del servicio.\n\n'
            '2.3 Nevumo actúa como proveedor de servicios de la sociedad de la información en '
            'el sentido de la Directiva 2000/31/CE y el Reglamento (UE) 2022/2065 (Ley de '
            'Servicios Digitales — DSA). Nevumo almacena contenido de terceros (listados de '
            'proveedores) y no es responsable de dicho contenido siempre que actúe con '
            'celeridad para eliminarlo tras conocer su carácter ilícito '
            '(puerto seguro del artículo 6 DSA).\n\n'
            '2.4 Nevumo no emplea a los proveedores de servicios y no es responsable de sus '
            'cualificaciones profesionales, licencias, seguros ni cumplimiento de la normativa '
            'profesional aplicable.'
        ),
        "et": (
            '2.1 Nevumo on vahendusplatvorm. Ühendame kliente sõltumatute teenusepakkujatega. '
            'Me ei osuta ise platvormil loetletud teenuseid ega ole poolteks kliendi ja pakkuja '
            'vahel sõlmitud lepingus.\n\n'
            '2.2 Teenuse leping (nt koristamine, torustikutööd, massaaž) sõlmitakse otse teie '
            '(kliendi) ja teenusepakkuja vahel. Nevumo hõlbustab seda kontakti, kuid ei vastuta '
            'teenuse kvaliteedi, õigeaegsuse ega tulemuse eest.\n\n'
            '2.3 Nevumo tegutseb infoühiskonna teenuse osutajana direktiivi 2000/31/EÜ ja '
            'määruse (EL) 2022/2065 (Digilepingute seadus — DSA) tähenduses. Nevumo talletab '
            'kolmandate isikute sisu (pakkujate loendid) ega vastuta selle sisu eest, '
            'tingimusel et tegutseb viivitamata ebaseadusliku sisu eemaldamiseks pärast '
            'sellest teadlikuks saamist (DSA artikli 6 turvaala).\n\n'
            '2.4 Nevumo ei tööta teenusepakkujaid ja ei vastuta nende erialase '
            'kvalifikatsiooni, litsentside, kindlustuse ega kohaldatavate ametialaste '
            'eeskirjade järgimise eest.'
        ),
        "fi": (
            '2.1 Nevumo on välitysalusta. Yhdistämme asiakkaat riippumattomiin '
            'palveluntarjoajiin. Emme itse tarjoa alustalla lueteltuja palveluja emmekä ole '
            'osapuolena asiakkaan ja tarjoajan välisessä sopimuksessa.\n\n'
            '2.2 Palvelusopimus (esim. siivous, putkityöt, hieronta) tehdään suoraan teidän '
            '(asiakkaan) ja palveluntarjoajan välillä. Nevumo helpottaa tätä yhteydenpitoa '
            'mutta ei vastaa palvelun laadusta, oikea-aikaisuudesta tai tuloksesta.\n\n'
            '2.3 Nevumo toimii tietoyhteiskunnan palvelun tarjoajana direktiivin 2000/31/EY '
            'ja asetuksen (EU) 2022/2065 (Digipalvelusäädös — DSA) tarkoittamalla tavalla. '
            'Nevumo tallentaa kolmansien osapuolten sisältöä (palveluntarjoajien listauksia) '
            'eikä vastaa tästä sisällöstä edellyttäen, että se toimii viipymättä laittoman '
            'sisällön poistamiseksi saatuaan siitä tiedon (DSA 6 artiklan turvasatama).\n\n'
            '2.4 Nevumo ei työllistä palveluntarjoajia eikä vastaa heidän ammatillisista '
            'pätevyyksistään, lisensseistään, vakuutuksistaan tai ammattisäädösten '
            'noudattamisesta.'
        ),
        "fr": (
            '2.1 Nevumo est une plateforme d\'intermédiation. Nous mettons en relation des '
            'clients avec des prestataires de services indépendants. Nous ne fournissons pas '
            'nous-mêmes les services répertoriés sur la plateforme et nous ne sommes pas partie '
            'au contrat conclu entre le client et le prestataire.\n\n'
            '2.2 Le contrat de prestation de services (p. ex. nettoyage, plomberie, massage) '
            'est conclu directement entre vous (le client) et le prestataire de services. '
            'Nevumo facilite ce contact mais n\'assume aucune responsabilité quant à la '
            'qualité, la ponctualité ou le résultat du service.\n\n'
            '2.3 Nevumo agit en tant que prestataire de services de la société de '
            'l\'information au sens de la directive 2000/31/CE et du règlement (UE) 2022/2065 '
            '(Règlement sur les services numériques — DSA). Nevumo stocke des contenus de '
            'tiers (annonces de prestataires) et n\'est pas responsable de ces contenus, à '
            'condition d\'agir promptement pour les supprimer après avoir eu connaissance de '
            'leur caractère illicite (port sûr de l\'article 6 du DSA).\n\n'
            '2.4 Nevumo n\'emploie pas de prestataires de services et n\'est pas responsable '
            'de leurs qualifications professionnelles, licences, assurances ou conformité aux '
            'réglementations professionnelles applicables.'
        ),
        "ga": (
            '2.1 Is ardán idirghabhála é Nevumo. Cuirimid cliaint i dteagmháil le soláthróirí '
            'seirbhíse neamhspleácha. Ní sholáthraímid féin na seirbhísí atá liostaithe ar an '
            'ardán, agus ní páirtí muid sa chonradh idir an cliant agus an soláthróir.\n\n'
            '2.2 Déantar an conradh seirbhíse (m.sh. glanadh, pluiméireacht, massáiste) go '
            'díreach idir tú féin (an cliant) agus an soláthróir seirbhíse. Éascaíonn Nevumo '
            'an teagmháil seo ach ní ghlacann sé aon fhreagracht as cáilíocht, tráthúlacht ná '
            'toradh na seirbhíse.\n\n'
            '2.3 Gníomhaíonn Nevumo mar sholáthróir seirbhíse chomhaltais an tsochaí '
            'faisnéise de réir bhrí Threoir 2000/31/CE agus Rialachán (AE) 2022/2065 '
            '(Gníomh um Sheirbhísí Digiteacha — DSA). Stórálann Nevumo ábhar tríú páirtí '
            'agus níl sé faoi dhliteanas as an ábhar sin ar choinníoll go ngníomhaíonn sé go '
            'pras chun ábhar neamhdhleathach a bhaint tar éis eolas a fháil air '
            '(tearmann sábháilte Airteagal 6 DSA).\n\n'
            '2.4 Ní fhostaíonn Nevumo soláthróirí seirbhíse agus níl sé freagrach as a '
            'gcáilíochtaí gairmiúla, ceadúnais, árachas ná comhlíonadh na rialachán '
            'gairmiúil is infheidhme.'
        ),
        "hr": (
            '2.1 Nevumo je posrednička platforma. Povezujemo klijente s neovisnim davateljima '
            'usluga. Sami ne pružamo usluge navedene na platformi i nismo stranka ugovora '
            'sklopljenog između klijenta i davatelja usluga.\n\n'
            '2.2 Ugovor o usluzi (npr. čišćenje, vodoinstalaterstvo, masaža) sklopljen je '
            'izravno između vas (klijenta) i davatelja usluge. Nevumo olakšava ovaj kontakt, '
            'ali ne preuzima odgovornost za kvalitetu, pravodobnost ili rezultat usluge.\n\n'
            '2.3 Nevumo djeluje kao pružatelj usluga informacijskog društva u smislu Direktive '
            '2000/31/EZ i Uredbe (EU) 2022/2065 (Akt o digitalnim uslugama — DSA). Nevumo '
            'pohranjuje sadržaj trećih strana (profili davatelja usluga) i nije odgovoran za '
            'taj sadržaj pod uvjetom da promptno poduzme mjere za uklanjanje nezakonitog '
            'sadržaja nakon saznanja o njegovoj nezakonitoj prirodi '
            '(sigurna luka prema čl. 6 DSA).\n\n'
            '2.4 Nevumo ne zapošljava davatelje usluga i nije odgovoran za njihove stručne '
            'kvalifikacije, licence, osiguranje ili usklađenost s primjenjivim profesionalnim '
            'propisima.'
        ),
        "hu": (
            '2.1 A Nevumo egy közvetítő platform. Ügyfeleket kapcsolunk össze független '
            'szolgáltatókkal. Magunk nem nyújtjuk a platformon feltüntetett szolgáltatásokat, '
            'és nem vagyunk felei az ügyfél és a szolgáltató között kötött szerződésnek.\n\n'
            '2.2 A szolgáltatási szerződés (pl. takarítás, vízvezetékszerelés, masszázs) '
            'közvetlenül Ön (az ügyfél) és a szolgáltató között jön létre. A Nevumo '
            'megkönnyíti ezt a kapcsolatot, de nem vállal felelősséget a szolgáltatás '
            'minőségéért, időszerűségéért vagy eredményéért.\n\n'
            '2.3 A Nevumo információs társadalmi szolgáltatóként működik a 2000/31/EK '
            'irányelv és az (EU) 2022/2065 rendelet (Digitális Szolgáltatásokról szóló törvény '
            '— DSA) értelmében. A Nevumo harmadik felek tartalmait tárolja és nem felel azért '
            'a tartalomért, feltéve, hogy jogellenes jellegének tudomásra jutásakor '
            'haladéktalanul intézkedik annak eltávolításáról '
            '(DSA 6. cikk szerinti biztonságos kikötő).\n\n'
            '2.4 A Nevumo nem alkalmaz szolgáltatókat, és nem felelős szakmai '
            'képzettségükért, engedélyeikért, biztosításaikért vagy az alkalmazandó szakmai '
            'szabályozásnak való megfelelésükért.'
        ),
        "is": (
            '2.1 Nevumo er milliliðavettvangur. Við tengum viðskiptavini við sjálfstæða '
            'þjónustuaðila. Við bjóðum ekki upp á þær þjónustur sem eru skráðar á vettvangi '
            'sjálfir og við erum ekki aðilar að samningi milli viðskiptavinar og '
            'þjónustuaðila.\n\n'
            '2.2 Þjónustusamningurinn (t.d. þrif, pípulagning, nudd) er gerður beint á milli '
            'ykkar (viðskiptavinarins) og þjónustuaðilans. Nevumo auðveldar þennan samband en '
            'ber enga ábyrgð á gæðum, tímanleika eða niðurstöðu þjónustunnar.\n\n'
            '2.3 Nevumo starfar sem þjónustuaðili upplýsingasamfélagsins í skilningi '
            'tilskipunar 2000/31/EB og reglugerðar (ESB) 2022/2065 (Lög um stafrænar '
            'þjónustur — DSA). Nevumo geymir efni þriðja aðila og ber ekki ábyrgð á því '
            'efni að því gefnu að það breyti skjótt til að fjarlægja ólöglegt efni eftir '
            'að það verður þess áskynja (örugg höfn samkvæmt 6. gr. DSA).\n\n'
            '2.4 Nevumo ræður ekki þjónustuaðila og ber ekki ábyrgð á faglegri menntun '
            'þeirra, leyfum, tryggingum eða fylgni við gildandi fagreglugerðir.'
        ),
        "it": (
            '2.1 Nevumo è una piattaforma di intermediazione. Mettiamo in contatto i clienti '
            'con prestatori di servizi indipendenti. Non forniamo noi stessi i servizi elencati '
            'sulla piattaforma e non siamo parte del contratto stipulato tra il cliente e il '
            'prestatore.\n\n'
            '2.2 Il contratto di servizio (ad es. pulizie, idraulica, massaggi) viene stipulato '
            'direttamente tra voi (il cliente) e il prestatore di servizi. Nevumo facilita '
            'questo contatto ma non si assume alcuna responsabilità per la qualità, la '
            'tempestività o il risultato del servizio.\n\n'
            '2.3 Nevumo agisce come fornitore di servizi della società dell\'informazione ai '
            'sensi della direttiva 2000/31/CE e del regolamento (UE) 2022/2065 (Regolamento '
            'sui servizi digitali — DSA). Nevumo conserva contenuti di terze parti (annunci '
            'dei prestatori) e non è responsabile di tali contenuti a condizione che agisca '
            'prontamente per rimuovere i contenuti illegali dopo aver acquisito conoscenza '
            'della loro natura illecita (porto sicuro ai sensi dell\'art. 6 DSA).\n\n'
            '2.4 Nevumo non assume i prestatori di servizi e non è responsabile delle loro '
            'qualifiche professionali, licenze, assicurazioni o conformità alle normative '
            'professionali applicabili.'
        ),
        "lb": (
            '2.1 Nevumo ass eng Vermëttlungsplattform. Mir verbannen Klienten mat '
            'onofhängege Serviceprestatairen. Mir bidden d\'Servicer op der Plattform net '
            'selwer un a sinn net Partei vum Kontrakt tëschent dem Klient an dem Prestataire.\n\n'
            '2.2 De Servicekontrakt (z.B. Botzen, Sanitärarbeiten, Massage) gëtt direkt '
            'tëschent Iech (dem Klient) an dem Serviceprestataire ofgeschloss. Nevumo '
            'erliichtert dëse Kontakt, mee iwwerhëlt keng Verantwortung fir d\'Qualitéit, '
            'd\'Pünktlechkeet oder d\'Resultat vum Service.\n\n'
            '2.3 Nevumo handelt als Ubidder vun Informatiounsgesellschaftsservicer am Sënn '
            'vun der Direktiv 2000/31/EG an der Verordnung (EU) 2022/2065 (Digital Services '
            'Act — DSA). Nevumo späichert Drëttpartei-Inhalter a ass net responsabel fir dës '
            'Inhalter, virausgesat datt et direkt handelt fir illegal Inhalter z\'entfernen '
            'nodeems et dovun erfuere gouf (séchere Hafen no Art. 6 DSA).\n\n'
            '2.4 Nevumo beschäftegt keng Serviceprestatairen a ass net verantwortlech fir hir '
            'berufflech Qualifikatiounen, Lizenzen, Versécherungen oder d\'Abalancéiere mat '
            'den gëltege Berufsvirschrëften.'
        ),
        "lt": (
            '2.1 Nevumo yra tarpininkavimo platforma. Jungiame klientus su nepriklausomais '
            'paslaugų teikėjais. Mes patys neteikiame platformoje išvardytų paslaugų ir '
            'nesame sutarties, sudarytos tarp kliento ir teikėjo, šalis.\n\n'
            '2.2 Paslaugų sutartis (pvz., valymas, santechnikos darbai, masažas) sudaroma '
            'tiesiogiai tarp jūsų (kliento) ir paslaugų teikėjo. Nevumo palengvina šį ryšį, '
            'tačiau neatsako už paslaugos kokybę, savalaikiškumą ar rezultatą.\n\n'
            '2.3 Nevumo veikia kaip informacinės visuomenės paslaugų teikėjas, kaip apibrėžta '
            'Direktyvoje 2000/31/EB ir Reglamente (ES) 2022/2065 (Skaitmeninių paslaugų aktas '
            '— DSA). Nevumo saugo trečiųjų šalių turinį (paslaugų teikėjų sąrašus) ir '
            'neatsako už tą turinį, jei sužinojus apie jo neteisėtą pobūdį nedelsiant imasi '
            'veiksmų jam pašalinti (DSA 6 str. saugioji prieplauka).\n\n'
            '2.4 Nevumo nesamdo paslaugų teikėjų ir neatsako už jų profesinę kvalifikaciją, '
            'licencijas, draudimą ar atitiktį taikomiems profesiniams reglamentams.'
        ),
        "lv": (
            '2.1 Nevumo ir starpniecības platforma. Mēs savienojam klientus ar neatkarīgiem '
            'pakalpojumu sniedzējiem. Mēs paši nesniedz platformā norādītos pakalpojumus un '
            'neesam puse līgumā, kas noslēgts starp klientu un sniedzēju.\n\n'
            '2.2 Pakalpojuma līgums (piemēram, tīrīšana, santehnikas darbi, masāža) tiek '
            'noslēgts tieši starp jums (klientu) un pakalpojumu sniedzēju. Nevumo atvieglo '
            'šo kontaktu, bet neatbild par pakalpojuma kvalitāti, savlaicīgumu vai rezultātu.\n\n'
            '2.3 Nevumo darbojas kā informācijas sabiedrības pakalpojumu sniedzējs Direktīvas '
            '2000/31/EK un Regulas (ES) 2022/2065 (Digitālo pakalpojumu akts — DSA) izpratnē. '
            'Nevumo uzglabā trešo pušu saturu (pakalpojumu sniedzēju sarakstus) un neatbild '
            'par šo saturu, ja pēc tā nelikumīgā rakstura uzzināšanas nekavējoties rīkojas '
            'tā noņemšanai (DSA 6. panta drošais ostas noteikums).\n\n'
            '2.4 Nevumo nenodarbina pakalpojumu sniedzējus un neatbild par viņu profesionālo '
            'kvalifikāciju, licencēm, apdrošināšanu vai atbilstību piemērojamiem '
            'profesionālajiem noteikumiem.'
        ),
        "mk": (
            '2.1 Nevumo е посредничка платформа. Ги поврзуваме клиентите со независни '
            'даватели на услуги. Ние самите не ги давамe услугите наведени на платформата '
            'и не сме странка во договорот склучен меѓу клиентот и давателот.\n\n'
            '2.2 Договорот за услугата (напр. чистење, водоводни работи, масажа) се '
            'склучува директно меѓу вас (клиентот) и давателот на услугата. Nevumo го '
            'олеснува овој контакт, но не сноси одговорност за квалитетот, навременоста '
            'или резултатот на услугата.\n\n'
            '2.3 Nevumo дејствува како давател на услуги на информациското општество во '
            'смисла на Директивата 2000/31/ЕЗ и Уредбата (ЕУ) 2022/2065 (Акт за дигитални '
            'услуги — DSA). Nevumo складира содржини на трети страни и не одговара за таа '
            'содржина, под услов да постапи веднаш за нејзино отстранување по дознавањето '
            'за нејзиниот незаконски карактер (безбедна пристаништа согласно чл. 6 DSA).\n\n'
            '2.4 Nevumo не вработува даватели на услуги и не одговара за нивната стручна '
            'квалификација, лиценци, осигурување или усогласеност со применливите '
            'професионални прописи.'
        ),
        "mt": (
            '2.1 Nevumo hija pjattaforma ta\' intermedjazzjoni. Norbtu lill-klijenti ma\' '
            'fornituri ta\' servizzi indipendenti. Aħna stess ma nipprovdux is-servizzi '
            'elenkati fuq il-pjattaforma u m\'aħniex parti fil-kuntratt bejn il-klijent u '
            'l-fornitur.\n\n'
            '2.2 Il-kuntratt għas-servizz (eż. tindif, dbanat, massaġġ) jiġi konkluż '
            'direttament bejnek (il-klijent) u l-fornitur tas-servizz. Nevumo jiffaċilita '
            'dan il-kuntatt iżda ma jassumix responsabbiltà għall-kwalità, il-puntwalità '
            'jew ir-riżultat tas-servizz.\n\n'
            '2.3 Nevumo jaġixxi bħala fornitur ta\' servizzi tas-soċjetà tal-informazzjoni '
            'skont id-Direttiva 2000/31/KE u r-Regolament (UE) 2022/2065 (Att dwar '
            'is-Servizzi Diġitali — DSA). Nevumo jaħżen kontenut ta\' partijiet terzi u '
            'mhuwiex responsabbli għal dak il-kontenut sakemm jaġixxi malajr sabiex ineħħi '
            'kontenut illegali wara li jikseb għarfien dwar in-natura illegali tiegħu '
            '(port sigur ta\' Artikolu 6 DSA).\n\n'
            '2.4 Nevumo ma jimpjegax fornituri ta\' servizzi u mhuwiex responsabbli '
            'għall-kwalifiki professjonali tagħhom, liċenzji, assigurazzjoni jew konformità '
            'mar-regolamenti professjonali applikabbli.'
        ),
        "nl": (
            '2.1 Nevumo is een bemiddelingsplatform. Wij verbinden klanten met onafhankelijke '
            'serviceproviders. Wij leveren de op het platform vermelde diensten niet zelf en '
            'zijn geen partij bij de overeenkomst die tussen de klant en de provider wordt '
            'gesloten.\n\n'
            '2.2 De serviceovereenkomst (bijv. schoonmaak, loodgieterswerk, massagetherapie) '
            'wordt rechtstreeks gesloten tussen u (de klant) en de serviceprovider. Nevumo '
            'faciliteert dit contact maar draagt geen verantwoordelijkheid voor de kwaliteit, '
            'tijdigheid of het resultaat van de dienst.\n\n'
            '2.3 Nevumo treedt op als aanbieder van diensten van de informatiemaatschappij '
            'in de zin van Richtlijn 2000/31/EG en Verordening (EU) 2022/2065 '
            '(Digitaledienstenverordening — DSA). Nevumo slaat inhoud van derden op '
            '(vermeldingen van providers) en is niet aansprakelijk voor die inhoud, mits het '
            'onverwijld handelt om onwettige inhoud te verwijderen nadat het er kennis van '
            'heeft gekregen (veilige haven van artikel 6 DSA).\n\n'
            '2.4 Nevumo stelt geen serviceproviders in dienst en is niet verantwoordelijk '
            'voor hun beroepskwalificaties, licenties, verzekeringen of naleving van de '
            'toepasselijke beroepsregelgeving.'
        ),
        "no": (
            '2.1 Nevumo er en formidlingsplattform. Vi forbinder kunder med uavhengige '
            'tjenesteleverandører. Vi tilbyr ikke selv tjenestene som er oppført på '
            'plattformen, og vi er ikke part i kontrakten inngått mellom kunden og '
            'leverandøren.\n\n'
            '2.2 Tjenestekontrakten (f.eks. rengjøring, rørleggerarbeid, massasje) inngås '
            'direkte mellom deg (kunden) og tjenesteleverandøren. Nevumo tilrettelegger for '
            'denne kontakten, men er ikke ansvarlig for tjenestens kvalitet, aktualitet '
            'eller resultat.\n\n'
            '2.3 Nevumo opptrer som leverandør av informasjonssamfunnstjenester i henhold '
            'til direktiv 2000/31/EF og forordning (EU) 2022/2065 (Digital Services Act '
            '— DSA). Nevumo lagrer tredjepartsinnhold (leverandøroppføringer) og er ikke '
            'ansvarlig for dette innholdet, forutsatt at det handler raskt for å fjerne '
            'ulovlig innhold etter å ha fått kjennskap til dets ulovlige karakter '
            '(trygg havn etter art. 6 DSA).\n\n'
            '2.4 Nevumo ansetter ikke tjenesteleverandører og er ikke ansvarlig for deres '
            'faglige kvalifikasjoner, lisenser, forsikringer eller overholdelse av '
            'gjeldende faglige reguleringer.'
        ),
        "pt": (
            '2.1 O Nevumo é uma plataforma de intermediação. Conectamos clientes a prestadores '
            'de serviços independentes. Não prestamos nós mesmos os serviços listados na '
            'plataforma e não somos parte no contrato celebrado entre o cliente e o prestador.\n\n'
            '2.2 O contrato de serviço (p. ex. limpeza, encanamento, massoterapia) é celebrado '
            'diretamente entre você (o cliente) e o prestador de serviços. O Nevumo facilita '
            'esse contato, mas não assume responsabilidade pela qualidade, pontualidade ou '
            'resultado do serviço.\n\n'
            '2.3 O Nevumo atua como prestador de serviços da sociedade da informação na '
            'acepção da Directiva 2000/31/CE e do Regulamento (UE) 2022/2065 (Lei dos '
            'Serviços Digitais — DSA). O Nevumo armazena conteúdo de terceiros (listagens de '
            'prestadores) e não é responsável por esse conteúdo, desde que aja prontamente '
            'para removê-lo após tomar conhecimento de seu caráter ilícito '
            '(porto seguro do artigo 6.º do DSA).\n\n'
            '2.4 O Nevumo não emprega prestadores de serviços e não é responsável pelas suas '
            'qualificações profissionais, licenças, seguros ou conformidade com os '
            'regulamentos profissionais aplicáveis.'
        ),
        "pt-PT": (
            '2.1 O Nevumo é uma plataforma de intermediação. Ligamos os clientes a prestadores '
            'de serviços independentes. Não prestamos nós próprios os serviços listados na '
            'plataforma e não somos parte no contrato celebrado entre o cliente e o prestador.\n\n'
            '2.2 O contrato de prestação de serviços (p. ex. limpeza, canalização, massagem) '
            'é celebrado directamente entre si (o cliente) e o prestador de serviços. O '
            'Nevumo facilita este contacto, mas não assume qualquer responsabilidade pela '
            'qualidade, pontualidade ou resultado do serviço.\n\n'
            '2.3 O Nevumo actua como prestador de serviços da sociedade da informação na '
            'acepção da Directiva 2000/31/CE e do Regulamento (UE) 2022/2065 (Regulamento '
            'dos Serviços Digitais — DSA). O Nevumo armazena conteúdos de terceiros '
            '(anúncios de prestadores) e não é responsável por esses conteúdos, desde que '
            'actue prontamente para os remover após tomar conhecimento da sua natureza '
            'ilícita (porto seguro do artigo 6.º do DSA).\n\n'
            '2.4 O Nevumo não emprega prestadores de serviços e não é responsável pelas suas '
            'qualificações profissionais, licenças, seguros ou conformidade com os '
            'regulamentos profissionais aplicáveis.'
        ),
        "ro": (
            '2.1 Nevumo este o platformă de intermediere. Conectăm clienții cu prestatori de '
            'servicii independenți. Nu furnizăm noi înșine serviciile listate pe platformă și '
            'nu suntem parte la contractul încheiat între client și prestator.\n\n'
            '2.2 Contractul de prestare a serviciilor (de ex. curățenie, instalații sanitare, '
            'masaj terapeutic) este încheiat direct între dumneavoastră (clientul) și '
            'prestatorul de servicii. Nevumo facilitează acest contact, dar nu își asumă '
            'nicio responsabilitate pentru calitatea, promptitudinea sau rezultatul '
            'serviciului.\n\n'
            '2.3 Nevumo acționează ca furnizor de servicii ale societății informaționale în '
            'sensul Directivei 2000/31/CE și al Regulamentului (UE) 2022/2065 (Regulamentul '
            'privind serviciile digitale — DSA). Nevumo stochează conținut al terților '
            '(listări de prestatori) și nu este responsabil pentru acel conținut, cu condiția '
            'să acționeze prompt pentru a-l elimina după ce a luat cunoștință de caracterul '
            'său ilegal (port sigur conform art. 6 DSA).\n\n'
            '2.4 Nevumo nu angajează prestatori de servicii și nu este responsabil pentru '
            'calificările lor profesionale, licențe, asigurări sau conformitatea cu '
            'reglementările profesionale aplicabile.'
        ),
        "ru": (
            '2.1 Nevumo — посредническая платформа. Мы связываем клиентов с независимыми '
            'исполнителями услуг. Мы не оказываем услуги, перечисленные на платформе, '
            'самостоятельно и не являемся стороной договора, заключённого между клиентом '
            'и исполнителем.\n\n'
            '2.2 Договор об оказании услуг (напр. уборка, сантехника, массаж) заключается '
            'непосредственно между вами (клиентом) и исполнителем. Nevumo содействует '
            'этому контакту, но не несёт ответственности за качество, своевременность '
            'или результат оказанной услуги.\n\n'
            '2.3 Nevumo действует как поставщик услуг информационного общества в смысле '
            'Директивы 2000/31/ЕС и Регламента (ЕС) 2022/2065 (Закон о цифровых услугах '
            '— DSA). Nevumo хранит контент третьих лиц (профили исполнителей) и не несёт '
            'ответственности за такой контент при условии, что после получения сведений о '
            'его незаконном характере немедленно принимает меры по его удалению '
            '(безопасная гавань согласно ст. 6 DSA).\n\n'
            '2.4 Nevumo не является работодателем исполнителей услуг и не несёт '
            'ответственности за их профессиональную квалификацию, лицензии, страховку '
            'или соответствие применимым профессиональным стандартам.'
        ),
        "sk": (
            '2.1 Nevumo je sprostredkovateľská platforma. Spájame klientov s nezávislými '
            'poskytovateľmi služieb. Sami neposkytujeme služby uvedené na platforme a nie '
            'sme stranou zmluvy uzatvorenej medzi klientom a poskytovateľom.\n\n'
            '2.2 Zmluva o poskytnutí služby (napr. upratovanie, inštalatérstvo, masáže) sa '
            'uzatvára priamo medzi vami (klientom) a poskytovateľom služby. Nevumo tento '
            'kontakt sprostredkúva, ale nenesie zodpovednosť za kvalitu, včasnosť ani '
            'výsledok poskytnutej služby.\n\n'
            '2.3 Nevumo pôsobí ako poskytovateľ služieb informačnej spoločnosti v zmysle '
            'smernice 2000/31/ES a nariadenia (EÚ) 2022/2065 (Akt o digitálnych službách '
            '— DSA). Nevumo uchováva obsah tretích strán (profily poskytovateľov) a nenesie '
            'zodpovednosť za tento obsah za predpokladu, že po zistení jeho nezákonnej povahy '
            'bezodkladne koná s cieľom jeho odstránenia '
            '(bezpečný prístav podľa čl. 6 DSA).\n\n'
            '2.4 Nevumo nezamestnáva poskytovateľov služieb a nenesie zodpovednosť za ich '
            'odbornú kvalifikáciu, licencie, poistenie ani za dodržiavanie platných '
            'profesijných predpisov.'
        ),
        "sl": (
            '2.1 Nevumo je posredniška platforma. Stranke povezujemo z neodvisnimi ponudniki '
            'storitev. Storitev, navedenih na platformi, sami ne opravljamo in nismo '
            'pogodbena stranka v pogodbi, sklenjeni med stranko in ponudnikom.\n\n'
            '2.2 Pogodba za storitev (npr. čiščenje, vodoinstalaterstvo, masaža) se sklene '
            'neposredno med vami (stranko) in ponudnikom storitev. Nevumo olajša ta stik, '
            'ni pa odgovoren za kakovost, pravočasnost ali rezultat storitve.\n\n'
            '2.3 Nevumo deluje kot ponudnik storitev informacijske družbe v smislu Direktive '
            '2000/31/ES in Uredbe (EU) 2022/2065 (Akt o digitalnih storitvah — DSA). Nevumo '
            'shranjuje vsebine tretjih strank (oglase ponudnikov) in ni odgovoren za to '
            'vsebino, pod pogojem, da po seznanitvi z njeno nezakonito naravo nemudoma '
            'ukrepa za njeno odstranitev '
            '(varno pristanišče iz 6. člena DSA).\n\n'
            '2.4 Nevumo ne zaposluje ponudnikov storitev in ni odgovoren za njihove strokovne '
            'kvalifikacije, licence, zavarovanje ali skladnost z veljavnimi poklicnimi '
            'predpisi.'
        ),
        "sq": (
            '2.1 Nevumo është një platformë ndërmjetësimi. Lidhim klientët me ofrues të '
            'pavarur të shërbimeve. Ne vetë nuk ofrojmë shërbimet e listuara në platformë '
            'dhe nuk jemi palë në kontratën e lidhur midis klientit dhe ofruesit.\n\n'
            '2.2 Kontrata e shërbimit (p.sh. pastrimi, hidraulika, masazh terapeutik) '
            'lidhet drejtpërdrejt midis jush (klientit) dhe ofruesit të shërbimit. Nevumo '
            'lehtëson këtë kontakt, por nuk mban asnjë përgjegjësi për cilësinë, '
            'kohëzgjatjen ose rezultatin e shërbimit.\n\n'
            '2.3 Nevumo vepron si ofrues i shërbimeve të shoqërisë së informacionit në '
            'kuptimin e Direktivës 2000/31/KE dhe Rregullores (BE) 2022/2065 (Akti i '
            'Shërbimeve Dixhitale — DSA). Nevumo ruan përmbajtje të palëve të treta dhe '
            'nuk është përgjegjës për atë përmbajtje, me kusht që të veprojë menjëherë '
            'për heqjen e saj pasi të marrë dijeni për natyrën e saj të paligjshme '
            '(porta e sigurt e nenit 6 DSA).\n\n'
            '2.4 Nevumo nuk punëson ofrues shërbimesh dhe nuk është përgjegjës për '
            'kualifikimet e tyre profesionale, licencat, sigurimet ose respektimin e '
            'rregulloreve profesionale të zbatueshme.'
        ),
        "sr": (
            '2.1 Nevumo je posrednička platforma. Povezujemo klijente sa nezavisnim '
            'pružaocima usluga. Mi sami ne pružamo usluge navedene na platformi i nismo '
            'strana u ugovoru zaključenom između klijenta i pružaoca.\n\n'
            '2.2 Ugovor o usluzi (npr. čišćenje, vodoinstalaterstvo, masaža) zaključuje se '
            'neposredno između vas (klijenta) i pružaoca usluge. Nevumo olakšava ovaj '
            'kontakt, ali ne preuzima odgovornost za kvalitet, blagovremenost ili rezultat '
            'usluge.\n\n'
            '2.3 Nevumo deluje kao pružalac usluga informacionog društva u smislu Direktive '
            '2000/31/EZ i Uredbe (EU) 2022/2065 (Akt o digitalnim uslugama — DSA). Nevumo '
            'čuva sadržaj trećih strana (profili pružalaca) i nije odgovoran za taj sadržaj, '
            'pod uslovom da odmah preduzme mere za uklanjanje nezakonitog sadržaja nakon '
            'saznanja o njegovoj nezakonitoj prirodi '
            '(bezbedna luka prema čl. 6 DSA).\n\n'
            '2.4 Nevumo ne zapošljava pružaoce usluga i nije odgovoran za njihove '
            'profesionalne kvalifikacije, licence, osiguranje ili usklađenost sa '
            'primenljivim profesionalnim propisima.'
        ),
        "sv": (
            '2.1 Nevumo är en förmedlingsplattform. Vi kopplar samman kunder med oberoende '
            'tjänsteleverantörer. Vi tillhandahåller inte själva de tjänster som listas på '
            'plattformen och är inte part i avtalet som ingås mellan kunden och leverantören.\n\n'
            '2.2 Tjänsteavtalet (t.ex. städning, VVS-arbeten, massageterapi) ingås direkt '
            'mellan er (kunden) och tjänsteleverantören. Nevumo underlättar denna kontakt '
            'men tar inget ansvar för tjänstens kvalitet, punktlighet eller resultat.\n\n'
            '2.3 Nevumo agerar som tillhandahållare av informationssamhällstjänster i '
            'enlighet med direktiv 2000/31/EG och förordning (EU) 2022/2065 (Lagen om '
            'digitala tjänster — DSA). Nevumo lagrar tredjepartsinnehåll (leverantörslistningar) '
            'och är inte ansvarigt för detta innehåll förutsatt att det agerar skyndsamt för '
            'att ta bort olagligt innehåll efter att ha fått kännedom om dess olagliga '
            'karaktär (säker hamn enligt art. 6 DSA).\n\n'
            '2.4 Nevumo anställer inte tjänsteleverantörer och ansvarar inte för deras '
            'yrkeskvalifikationer, licenser, försäkringar eller efterlevnad av tillämpliga '
            'yrkesregler.'
        ),
        "tr": (
            '2.1 Nevumo bir aracı platformdur. Müşterileri bağımsız hizmet sağlayıcılarla '
            'buluşturuyoruz. Platformda listelenen hizmetleri kendimiz sunmuyoruz ve müşteri '
            'ile sağlayıcı arasında kurulan sözleşmenin tarafı değiliz.\n\n'
            '2.2 Hizmet sözleşmesi (örn. temizlik, tesisatçılık, masaj terapisi) doğrudan '
            'sizinle (müşteri) hizmet sağlayıcı arasında kurulur. Nevumo bu temas için '
            'kolaylık sağlar; ancak hizmetin kalitesi, zamanlaması veya sonucundan '
            'sorumluluk kabul etmez.\n\n'
            '2.3 Nevumo, 2000/31/AT Direktifi ve (AB) 2022/2065 sayılı Tüzük (Dijital '
            'Hizmetler Yasası — DSA) kapsamında bir bilgi toplumu hizmeti sağlayıcısı olarak '
            'hareket etmektedir. Nevumo üçüncü taraf içeriklerini barındırmakta ve '
            'yasadışı niteliğini öğrendikten sonra hızla kaldırma işlemi gerçekleştirmesi '
            'koşuluyla bu içeriklerden sorumlu değildir (DSA Madde 6 güvenli liman).\n\n'
            '2.4 Nevumo hizmet sağlayıcıları istihdam etmemektedir ve onların mesleki '
            'nitelikleri, lisansları, sigorta durumları veya geçerli mesleki düzenlemelere '
            'uyumlarından sorumlu değildir.'
        ),
        "uk": (
            '2.1 Nevumo — посередницька платформа. Ми з\'єднуємо клієнтів з незалежними '
            'виконавцями послуг. Ми самі не надаємо послуги, перелічені на платформі, '
            'і не є стороною договору, укладеного між клієнтом і виконавцем.\n\n'
            '2.2 Договір про надання послуг (напр. прибирання, сантехніка, масаж) '
            'укладається безпосередньо між вами (клієнтом) і виконавцем послуг. Nevumo '
            'сприяє цьому контакту, але не несе відповідальності за якість, своєчасність '
            'або результат наданої послуги.\n\n'
            '2.3 Nevumo діє як постачальник послуг інформаційного суспільства у значенні '
            'Директиви 2000/31/ЄС і Регламенту (ЄС) 2022/2065 (Акт про цифрові послуги '
            '— DSA). Nevumo зберігає контент третіх сторін (профілі виконавців) і не несе '
            'відповідальності за такий контент, за умови що після отримання відомостей про '
            'його незаконний характер негайно вживає заходів для його видалення '
            '(безпечна гавань згідно зі ст. 6 DSA).\n\n'
            '2.4 Nevumo не є роботодавцем виконавців послуг і не несе відповідальності '
            'за їхню професійну кваліфікацію, ліцензії, страхування або відповідність '
            'застосовним професійним стандартам.'
        ),
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_p2_bodies: {count} rows upserted ({NAMESPACE}, art2_body × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()
