# -*- coding: utf-8 -*-
"""
seed_cookies_p16.py — namespace 'cookies'
cookies.s3_3_text, cookies.s3_4_text
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p16
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL")
engine = create_engine(DATABASE_URL)

TRANSLATIONS = {
    "cookies.s3_3_text": {
        "en": "Help us understand how visitors use Nevumo - which pages are visited, how long users stay, and where they come from. We use Google Analytics 4 (GA4) with Advanced Consent Mode v2. If you decline analytics cookies, GA4 still loads but sends only anonymised, cookieless pings. Google uses statistical modelling to estimate traffic trends without identifying you personally. No analytics cookies are placed without your explicit consent. Legal basis: Art. 6(1)(a) GDPR - your consent.",
        "bg": "Pomagat ni da razberem kak posetitelite izpolzvat Nevumo - koi stranitsi se poseshchavat, kolko dulgo potrebitelite ostavat i otkude idvat. Izpolzvame Google Analytics 4 (GA4) s Advanced Consent Mode v2. Ako otkazhete analitichnite biskvitki, GA4 vse oshte se zarеzhda, no izprashtа samo anonimizirаni signali bez biskvitki. Google izpolzva statistichesko modelirane za otsenka na tendentsiite v trafika bez lichno identifitsirane. Niakakvi analitichni biskvitki ne se postavyat bez vasheto izrichno sаglasie. Pravno osnovanie: Chl. 6, al. 1, b. a) GDPR - vasheto saglasiе.",
        "cs": "Pomahaji nam pochopit, jak navstevnici pouzivaji Nevumo - ktere stranky jsou navstevovany, jak dlouho uzivatele zustavaji a odkud prichаzeji. Pouzivame Google Analytics 4 (GA4) s Advanced Consent Mode v2. Pokud odmitnete analyticke cookies, GA4 se stale nacita, ale odesilа pouze anonymizovane signaly bez cookies. Google vyuziva statisticke modelovani k odhadu trendu provozu bez osobni identifikace. Zadne analyticke cookies se neumistují bez vascho vyslovneho souhlasu. Pravni zaklad: Cl. 6(1)(a) GDPR - vas souhlas.",
        "da": "Hjaelper os med at forsta, hvordan besogende bruger Nevumo - hvilke sider der besоges, hvor laenge brugerne forbliver, og hvorfra de kommer. Vi bruger Google Analytics 4 (GA4) med Advanced Consent Mode v2. Hvis du afviser analytiske cookies, indlаeses GA4 stadig, men sender kun anonymiserede pings uden cookies. Google bruger statistisk modellering til at estimere trafiktrends uden personlig identifikation. Ingen analytiske cookies placeres uden dit udtrykkelige samtykke. Retsgrundlag: Art. 6(1)(a) GDPR - dit samtykke.",
        "de": "Helfen uns zu verstehen, wie Besucher Nevumo nutzen - welche Seiten besucht werden, wie lange Nutzer bleiben und woher sie kommen. Wir verwenden Google Analytics 4 (GA4) mit Advanced Consent Mode v2. Wenn Sie Analyse-Cookies ablehnen, lаdt GA4 trotzdem, sendet jedoch nur anonymisierte, cookielose Pings. Google nutzt statistische Modellierung zur Schаtzung von Traffic-Trends, ohne Sie personlich zu identifizieren. Es werden keine Analyse-Cookies ohne Ihre ausdrueckliche Einwilligung gesetzt. Rechtsgrundlage: Art. 6(1)(a) DSGVO - Ihre Einwilligung.",
        "el": "Mas voithoun na katanosоume pos oi episkeptes chrisimopoioun to Nevumo - pois selides episkeptontai, poso kairo menoun oi christes kai apo pou erchontai. Chrisimopoioume Google Analytics 4 (GA4) me Advanced Consent Mode v2. An arnitheite ta analytika cookies, to GA4 fortonetai akoma alla stelnei mono anonymopoiimena simmata choris cookies. I Google chrisimopoiei statistiki montellopoiisi gia tin ektimiisi taseon kykloforias choris prosopiki taytopioisi. Kena analytika cookies tithentai choris tin riti sygkatathesi sas. Nomiki vasi: Arthro 6(1)(a) GDPR - i sygkatathesi sas.",
        "es": "Nos ayudan a entender como los visitantes usan Nevumo - que paginas se visitan, cuanto tiempo permanecen los usuarios y de donde vienen. Utilizamos Google Analytics 4 (GA4) con Advanced Consent Mode v2. Si rechaza las cookies analiticas, GA4 sigue cargando pero solo envia pings anonimos sin cookies. Google utiliza modelado estadistico para estimar tendencias de trafico sin identificarle personalmente. No se colocan cookies analiticas sin su consentimiento explicito. Base juridica: Art. 6(1)(a) RGPD - su consentimiento.",
        "et": "Aitab meil mõista, kuidas külastajad Nevumot kasutavad - milliseid lehti külastatakse, kui kaua kasutajad viibivad ja kust nad tulevad. Kasutame Google Analytics 4 (GA4) koos Advanced Consent Mode v2-ga. Kui keeldute anаlüütilistest küpsistest, laadib GA4 ikkagi, kuid saadab ainult anonümiseeritud, küpsisevabad signaale. Google kasutab statistilist modelleerimist liiklustrende hindamiseks ilma teid isiklikult tuvastamata. Ilma teie selgesõnalise nõusolekuta ei paigutata ühtegi analüütilist küpsist. Õiguslik alus: Art. 6(1)(a) GDPR - teie nõusolek.",
        "fi": "Auttaa meita ymmartamaan, miten kavijat kayttavat Nevumoa - mita sivuja vieraillaan, kuinka kauan kayttajat viipyvat ja mista he tulevat. Kaytamme Google Analytics 4:aa (GA4) Advanced Consent Mode v2:n kanssa. Jos kieltaydyt analytiikkaeva steista, GA4 latautuu silti, mutta lahettaa vain anonyymeja, evasteetomia signaaleita. Google kayttaa tilastollista mallintamista liikennetrendien arvioimiseen tunnistamatta sinua henkilokohtaisesti. Mitaan analytiikkaevаsteita ei aseteta ilman nimenomaista suostumustasi. Oikeusperuste: Art. 6(1)(a) GDPR - suostumuksesi.",
        "fr": "Nous aident a comprendre comment les visiteurs utilisent Nevumo - quelles pages sont visitees, combien de temps les utilisateurs restent et d'ou ils viennent. Nous utilisons Google Analytics 4 (GA4) avec Advanced Consent Mode v2. Si vous refusez les cookies analytiques, GA4 se charge quand meme mais n'envoie que des signaux anonymises sans cookies. Google utilise la modelisation statistique pour estimer les tendances de trafic sans vous identifier personnellement. Aucun cookie analytique n'est depose sans votre consentement explicite. Base juridique : Art. 6(1)(a) RGPD - votre consentement.",
        "ga": "Cuidionn siad linn a thuiscint conas a usaideann cuairteoiri Nevumo - ce na leathanaigh a dtugtar cuairt orthu, ce chomh fada a fhanann usaideoiri, agus cad as doibh. Usaidimid Google Analytics 4 (GA4) le Advanced Consent Mode v2. Ma dhiultaionn tu fianain anailisiochta, luchtaionn GA4 fos ach seolann se comharthai gan fianain amhain. Usaideann Google samhltu staitistiuil chun treochta trachta a mheas gan tu a aithint go pearsanta. Ni chuirtear fianain anailisiochta gan do thoiliu sainraite. Banus dli: Alt 6(1)(a) GDPR - do thoiliu.",
        "hr": "Pomazu nam razumjeti kako posjetitelji koriste Nevumo - koje se stranice posjécuju, koliko dugo korisnici ostaju i odakle dolaze. Koristimo Google Analytics 4 (GA4) s Advanced Consent Mode v2. Ako odbijete analiticke kolacice, GA4 se i dalje ucitava, ali salje samo anonimne signale bez kolacica. Google koristi statisticko modeliranje za procjenu trendova prometa bez osobne identifikacije. Ni jedan analiticki kolacic se ne postavlja bez vaseg izricitog pristanka. Pravna osnova: cl. 6(1)(a) GDPR - vas pristanak.",
        "hu": "Segitenek megerteni, hogyan hasznaljak a latogatоk a Nevumot - mely oldalakat latogatjak, mennyi ideig maradnak a felhasznalok, es honnan erkeznek. A Google Analytics 4 (GA4) alkalmazast hasznaljuk az Advanced Consent Mode v2-vel. Ha elutasitja az analitikai sutiket, a GA4 akkor is betoltodik, de csak anonimizalt, sutimentes pingeket kuldh. A Google statisztikai modellezest alkalmaz a forgalmi trendek becslésеhez anelkul, hogy szemellyesen azonositana Ont. Az On kifejezett hozzajarulasa nelkul semmilyen analitikai suti nem kerül elhelyezesre. Jogalap: 6. cikk (1) bek. a) pont GDPR - az On hozzajarulasa.",
        "is": "Hjalpar okkur ad skilja hvernig gestir nota Nevumo - hvadar sidur eru heimsottar, hve lengi notendur eru og hvadаn their koma. Vid notum Google Analytics 4 (GA4) med Advanced Consent Mode v2. Ef thu hafnar greiningarvafrakokum hlaeour GA4 engu ad sidur en sendir adeinns nafnlaegar, vafrakokulaesar merkingar. Google notar tolfraeolega likaagerd til ad meta umferdarthroun an thess ad bera thig kennsl a persónulega. Engar greiningarvafrakokur eru settar an thins skýra samthykkis. Lagagrundvollur: Gr. 6(1)(a) GDPR - thitt samthykki.",
        "it": "Ci aiutano a capire come i visitatori usano Nevumo - quali pagine vengono visitate, quanto a lungo gli utenti rimangono e da dove provengono. Utilizziamo Google Analytics 4 (GA4) con Advanced Consent Mode v2. Se rifiuti i cookie analitici, GA4 si carica comunque ma invia solo segnali anonimi, senza cookie. Google utilizza la modellazione statistica per stimare le tendenze del traffico senza identificarti personalmente. Nessun cookie analitico viene impostato senza il tuo consenso esplicito. Base giuridica: Art. 6(1)(a) GDPR - il tuo consenso.",
        "lb": "Hellefen eis ze verstoen, wei Besucher Nevumo benotzen - wei Saiten besicht ginn, wei laang Benotzer bleiwen an wou sie hirkommen. Mir benotzen Google Analytics 4 (GA4) mat Advanced Consent Mode v2. Wann Dir Analyse-Cookies ofleent, gett GA4 trotzdem gelueden, awer schickt nemen anonymiseirte, cookielose Signaler. Google benotzt statistesch Modellierung fir Verkeierstendenzen ouni persenlecher Identifikatioun ze schätzen. Keng Analyse-Cookies ginn ouni Arem explizite Consent gesat. Rechtlech Basis: Art. 6(1)(a) DSGVO - Ären Consent.",
        "lt": "Padeda mums suprasti, kaip lankytojai naudoja Nevumo - kurios puslapiai lankomi, kiek laiko vartotojai lieka ir is kur jie ateina. Naudojame Google Analytics 4 (GA4) su Advanced Consent Mode v2. Jei atsisakote analitiniu slapuku, GA4 vis tiek ikeliamas, bet siuncia tik anonimizuotus, be slapuku signalus. Google naudoja statistini modeliavima eismo tendencijoms ivertinti neasmeniniu jusu atpaziinimu. Jokie analitiniai slapukai nededami be jusu aiSkaus sutikimo. Teisinis pagrindas: BDAR 6 str. 1 d. a p. - jusu sutikimas.",
        "lv": "Palīdz mums saprast, ka apmekletaji izmanto Nevumo - kuras lapas tiek apmekleatas, cik ilgi lietotaji uzturas un no kurienes vini nak. Mes izmantojam Google Analytics 4 (GA4) ar Advanced Consent Mode v2. Ja atsakaties no analitiaskajam sikdatnem, GA4 joprojam ielаdеjas, bet suta tikai anonimizetus, bez sikdatnem signalus. Google izmanto statistisko modelesanu, lai novertetu satiksmes tendences bez personiskas identifikacijas. Nekadas analitiaskas sikdatnes netiek ievietotas bez jusu tiesаs piekrišanas. Juridiskais pamats: VDAR 6. panta 1. punkta a) apaksunkts - jusu piekrišana.",
        "mk": "Ni pomagaat da razbereme kak posetitelite go koristat Nevumo - koi stranici se posetuvaat, kolku dolgo ostanuvaat korisnicite i od kade doadaat. Go koristime Google Analytics 4 (GA4) so Advanced Consent Mode v2. Ako gi odbievte analitiсhkite kolacinja, GA4 sepak se vcituva, no isprakja samo anonimizirаni signali bez kolacinja. Google koristi statistichko modeliranje za procenka na trendovite vo soobrakajot bez licna identifikacija. Niakakvi analitichki kolacinja ne se postavuvaat bez vasata izrichna soglasnost. Pravna osnova: chl. 6(1)(a) GDPR - vasata soglasnost.",
        "mt": "Jghinna nifhmu kif il-vizitauri juzaw Nevumo - liema pagni giju zzurati, kemm idum l-utenti u minn fejn gejjin. Nuzaw Google Analytics 4 (GA4) b'Advanced Consent Mode v2. Jekk tirrifuta l-cookies analiticи, GA4 xorta jitghabbа izda jibghat biss pings anonimizzati bla cookies. Google juza mudelli statitiCi biex jistima t-tendenzi tat-traffiku minghaр ma jidentifika lek personalment. L-ebda cookie analitiku ma jitqieghd minghajar il-kunsens espliCitu tieghek. Bazi legali: Art. 6(1)(a) GDPR - il-kunsens tieghek.",
        "nl": "Helpen ons te begrijpen hoe bezoekers Nevumo gebruiken - welke pagina's worden bezocht, hoe lang gebruikers blijven en waar ze vandaan komen. We gebruiken Google Analytics 4 (GA4) met Advanced Consent Mode v2. Als u analytische cookies weigert, laadt GA4 toch, maar stuurt alleen geanonimiseerde, cookieloze pings. Google gebruikt statistische modellering om verkeerstendensen te schatten zonder u persoonlijk te identificeren. Er worden geen analytische cookies geplaatst zonder uw uitdrukkelijke toestemming. Rechtsgrondslag: Art. 6(1)(a) AVG - uw toestemming.",
        "no": "Hjelper oss a forsta hvordan besokende bruker Nevumo - hvilke sider som besokes, hvor lenge brukere er og hvor de kommer fra. Vi bruker Google Analytics 4 (GA4) med Advanced Consent Mode v2. Hvis du avviser analytiske informasjonskapsler, laster GA4 likevel, men sender bare anonymiserte, informasjonskapsellose signaler. Google bruker statistisk modellering for a estimere trafikktrender uten a identifisere deg personlig. Ingen analytiske informasjonskapsler plasseres uten ditt uttrykkelige samtykke. Rettsgrunnlag: Art. 6(1)(a) GDPR - ditt samtykke.",
        "pl": "Pomagaja nam zrozumiec, jak odwiedzajacy korzystaja z Nevumo - ktore strony sa odwiedzane, jak dlugo uzytkownicy pozostaja i skad przychodza. Uzywamy Google Analytics 4 (GA4) z Advanced Consent Mode v2. Jesli odrzucisz analityczne pliki cookie, GA4 nadal sie laduje, ale wysyla tylko anonimowe sygnafy bez plikow cookie. Google wykorzystuje modelowanie statystyczne do szacowania trendow ruchu bez osobistej identyfikacji. Zadne analityczne pliki cookie nie sa umieszczane bez Twojej wyraznej zgody. Podstawa prawna: Art. 6(1)(a) RODO - Twoja zgoda.",
        "pt": "Ajudam-nos a entender como os visitantes usam o Nevumo - quais paginas sao visitadas, quanto tempo os usuarios ficam e de onde vem. Usamos o Google Analytics 4 (GA4) com Advanced Consent Mode v2. Se voce recusar os cookies analiticos, o GA4 ainda carrega, mas envia apenas pings anonimos sem cookies. O Google usa modelagem estatistica para estimar tendencias de trafego sem identifica-lo pessoalmente. Nenhum cookie analitico e colocado sem o seu consentimento explicito. Base juridica: Art. 6(1)(a) RGPD - seu consentimento.",
        "pt-PT": "Ajudam-nos a compreender como os visitantes utilizam o Nevumo - quais as paginas visitadas, quanto tempo os utilizadores ficam e de onde provem. Utilizamos o Google Analytics 4 (GA4) com Advanced Consent Mode v2. Se recusar os cookies analiticos, o GA4 continua a carregar mas envia apenas sinais anonimos sem cookies. O Google utiliza modelacao estatistica para estimar tendencias de trafego sem identificа-lo pessoalmente. Nenhum cookie analitico e colocado sem o seu consentimento explicito. Base juridica: Art. 6(1)(a) RGPD - o seu consentimento.",
        "ro": "Ne ajuta sa intelegem cum folosesc vizitatorii Nevumo - ce pagini sunt vizitate, cat timp stau utilizatorii si de unde vin. Folosim Google Analytics 4 (GA4) cu Advanced Consent Mode v2. Daca refuzati cookie-urile analitice, GA4 se incarca in continuare, dar trimite doar semnale anonimizate fara cookie-uri. Google foloseste modelarea statistica pentru a estima tendintele de trafic fara a va identifica personal. Niciun cookie analitic nu este plasat fara consimtamantul dvs. explicit. Temei juridic: Art. 6(1)(a) GDPR - consimtamantul dvs.",
        "ru": "Pomogayut nam ponyat', kak posetiteli ispol'zuyut Nevumo - kakiye stranitsy poseshchayutsya, kak dolgo pol'zovateli ostayutsya i otkuda oni prikhodyat. My ispol'zuyem Google Analytics 4 (GA4) s Advanced Consent Mode v2. Yesli vy otkazyvayetes' ot analiticheskikh cookies, GA4 vsyo ravno zagruzhayetsya, no otpravlyayet tol'ko anonimizirovannyye signaly bez cookies. Google ispol'zuyet statisticheskoye modelirovaniye dlya otsenki tendentsiy trafika bez lichnoy identifikatsii. Bez vashego yavnogo soglasiya analiticheskiye cookies ne ustanavlivayutsya. Pravovaya osnova: St. 6(1)(a) GDPR - vashe soglasiye.",
        "sk": "Pomahaju nam pochopit', ako navstevnici pouzivaju Nevumo - ktore stranky su navstevovane, ako dlho uzivatel'а zostаvaju a odkial' prichаdzaju. Pouzivame Google Analytics 4 (GA4) s Advanced Consent Mode v2. Ak odmietnete analyticke cookies, GA4 sa stale nacita, ale odosiela iba anonymizovane signaly bez cookies. Google vyuziva statisticke modelovanie na odhadovanie trendov prevadzky bez osobnej identifikacie. Ziadne analyticke cookies sa neumiestnuju bez vasho vyslovneho suhlasu. Pravny zaklad: Cl. 6(1)(a) GDPR - vas suhlas.",
        "sl": "Pomagajo nam razumeti, kako obiskovalci uporabljajo Nevumo - katere strani so obiskane, kako dolgo ostajajo uporabniki in od kod prihajajo. Uporabljamo Google Analytics 4 (GA4) z Advanced Consent Mode v2. Ce zavrnete analiticne piskotke, se GA4 vseeno nalozi, a poslja samo anonimne signale brez piskotkov. Google uporablja statisticno modeliranje za ocenjevanje prometnih trendov brez osebne identifikacije. Brez vasega izrecnega soglasja se ne postavljajo nobeni analiticni piskotki. Pravna podlaga: cl. 6(1)(a) GDPR - vase soglasje.",
        "sq": "Na ndihmojne te kuptojme si vizitoret perdorin Nevumo - cilat faqe vizitohen, sa kohe qendrojne perdoruesit dhe nga vijn. Perdorim Google Analytics 4 (GA4) me Advanced Consent Mode v2. Nese refuzoni cookies analitike, GA4 ngarkon gjithsesi por dergon vetem sinjale anonime pa cookies. Google perdor modelimin statistikor per te vleresuar tendencat e trafikut pa ju identifikuar personalisht. Asnje cookie analitike nuk vendoset pa pelqimin tuaj eksplicit. Baza ligjore: Neni 6(1)(a) GDPR - pelqimi juaj.",
        "sr": "Pomazu nam da razumemo kako posetioci koriste Nevumo - koje stranice se posecuju, koliko dugo korisnici ostaju i odakle dolaze. Koristimo Google Analytics 4 (GA4) sa Advanced Consent Mode v2. Ako odbijete analiticke kolacice, GA4 se ipak ucitava, ali salje samo anonimizovane signale bez kolacica. Google koristi statisticko modelovanje za procenu trendova saobracaja bez licne identifikacije. Nijedan analiticki kolacic se ne postavlja bez vaseg izricnog pristanka. Pravni osnov: cl. 6(1)(a) GDPR - vas pristanak.",
        "sv": "Hjalper oss forsta hur besokare anvander Nevumo - vilka sidor som besoks, hur lange anvandare stannar och varifrаn de kommer. Vi anvander Google Analytics 4 (GA4) med Advanced Consent Mode v2. Om du avvisar analytiska cookies ladas GA4 anda men skickar bara anonymiserade, cookieloasa signaler. Google anvander statistisk modellering for att uppskatta trafiktrender utan att identifiera dig personligen. Inga analytiska cookies placeras utan ditt uttryckliga samtycke. Rattslig grund: Art. 6(1)(a) GDPR - ditt samtycke.",
        "tr": "Ziyaretcilerin Nevumo'yu nasil kullandigini anlamamiza yardimci olur - hangi sayfalarin ziyaret edildigi, kullanicilarin ne kadar kaldigi ve nereden geldikleri. Advanced Consent Mode v2 ile Google Analytics 4 (GA4) kullaniyoruz. Analitik cerezleri reddederseniz GA4 yine de yuklenir, ancak yalnizca anonimlestirilmis, cerez icermeyen sinyaller gonderir. Google, sizi kisisel olarak tanimlamadan trafik egilimlerini tahmin etmek icin istatistiksel modelleme kullanir. Acik rizaniz olmadan analitik cerez yerlestirilmez. Hukuki dayanak: GDPR Madde 6(1)(a) - rizaniz.",
        "uk": "Dopomagayut nam zrоzumity, yak vidviduvachi vykorystovuyut Nevumo - yaki storinky vidviduyutsya, skilky chasu zalishayutsya korystuvachi ta zvidky vony prykhodyat. My vykorystovuyemo Google Analytics 4 (GA4) z Advanced Consent Mode v2. Yakshcho vy vidmovlyayetesya vid analitychnykh fayliv cookie, GA4 vse odno zavantazhuyetsya, ale nadsilyaye lyshe anonimizovani syhnaly bez cookie. Google vykorystovuye statystychne modelyuvannya dlya otsinky tendentsiy trafiku bez osobystoyi identyfikatsiyi. Bez vashoyi yavnoyi zhody analitychni cookie ne vstanovlyuyutsya. Pravova osnova: St. 6(1)(a) GDPR - vasha zhoda.",
    },
    "cookies.s3_4_text": {
        "en": "Currently, Nevumo does not use marketing or advertising cookies. This category is reserved for future features (e.g., retargeting). No marketing cookies are set at this time. Legal basis (when used): Art. 6(1)(a) GDPR - your consent.",
        "bg": "V momenta Nevumo ne izpolzva marketingovi ili reklamni biskvitki. Tazi kategoriya e zapazena za budeшti funktsii (napr. remarketing). V momenta ne se postavyat marketingovi biskvitki. Pravno osnovanie (pri izpolzvanе): Chl. 6, al. 1, b. a) GDPR - vasheto saglasie.",
        "cs": "V soucasne dobe Nevumo nepouziva marketingove ani reklamni soubory cookie. Tato kategorie je vyhrazena pro budouci funkce (napr. remarketing). V tuto chvili nejsou nastaveny zadne marketingove soubory cookie. Pravni zaklad (pri pouziti): Cl. 6(1)(a) GDPR - vas souhlas.",
        "da": "I ojeblikket bruger Nevumo ikke marketing- eller reklamecookies. Denne kategori er forbeholdt fremtidige funktioner (f.eks. retargeting). Der er i ojeblikket ingen marketingcookies sat. Retsgrundlag (nar det bruges): Art. 6(1)(a) GDPR - dit samtykke.",
        "de": "Derzeit verwendet Nevumo keine Marketing- oder Werbe-Cookies. Diese Kategorie ist fur zukunftige Funktionen vorbehalten (z. B. Retargeting). Derzeit werden keine Marketing-Cookies gesetzt. Rechtsgrundlage (bei Verwendung): Art. 6(1)(a) DSGVO - Ihre Einwilligung.",
        "el": "Pros to paron, i Nevumo den chrisimopoiei cookies marketing i diafimisis. Ayti i katigoria proorizetai gia mellontikes leitourgies (p.ch. epanastocheysi). Ayti ti stigmi den tithentai cookies marketing. Nomiki vasi (otan chrisimopoieitai): Arthro 6(1)(a) GDPR - i sygkatathesi sas.",
        "es": "Actualmente, Nevumo no utiliza cookies de marketing o publicidad. Esta categoria esta reservada para funciones futuras (p. ej., retargeting). Actualmente no hay cookies de marketing configuradas. Base juridica (cuando se usen): Art. 6(1)(a) RGPD - su consentimiento.",
        "et": "Praegu ei kasuta Nevumo turundus- ega reklaamiküpsiseid. See kategooria on reserveeritud tulevasteks funktsioonideks (nt umbersihtimine). Praegu ei ole ühtegi turundusküpsist seadistatud. Оiguslik alus (kasutamisel): Art. 6(1)(a) GDPR - teie nоusolek.",
        "fi": "Tallа hetkella Nevumo ei kayta markkinointi- tai mainosevаsteita. Tama kategoria on varattu tuleville ominaisuuksille (esim. uudelleenkohdistaminen). Tallа hetkella markkinointieva steita ei ole asetettu. Oikeusperuste (kaytettaessa): Art. 6(1)(a) GDPR - suostumuksesi.",
        "fr": "Actuellement, Nevumo n'utilise pas de cookies de marketing ou de publicite. Cette categorie est reservee pour de futures fonctionnalites (p. ex. le reciblage). Aucun cookie marketing n'est actuellement defini. Base juridique (lorsqu'utilises) : Art. 6(1)(a) RGPD - votre consentement.",
        "ga": "Faoi lathair, ni usaideann Nevumo fianain margaiochta na foglarаiochta. Ta an chatagoir seo curtha i leataobh le haghaidh gneithe amach anseo (m.sh. athdhiriu). Nil aon fianain margaiochta socraithe faoi lathair. Banus dli (nuair a usaidtear): Alt 6(1)(a) GDPR - do thoiliu.",
        "hr": "Trenutno Nevumo ne koristi marketinske ili oglasivacke kolacice. Ova kategorija je rezervirana za buduce znacajke (npr. retargeting). Trenutno nisu postavljeni nikakvi marketinski kolacici. Pravna osnova (kada se koristi): cl. 6(1)(a) GDPR - vas pristanak.",
        "hu": "Jelenleg a Nevumo nem hasznal marketing vagy hirdetes sуtiket. Ez а kategoria jovobeli funkciokra van fenntartva (pl. remarketing). Jelenleg nincsenek marketing sutik beallitva. Jogalap (hasznаlatkor): 6. cikk (1) bek. a) pont GDPR - az On hozzajarulasa.",
        "is": "Eins og er notar Nevumo ekki markadssetningar- edur auglуsingavafrakokur. Thessi flokkur er fratekinn fyrir framtidareigинleika (t.d. endurmiоun). Engar markadssetningarvafrakokur eru stilltar eins og er. Lagagrundvollur (thegar notadur): Gr. 6(1)(a) GDPR - thitt samthykki.",
        "it": "Attualmente, Nevumo non utilizza cookie di marketing o pubblicitari. Questa categoria e riservata per funzionalita future (es. retargeting). Al momento non sono impostati cookie di marketing. Base giuridica (quando utilizzati): Art. 6(1)(a) GDPR - il tuo consenso.",
        "lb": "Aktuell benotzt Nevumo keng Marketing- oder Reklamecookies. Des Kategorie ass fir zukunftige Funktiounen reserviert (z.B. Retargeting). Aktuell gi keng Marketing-Cookies gesat. Rechtlech Basis (wann benotzt): Art. 6(1)(a) DSGVO - Ären Consent.",
        "lt": "Siuo metu Nevumo nenaudoja rinkodaros ar reklaminiu slapuku. Si kategorija skirta busimiem funkcionalumams (pvz., pakartotinei rinkodarai). Siuo metu nenustatyti jokie rinkodaros slapukai. Teisinis pagrindas (naudojant): BDAR 6 str. 1 d. a p. - jusu sutikimas.",
        "lv": "Paslal Nevumo neizmanto marketinga vai reklamas sikdatnes. Sa kategorija ir rezerveta nakotnei paraedzеtajam (piem. atkartotai merkesanai). Paslal nav iestatitas nekadas marketinga sikdatnes. Juridiskais pamats (lietojot): VDAR 6. panta 1. punkta a) apakspunkts - jusu piekrišana.",
        "mk": "Vo moментov, Nevumo ne koristi marketinski ili reklamni kolacinja. Ovaa kategorija е rezervirana za idni funktsii (napr. retargeting). Vo momentov ne se postaveni marketinski kolacinja. Pravna osnova (pri upotreba): chl. 6(1)(a) GDPR - vasata soglasnost.",
        "mt": "Bhalissa, Nevumo ma tuza l-ebda cookies ta' marketing jew reklamar. Din il-kategorija hija rizervata ghal karatteristici futuri (ez. retargeting). Bhalissa ma jitqieghdu l-ebda cookies ta' marketing. Bazi legali (meta jintuza): Art. 6(1)(a) GDPR - il-kunsens tieghek.",
        "nl": "Momenteel gebruikt Nevumo geen marketing- of advertentiecookies. Deze categorie is gereserveerd voor toekomstige functies (bijv. retargeting). Er zijn momenteel geen marketingcookies ingesteld. Rechtsgrondslag (bij gebruik): Art. 6(1)(a) AVG - uw toestemming.",
        "no": "For oyeblikket bruker Nevumo ingen markedsforing- eller reklameinformasjonskapsler. Denne kategorien er reservert for fremtidige funksjoner (f.eks. retargeting). Det er for oyeblikket ingen markedsforingsinformasjonskapsler angitt. Rettsgrunnlag (ved bruk): Art. 6(1)(a) GDPR - ditt samtykke.",
        "pl": "Obecnie Nevumo nie uzywa plikow cookie marketingowych ani reklamowych. Ta kategoria jest zarezerwowana na przyszle funkcje (np. retargeting). Obecnie nie sa ustawione zadne marketingowe pliki cookie. Podstawa prawna (gdy uzywane): Art. 6(1)(a) RODO - Twoja zgoda.",
        "pt": "Atualmente, a Nevumo nao usa cookies de marketing ou publicidade. Esta categoria esta reservada para funcionalidades futuras (ex. retargeting). Nenhum cookie de marketing esta configurado no momento. Base juridica (quando utilizado): Art. 6(1)(a) RGPD - seu consentimento.",
        "pt-PT": "Atualmente, a Nevumo nao utiliza cookies de marketing ou publicidade. Esta categoria esta reservada para funcionalidades futuras (ex. retargeting). Nao estao configurados cookies de marketing neste momento. Base juridica (quando utilizados): Art. 6(1)(a) RGPD - o seu consentimento.",
        "ro": "In prezent, Nevumo nu foloseste cookie-uri de marketing sau publicitate. Aceasta categorie este rezervata pentru functionalitati viitoare (de ex., retargeting). In prezent nu sunt configurate cookie-uri de marketing. Temei juridic (cand sunt utilizate): Art. 6(1)(a) GDPR - consimtamantul dvs.",
        "ru": "V nastoyashcheye vremya Nevumo ne ispol'zuyet marketingovyye ili reklamnyye cookies. Eta kategoriya zarezervirana dlya budushchikh funktsiy (naprimer, retargetinga). V nastoyashcheye vremya marketingovyye cookies ne ustanovleny. Pravovaya osnova (pri ispol'zovanii): St. 6(1)(a) GDPR - vashe soglasiye.",
        "sk": "V sucasnosti Nevumo nepouziva marketingove ani reklamne cookies. Tato kategoria je vyhradena pre buduce funkcie (napr. retargeting). V sucasnosti nie su nastavene ziadne marketingove cookies. Pravny zaklad (pri pouziti): Cl. 6(1)(a) GDPR - vas suhlas.",
        "sl": "Trenutno Nevumo ne uporablja marketinskih ali oglasevalskih piskotkov. Ta kategorija je rezervirana za prihodnje funkcije (npr. ponovni marketing). Trenutno ni nastavljenih marketinskih piskotkov. Pravna podlaga (pri uporabi): cl. 6(1)(a) GDPR - vase soglasje.",
        "sq": "Aktualisht, Nevumo nuk perdor cookies marketingu apo reklamuese. Kjo kategori eshte rezervuar per veçori te ardhshme (p.sh. retargeting). Aktualisht nuk jane vendosur cookies marketingu. Baza ligjore (kur perdoret): Neni 6(1)(a) GDPR - pelqimi juaj.",
        "sr": "Trenutno, Nevumo ne koristi marketinske ili reklamne kolacice. Ova kategorija je rezervisana za buduce funkcije (npr. retargeting). Trenutno nisu postavljeni nikakvi marketinski kolacici. Pravni osnov (pri upotrebi): cl. 6(1)(a) GDPR - vas pristanak.",
        "sv": "For narvarande anvander Nevumo inga marknadsforings- eller reklamcookies. Denna kategori ar reserverad for framtida funktioner (t.ex. atermarknadsf oring). Inga marknadsforingscookies ar installda for tillfalletI. Rattslig grund (vid anvandning): Art. 6(1)(a) GDPR - ditt samtycke.",
        "tr": "Su anda Nevumo, pazarlama veya reklam cerezleri kullanmamaktadir. Bu kategori gelecekteki ozellikler icin ayrilmistir (orn. yeniden hedefleme). Su anda pazarlama cerezi ayarlanmamistir. Hukuki dayanak (kullanildiginda): GDPR Madde 6(1)(a) - rizaniz.",
        "uk": "Nаrazi Nevumo ne vykorystovuye marketynhovi abo reklamni fayly cookie. Tsya katehoriya zarezervovana dlya maybutnikh funktsiy (napryklad, retarhetynhu). Nаrazi marketynhovi fayly cookie ne vstanovleni. Pravova osnova (pry vykorystanni): St. 6(1)(a) GDPR - vasha zhoda.",
    },
}


def seed():
    with engine.begin() as conn:
        for key, translations in TRANSLATIONS.items():
            for lang, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (key, lang, value)
                        VALUES (:key, :lang, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"key": key, "lang": lang, "value": value},
                )
    print(f"Seeded {len(TRANSLATIONS)} keys x 34 languages")


if __name__ == "__main__":
    seed()