"""
seed_cookies_p21.py  —  Nevumo | namespace: cookies
Keys: cat_necessary, cat_functional, cat_analytics, cat_marketing,
      s6_title, s6_banner, s6_settings, s6_browser, s6_storage,
      s6_col_browser, s6_col_path  (11 keys × 34 langs = 374 rows)
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p21
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "cookies"

TRANSLATIONS: dict[str, dict[str, str]] = {

    # ── Category labels ──────────────────────────────────────────────────────

    "cat_necessary": {
        "en": "Strictly Necessary",
        "pl": "Niezbędne",
        "bg": "Задължително необходими",
        "cs": "Nezbytně nutné",
        "da": "Absolut nødvendige",
        "de": "Unbedingt erforderlich",
        "el": "Απολύτως απαραίτητα",
        "es": "Estrictamente necesarias",
        "et": "Rangelt vajalikud",
        "fi": "Ehdottoman välttämättömät",
        "fr": "Strictement nécessaires",
        "ga": "Go docht riachtanach",
        "hr": "Strogo potrebni",
        "hu": "Feltétlenül szükséges",
        "is": "Algerlega nauðsynleg",
        "it": "Strettamente necessari",
        "lb": "Absolut néideg",
        "lt": "Griežtai būtini",
        "lv": "Absolūti nepieciešamie",
        "mk": "Строго неопходни",
        "mt": "Strettament meħtieġa",
        "nl": "Strikt noodzakelijk",
        "no": "Strengt nødvendige",
        "pt": "Estritamente necessários",
        "pt-PT": "Estritamente necessários",
        "ro": "Strict necesare",
        "ru": "Строго необходимые",
        "sk": "Nevyhnutne potrebné",
        "sl": "Nujno potrebni",
        "sq": "Rreptësisht të nevojshme",
        "sr": "Строго неопходни",
        "sv": "Strikt nödvändiga",
        "tr": "Kesinlikle gerekli",
        "uk": "Строго необхідні",
    },

    "cat_functional": {
        "en": "Functional",
        "pl": "Funkcjonalne",
        "bg": "Функционални",
        "cs": "Funkční",
        "da": "Funktionelle",
        "de": "Funktionale",
        "el": "Λειτουργικά",
        "es": "Funcionales",
        "et": "Funktsionaalsed",
        "fi": "Toiminnalliset",
        "fr": "Fonctionnels",
        "ga": "Feidhmiúil",
        "hr": "Funkcionalni",
        "hu": "Funkcionális",
        "is": "Virkni",
        "it": "Funzionali",
        "lb": "Funktionell",
        "lt": "Funkciniai",
        "lv": "Funkcionālie",
        "mk": "Функционални",
        "mt": "Funzjonali",
        "nl": "Functioneel",
        "no": "Funksjonelle",
        "pt": "Funcionais",
        "pt-PT": "Funcionais",
        "ro": "Funcționale",
        "ru": "Функциональные",
        "sk": "Funkčné",
        "sl": "Funkcionalni",
        "sq": "Funksionale",
        "sr": "Функционални",
        "sv": "Funktionella",
        "tr": "İşlevsel",
        "uk": "Функціональні",
    },

    "cat_analytics": {
        "en": "Analytics",
        "pl": "Analityczne",
        "bg": "Аналитични",
        "cs": "Analytické",
        "da": "Analytiske",
        "de": "Analytisch",
        "el": "Αναλυτικά",
        "es": "Analíticas",
        "et": "Analüütilised",
        "fi": "Analytiikka",
        "fr": "Analytiques",
        "ga": "Anailísíocht",
        "hr": "Analitički",
        "hu": "Analitikai",
        "is": "Greiningartengd",
        "it": "Analitici",
        "lb": "Analytesch",
        "lt": "Analitiniai",
        "lv": "Analītiskie",
        "mk": "Аналитички",
        "mt": "Analitiċi",
        "nl": "Analytisch",
        "no": "Analytiske",
        "pt": "Analíticos",
        "pt-PT": "Analíticos",
        "ro": "Analitice",
        "ru": "Аналитические",
        "sk": "Analytické",
        "sl": "Analitični",
        "sq": "Analitike",
        "sr": "Аналитички",
        "sv": "Analytiska",
        "tr": "Analitik",
        "uk": "Аналітичні",
    },

    "cat_marketing": {
        "en": "Marketing",
        "pl": "Marketingowe",
        "bg": "Маркетингови",
        "cs": "Marketingové",
        "da": "Marketing",
        "de": "Marketing",
        "el": "Μάρκετινγκ",
        "es": "Marketing",
        "et": "Turunduslikud",
        "fi": "Markkinointi",
        "fr": "Marketing",
        "ga": "Margaíocht",
        "hr": "Marketinški",
        "hu": "Marketing",
        "is": "Markaðssetning",
        "it": "Marketing",
        "lb": "Marketing",
        "lt": "Rinkodaros",
        "lv": "Mārketinga",
        "mk": "Маркетиншки",
        "mt": "Marketing",
        "nl": "Marketing",
        "no": "Markedsføring",
        "pt": "Marketing",
        "pt-PT": "Marketing",
        "ro": "Marketing",
        "ru": "Маркетинговые",
        "sk": "Marketingové",
        "sl": "Trženjski",
        "sq": "Marketing",
        "sr": "Маркетиншки",
        "sv": "Marknadsföring",
        "tr": "Pazarlama",
        "uk": "Маркетингові",
    },

    # ── Section 6 ────────────────────────────────────────────────────────────

    "s6_title": {
        "en": "6. How to Manage Your Preferences",
        "pl": "6. Jak zarządzać preferencjami",
        "bg": "6. Как да управлявате предпочитанията си",
        "cs": "6. Jak spravovat vaše předvolby",
        "da": "6. Sådan administrerer du dine præferencer",
        "de": "6. So verwalten Sie Ihre Einstellungen",
        "el": "6. Πώς να διαχειριστείτε τις προτιμήσεις σας",
        "es": "6. Cómo gestionar sus preferencias",
        "et": "6. Kuidas oma eelistusi hallata",
        "fi": "6. Kuinka hallita asetuksiasi",
        "fr": "6. Comment gérer vos préférences",
        "ga": "6. Conas Do Roghanna a Bhainistiú",
        "hr": "6. Kako upravljati vašim postavkama",
        "hu": "6. Hogyan kezelheti beállításait",
        "is": "6. Hvernig á að stjórna stillingum þínum",
        "it": "6. Come gestire le proprie preferenze",
        "lb": "6. Wéi Dir Är Astellungen verwalte kënnt",
        "lt": "6. Kaip tvarkyti savo nuostatas",
        "lv": "6. Kā pārvaldīt savas preferences",
        "mk": "6. Kako да ги управувате вашите поставки",
        "mt": "6. Kif Timmaniġġja l-Preferenzi Tiegħek",
        "nl": "6. Hoe u uw voorkeuren kunt beheren",
        "no": "6. Slik administrerer du dine preferanser",
        "pt": "6. Como gerenciar suas preferências",
        "pt-PT": "6. Como gerir as suas preferências",
        "ro": "6. Cum să vă gestionați preferințele",
        "ru": "6. Как управлять вашими настройками",
        "sk": "6. Ako spravovať vaše nastavenia",
        "sl": "6. Kako upravljati z nastavitvami",
        "sq": "6. Si të menaxhoni preferencat tuaja",
        "sr": "6. Kako управљати вашим поставкама",
        "sv": "6. Hur du hanterar dina inställningar",
        "tr": "6. Tercihlerinizi Nasıl Yönetirsiniz",
        "uk": "6. Як керувати вашими налаштуваннями",
    },

    "s6_banner": {
        "en": "Via the Cookie Banner: When you first visit Nevumo, a banner appears allowing you to accept all, reject all, or customise your preferences by category.",
        "pl": "Za pomocą banera cookies: Przy pierwszej wizycie na Nevumo pojawia się baner umożliwiający akceptację wszystkich, odrzucenie wszystkich lub dostosowanie preferencji według kategorii.",
        "bg": "Чрез банера за бисквитки: При първото ви посещение на Nevumo се появява банер, позволяващ да приемете всички, да откажете всички или да персонализирате предпочитанията си по категории.",
        "cs": "Prostřednictvím banneru pro cookies: Při první návštěvě Nevumo se zobrazí banner, který vám umožní přijmout vše, odmítnout vše nebo přizpůsobit si preference podle kategorie.",
        "da": "Via cookiebanneret: Første gang du besøger Nevumo, vises et banner, der giver dig mulighed for at acceptere alle, afvise alle eller tilpasse dine præferencer pr. kategori.",
        "de": "Über das Cookie-Banner: Wenn Sie Nevumo zum ersten Mal besuchen, erscheint ein Banner, mit dem Sie alle akzeptieren, alle ablehnen oder Ihre Einstellungen nach Kategorie anpassen können.",
        "el": "Μέσω του Banner Cookies: Κατά την πρώτη σας επίσκεψη στο Nevumo, εμφανίζεται ένα banner που σας επιτρέπει να αποδεχτείτε όλα, να απορρίψετε όλα ή να προσαρμόσετε τις προτιμήσεις σας ανά κατηγορία.",
        "es": "Mediante el banner de cookies: La primera vez que visita Nevumo, aparece un banner que le permite aceptar todas, rechazar todas o personalizar sus preferencias por categoría.",
        "et": "Cookie-banneri kaudu: Kui külastate Nevumot esimest korda, ilmub banner, mis võimaldab teil kõik vastu võtta, kõik tagasi lükata või oma eelistusi kategooriate kaupa kohandada.",
        "fi": "Evästebannerin kautta: Kun vierailet Nevumossa ensimmäistä kertaa, näyttöön tulee banneri, jonka avulla voit hyväksyä kaikki, hylätä kaikki tai mukauttaa asetuksesi luokittain.",
        "fr": "Via la bannière de cookies : Lors de votre première visite sur Nevumo, une bannière apparaît vous permettant d'accepter tout, de refuser tout ou de personnaliser vos préférences par catégorie.",
        "ga": "Trí Bhratach na bhFianán: Nuair a thugann tú cuairt ar Nevumo den chéad uair, feicfidh tú bratach a ligeann duit gach rud a ghlacadh, gach rud a dhiúltú, nó do roghanna a shaincheapadh de réir catagóire.",
        "hr": "Putem bannera za kolačiće: Kada prvi put posjetite Nevumo, pojavljuje se banner koji vam omogućuje prihvaćanje svih, odbijanje svih ili prilagodbu preferencija prema kategoriji.",
        "hu": "A cookie-banner segítségével: Amikor először látogatja meg a Nevumót, egy banner jelenik meg, amellyel elfogadhatja az összeset, elutasíthatja az összeset, vagy kategóriánként testreszabhatja beállításait.",
        "is": "Með cookie-borðanum: Í fyrstu heimsókn þinni á Nevumo birtist borði þar sem þú getur samþykkt allt, hafnað öllu eða sérsniðið stillingar þínar eftir flokki.",
        "it": "Tramite il banner dei cookie: Alla prima visita su Nevumo, appare un banner che consente di accettare tutti, rifiutare tutti o personalizzare le preferenze per categoria.",
        "lb": "Iwwer de Cookie-Banner: Wann Dir Nevumo zum éischte Mol besicht, erschéngt e Banner, deen Iech erlaabt alles unzehuelen, alles ofzeléinen oder Är Astellungen no Kategorie unzepassen.",
        "lt": "Per slapukų juostą: Pirmą kartą apsilankę Nevumo, pamatysite juostą, leidžiančią priimti visus, atmesti visus arba tinkinti nuostatas pagal kategoriją.",
        "lv": "Izmantojot sīkfailu joslu: Pirmoreiz apmeklējot Nevumo, parādīsies josla, kas ļauj pieņemt visus, noraidīt visus vai pielāgot preferences pēc kategorijām.",
        "mk": "Преку банерот за колачиња: При вашата прва посета на Nevumo, се прикажува банер кој ви овозможува да ги прифатите сите, да ги одбиете сите или да ги приспособите вашите преференции по категорија.",
        "mt": "Permezz tal-Banner tal-Cookies: Meta żżur Nevumo għall-ewwel darba, tidher banner li tippermettik taċċetta kollox, tirrifjuta kollox, jew tippersonalizza l-preferenzi tiegħek skont il-kategorija.",
        "nl": "Via de cookiebanner: Wanneer u Nevumo voor het eerst bezoekt, verschijnt een banner waarmee u alles kunt accepteren, alles kunt weigeren of uw voorkeuren per categorie kunt aanpassen.",
        "no": "Via informasjonskapselbanneret: Første gang du besøker Nevumo, vises et banner der du kan godta alle, avvise alle eller tilpasse innstillingene dine etter kategori.",
        "pt": "Pelo banner de cookies: Quando você visita o Nevumo pela primeira vez, aparece um banner permitindo aceitar todos, rejeitar todos ou personalizar suas preferências por categoria.",
        "pt-PT": "Através do banner de cookies: Quando visita o Nevumo pela primeira vez, aparece um banner que lhe permite aceitar todos, rejeitar todos ou personalizar as suas preferências por categoria.",
        "ro": "Prin bannerul de cookies: Când vizitați Nevumo pentru prima dată, apare un banner care vă permite să acceptați toate, să refuzați toate sau să vă personalizați preferințele pe categorii.",
        "ru": "Через баннер cookie: При первом посещении Nevumo появляется баннер, позволяющий принять все, отклонить все или настроить свои предпочтения по категориям.",
        "sk": "Prostredníctvom cookie bannera: Keď prvýkrát navštívite Nevumo, zobrazí sa banner, ktorý vám umožní prijať všetky, odmietnuť všetky alebo prispôsobiť si preferencie podľa kategórie.",
        "sl": "Prek pasice za piškotke: Ko prvič obiščete Nevumo, se prikaže pasica, ki vam omogoča, da sprejmete vse, zavrnete vse ali prilagodite nastavitve po kategorijah.",
        "sq": "Nëpërmjet banderolës së cookies: Kur vizitoni Nevumo për herë të parë, shfaqet një banderolë që ju lejon të pranoni të gjitha, refuzoni të gjitha ose të personalizoni preferencat tuaja sipas kategorisë.",
        "sr": "Преко банера за колачиће: Приликом прве посете Nevumo, приказује се банер који вам омогућава да прихватите све, одбијете све или прилагодите своје поставке по категорији.",
        "sv": "Via cookie-bannern: När du besöker Nevumo för första gången visas en banner som låter dig acceptera alla, avvisa alla eller anpassa dina inställningar per kategori.",
        "tr": "Çerez Bandı Aracılığıyla: Nevumo'yu ilk ziyaret ettiğinizde, tümünü kabul etmenizi, tümünü reddetmenizi veya tercihlerinizi kategoriye göre özelleştirmenizi sağlayan bir banner görüntülenir.",
        "uk": "Через банер cookie: Під час першого відвідування Nevumo з'являється банер, що дозволяє прийняти всі, відхилити всі або налаштувати параметри за категоріями.",
    },

    "s6_settings": {
        "en": 'Via Cookie Settings: A "Cookie Settings" link is always available in the website footer. Click it at any time to review or change your choices.',
        "pl": 'Za pomocą Ustawień cookies: Link „Ustawienia cookies" jest zawsze dostępny w stopce witryny. Kliknij go w dowolnym momencie, aby przejrzeć lub zmienić swoje wybory.',
        "bg": 'Чрез Настройки за бисквитки: Връзката „Настройки за бисквитки" е винаги достъпна в долния колонтитул на уебсайта. Кликнете върху нея по всяко време, за да прегледате или промените изборите си.',
        "cs": 'Prostřednictvím nastavení cookies: Odkaz „Nastavení cookies" je vždy dostupný v zápatí webu. Kdykoli na něj klikněte, abyste si prohlédli nebo změnili svá nastavení.',
        "da": 'Via cookieindstillinger: Et link til „Cookieindstillinger" er altid tilgængeligt i webstedets sidefod. Klik på det når som helst for at gennemse eller ændre dine valg.',
        "de": 'Über Cookie-Einstellungen: Ein Link zu den „Cookie-Einstellungen" ist immer in der Website-Fußzeile verfügbar. Klicken Sie jederzeit darauf, um Ihre Auswahl zu überprüfen oder zu ändern.',
        "el": 'Μέσω των Ρυθμίσεων cookies: Ένας σύνδεσμος «Ρυθμίσεις cookies» είναι πάντα διαθέσιμος στο υποσέλιδο του ιστότοπου. Κάντε κλικ ανά πάσα στιγμή για να ελέγξετε ή να αλλάξετε τις επιλογές σας.',
        "es": 'Mediante la Configuración de cookies: Un enlace de «Configuración de cookies» siempre está disponible en el pie de página. Haga clic en él en cualquier momento para revisar o cambiar sus opciones.',
        "et": 'Küpsiste seadete kaudu: Link „Küpsiste seaded" on alati saadaval veebisaidi jaluses. Klõpsake sellel igal ajal, et vaadata üle või muuta oma valikuid.',
        "fi": 'Evästeasetuksien kautta: Evästeasetukset-linkki on aina saatavilla verkkosivuston alatunnisteessa. Napsauta sitä milloin tahansa tarkistaaksesi tai muuttaaksesi valintojasi.',
        "fr": 'Via les Paramètres des cookies : Un lien « Paramètres des cookies » est toujours disponible dans le pied de page du site. Cliquez dessus à tout moment pour consulter ou modifier vos choix.',
        "ga": 'Trí Socruithe Fianán: Tá nasc «Socruithe Fianán» ar fáil i gcónaí i gcochall an láithreáin ghréasáin. Cliceáil air am ar bith chun do roghanna a athbhreithniú nó a athrú.',
        "hr": 'Putem Postavki kolačića: Veza „Postavke kolačića" uvijek je dostupna u podnožju web-mjesta. Kliknite je u bilo kojem trenutku da pregledate ili promijenite svoje izbore.',
        "hu": 'A Cookie-beállítások segítségével: A „Cookie-beállítások" link mindig elérhető az oldal aloldalán. Kattintson rá bármikor, hogy felülvizsgálja vagy módosítsa döntéseit.',
        "is": 'Með stillingum vafrakaka: Tengill „Stillingar vafrakaka" er alltaf tiltækur í fæti vefsins. Smelltu á hann hvenær sem er til að yfirfara eða breyta vali þínu.',
        "it": 'Tramite le Impostazioni cookie: Un link «Impostazioni cookie» è sempre disponibile nel piè di pagina del sito. Cliccatelo in qualsiasi momento per rivedere o modificare le vostre scelte.',
        "lb": 'Iwwer d\'Cookie-Astellungen: E Link zu den „Cookie-Astellungen" ass ëmmer an der Websäitefußzeile verfügbar. Klickt se jiddereen, fir Är Auswahl ze iwwerpréiwen oder ze änneren.',
        "lt": 'Per slapukų nustatymus: Nuoroda „Slapukų nustatymai" visada prieinama svetainės apačioje. Spustelėkite ją bet kada, kad peržiūrėtumėte arba pakeistumėte savo pasirinkimus.',
        "lv": 'Izmantojot sīkfailu iestatījumus: Saite „Sīkfailu iestatījumi" vienmēr ir pieejama vietnes kājenē. Noklikšķiniet uz tās jebkurā laikā, lai pārskatītu vai mainītu savus izvēles.',
        "mk": 'Преку Поставките за колачиња: Врска „Поставки за колачиња" е секогаш достапна во подножјето на веб-страницата. Кликнете на неа во секое време за да ги прегледате или промените вашите избори.',
        "mt": 'Permezz tal-Impostazzjonijiet tal-Cookies: Hemm link tal-«Impostazzjonijiet tal-Cookies» disponibbli dejjem fil-footer tal-websajt. Ikklikkja fuqu fi kwalunkwe ħin biex tirrevedu jew tibdel l-għażliet tiegħek.',
        "nl": 'Via Cookie-instellingen: Een link naar „Cookie-instellingen" is altijd beschikbaar in de voettekst van de website. Klik er op elk moment op om uw keuzes te bekijken of te wijzigen.',
        "no": 'Via Informasjonskapselsinnstillinger: En lenke til «Informasjonskapselsinnstillinger» er alltid tilgjengelig i nettstedets bunntekst. Klikk på den når som helst for å gjennomgå eller endre valgene dine.',
        "pt": 'Pelas Configurações de cookies: Um link de «Configurações de cookies» está sempre disponível no rodapé do site. Clique nele a qualquer momento para revisar ou alterar suas escolhas.',
        "pt-PT": 'Através das Definições de cookies: Um link «Definições de cookies» está sempre disponível no rodapé do site. Clique nele a qualquer momento para rever ou alterar as suas escolhas.',
        "ro": 'Prin Setările cookie-urilor: Un link «Setări cookie-uri» este întotdeauna disponibil în subsolul site-ului. Faceți clic pe el oricând pentru a revizui sau modifica alegerile dvs.',
        "ru": 'Через Настройки cookie: Ссылка «Настройки cookie» всегда доступна в нижней части сайта. Нажмите на неё в любое время, чтобы просмотреть или изменить свои настройки.',
        "sk": 'Prostredníctvom nastavení cookies: Odkaz „Nastavenia cookies" je vždy dostupný v päte webovej stránky. Kedykoľvek naň kliknite a skontrolujte alebo zmeňte svoje voľby.',
        "sl": 'Prek nastavitev piškotkov: Povezava »Nastavitve piškotkov« je vedno na voljo v nogi spletnega mesta. Kliknite nanjo kadar koli, da pregledate ali spremenite svoje nastavitve.',
        "sq": 'Nëpërmjet Cilësimeve të cookies: Një lidhje «Cilësimet e cookies» është gjithmonë e disponueshme në fund të faqes. Klikoni mbi të në çdo kohë për të rishikuar ose ndryshuar zgjedhjet tuaja.',
        "sr": 'Преко Поставки колачића: Веза „Поставке колачића" увек је доступна у подножју веб-сајта. Кликните на њу у било ком тренутку да бисте прегледали или променили своје изборе.',
        "sv": 'Via Cookie-inställningar: En länk till «Cookie-inställningar» finns alltid tillgänglig i webbplatsens sidfot. Klicka på den när som helst för att granska eller ändra dina val.',
        "tr": 'Çerez Ayarları aracılığıyla: Web sitesinin alt bilgisinde her zaman bir «Çerez Ayarları» bağlantısı mevcuttur. Seçimlerinizi incelemek veya değiştirmek için istediğiniz zaman tıklayın.',
        "uk": 'Через Налаштування cookie: Посилання «Налаштування cookie» завжди доступне в нижній частині сайту. Натисніть на нього в будь-який час, щоб переглянути або змінити свої вибори.',
    },

    "s6_browser": {
        "en": "Via your browser: You can delete, block, or manage all cookies through your browser settings. Note that blocking strictly necessary cookies may prevent the platform from functioning correctly.",
        "pl": "Za pomocą przeglądarki: Możesz usuwać, blokować lub zarządzać wszystkimi plikami cookies w ustawieniach przeglądarki. Pamiętaj, że zablokowanie niezbędnych cookies może uniemożliwić prawidłowe działanie platformy.",
        "bg": "Чрез вашия браузър: Можете да изтривате, блокирате или управлявате всички бисквитки чрез настройките на браузъра. Имайте предвид, че блокирането на задължително необходимите бисквитки може да попречи на правилното функциониране на платформата.",
        "cs": "Prostřednictvím vašeho prohlížeče: Všechny soubory cookies můžete mazat, blokovat nebo spravovat prostřednictvím nastavení prohlížeče. Upozorňujeme, že blokování nezbytně nutných cookies může bránit správnému fungování platformy.",
        "da": "Via din browser: Du kan slette, blokere eller administrere alle cookies via dine browserindstillinger. Bemærk, at blokering af absolut nødvendige cookies kan forhindre, at platformen fungerer korrekt.",
        "de": "Über Ihren Browser: Sie können alle Cookies über Ihre Browsereinstellungen löschen, blockieren oder verwalten. Beachten Sie, dass das Blockieren unbedingt erforderlicher Cookies die ordnungsgemäße Funktion der Plattform beeinträchtigen kann.",
        "el": "Μέσω του προγράμματος περιήγησής σας: Μπορείτε να διαγράψετε, να αποκλείσετε ή να διαχειριστείτε όλα τα cookies μέσω των ρυθμίσεων. Σημειώστε ότι ο αποκλεισμός των απολύτως απαραίτητων cookies ενδέχεται να εμποδίσει τη σωστή λειτουργία της πλατφόρμας.",
        "es": "Mediante su navegador: Puede eliminar, bloquear o gestionar todas las cookies a través de la configuración del navegador. Tenga en cuenta que bloquear las cookies estrictamente necesarias puede impedir el correcto funcionamiento de la plataforma.",
        "et": "Teie brauseri kaudu: Saate kõiki küpsiseid kustutada, blokeerida või hallata oma brauseri seadete kaudu. Pange tähele, et rangelt vajalike küpsiste blokeerimine võib takistada platvormi nõuetekohast toimimist.",
        "fi": "Selaimen kautta: Voit poistaa, estää tai hallita kaikkia evästeitä selaimen asetusten kautta. Huomaa, että ehdottoman välttämättömien evästeiden estäminen saattaa estää alustan asianmukaisen toiminnan.",
        "fr": "Via votre navigateur : Vous pouvez supprimer, bloquer ou gérer tous les cookies via les paramètres de votre navigateur. Notez que le blocage des cookies strictement nécessaires peut empêcher le bon fonctionnement de la plateforme.",
        "ga": "Trí do bhrabhsálaí: Is féidir leat gach fianán a scriosadh, a bhlocáil nó a bhainistiú trí shocruithe do bhrabhsálaí. Tabhair faoi deara go bhféadfadh bac a chur ar fhianáin go docht riachtanacha an t-ardán a chosc ó fheidhmiú i gceart.",
        "hr": "Putem vašeg preglednika: Sve kolačiće možete brisati, blokirati ili upravljati njima putem postavki preglednika. Imajte na umu da blokiranje strogo potrebnih kolačića može spriječiti ispravno funkcioniranje platforme.",
        "hu": "A böngészőn keresztül: Az összes cookie-t törölheti, blokkolhatja vagy kezelheti a böngészőbeállításokon keresztül. Vegye figyelembe, hogy a feltétlenül szükséges cookie-k blokkolása megakadályozhatja a platform megfelelő működését.",
        "is": "Í gegnum vafrann þinn: Þú getur eytt, lokað á eða stjórnað öllum vafrakökum í stillingum vafrans. Athugaðu að loka á algerlega nauðsynlegar vafrakökur getur komið í veg fyrir að vettvangurinn virki rétt.",
        "it": "Tramite il vostro browser: Potete eliminare, bloccare o gestire tutti i cookie tramite le impostazioni del browser. Si noti che il blocco dei cookie strettamente necessari potrebbe impedire il corretto funzionamento della piattaforma.",
        "lb": "Iwwer Ären Browser: Dir kënnt all Cookies iwwer Är Browserastellungen läschen, blockéieren oder verwalten. Bedenkt, datt d'Blockéiere vun onbedéngt erfuerderleche Cookies d'Plattform am richtege Funktionéiere behinderen kann.",
        "lt": "Per savo naršyklę: Visus slapukus galite ištrinti, užblokuoti arba valdyti per naršyklės nustatymus. Atkreipkite dėmesį, kad griežtai būtinų slapukų blokavimas gali neleisti platformai tinkamai veikti.",
        "lv": "Izmantojot savu pārlūkprogrammu: Varat dzēst, bloķēt vai pārvaldīt visus sīkfailus, izmantojot pārlūkprogrammas iestatījumus. Ņemiet vērā, ka absolūti nepieciešamo sīkfailu bloķēšana var traucēt platformas pareizu darbību.",
        "mk": "Преку вашиот прелистувач: Можете да бришете, блокирате или управувате со сите колачиња преку поставките на прелистувачот. Имајте на ум дека блокирањето на строго неопходните колачиња може да го спречи правилното функционирање на платформата.",
        "mt": "Permezz tal-browser tiegħek: Tista' tħassar, timblokka, jew timmaniġġja l-cookies kollha permezz tal-impostazzjonijiet tal-browser. Innota li l-imblukkar tal-cookies strettament meħtieġa jista' jipprevjeni l-funzjonament korrett tal-pjattaforma.",
        "nl": "Via uw browser: U kunt alle cookies verwijderen, blokkeren of beheren via de browserinstellingen. Houd er rekening mee dat het blokkeren van strikt noodzakelijke cookies de goede werking van het platform kan verhinderen.",
        "no": "Via nettleseren din: Du kan slette, blokkere eller administrere alle informasjonskapsler via nettleserinnstillingene. Merk at blokkering av strengt nødvendige informasjonskapsler kan forhindre at plattformen fungerer riktig.",
        "pt": "Pelo seu navegador: Você pode excluir, bloquear ou gerenciar todos os cookies pelas configurações do navegador. Observe que bloquear os cookies estritamente necessários pode impedir o correto funcionamento da plataforma.",
        "pt-PT": "Através do seu browser: Pode eliminar, bloquear ou gerir todos os cookies através das definições do browser. Tenha em atenção que bloquear os cookies estritamente necessários pode impedir o correto funcionamento da plataforma.",
        "ro": "Prin browser-ul dvs.: Puteți șterge, bloca sau gestiona toate cookie-urile prin setările browser-ului. Rețineți că blocarea cookie-urilor strict necesare poate împiedica funcționarea corectă a platformei.",
        "ru": "Через ваш браузер: Вы можете удалять, блокировать или управлять всеми cookie-файлами через настройки браузера. Обратите внимание, что блокировка строго необходимых cookie может нарушить нормальную работу платформы.",
        "sk": "Prostredníctvom vášho prehliadača: Všetky cookies môžete vymazať, zablokovať alebo spravovať prostredníctvom nastavení prehliadača. Upozorňujeme, že blokovanie nevyhnutne potrebných cookies môže zabrániť správnemu fungovaniu platformy.",
        "sl": "Prek svojega brskalnika: Vse piškotke lahko izbrišete, blokirate ali upravljate prek nastavitev brskalnika. Upoštevajte, da blokiranje nujno potrebnih piškotkov lahko prepreči pravilno delovanje platforme.",
        "sq": "Nëpërmjet shfletuesit tuaj: Mund të fshini, bllokoni ose menaxhoni të gjitha cookies nëpërmjet cilësimeve të shfletuesit. Vini re se bllokimi i cookies rreptësisht të nevojshme mund të pengojë funksionimin e saktë të platformës.",
        "sr": "Преко вашег претраживача: Можете да бришете, блокирате или управљате свим колачићима преко поставки претраживача. Имајте на уму да блокирање строго неопходних колачића може спречити правилно функционисање платформе.",
        "sv": "Via din webbläsare: Du kan ta bort, blockera eller hantera alla cookies via webbläsarinställningarna. Observera att blockering av strikt nödvändiga cookies kan förhindra att plattformen fungerar korrekt.",
        "tr": "Tarayıcınız aracılığıyla: Tüm çerezleri tarayıcı ayarlarınız üzerinden silebilir, engelleyebilir veya yönetebilirsiniz. Kesinlikle gerekli çerezlerin engellenmesinin platformun doğru çalışmasını engelleyebileceğini unutmayın.",
        "uk": "Через ваш браузер: Ви можете видаляти, блокувати або керувати всіма cookie-файлами через налаштування браузера. Зверніть увагу, що блокування строго необхідних cookie може перешкодити нормальній роботі платформи.",
    },

    "s6_storage": {
        "en": "Via local/session storage: You can clear browser storage data through your browser's developer tools (Application → Local Storage / Session Storage → nevumo.com → Delete all).",
        "pl": "Za pomocą pamięci przeglądarki: Możesz wyczyścić dane local/session storage za pomocą narzędzi deweloperskich przeglądarki (Aplikacja → Local Storage / Session Storage → nevumo.com → Usuń wszystko).",
        "bg": "Чрез браузърното хранилище: Можете да изчистите данните в local/session storage чрез инструментите за разработчици на браузъра (Приложение → Local Storage / Session Storage → nevumo.com → Изтрий всичко).",
        "cs": "Prostřednictvím místního/relačního úložiště: Data úložiště prohlížeče můžete vymazat prostřednictvím vývojářských nástrojů prohlížeče (Aplikace → Local Storage / Session Storage → nevumo.com → Smazat vše).",
        "da": "Via lokal/sessionslager: Du kan rydde browserens lagerdata via browserens udviklerværktøjer (Applikation → Lokalt lager / Sessionslager → nevumo.com → Slet alle).",
        "de": "Über den lokalen/Sitzungsspeicher: Sie können Browser-Speicherdaten über die Entwicklertools Ihres Browsers löschen (Anwendung → Local Storage / Session Storage → nevumo.com → Alle löschen).",
        "el": "Μέσω τοπικής/αποθήκευσης συνόδου: Μπορείτε να διαγράψετε δεδομένα αποθήκευσης μέσω των εργαλείων προγραμματιστή (Εφαρμογή → Local Storage / Session Storage → nevumo.com → Διαγραφή όλων).",
        "es": "Mediante almacenamiento local/de sesión: Puede borrar los datos de almacenamiento del navegador mediante las herramientas de desarrollo (Aplicación → Almacenamiento local / Almacenamiento de sesión → nevumo.com → Eliminar todo).",
        "et": "Kohaliku/seansimälu kaudu: Saate brauseri salvestusandmeid kustutada arendajatööriistade kaudu (Rakendus → Kohalik salvestus / Seansi salvestus → nevumo.com → Kustuta kõik).",
        "fi": "Paikallisen/istuntotallenteen kautta: Voit tyhjentää selaimen tallennustiedot kehittäjätyökalujen kautta (Sovellus → Paikallinen tallennus / Istuntotallennus → nevumo.com → Poista kaikki).",
        "fr": "Via le stockage local/de session : Vous pouvez effacer les données du stockage du navigateur via les outils de développement (Application → Local Storage / Session Storage → nevumo.com → Tout supprimer).",
        "ga": "Trí stóráil áitiúil/seisiúin: Is féidir leat sonraí stórála a ghlanadh trí uirlisí forbróra do bhrabhsálaí (Feidhmchlár → Local Storage / Session Storage → nevumo.com → Scrios gach rud).",
        "hr": "Putem lokalnog/sesijskog pohrana: Podatke pohrana možete obrisati putem alata za razvojne programere (Aplikacija → Local Storage / Session Storage → nevumo.com → Izbriši sve).",
        "hu": "A helyi/munkamenet tárhelyen keresztül: A böngészőtárhely adatait törölheti a fejlesztői eszközökkel (Alkalmazás → Local Storage / Session Storage → nevumo.com → Összes törlése).",
        "is": "Með local/session storage: Þú getur hreinsað geymsluögn vafrans í gegnum þróunarverkfæri (Forrit → Local Storage / Session Storage → nevumo.com → Eyða öllu).",
        "it": "Tramite il local/session storage: È possibile cancellare i dati di archiviazione tramite gli strumenti per sviluppatori (Applicazione → Local Storage / Session Storage → nevumo.com → Elimina tutto).",
        "lb": "Iwwer Local/Session Storage: Dir kënnt Browserspeicherdaten iwwer d'Entwécklerwerkzeuge vum Browser läschen (Applikatioun → Local Storage / Session Storage → nevumo.com → Alles läschen).",
        "lt": "Per vietinę/seanso saugyklą: Naršyklės saugojimo duomenis galite išvalyti per kūrėjų įrankius (Programa → Local Storage / Session Storage → nevumo.com → Ištrinti viską).",
        "lv": "Izmantojot lokālo/sesijas krātuvi: Pārlūkprogrammas krātuves datus var dzēst, izmantojot izstrādātāja rīkus (Lietojumprogramma → Local Storage / Session Storage → nevumo.com → Dzēst visu).",
        "mk": "Преку локалното/сесиско складирање: Можете да ги исчистите податоците преку алатките за програмери (Апликација → Local Storage / Session Storage → nevumo.com → Избриши сè).",
        "mt": "Permezz tal-ħażna lokali/tal-sessjoni: Tista' tneħħi d-data tal-ħażna permezz tal-għodod tal-iżviluppatur (Applikazzjoni → Local Storage / Session Storage → nevumo.com → Ħassar kollox).",
        "nl": "Via lokale/sessieopslag: U kunt browseropslaggegevens wissen via de ontwikkelaarstools (Toepassing → Local Storage / Session Storage → nevumo.com → Alles verwijderen).",
        "no": "Via lokal/øktlagring: Du kan slette nettleserlagringsdata via utviklerverktøy (Applikasjon → Local Storage / Session Storage → nevumo.com → Slett alle).",
        "pt": "Por meio do armazenamento local/de sessão: Você pode limpar os dados de armazenamento pelas ferramentas de desenvolvedor (Aplicativo → Local Storage / Session Storage → nevumo.com → Excluir tudo).",
        "pt-PT": "Através do armazenamento local/de sessão: Pode limpar os dados de armazenamento pelas ferramentas de programador (Aplicação → Local Storage / Session Storage → nevumo.com → Apagar tudo).",
        "ro": "Prin stocarea locală/de sesiune: Puteți șterge datele de stocare prin instrumentele pentru dezvoltatori (Aplicație → Local Storage / Session Storage → nevumo.com → Șterge tot).",
        "ru": "Через локальное/сессионное хранилище: Вы можете очистить данные хранилища через инструменты разработчика (Приложение → Local Storage / Session Storage → nevumo.com → Удалить все).",
        "sk": "Prostredníctvom miestneho/reláciového úložiska: Údaje úložiska môžete vymazať prostredníctvom vývojárskych nástrojov (Aplikácia → Local Storage / Session Storage → nevumo.com → Odstrániť všetko).",
        "sl": "Prek lokalnega/sejnega shranjevanja: Podatke shranjevanja lahko počistite prek razvijalskih orodij (Aplikacija → Local Storage / Session Storage → nevumo.com → Izbriši vse).",
        "sq": "Nëpërmjet ruajtjes lokale/të sesionit: Mund të pastroni të dhënat e ruajtjes nëpërmjet mjeteve të zhvilluesit (Aplikacioni → Local Storage / Session Storage → nevumo.com → Fshi të gjitha).",
        "sr": "Преко локалног/сесијског складишта: Можете да обришете податке складишта преко алата за програмере (Апликација → Local Storage / Session Storage → nevumo.com → Обриши све).",
        "sv": "Via lokal/sessionslagring: Du kan rensa webbläsarens lagringsdata via utvecklarverktygen (Applikation → Local Storage / Session Storage → nevumo.com → Radera alla).",
        "tr": "Yerel/oturum depolama aracılığıyla: Tarayıcı depolama verilerini geliştirici araçları aracılığıyla temizleyebilirsiniz (Uygulama → Yerel Depolama / Oturum Depolama → nevumo.com → Tümünü sil).",
        "uk": "Через локальне/сесійне сховище: Ви можете очистити дані сховища через інструменти розробника (Додаток → Local Storage / Session Storage → nevumo.com → Видалити все).",
    },

    "s6_col_browser": {
        "en": "Browser",
        "pl": "Przeglądarka",
        "bg": "Браузър",
        "cs": "Prohlížeč",
        "da": "Browser",
        "de": "Browser",
        "el": "Πρόγραμμα περιήγησης",
        "es": "Navegador",
        "et": "Brauser",
        "fi": "Selain",
        "fr": "Navigateur",
        "ga": "Brabhsálaí",
        "hr": "Preglednik",
        "hu": "Böngésző",
        "is": "Vafri",
        "it": "Browser",
        "lb": "Browser",
        "lt": "Naršyklė",
        "lv": "Pārlūkprogramma",
        "mk": "Прелистувач",
        "mt": "Browser",
        "nl": "Browser",
        "no": "Nettleser",
        "pt": "Navegador",
        "pt-PT": "Navegador",
        "ro": "Browser",
        "ru": "Браузер",
        "sk": "Prehliadač",
        "sl": "Brskalnik",
        "sq": "Shfletues",
        "sr": "Претраживач",
        "sv": "Webbläsare",
        "tr": "Tarayıcı",
        "uk": "Браузер",
    },

    "s6_col_path": {
        "en": "Settings path",
        "pl": "Ścieżka ustawień",
        "bg": "Път до настройките",
        "cs": "Cesta k nastavení",
        "da": "Indstillingssti",
        "de": "Einstellungspfad",
        "el": "Διαδρομή ρυθμίσεων",
        "es": "Ruta de configuración",
        "et": "Seadete tee",
        "fi": "Asetuspolku",
        "fr": "Chemin des paramètres",
        "ga": "Cosán socruithe",
        "hr": "Put do postavki",
        "hu": "Beállítások elérési útja",
        "is": "Slóð stillinga",
        "it": "Percorso impostazioni",
        "lb": "Astellungspfad",
        "lt": "Nustatymų kelias",
        "lv": "Iestatījumu ceļš",
        "mk": "Пат до поставките",
        "mt": "Triq tal-impostazzjonijiet",
        "nl": "Instellingenpad",
        "no": "Innstillingssti",
        "pt": "Caminho das configurações",
        "pt-PT": "Caminho das definições",
        "ro": "Calea setărilor",
        "ru": "Путь к настройкам",
        "sk": "Cesta k nastaveniam",
        "sl": "Pot do nastavitev",
        "sq": "Rruga e cilësimeve",
        "sr": "Путања поставки",
        "sv": "Inställningsstig",
        "tr": "Ayarlar yolu",
        "uk": "Шлях до налаштувань",
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_cookies_p21: {count} rows upserted ({NAMESPACE}, 11 keys × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()
