# -*- coding: utf-8 -*-
"""
seed_cookies_p14.py — namespace 'cookies'
cookies.s5_col_retention, cookies.s5_col_category, cookies.s5_col_basis,
cookies.s1_sessionstorage, cookies.s1_note
Run: docker exec nevumo-api python -m apps.api.scripts.seed_cookies_p14
"""

import os
from sqlalchemy import create_engine, text

DATABASE_URL = os.environ.get("DATABASE_URL")
engine = create_engine(DATABASE_URL)

TRANSLATIONS = {
    "cookies.s5_col_retention": {
        "en": "Retention",
        "bg": "Период на съхранение",
        "cs": "Uchovávání",
        "da": "Opbevaring",
        "de": "Aufbewahrung",
        "el": "Διατήρηση",
        "es": "Retención",
        "et": "Säilitamine",
        "fi": "Säilytys",
        "fr": "Conservation",
        "ga": "Coinneáil",
        "hr": "Čuvanje",
        "hu": "Megőrzés",
        "is": "Varðveisla",
        "it": "Conservazione",
        "lb": "Aufbewahrung",
        "lt": "Saugojimas",
        "lv": "Glabāšana",
        "mk": "Чување",
        "mt": "Zamma",
        "nl": "Bewaring",
        "no": "Oppbevaring",
        "pl": "Przechowywanie",
        "pt": "Retenção",
        "pt-PT": "Retenção",
        "ro": "Retenție",
        "ru": "Хранение",
        "sk": "Uchovávanie",
        "sl": "Hramba",
        "sq": "Ruajtja",
        "sr": "Чување",
        "sv": "Lagring",
        "tr": "Saklama",
        "uk": "Зберігання",
    },
    "cookies.s5_col_category": {
        "en": "Category",
        "bg": "Категория",
        "cs": "Kategorie",
        "da": "Kategori",
        "de": "Kategorie",
        "el": "Κατηγορία",
        "es": "Categoría",
        "et": "Kategooria",
        "fi": "Kategoria",
        "fr": "Catégorie",
        "ga": "Catagóir",
        "hr": "Kategorija",
        "hu": "Kategória",
        "is": "Flokkur",
        "it": "Categoria",
        "lb": "Kategorie",
        "lt": "Kategorija",
        "lv": "Kategorija",
        "mk": "Категорија",
        "mt": "Kategorija",
        "nl": "Categorie",
        "no": "Kategori",
        "pl": "Kategoria",
        "pt": "Categoria",
        "pt-PT": "Categoria",
        "ro": "Categorie",
        "ru": "Категория",
        "sk": "Kategória",
        "sl": "Kategorija",
        "sq": "Kategoria",
        "sr": "Категорија",
        "sv": "Kategori",
        "tr": "Kategori",
        "uk": "Категорія",
    },
    "cookies.s5_col_basis": {
        "en": "Legal Basis",
        "bg": "Правно основание",
        "cs": "Právní základ",
        "da": "Retsgrundlag",
        "de": "Rechtsgrundlage",
        "el": "Νομική Βάση",
        "es": "Base jurídica",
        "et": "Õiguslik alus",
        "fi": "Oikeusperuste",
        "fr": "Base juridique",
        "ga": "Bunús Dlí",
        "hr": "Pravna osnova",
        "hu": "Jogalap",
        "is": "Lagagrundvöllur",
        "it": "Base giuridica",
        "lb": "Rechtlech Basis",
        "lt": "Teisinis pagrindas",
        "lv": "Juridiskais pamats",
        "mk": "Правна основа",
        "mt": "Bażi Legali",
        "nl": "Rechtsgrondslag",
        "no": "Rettsgrunnlag",
        "pl": "Podstawa prawna",
        "pt": "Base jurídica",
        "pt-PT": "Base jurídica",
        "ro": "Temei juridic",
        "ru": "Правовая основа",
        "sk": "Právny základ",
        "sl": "Pravna podlaga",
        "sq": "Baza ligjore",
        "sr": "Правни основ",
        "sv": "Rättslig grund",
        "tr": "Hukuki Dayanak",
        "uk": "Правова основа",
    },
    "cookies.s1_sessionstorage": {
        "en": "Session storage works like local storage but is automatically deleted when you close the browser tab.",
        "bg": "Сесийното хранилище работи като локалното хранилище, но се изтрива автоматично при затваряне на браузърния раздел.",
        "cs": "Úložiště relace funguje jako lokální úložiště, ale automaticky se maže po zavření karty prohlížeče.",
        "da": "Sessionslagring fungerer som lokal lagring, men slettes automatisk, når du lukker browserfanen.",
        "de": "Der Sitzungsspeicher funktioniert wie der lokale Speicher, wird jedoch automatisch gelöscht, wenn Sie den Browser-Tab schließen.",
        "el": "Ο χώρος αποθήκευσης περιόδου λειτουργίας λειτουργεί όπως ο τοπικός χώρος, αλλά διαγράφεται αυτόματα όταν κλείσετε την καρτέλα του προγράμματος περιήγησης.",
        "es": "El almacenamiento de sesión funciona como el almacenamiento local, pero se elimina automáticamente cuando cierra la pestaña del navegador.",
        "et": "Seansi salvestusruum toimib nagu kohalik salvestusruum, kuid kustutatakse automaatselt, kui sulgete brauseri vahekaardi.",
        "fi": "Istuntotallennustila toimii kuten paikallinen tallennustila, mutta poistetaan automaattisesti, kun suljet selaimen välilehden.",
        "fr": "Le stockage de session fonctionne comme le stockage local, mais il est automatiquement supprimé à la fermeture de l'onglet du navigateur.",
        "ga": "Oibríonn stóráil seisiúin cosúil le stóráil áitiúil ach scriostar go huathoibríoch é nuair a dhúnann tú an táb brabhsálaí.",
        "hr": "Pohrana sesije funkcionira kao lokalna pohrana, ali se automatski briše kada zatvorite karticu preglednika.",
        "hu": "A munkamenet-tároló ugyanúgy működik, mint a helyi tároló, de automatikusan törlődik, amikor bezárja a böngészőlapot.",
        "is": "Lotugeymsla virkar eins og staðbundin geymsla en er sjálfkrafa eytt þegar þú lokar vafraflipanum.",
        "it": "Il session storage funziona come il local storage, ma viene eliminato automaticamente alla chiusura della scheda del browser.",
        "lb": "Session Storage funktionéiert wéi lokale Späicher, mee gëtt automatesch geläscht, wann Dir den Browser-Tab zoumaacht.",
        "lt": "Seanso saugykla veikia kaip vietinė saugykla, tačiau automatiškai ištrinama uždarant naršyklės skirtuką.",
        "lv": "Sesijas krātuve darbojas tāpat kā lokālā krātuve, taču tiek automātiski dzēsta, aizvērot pārlūkprogrammas cilni.",
        "mk": "Сесиското складирање функционира како локалното, но автоматски се брише кога ќе го затворите јазичето на прелистувачот.",
        "mt": "Il-ħażna tal-sessjoni taħdem bħall-ħażna lokali iżda titħassar awtomatikament meta tagħlaq it-tab tal-browser.",
        "nl": "Sessieopslag werkt als lokale opslag, maar wordt automatisch verwijderd wanneer u het browsertabblad sluit.",
        "no": "Øktlagring fungerer som lokal lagring, men slettes automatisk når du lukker nettleserfanen.",
        "pl": "Pamięć sesji działa jak pamięć lokalna, ale jest automatycznie usuwana po zamknięciu karty przeglądarki.",
        "pt": "O armazenamento de sessão funciona como o armazenamento local, mas é automaticamente excluído quando você fecha a aba do navegador.",
        "pt-PT": "O armazenamento de sessão funciona como o armazenamento local, mas é eliminado automaticamente quando fecha o separador do navegador.",
        "ro": "Stocarea de sesiune funcționează ca stocarea locală, dar este ștearsă automat când închideți fila browserului.",
        "ru": "Хранилище сессии работает как локальное хранилище, но автоматически удаляется при закрытии вкладки браузера.",
        "sk": "Úložisko relácie funguje ako lokálne úložisko, ale automaticky sa vymaže po zatvorení karty prehliadača.",
        "sl": "Shramba seje deluje kot lokalna shramba, vendar se samodejno izbriše, ko zaprete zavihek brskalnika.",
        "sq": "Ruajtja e sesionit funksionon si ruajtja lokale, por fshihet automatikisht kur mbyllni skedën e shfletuesit.",
        "sr": "Складиштење сесије ради као локално складиштење, али се аутоматски брише када затворите картицу прегледача.",
        "sv": "Sessionslagring fungerar som lokal lagring men raderas automatiskt när du stänger webbläsarfliken.",
        "tr": "Oturum depolama, yerel depolama gibi çalışır, ancak tarayıcı sekmesini kapattığınızda otomatik olarak silinir.",
        "uk": "Сховище сесії працює як локальне сховище, але автоматично видаляється при закритті вкладки браузера.",
    },
    "cookies.s1_note": {
        "en": "All three technologies are used on the Nevumo platform. This policy covers all of them.",
        "bg": "И трите технологии се използват в платформата Nevumo. Настоящата политика обхваща всички тях.",
        "cs": "Všechny tři technologie jsou používány na platformě Nevumo. Tato zásada se vztahuje na všechny z nich.",
        "da": "Alle tre teknologier bruges på Nevumo-platformen. Denne politik dækker dem alle.",
        "de": "Alle drei Technologien werden auf der Nevumo-Plattform verwendet. Diese Richtlinie gilt für alle.",
        "el": "Και οι τρεις τεχνολογίες χρησιμοποιούνται στην πλατφόρμα Nevumo. Αυτή η πολιτική καλύπτει και τις τρεις.",
        "es": "Las tres tecnologías se utilizan en la plataforma Nevumo. Esta política las cubre todas.",
        "et": "Kõiki kolme tehnoloogiat kasutatakse Nevumo platvormil. See poliitika hõlmab kõiki neid.",
        "fi": "Kaikkia kolmea teknologiaa käytetään Nevumo-alustalla. Tämä käytäntö kattaa ne kaikki.",
        "fr": "Ces trois technologies sont utilisées sur la plateforme Nevumo. Cette politique les couvre toutes.",
        "ga": "Úsáidtear na trí theicneolaíocht ar ardán Nevumo. Clúdaíonn an polasaí seo iad ar fad.",
        "hr": "Sve tri tehnologije koriste se na platformi Nevumo. Ova politika obuhvaća sve njih.",
        "hu": "Mindhárom technológiát használja a Nevumo platform. Ez a szabályzat mindegyikre kiterjed.",
        "is": "Allar þrjár tæknilegar lausnir eru notaðar á Nevumo-vettvangi. Þessi stefna nær yfir þær allar.",
        "it": "Tutte e tre le tecnologie vengono utilizzate sulla piattaforma Nevumo. Questa politica le copre tutte.",
        "lb": "Alleguer dräi Technologien ginn op der Nevumo-Plattform benotzt. Dës Politik deckt se alleguer of.",
        "lt": "Visos trys technologijos naudojamos Nevumo platformoje. Ši politika apima jas visas.",
        "lv": "Visas trīs tehnoloģijas tiek izmantotas Nevumo platformā. Šī politika attiecas uz visām tām.",
        "mk": "Сите три технологии се користат на платформата Nevumo. Оваа политика ги опфаќа сите.",
        "mt": "It-tliet teknoloġiji kollha huma użati fuq il-pjattaforma Nevumo. Din il-politika tkopri lkoll minnhom.",
        "nl": "Alle drie de technologieën worden gebruikt op het Nevumo-platform. Dit beleid dekt ze allemaal.",
        "no": "Alle tre teknologiene brukes på Nevumo-plattformen. Denne policyen dekker dem alle.",
        "pl": "Wszystkie trzy technologie są używane na platformie Nevumo. Niniejsza polityka obejmuje je wszystkie.",
        "pt": "As três tecnologias são usadas na plataforma Nevumo. Esta política abrange todas elas.",
        "pt-PT": "As três tecnologias são utilizadas na plataforma Nevumo. Esta política abrange todas elas.",
        "ro": "Toate cele trei tehnologii sunt utilizate pe platforma Nevumo. Această politică le acoperă pe toate.",
        "ru": "Все три технологии используются на платформе Nevumo. Данная политика распространяется на все из них.",
        "sk": "Všetky tri technológie sú používané na platforme Nevumo. Tieto zásady sa vzťahujú na všetky z nich.",
        "sl": "Vse tri tehnologije se uporabljajo na platformi Nevumo. Ta politika zajema vse tri.",
        "sq": "Të tria teknologjitë përdoren në platformën Nevumo. Kjo politikë i mbulon të gjitha.",
        "sr": "Све три технологије се користе на платформи Nevumo. Ова политика обухвата све њих.",
        "sv": "Alla tre teknologier används på Nevumo-plattformen. Denna policy täcker dem alla.",
        "tr": "Her üç teknoloji de Nevumo platformunda kullanılmaktadır. Bu politika hepsini kapsamaktadır.",
        "uk": "Усі три технології використовуються на платформі Nevumo. Ця політика охоплює всі з них.",
    },
}


def seed():
    with engine.begin() as conn:
        for key, translations in TRANSLATIONS.items():
            for lang, value in translations.items():
                conn.execute(
                    text("""
                        INSERT INTO translations (key, lang, value)
                        VALUES (:key, :lang, :value)
                        ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value
                    """),
                    {"key": key, "lang": lang, "value": value},
                )
    print(f"Seeded {len(TRANSLATIONS)} keys x 34 languages")


if __name__ == "__main__":
    seed()