"""
seed_terms_p2.py  —  Nevumo | namespace: terms
Keys (13): art4_title ... art15_title + annex1_title
Run: docker exec nevumo-api python -m apps.api.scripts.seed_terms_p2
"""
import os
from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://nevumo:nevumo@postgres:5432/nevumo_leads",
)

NAMESPACE = "terms"

TRANSLATIONS: dict[str, dict[str, str]] = {

    "art4_title": {
        "bg": "Чл. 4. Параметри на класиране на Доставчиците",
        "cs": "4. Jak jsou seřazeni poskytovatelé",
        "da": "4. Sådan rangeres udbydere",
        "de": "4. Wie Anbieter eingestuft werden",
        "el": "4. Πώς κατατάσσονται οι Πάροχοι",
        "en": "4. How Providers Are Ranked",
        "es": "4. Cómo se clasifican los proveedores",
        "et": "4. Kuidas teenusepakkujaid järjestatakse",
        "fi": "4. Kuinka palveluntarjoajat järjestetään",
        "fr": "4. Comment les prestataires sont classés",
        "ga": "4. Conas a Rangaítear Soláthróirí",
        "hr": "4. Kako se rangiraju davatelji usluga",
        "hu": "4. A szolgáltatók rangsorolása",
        "is": "4. Hvernig þjónustuaðilar eru flokkaðir",
        "it": "4. Come vengono classificati i prestatori",
        "lb": "4. Wéi Serviceprestatairen Klassifizéiert Ginn",
        "lt": "4. Kaip reitinguojami paslaugų teikėjai",
        "lv": "4. Kā tiek rangoti pakalpojumu sniedzēji",
        "mk": "4. Како се рангираат Давателите",
        "mt": "4. Kif jiġu Kklassifikati l-Fornituri",
        "nl": "4. Hoe providers worden gerangschikt",
        "no": "4. Slik rangeres leverandørene",
        "pl": "§6. Parametry rankingu Usługodawców",
        "pt": "4. Como os prestadores são classificados",
        "pt-PT": "4. Como os prestadores são classificados",
        "ro": "4. Cum sunt clasați prestatorii",
        "ru": "4. Как ранжируются исполнители",
        "sk": "4. Ako sú poskytovatelia zoradení",
        "sl": "4. Kako so razvrščeni ponudniki",
        "sq": "4. Si renditen ofruesit",
        "sr": "4. Kako se rangiraju pružaoci",
        "sv": "4. Hur leverantörer rangordnas",
        "tr": "4. Sağlayıcılar Nasıl Sıralanır",
        "uk": "4. Як ранжуються виконавці",
    },

    "art5_title": {
        "bg": "Чл. 5. Подаване на запитване за услуга",
        "cs": "5. Podání žádosti o službu",
        "da": "5. Indsendelse af en serviceanmodning",
        "de": "5. Einreichung einer Dienstleistungsanfrage",
        "el": "5. Υποβολή Αιτήματος Υπηρεσίας",
        "en": "5. Submitting a Service Request (Lead)",
        "es": "5. Envío de una solicitud de servicio",
        "et": "5. Teenusepäringu esitamine",
        "fi": "5. Palvelupyynnön lähettäminen",
        "fr": "5. Soumettre une demande de service",
        "ga": "5. Iarratas Seirbhíse a Chur Isteach",
        "hr": "5. Podnošenje zahtjeva za uslugu",
        "hu": "5. Szolgáltatáskérés benyújtása",
        "is": "5. Sending þjónustubeiðni",
        "it": "5. Invio di una richiesta di servizio",
        "lb": "5. Eng Serviceanfro Aschreiwen",
        "lt": "5. Paslaugos užklausos pateikimas",
        "lv": "5. Pakalpojuma pieprasījuma iesniegšana",
        "mk": "5. Поднесување барање за услуга",
        "mt": "5. Tissottometti Talba għal Servizz",
        "nl": "5. Een serviceverzoek indienen",
        "no": "5. Sende inn en tjenesteforespørsel",
        "pl": "§7. Zlecenie usługi (zapytanie)",
        "pt": "5. Envio de uma solicitação de serviço",
        "pt-PT": "5. Envio de um pedido de serviço",
        "ro": "5. Trimiterea unei cereri de serviciu",
        "ru": "5. Отправка заявки на услугу",
        "sk": "5. Odoslanie žiadosti o službu",
        "sl": "5. Oddaja zahtevka za storitev",
        "sq": "5. Dërgimi i një kërkese shërbimi",
        "sr": "5. Slanje zahteva za uslugu",
        "sv": "5. Skicka in en tjänsteförfrågan",
        "tr": "5. Hizmet Talebi Gönderme",
        "uk": "5. Надсилання запиту на послугу",
    },

    "art6_title": {
        "bg": "Чл. 6. Цени и плащания",
        "cs": "6. Ceny a platby",
        "da": "6. Priser og betalinger",
        "de": "6. Preise und Zahlungen",
        "el": "6. Τιμές και Πληρωμές",
        "en": "6. Prices and Payments",
        "es": "6. Precios y pagos",
        "et": "6. Hinnad ja maksed",
        "fi": "6. Hinnat ja maksut",
        "fr": "6. Prix et paiements",
        "ga": "6. Praghsanna agus Íocaíochtaí",
        "hr": "6. Cijene i plaćanja",
        "hu": "6. Árak és fizetések",
        "is": "6. Verð og greiðslur",
        "it": "6. Prezzi e pagamenti",
        "lb": "6. Präisser a Bezuelungen",
        "lt": "6. Kainos ir mokėjimai",
        "lv": "6. Cenas un maksājumi",
        "mk": "6. Цени и плаќања",
        "mt": "6. Prezzijiet u Pagamenti",
        "nl": "6. Prijzen en betalingen",
        "no": "6. Priser og betalinger",
        "pl": "§8. Ceny i płatności",
        "pt": "6. Preços e pagamentos",
        "pt-PT": "6. Preços e pagamentos",
        "ro": "6. Prețuri și plăți",
        "ru": "6. Цены и оплата",
        "sk": "6. Ceny a platby",
        "sl": "6. Cene in plačila",
        "sq": "6. Çmimet dhe pagesat",
        "sr": "6. Cene i plaćanja",
        "sv": "6. Priser och betalningar",
        "tr": "6. Fiyatlar ve Ödemeler",
        "uk": "6. Ціни та платежі",
    },

    "art7_title": {
        "bg": "Чл. 7. Право на отказ — потребители",
        "cs": "7. Právo na odstoupení — spotřebitelé",
        "da": "7. Fortrydelsesret — forbrugere",
        "de": "7. Widerrufsrecht — Verbraucher",
        "el": "7. Δικαίωμα Υπαναχώρησης — Καταναλωτές",
        "en": "7. Right of Withdrawal — Consumers",
        "es": "7. Derecho de desistimiento — Consumidores",
        "et": "7. Taganemisõigus — tarbijad",
        "fi": "7. Peruuttamisoikeus — kuluttajat",
        "fr": "7. Droit de rétractation — Consommateurs",
        "ga": "7. Ceart Aistarraingthe — Tomhaltóirí",
        "hr": "7. Pravo na odustanak — potrošači",
        "hu": "7. Elállási jog — fogyasztók",
        "is": "7. Afturköllunartéttur — Neytendur",
        "it": "7. Diritto di recesso — Consumatori",
        "lb": "7. Widderhollungsrecht — Konsumenten",
        "lt": "7. Atsisakymo teisė — vartotojai",
        "lv": "7. Atteikuma tiesības — patērētāji",
        "mk": "7. Право на отстапување — потрошувачи",
        "mt": "7. Dritt tal-Irtirar — Konsumaturi",
        "nl": "7. Herroepingsrecht — consumenten",
        "no": "7. Angrerett — forbrukere",
        "pl": "§9. Prawo odstąpienia od umowy",
        "pt": "7. Direito de arrependimento — Consumidores",
        "pt-PT": "7. Direito de retractação — Consumidores",
        "ro": "7. Dreptul de retragere — Consumatori",
        "ru": "7. Право на отказ — потребители",
        "sk": "7. Právo na odstúpenie — spotrebitelia",
        "sl": "7. Pravica do odstopa — potrošniki",
        "sq": "7. E drejta e tërheqjes — Konsumatorët",
        "sr": "7. Pravo na odustanak — potrošači",
        "sv": "7. Ångerrätt — konsumenter",
        "tr": "7. Cayma Hakkı — Tüketiciler",
        "uk": "7. Право на відмову — споживачі",
    },

    "art8_title": {
        "bg": "Чл. 8. Отзиви",
        "cs": "8. Recenze",
        "da": "8. Anmeldelser",
        "de": "8. Bewertungen",
        "el": "8. Αξιολογήσεις",
        "en": "8. Reviews",
        "es": "8. Reseñas",
        "et": "8. Arvustused",
        "fi": "8. Arvostelut",
        "fr": "8. Avis",
        "ga": "8. Athbhreithnithe",
        "hr": "8. Recenzije",
        "hu": "8. Vélemények",
        "is": "8. Umsagnir",
        "it": "8. Recensioni",
        "lb": "8. Bewäertungen",
        "lt": "8. Atsiliepimai",
        "lv": "8. Atsauksmes",
        "mk": "8. Рецензии",
        "mt": "8. Reviżjonijiet",
        "nl": "8. Beoordelingen",
        "no": "8. Anmeldelser",
        "pl": "§10. Opinie",
        "pt": "8. Avaliações",
        "pt-PT": "8. Avaliações",
        "ro": "8. Recenzii",
        "ru": "8. Отзывы",
        "sk": "8. Recenzie",
        "sl": "8. Ocene",
        "sq": "8. Vlerësime",
        "sr": "8. Recenzije",
        "sv": "8. Recensioner",
        "tr": "8. Değerlendirmeler",
        "uk": "8. Відгуки",
    },

    "art9_title": {
        "bg": "Чл. 9. Забранено поведение",
        "cs": "9. Zakázané jednání",
        "da": "9. Forbudt adfærd",
        "de": "9. Verbotenes Verhalten",
        "el": "9. Απαγορευμένη Συμπεριφορά",
        "en": "9. Prohibited Conduct",
        "es": "9. Conducta prohibida",
        "et": "9. Keelatud tegevus",
        "fi": "9. Kielletty toiminta",
        "fr": "9. Comportements interdits",
        "ga": "9. Iompar Toirmiscthe",
        "hr": "9. Zabranjeno ponašanje",
        "hu": "9. Tiltott magatartás",
        "is": "9. Bönnuð hegðun",
        "it": "9. Condotte vietate",
        "lb": "9. Verbueden Verhalen",
        "lt": "9. Draudžiamas elgesys",
        "lv": "9. Aizliegta rīcība",
        "mk": "9. Забранено однесување",
        "mt": "9. Kondotta Pprojbita",
        "nl": "9. Verboden gedrag",
        "no": "9. Forbudt atferd",
        "pl": "§5. Zakaz dostarczania treści bezprawnych",
        "pt": "9. Conduta proibida",
        "pt-PT": "9. Conduta proibida",
        "ro": "9. Conduită interzisă",
        "ru": "9. Запрещённые действия",
        "sk": "9. Zakázané správanie",
        "sl": "9. Prepovedano ravnanje",
        "sq": "9. Sjellje e ndaluar",
        "sr": "9. Zabranjeno ponašanje",
        "sv": "9. Förbjudet beteende",
        "tr": "9. Yasak Davranışlar",
        "uk": "9. Заборонена поведінка",
    },

    "art10_title": {
        "bg": "Чл. 10. Отговорност",
        "cs": "10. Odpovědnost",
        "da": "10. Ansvar",
        "de": "10. Haftung",
        "el": "10. Ευθύνη",
        "en": "10. Liability",
        "es": "10. Responsabilidad",
        "et": "10. Vastutus",
        "fi": "10. Vastuunrajoitus",
        "fr": "10. Responsabilité",
        "ga": "10. Dliteanas",
        "hr": "10. Odgovornost",
        "hu": "10. Felelősség",
        "is": "10. Ábyrgð",
        "it": "10. Responsabilità",
        "lb": "10. Haftung",
        "lt": "10. Atsakomybė",
        "lv": "10. Atbildība",
        "mk": "10. Одговорност",
        "mt": "10. Responsabbiltà",
        "nl": "10. Aansprakelijkheid",
        "no": "10. Ansvar",
        "pl": "10. Odpowiedzialność Nevumo",
        "pt": "10. Responsabilidade",
        "pt-PT": "10. Responsabilidade",
        "ro": "10. Răspundere",
        "ru": "10. Ответственность",
        "sk": "10. Zodpovednosť",
        "sl": "10. Odgovornost",
        "sq": "10. Përgjegjësia",
        "sr": "10. Odgovornost",
        "sv": "10. Ansvar",
        "tr": "10. Sorumluluk",
        "uk": "10. Відповідальність",
    },

    "art11_title": {
        "bg": "Чл. 11. Рекламации",
        "cs": "11. Stížnosti",
        "da": "11. Klager",
        "de": "11. Beschwerden",
        "el": "11. Παράπονα",
        "en": "11. Complaints",
        "es": "11. Reclamaciones",
        "et": "11. Kaebused",
        "fi": "11. Valitukset",
        "fr": "11. Réclamations",
        "ga": "11. Gearáin",
        "hr": "11. Pritužbe",
        "hu": "11. Panaszok",
        "is": "11. Kvartanir",
        "it": "11. Reclami",
        "lb": "11. Beschwerden",
        "lt": "11. Skundai",
        "lv": "11. Sūdzības",
        "mk": "11. Рекламации",
        "mt": "11. Ilmenti",
        "nl": "11. Klachten",
        "no": "11. Klager",
        "pl": "§11. Reklamacje",
        "pt": "11. Reclamações",
        "pt-PT": "11. Reclamações",
        "ro": "11. Reclamații",
        "ru": "11. Жалобы",
        "sk": "11. Sťažnosti",
        "sl": "11. Pritožbe",
        "sq": "11. Ankesat",
        "sr": "11. Reklamacije",
        "sv": "11. Klagomål",
        "tr": "11. Şikayetler",
        "uk": "11. Скарги",
    },

    "art12_title": {
        "bg": "Чл. 12. Алтернативно решаване на спорове (АРС)",
        "cs": "12. Alternativní řešení sporů (ADR)",
        "da": "12. Alternativ tvistbilæggelse (ADR)",
        "de": "12. Alternative Streitbeilegung (ADR)",
        "el": "12. Εναλλακτική Επίλυση Διαφορών (ADR)",
        "en": "12. Alternative Dispute Resolution (ADR)",
        "es": "12. Resolución alternativa de conflictos (ADR)",
        "et": "12. Alternatiivne vaidluste lahendamine (ADR)",
        "fi": "12. Vaihtoehtoinen riidanratkaisu (ADR)",
        "fr": "12. Règlement alternatif des litiges (ADR)",
        "ga": "12. Réiteach Malartach Díospóidí (ADR)",
        "hr": "12. Alternativno rješavanje sporova (ADR)",
        "hu": "12. Alternatív vitarendezés (ADR)",
        "is": "12. Óformleg deilulausn (ADR)",
        "it": "12. Risoluzione alternativa delle controversie (ADR)",
        "lb": "12. Alternativ Sträitbäilegung (ADR)",
        "lt": "12. Alternatyvus ginčų sprendimas (AGS)",
        "lv": "12. Alternatīva strīdu izšķiršana (ADR)",
        "mk": "12. Алтернативно решавање спорови (АРС)",
        "mt": "12. Riżoluzzjoni Alternattiva tat-Tilwim (ADR)",
        "nl": "12. Alternatieve geschillenbeslechting (ADR)",
        "no": "12. Alternativ tvisteløsning (ADR)",
        "pl": "§12. Pozasądowe sposoby rozwiązywania sporów (ADR)",
        "pt": "12. Resolução alternativa de litígios (ADR)",
        "pt-PT": "12. Resolução alternativa de litígios (ADR)",
        "ro": "12. Soluționarea alternativă a litigiilor (ADR)",
        "ru": "12. Альтернативное урегулирование споров (АУС)",
        "sk": "12. Alternatívne riešenie sporov (ARS)",
        "sl": "12. Alternativno reševanje sporov (ARS)",
        "sq": "12. Zgjidhja alternative e mosmarrëveshjeve (ADR)",
        "sr": "12. Alternativno rešavanje sporova (ARS)",
        "sv": "12. Alternativ tvistlösning (ADR)",
        "tr": "12. Alternatif Uyuşmazlık Çözümü (AUÇ)",
        "uk": "12. Альтернативне вирішення спорів (АВС)",
    },

    "art13_title": {
        "bg": "Чл. 13. Приложимо право и компетентен съд",
        "cs": "13. Rozhodné právo a příslušnost soudů",
        "da": "13. Gældende ret og jurisdiktion",
        "de": "13. Anwendbares Recht und Gerichtsstand",
        "el": "13. Εφαρμοστέο Δίκαιο και Δικαιοδοσία",
        "en": "13. Applicable Law and Jurisdiction",
        "es": "13. Ley aplicable y jurisdicción",
        "et": "13. Kohaldatav õigus ja kohtualluvus",
        "fi": "13. Sovellettava laki ja lainkäyttövalta",
        "fr": "13. Droit applicable et juridiction compétente",
        "ga": "13. Dlí Infheidhmithe agus Dlínse",
        "hr": "13. Mjerodavno pravo i nadležnost",
        "hu": "13. Alkalmazandó jog és joghatóság",
        "is": "13. Gildandi lög og lögsaga",
        "it": "13. Legge applicabile e giurisdizione",
        "lb": "13. Gëltend Recht a Gerichtsstanduert",
        "lt": "13. Taikytina teisė ir jurisdikcija",
        "lv": "13. Piemērojamie tiesību akti un jurisdikcija",
        "mk": "13. Применливо право и надлежност",
        "mt": "13. Liġi Applikabbli u Ġurisdizzjoni",
        "nl": "13. Toepasselijk recht en jurisdictie",
        "no": "13. Gjeldende lov og jurisdiksjon",
        "pl": "§13. Prawo właściwe i właściwość sądów",
        "pt": "13. Lei aplicável e jurisdição",
        "pt-PT": "13. Lei aplicável e jurisdição",
        "ro": "13. Legea aplicabilă și jurisdicția",
        "ru": "13. Применимое право и юрисдикция",
        "sk": "13. Rozhodné právo a príslušnosť súdov",
        "sl": "13. Veljavno pravo in sodna pristojnost",
        "sq": "13. Ligji i zbatueshëm dhe juridiksioni",
        "sr": "13. Merodavno pravo i nadležnost",
        "sv": "13. Tillämplig lag och jurisdiktion",
        "tr": "13. Uygulanacak Hukuk ve Yargı Yetkisi",
        "uk": "13. Застосовне право та юрисдикція",
    },

    "art14_title": {
        "bg": "Чл. 14. Изменения на ОУ",
        "cs": "14. Změny podmínek",
        "da": "14. Ændringer af vilkår",
        "de": "14. Änderungen der Bedingungen",
        "el": "14. Τροποποιήσεις Όρων",
        "en": "14. Amendments",
        "es": "14. Modificaciones",
        "et": "14. Muudatused",
        "fi": "14. Muutokset",
        "fr": "14. Modifications",
        "ga": "14. Leasuithe",
        "hr": "14. Izmjene uvjeta",
        "hu": "14. Módosítások",
        "is": "14. Breytingar",
        "it": "14. Modifiche",
        "lb": "14. Ännerungen",
        "lt": "14. Pakeitimai",
        "lv": "14. Grozījumi",
        "mk": "14. Измени",
        "mt": "14. Emendi",
        "nl": "14. Wijzigingen",
        "no": "14. Endringer",
        "pl": "§14. Zmiany Regulaminu",
        "pt": "14. Alterações",
        "pt-PT": "14. Alterações",
        "ro": "14. Modificări",
        "ru": "14. Изменения",
        "sk": "14. Zmeny podmienok",
        "sl": "14. Spremembe pogojev",
        "sq": "14. Ndryshime",
        "sr": "14. Izmene uslova",
        "sv": "14. Ändringar",
        "tr": "14. Değişiklikler",
        "uk": "14. Зміни умов",
    },

    "art15_title": {
        "bg": "Чл. 15. Заключителни разпоредби",
        "cs": "15. Závěrečná ustanovení",
        "da": "15. Generelle bestemmelser",
        "de": "15. Allgemeine Bestimmungen",
        "el": "15. Γενικές Διατάξεις",
        "en": "15. General Provisions",
        "es": "15. Disposiciones generales",
        "et": "15. Üldsätted",
        "fi": "15. Yleiset määräykset",
        "fr": "15. Dispositions générales",
        "ga": "15. Forálacha Ginearálta",
        "hr": "15. Opće odredbe",
        "hu": "15. Általános rendelkezések",
        "is": "15. Almennar ákvæði",
        "it": "15. Disposizioni generali",
        "lb": "15. Allgemeng Bestëmmungen",
        "lt": "15. Bendrosios nuostatos",
        "lv": "15. Vispārīgie noteikumi",
        "mk": "15. Општи одредби",
        "mt": "15. Dispożizzjonijiet Ġenerali",
        "nl": "15. Algemene bepalingen",
        "no": "15. Generelle bestemmelser",
        "pl": "§15. Postanowienia końcowe",
        "pt": "15. Disposições gerais",
        "pt-PT": "15. Disposições gerais",
        "ro": "15. Dispoziții generale",
        "ru": "15. Общие положения",
        "sk": "15. Záverečné ustanovenia",
        "sl": "15. Splošne določbe",
        "sq": "15. Dispozita të Përgjithshme",
        "sr": "15. Opšte odredbe",
        "sv": "15. Allmänna bestämmelser",
        "tr": "15. Genel Hükümler",
        "uk": "15. Загальні положення",
    },

    "annex1_title": {
        "bg": "Приложение 1 — Формуляр за отказ от договор с Nevumo",
        "cs": "Příloha 1 — Vzorový formulář pro odstoupení od smlouvy s Nevumo",
        "da": "Bilag 1 — Standardfortrydelsesformular for Nevumo",
        "de": "Anhang 1 — Muster-Widerrufsformular für Nevumo",
        "el": "Παράρτημα 1 — Τυποποιημένο έντυπο υπαναχώρησης από Nevumo",
        "en": "Annex 1 — Standard Withdrawal Form (Nevumo Platform Services Only)",
        "es": "Anexo 1 — Formulario de desistimiento estándar de Nevumo",
        "et": "Lisa 1 — Nevumo standardne taganemisvorm",
        "fi": "Liite 1 — Nevumon vakiolomake peruuttamista varten",
        "fr": "Annexe 1 — Formulaire de rétractation standard Nevumo",
        "ga": "Aguisín 1 — Foirm Chaighdeánach Aistarraingthe Nevumo",
        "hr": "Prilog 1 — Standardni obrazac za odustanak od ugovora s Nevumo",
        "hu": "1. melléklet — Nevumo elállási nyilatkozat minta",
        "is": "Viðauki 1 — Staðlað afturköllunaryfirlýsing Nevumo",
        "it": "Allegato 1 — Modulo di recesso standard Nevumo",
        "lb": "Anhang 1 — Standard-Widerrufsformular fir Nevumo",
        "lt": "1 priedas — Standartinė atsisakymo forma Nevumo",
        "lv": "1. pielikums — Nevumo standarta atteikuma veidlapa",
        "mk": "Прилог 1 — Стандарден формулар за отстапување од договор со Nevumo",
        "mt": "Anness 1 — Formola Standard ta' Irtirar Nevumo",
        "nl": "Bijlage 1 — Standaard herroepingsformulier Nevumo",
        "no": "Vedlegg 1 — Standard angreskjema for Nevumo",
        "pl": "Załącznik nr 1 — Wzór formularza odstąpienia od umowy z Nevumo",
        "pt": "Anexo 1 — Formulário de retratação padrão da Nevumo",
        "pt-PT": "Anexo 1 — Formulário de retractação padrão da Nevumo",
        "ro": "Anexa 1 — Formular standard de retragere Nevumo",
        "ru": "Приложение 1 — Стандартная форма отказа от договора с Nevumo",
        "sk": "Príloha 1 — Vzorový formulár na odstúpenie od zmluvy s Nevumo",
        "sl": "Priloga 1 — Standardni obrazec za odstop od pogodbe z Nevumo",
        "sq": "Shtojca 1 — Formulari standard i tërheqjes Nevumo",
        "sr": "Prilog 1 — Standardni obrazac za odustanak od ugovora sa Nevumo",
        "sv": "Bilaga 1 — Standardformulär för ångerrätt Nevumo",
        "tr": "Ek 1 — Nevumo Standart Cayma Formu",
        "uk": "Додаток 1 — Стандартна форма відмови від договору з Nevumo",
    },
}


def seed() -> None:
    engine = create_engine(DATABASE_URL, echo=False)
    Session = sessionmaker(bind=engine)

    with Session() as session:
        count = 0
        for key, lang_values in TRANSLATIONS.items():
            db_key = f"{NAMESPACE}.{key}"
            for lang, value in lang_values.items():
                session.execute(
                    text(
                        "INSERT INTO translations (lang, key, value) "
                        "VALUES (:lang, :key, :value) "
                        "ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value"
                    ),
                    {"lang": lang, "key": db_key, "value": value},
                )
                count += 1
        session.commit()
        print(f"✅ seed_terms_p2: {count} rows upserted ({NAMESPACE}, 13 keys × 34 langs)")

    engine.dispose()


if __name__ == "__main__":
    seed()
